import { beforeEach,describe,expect,it,vi } from "vitest";
vi.mock("server-only",()=>({}));
const mocks=vi.hoisted(()=>({rpc:vi.fn(),actor:vi.fn(),render:vi.fn(),buffer:vi.fn()}));
vi.mock("@/lib/objects/auth",()=>({getObjectActor:mocks.actor}));
vi.mock("@/lib/work-orders/report-pdf",()=>({renderWorkOrderReportPdf:mocks.render}));
vi.mock("@/lib/files/private-download",()=>({bufferPrivateFile:mocks.buffer,samePrivateFile:(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b),privateFileHeaders:{"Cache-Control":"private, no-store"}}));
import { customerReportResponse } from "./report-download";
const tenant="10000000-0000-4000-8000-000000000001",account="10000000-0000-4000-8000-000000000002",id="10000000-0000-4000-8000-000000000003";
const report={id,version:1,state:"approved",projection:"customer_copy",contentHash:"a".repeat(64),createdAt:"2026-10-05T10:00:00Z",approvedAt:"2026-10-05T10:00:00Z",policy:{mode:"none",source:"tenant",employeeRequired:false},signatures:[],waiver:null,snapshot:{schema:1,number:"REPORT-TEST",title:"Fictief rapport",summary:"Uitgevoerd",tenant:{name:"Fictieve leverancier",primaryColor:"#123456",accentColor:"#123456"},customer:{name:"Fictieve klant"},object:{name:"Fictief object",address:{}},executionDate:null,endedAt:null,timezone:"Europe/Amsterdam",tasks:[],notes:[],attachments:[]}};
beforeEach(()=>{vi.resetAllMocks();mocks.actor.mockResolvedValue({tenant:{id:tenant},db:{rpc:mocks.rpc}});mocks.rpc.mockResolvedValue({data:report,error:null});mocks.render.mockResolvedValue(new Uint8Array([37,80,68,70]));});
describe("forced customer report delivery",()=>{
 it("uses only the account-scoped copy RPC before and after rendering",async()=>{const result=await customerReportResponse(id,account);expect(result.status).toBe(200);expect(result.headers.get("content-type")).toBe("application/pdf");expect(mocks.rpc).toHaveBeenCalledTimes(2);expect(mocks.rpc).toHaveBeenCalledWith("customer_portal_report_file",{target_tenant:tenant,target_account:account,target_report:id});expect(mocks.render.mock.calls[0][0].projection).toBe("customer_copy");});
 it.each(["original","own_contribution"])("rejects a role-sensitive %s result before PDF rendering",async projection=>{mocks.rpc.mockResolvedValueOnce({data:{...report,projection},error:null});await expect(customerReportResponse(id,account)).rejects.toThrow();expect(mocks.render).not.toHaveBeenCalled();});
 it("discards generated bytes when the account loses access",async()=>{mocks.render.mockImplementation(async()=>{mocks.rpc.mockResolvedValue({data:null,error:{code:"42501"}});return new Uint8Array([37,80,68,70]);});await expect(customerReportResponse(id,account)).rejects.toThrow();});
 it("rejects employee signatures or captured-by labels even in a claimed customer copy",async()=>{for(const signature of [{kind:"employee",capturedBy:null},{kind:"customer",capturedBy:"PRIVATE EMPLOYEE"}]){mocks.rpc.mockResolvedValueOnce({data:{...report,signatures:[{id,name:"Signer",capacity:"Staff",signedAt:"2026-10-05T10:00:00Z",channel:"in_person",...signature}]},error:null});await expect(customerReportResponse(id,account)).rejects.toThrow();}expect(mocks.render).not.toHaveBeenCalled();});
});
