import {test,expect} from "@playwright/test";
import {randomUUID} from "node:crypto";
import {Client} from "pg";
import {authenticateWorkspace} from "./login-auth";
import {requireLocalDatabaseUrl} from "./local-target";

const prefix=`E2E${randomUUID().replaceAll("-","").slice(0,8).toUpperCase()}`,categoryName=`Categorie ${prefix}`;
let db:Client,tenant:string;
test.beforeAll(async()=>{db=new Client({connectionString:requireLocalDatabaseUrl().href});await db.connect();tenant=(await db.query("select id from public.tenants where slug='fieldgrid-e2e'")).rows[0].id;});
test.afterAll(async()=>{if(!db)return;try{const categories=(await db.query('select id from public.task_categories where tenant_id=$1 and prefix=$2',[tenant,prefix])).rows.map(r=>r.id);const tasks=(await db.query('select id from public.task_catalog where tenant_id=$1 and category_id=any($2)',[tenant,categories])).rows.map(r=>r.id);const ids=[...categories,...tasks];
 // Cleanup is restricted to this run's isolated local fixture; no application mutation uses this setting.
 requireLocalDatabaseUrl();expect((await db.query('select slug from public.tenants where id=$1',[tenant])).rows[0].slug).toBe('fieldgrid-e2e');await db.query('begin');try{await db.query("set local session_replication_role='replica'");await db.query('delete from public.extra_work_rules where task_revision_id in(select id from public.task_revisions where task_id=any($1))',[tasks]);await db.query('delete from public.task_revisions where task_id=any($1)',[tasks]);await db.query('delete from public.task_catalog where id=any($1)',[tasks]);await db.query('delete from public.task_categories where id=any($1)',[categories]);await db.query('delete from public.audit_events where entity_id=any($1)',[ids]);await db.query("delete from private.work_order_commands where tenant_id=$1 and command like 'catalogue:%' and result->>'id'=any($2::text[])",[tenant,ids]);await db.query('commit');}catch(e){await db.query('rollback');throw e;}
 }finally{await db.end();}});

test('categorieën nummeren taken; wizard bewaart invoer en acties werken zonder mobiele overlap',async({page},info)=>{
 test.setTimeout(120000);await authenticateWorkspace(page,'platform-admin@fieldgrid.test','/app/taken');
 await expect(page.getByRole('heading',{name:'Taken & tarieven',exact:true})).toBeVisible();await page.getByRole('tab',{name:'Categorieën',exact:true}).click();await page.getByRole('button',{name:'Voeg toe',exact:true}).click();
 let dialog=page.getByRole('dialog',{name:'Nieuwe taakcategorie',exact:true});await dialog.getByLabel('Naam',{exact:true}).fill(categoryName);await dialog.getByLabel('Prefix',{exact:true}).fill(prefix);await dialog.getByRole('button',{name:'Opslaan',exact:true}).click();await expect(dialog).toHaveCount(0);
 await expect(page.getByRole('row').filter({hasText:categoryName})).toContainText(`${prefix}-001`);
 await page.getByRole('tab',{name:'Taken',exact:true}).click();await page.getByRole('button',{name:'Voeg toe',exact:true}).click();dialog=page.getByRole('dialog',{name:'Nieuwe taak',exact:true});await dialog.getByLabel('Categorie',{exact:true}).selectOption({label:categoryName});await dialog.getByLabel('Naam',{exact:true}).fill(`Taak ${prefix}`);await dialog.getByLabel('Discipline',{exact:true}).fill('Onderhoud');await dialog.getByLabel('Prijs excl. btw',{exact:true}).fill('125.50');await dialog.getByRole('button',{name:'Volgende',exact:true}).click();await dialog.getByLabel('Mag als meerwerk worden aangeboden').check();await dialog.getByLabel('Klant moet het opleverrapport ondertekenen').check();await dialog.getByLabel('Foto van de werkzaamheden verplicht').check();await dialog.getByRole('button',{name:'Vorige',exact:true}).click();await expect(dialog.getByLabel('Naam',{exact:true})).toHaveValue(`Taak ${prefix}`);await dialog.getByRole('button',{name:'Volgende',exact:true}).click();
 for(const width of[320,390,1440]){await page.setViewportSize({width,height:900});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect.poll(()=>dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await expect(dialog.getByRole('button',{name:'Opslaan',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath(`task-wizard-${width}.png`),animations:'disabled'});}
 await dialog.getByRole('button',{name:'Opslaan',exact:true}).click();await expect(dialog).toHaveCount(0);const row=page.getByRole('row').filter({hasText:`Taak ${prefix}`});await expect(row).toContainText(`${prefix}-001`);await expect(row).toContainText('Handtekening');await expect(row).toContainText('Foto');await row.getByRole('button',{name:'Bewerk',exact:true}).click();dialog=page.getByRole('dialog',{name:'Taak bewerken',exact:true});await dialog.getByLabel('Duur (minuten)',{exact:true}).fill('75');await dialog.getByRole('button',{name:'Volgende',exact:true}).click();await dialog.getByRole('button',{name:'Opslaan',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(row).toContainText('75 min');await row.getByRole('button',{name:'Archiveer',exact:true}).click();await expect(row).toContainText('Gearchiveerd');
 await page.getByRole('tab',{name:'Categorieën',exact:true}).click();await expect(page.getByRole('row').filter({hasText:categoryName})).toContainText(`${prefix}-002`);
});

test('instellingentabs bewaren huisstijlconcepten en velden blijven compact',async({page})=>{
 await authenticateWorkspace(page,'platform-admin@fieldgrid.test','/app/instellingen');const input=page.getByLabel('Primaire kleur hexcode',{exact:true});await input.fill('#123456');await expect.poll(async()=>Number((await input.boundingBox())?.height)).toBeLessThanOrEqual(48);await page.getByRole('tab',{name:'Reizen',exact:true}).click();await expect(input).toBeHidden();await page.getByRole('tab',{name:'Huisstijl & afzender',exact:true}).click();await expect(input).toHaveValue('#123456');await page.getByRole('button',{name:'Wijzigingen annuleren',exact:true}).click();
});
