import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

function read(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
}

const invoiceSchema = read("lib/db/src/schema/invoices.ts");
const generatedMigration = read("lib/db/migrations/generated/0001_wandering_matthew_murdock.sql");
const tenantScopeMigration = read("lib/db/migrations/062_finance_reports_tenant_scope.sql");
const tenantHardeningMigration = read("lib/db/migrations/062_post_migration_tenant_hardening.sql");
const allMigrationHints = [
  generatedMigration,
  tenantScopeMigration,
  tenantHardeningMigration,
].join("\n");

test("current invoice schema baseline documents statuses and global invoice number behavior", () => {
  assert.match(invoiceSchema, /export const INVOICE_STATUSES = \["draft", "sent", "paid", "cancelled"\] as const/u);
  assert.match(invoiceSchema, /invoiceNumber:\s+varchar\("invoice_number", \{ length: 30 \}\)\.notNull\(\)\.unique\(\)\.\$defaultFn\(\(\) => ""\)/u);
  assert.match(invoiceSchema, /invoice_number is auto-generated by DB trigger trg_invoices_set_number/u);
  assert.match(invoiceSchema, /Format: FACT-YYYY-NNNN/u);
  assert.match(invoiceSchema, /insertInvoiceSchema = createInsertSchema\(invoicesTable\)\.omit\(\{/u);
  assert.match(invoiceSchema, /invoiceNumber: true/u);
  assert.match(invoiceSchema, /tenantId: true/u);
});

test("current migrations create global invoice number uniqueness and tenant hardening separately", () => {
  assert.match(generatedMigration, /"invoice_number" varchar\(30\) NOT NULL/u);
  assert.match(generatedMigration, /CONSTRAINT "invoices_invoice_number_unique" UNIQUE\("invoice_number"\)/u);
  assert.match(tenantScopeMigration, /CREATE OR REPLACE FUNCTION fieldgrid_set_invoice_tenant_id\(\)/u);
  assert.match(tenantScopeMigration, /DROP TRIGGER IF EXISTS trg_invoices_set_tenant_id ON invoices/u);
  assert.match(tenantScopeMigration, /CREATE TRIGGER trg_invoices_set_tenant_id/u);
  assert.match(tenantHardeningMigration, /SELECT pg_temp\.fieldgrid_add_tenant_required_check\('invoices', 'invoices_tenant_id_required_check'\)/u);
});

test("current baseline has no canon invoice numbering tables or claim function yet", () => {
  assert.doesNotMatch(allMigrationHints, /invoice_numbering_settings/u);
  assert.doesNotMatch(allMigrationHints, /invoice_number_sequences/u);
  assert.doesNotMatch(allMigrationHints, /claim_invoice_number/u);
  assert.doesNotMatch(allMigrationHints, /invoice_settings_snapshot/u);
  assert.doesNotMatch(allMigrationHints, /company_snapshot/u);
  assert.doesNotMatch(allMigrationHints, /line_items_snapshot/u);
});
