"use client";
import { EmptyState } from "../empty-state";
import { ActionIcon } from "../action-icon";
import { Plus, UserRoundMinus } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { requestNotificationVerification, confirmNotificationVerification } from "@/app/notifications/actions";
import { notificationScopeSchema, type Choice, type NotificationAccess, type NotificationGrant, type NotificationPermissions, type NotificationScope } from "@/lib/notifications/model";
import { ErrorMessage, NotificationDialog, notificationDate, useNotificationCommand } from "./shared";

function scopeLabel(scope: NotificationScope, data: NotificationPermissions) { return [scope.all ? "Gehele toegestane organisatie / platformscope" : "", ...([['personnelIds', 'personnel'], ['objectIds', 'objects'], ['customerIds', 'customers'], ['tenantIds', 'tenants']] as const).flatMap(([key, choices]) => scope[key].map(id => data.scopeOptions[choices].find(o => o.id === id)?.label ?? "Niet meer beschikbaar"))].filter(Boolean).join(" · ") || "Nog geen bereik gekozen"; }
function ScopeChoices({ label, options, values, onChange }: { label: string; options: Choice[]; values: string[]; onChange: (value: string[]) => void }) { return <fieldset className="nt-selection"><legend>{label}</legend>{options.map(o => <label className="nt-check" key={o.id}><input type="checkbox" checked={values.includes(o.id)} onChange={e => onChange(e.target.checked ? [...values, o.id] : values.filter(id => id !== o.id))}/>{o.label}</label>)}</fieldset>; }
function GrantEditor({ access, data, grant, onClose, onSaved }: { access: NotificationAccess; data: NotificationPermissions; grant?: NotificationGrant; onClose: () => void; onSaved: () => void }) {
  const action = useNotificationCommand(access), [phase, setPhase] = useState<"edit" | "review" | "verify">("edit"), [userId, setUserId] = useState(grant?.userId ?? ""), [capability, setCapability] = useState(grant?.capability ?? ""), [scope, setScope] = useState(grant?.scope ?? notificationScopeSchema.parse(data.delegationScope)), [reason, setReason] = useState(""), [challengeId, setChallengeId] = useState(""), [code, setCode] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const definition = data.catalog.find(c => c.key === capability), command = grant ? "grant_revoke" : "grant_save";
  const version = grant?.version ?? data.grants.find(g => g.userId === userId && g.capability === capability)?.version ?? 0;
  const payload = grant ? { id: grant.id, version, reason } : { userId, capability, version, scope, reason };
  const send = async () => { setBusy(true); setError(""); try { const result = await requestNotificationVerification(access.workspace, command, payload); if (result.ok) { setChallengeId(result.data.challengeId); setPhase("verify"); setCode(""); } else setError(result.error); } catch { setError("De verificatie kon niet worden gestart. Er zijn geen rechten gewijzigd."); } finally { setBusy(false); } };
  return <NotificationDialog access={access} title={grant ? "Notificatierecht intrekken" : "Notificatierecht toekennen"} description="Alleen notificatierechten, zonder extra toegang tot operationele dossiers." onClose={onClose} dirty={reason.length > 0} busy={busy || action.busy}>{phase === "edit" ? <form className="nt-form" onSubmit={e => { e.preventDefault(); setPhase("review"); }}>
    {!grant && <><label>Actieve gebruiker<select aria-label="Actieve gebruiker" required value={userId} onChange={e => setUserId(e.target.value)}><option value="">Kies een gebruiker</option>{data.members.map(m => <option key={m.id} value={m.id}>{m.label}</option>)}</select></label><label>Notificatierecht<select aria-label="Notificatierecht" required value={capability} onChange={e => setCapability(e.target.value)}><option value="">Kies een recht</option>{data.catalog.map(c => <option key={c.key} value={c.key}>{c.label}</option>)}</select></label>{definition && <p className="nt-notice">{definition.description}{definition.sensitive ? " Dit is een gevoelig recht." : ""}{definition.dependencies.length ? ` Vereist ook: ${definition.dependencies.map(key => data.catalog.find(c => c.key === key)?.label ?? key).join(", ")}.` : ""}</p>}{data.delegationScope.all && !data.delegationScope.personnelIds.length && !data.delegationScope.objectIds.length && !data.delegationScope.customerIds.length && !data.delegationScope.tenantIds.length && <label className="nt-check"><input type="checkbox" checked={scope.all} onChange={e => setScope(s => ({ ...s, all: e.target.checked }))}/>Gehele organisatie / platformscope</label>}<div className="nt-grid">{([['personnelIds', 'personnel', 'Medewerkers'], ['objectIds', 'objects', 'Objecten'], ['customerIds', 'customers', 'Klanten'], ['tenantIds', 'tenants', 'Tenants']] as const).filter(([, key]) => data.scopeOptions[key].length > 0).map(([field, key, label]) => <ScopeChoices key={field} label={label} options={data.scopeOptions[key]} values={scope[field]} onChange={ids => setScope(s => ({ ...s, [field]: ids }))}/>)}</div></>}
    <label>Reden<textarea aria-label="Reden" required minLength={3} maxLength={2000} value={reason} onChange={e => setReason(e.target.value)}/></label><p className="nt-notice">Je kunt je eigen rechten niet uitbreiden. De server controleert gebruiker, scope, afhankelijkheden, delegatie en actuele revisie opnieuw.</p><button className="primary-button">Controleer wijziging</button>
  </form> : <div className="nt-form"><div className="nt-preview"><small>{grant ? "Intrekken" : "Toekennen"}</small><h3>{grant?.userLabel ?? data.members.find(m => m.id === userId)?.label}</h3><strong>{definition?.label ?? capability}</strong><p>{scopeLabel(scope, data)}</p><p className="nt-prose">{reason}</p></div>{phase === "review" ? <><p className="nt-notice">De verificatiecode is alleen bruikbaar voor deze gebruiker, dit recht, dit bereik en deze versie in je huidige sessie.</p><button className="primary-button" disabled={busy} onClick={() => { void send(); }}>Verificatiecode aanvragen</button></> : <><p className="nt-notice">De code is verstuurd naar je geregistreerde e-mailadres. Er zijn nog geen rechten gewijzigd.</p><label>Verificatiecode<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ""))}/></label><button className="primary-button" disabled={busy || action.busy || code.length !== 6} onClick={async () => { setBusy(true); setError(""); try { const result = await confirmNotificationVerification(access.workspace, challengeId, code); if (!result.ok) { setError(result.error); return; } const changed = await action.execute(command, { ...payload, verificationId: result.data.verificationId }); if (changed?.ok) onSaved(); } catch { setError("De wijziging is niet bevestigd. Controleer je invoer en vernieuw de verificatie."); } finally { setBusy(false); } }}>{grant ? "Verifiëren en intrekken" : "Verifiëren en toekennen"}</button><button className="text-link" disabled={busy || action.busy} onClick={() => { void send(); }}>Nieuwe code aanvragen</button></>}<button className="secondary-button" disabled={busy || action.busy} onClick={() => { setPhase("edit"); setChallengeId(""); setCode(""); }}>Wijziging aanpassen</button></div>}<ErrorMessage message={error || action.error}/></NotificationDialog>;
}
export function Permissions({ access, data }: { access: NotificationAccess; data: NotificationPermissions }) { const router = useRouter(), [editing, setEditing] = useState<NotificationGrant | "new" | null>(null); return <section className="nt-panel nt-permissions"><div className="nt-panel-heading"><div><h2>Notificatiebevoegdheden</h2><p className="nt-muted">Expliciete rechten in het centrale register, met eigen delegatiebevoegdheid.</p></div><ActionIcon className="primary-button" label="Notificatierecht toekennen" icon={<Plus size={17}/>} onClick={() => setEditing("new")}/></div><div className="nt-table-wrap"><table className="nt-table"><thead><tr><th>Gebruiker</th><th>Recht</th><th>Bereik</th><th>Actie</th></tr></thead><tbody>{data.grants.filter(g => g.active).map(g => <tr key={g.id}><td>{g.userLabel}</td><td>{data.catalog.find(c => c.key === g.capability)?.label ?? g.capability}</td><td>{scopeLabel(g.scope, data)}</td><td>{g.canRevoke && <ActionIcon className="resource-action" label="Intrekken" icon={<UserRoundMinus size={16}/>} onClick={() => setEditing(g)}/>}</td></tr>)}</tbody></table>{!data.grants.some(g => g.active) && <EmptyState title="Nog geen notificatiebevoegdheden" description="Gebruik de plusknop om een bevoegdheid toe te kennen."/>}</div>{data.audit.length > 0 && <details><summary>Wijzigingsgeschiedenis</summary><ul className="nt-audit">{data.audit.map(a => <li key={a.id}>{a.label}<small>{a.actorName} · {notificationDate(a.createdAt, access.timezone)}</small></li>)}</ul></details>}{editing && <GrantEditor access={access} data={data} grant={editing === "new" ? undefined : editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); router.refresh(); }}/>}</section>; }
