/** Stable account preference keys. Change copy without resetting a read receipt. */
export const guideCatalogue = {
  "backoffice.overzicht": ["Overzicht", "Hier zie je hoe je organisatie ervoor staat. Open een signaal om verder te gaan naar de bijbehorende aanvraag, werkbon of controle."],
  "backoffice.aanvragen": ["Aanvragen en offertes", "Bekijk ontvangen aanvragen en maak een offerte met de afgesproken werkzaamheden en prijzen. Open een rij voor het dossier en gebruik de tabs voor de volgende stap."],
  "backoffice.planning": ["Planbord", "Plan werkbonnen bij medewerkers. Kies een dag, open een bon of sleep deze naar de planning. Het informatie-icoon naast de titel legt de statuskleuren uit."],
  "backoffice.werkbonnen": ["Werkbonnen", "Maak een werkbon, plan medewerkers en volg de uitvoering. Open een bon voor taken, notities, rapport en historie. Gereedmelden volgt pas na het indienen van het rapport en de vereiste ondertekening."],
  "backoffice.taken": ["Taken en tarieven", "Leg standaardtaken, tarieven en checklists vast voor nieuwe opdrachten. Gebruik de tabs om categorieën, meerwerk en templates te beheren."],
  "backoffice.klanten": ["Klanten", "Beheer klanten en contactpersonen. Open een klant om objecten, afspraken, documenten en financiële gegevens te bekijken. Gebruik de filters om snel een klant te vinden."],
  "backoffice.objecten": ["Objecten", "Beheer de locaties waar het werk wordt uitgevoerd. Open een object voor instructies, bezoeken en gekoppelde werkzaamheden. Voeg nieuwe locaties toe met Nieuw object."],
  "backoffice.personeel": ["Personeel", "Beheer medewerkers, beschikbaarheid en personeelsdossiers. Open een medewerker voor de details en gebruik Actie nodig om open personeelszaken te bekijken."],
  "backoffice.controle": ["Rapportcontrole", "Controleer de ingediende uitvoering voordat je goedkeurt. Open een rapport en bekijk de tabs voor taken, notities, foto's, handtekeningen en kosten. Vraag een correctie met een duidelijke reden als iets ontbreekt."],
  "backoffice.facturen": ["Facturen", "Goedgekeurd werk verschijnt automatisch als concept. Bekijk eerst het PDF-voorbeeld en de bedragen, maak het concept definitief en verstuur de factuur. Selecteer meerdere rijen voor gezamenlijke acties."],
  "backoffice.nieuws": ["Nieuws", "Bekijk nieuws voor medewerkers of publiceer een nieuw bericht via Voeg toe. Je kunt een pushmelding meesturen en later zien wie het bericht heeft gelezen."],
  "backoffice.opvolging": ["Opvolging", "Hier staan open acties uit de verbonden dossiers. Open de bron om een actie uit te voeren of af te ronden; alle overzichten volgen diezelfde registratie."],
  "backoffice.instellingen": ["Instellingen", "Stel de huisstijl en werkafspraken van je organisatie in. Kies een tab, wijzig de gewenste gegevens en sla je wijzigingen op."],
  "backoffice.meldingen": ["Personeelsmeldingen", "Bekijk vragen en meldingen van medewerkers. Open een gesprek om de berichten te lezen, te antwoorden en de melding op te volgen."],
  "backoffice.support": ["Support", "Stel een vraag aan Fieldgrid of volg een bestaand supportgesprek. Beschrijf wat er gebeurt en voeg zo nodig een veilig bestand toe."],
  "backoffice.notificaties": ["Notificaties", "Open een melding in het compacte venster en ga via de actieknop naar de bron. Gelezen markeren en archiveren wijzigen alleen je inbox."],
  "staff.planning": ["Dagplanning", "Hier staan jouw toegewezen werkbonnen. Open een bon voor locatie en instructies, registreer onderweg en start daarna je werk. Rond je eigen inzet af voordat je het rapport indient."],
  "staff.nieuws": ["Teamnieuws", "Lees de berichten van je organisatie. Open een bericht en markeer het na het lezen als gelezen."],
  "staff.uren": ["Mijn uren", "Bekijk je geregistreerde werk- en reistijd. Kies een registratie om een correctie met reden aan te vragen; je oorspronkelijke uren blijven staan totdat die is behandeld."],
  "staff.meer": ["Personeelszaken", "Hier vind je je profiel, verlof, beschikbaarheid, documenten en instellingen. Kies een onderdeel om de gegevens te bekijken of een verzoek in te dienen."],
  "staff.verlof": ["Verlof", "Bekijk je verlof en vraag een nieuwe periode aan. Controleer de datums voordat je verstuurt en volg hier de beoordeling van je aanvraag."],
  "staff.beschikbaarheid": ["Beschikbaarheid", "Geef aan wanneer je beschikbaar bent en bekijk open diensten. Je organisatie gebruikt deze informatie bij het plannen van werk."],
  "staff.documenten": ["Mijn documenten", "Open de documenten die je organisatie met jou heeft gedeeld. De naam en versie helpen je om het juiste document te kiezen."],
  "staff.instellingen": ["Mijn instellingen", "Pas je voorkeuren voor het portaal en meldingen aan. Pushmeldingen stel je apart in op ieder apparaat waarop je ze wilt ontvangen."],
  "staff.profiel": ["Mijn profiel", "Controleer je contact- en vervoersgegevens. Pas onjuiste gegevens aan en sla de wijzigingen op voor je organisatie."],
  "staff.tickets": ["Mijn meldingen", "Stel een vraag over je werk of volg een eerder gesprek. Open een melding om berichten te lezen, te antwoorden of een bestand toe te voegen."],
  "staff.notifications": ["Mijn notificaties", "Bekijk meldingen voor jouw account. Open een melding en ga naar de bron voor de bijbehorende actie. Een leesbevestiging rondt die actie niet af."],
  "customer.dashboard": ["Mijn overzicht", "Hier zie je de volgende afspraak, open aanvragen en facturen voor je klantaccount. Kies een kaart om de details te bekijken."],
  "customer.objects": ["Mijn objecten", "Bekijk je locaties en de instructies voor het werk. Open een object voor afspraken en informatie, of voeg een locatie toe als je account dat toestaat."],
  "customer.appointments": ["Mijn afspraken", "Bekijk geplande en uitgevoerde bezoeken. Open een afspraak om de werkzaamheden te bekijken of een instructie door te geven."],
  "customer.reports": ["Mijn rapporten", "Bekijk de vrijgegeven resultaten van uitgevoerde werkzaamheden. Open een rapport om de PDF en de bijbehorende informatie te lezen."],
  "customer.invoices": ["Mijn facturen", "Bekijk je facturen en het openstaande bedrag. Open een factuur voor de PDF of selecteer facturen om een betaling te controleren en te starten."],
  "customer.services": ["Diensten en aanvragen", "Vraag werkzaamheden voor een object aan en volg de behandeling. Open een aanvraag om de afspraken of offerte te bekijken en een beslissing door te geven."],
  "customer.tickets": ["Mijn gesprekken", "Stel een vraag aan je contactpersoon of technische support. Open een gesprek om de antwoorden te lezen en te reageren."],
  "customer.news": ["Nieuws", "Lees updates en praktische informatie van je organisatie. Open een bericht om de volledige tekst te bekijken."],
  "customer.profile": ["Mijn gegevens", "Controleer je contactgegevens en factuuradres en pas ze aan als je account dat toestaat. Sla je e-mailvoorkeuren apart op."],
  "customer.notifications": ["Mijn meldingen", "Bekijk wat er speelt bij jouw objecten en afspraken. Open een melding om de betreffende informatie te bekijken en markeer gelezen berichten als gelezen."],
  "customer.more": ["Meer onderdelen", "Kies hier een ander onderdeel van je klantomgeving, zoals nieuws, gesprekken of je gegevens."],
  "feature.tasks": ["Werkzaamheden", "Bekijk de afgesproken taken en open een taak voor de uitvoering en individuele bijdragen. Leg de werkelijk uitgevoerde hoeveelheid vast; extra werktijd geeft op zichzelf geen extra kosten."],
  "feature.checklists": ["Checklists", "Beantwoord de controles die bij deze opdracht horen. Verplichte vragen moeten zijn afgehandeld voordat het rapport kan worden ingediend."],
  "feature.people": ["Medewerkers", "Bekijk wie aan deze opdracht werkt en de geplande en werkelijke inzet. Wijzig de planning via de beschikbare acties; eerdere inzet blijft in de historie bewaard."],
  "feature.travel": ["Reisinformatie", "Bekijk de reisplanning per medewerker. Open een medewerker voor route en verwachte reistijd. Een reisadvies is geen geregistreerde of factureerbare reistijd."],
  "feature.time": ["Werk en reistijd", "Bekijk geregistreerde werk- en reisuren met begin, einde en status. Deze registraties laten zien wanneer de inzet heeft plaatsgevonden."],
  "feature.instructions": ["Instructies", "Lees de afspraken voor de locatie en deze uitvoering voordat je begint. Geef aanvullingen via de beschikbare notitie- of verzoekactie door."],
  "feature.notes": ["Notities", "Lees of voeg opmerkingen over de uitvoering toe. Interne notities zijn bedoeld voor je organisatie. Een bijdrage voor het klantrapport wordt eerst gecontroleerd."],
  "feature.files": ["Foto's en documenten", "Open bestanden om de uitvoering te controleren. Voeg foto's of documenten toe via de uploadactie en controleer of ze voor het klantrapport bestemd zijn."],
  "feature.history": ["Actietijdlijn", "Volg de belangrijke stappen in het dossier. Bij iedere registratie zie je wat er is gebeurd, wanneer en door wie."],
  "feature.materials": ["Materiaal en onkosten", "Leg gebruikt materiaal en gemaakte onkosten vast met hoeveelheid en bedrag. Controleer de prijs en zichtbaarheid voor de klant voordat je opslaat."],
  "feature.extra": ["Meerwerk", "Leg extra werkzaamheden en de prijsafspraak apart vast. Voer meerwerk pas uit volgens de afgesproken goedkeuring en registreer daarna het resultaat."],
  "feature.related": ["Gekoppelde werkzaamheden", "Maak een deelbon of opvolgbon voor werk dat apart wordt uitgevoerd. Open een gekoppelde bon om de bijbehorende planning en uitvoering te bekijken."],
  "feature.costs": ["Kostenoverzicht", "Vergelijk de oorspronkelijke opdracht met uitgevoerd en goedgekeurd meerwerk, materiaal en onkosten. Het overzicht toont de bronbedragen; de factuur volgt de vrijgegeven facturatieregels."],
  "feature.delivery": ["Rapport en oplevering", "Controleer de werkzaamheden en opmerkingen en open het rapport. Leg de benodigde handtekeningen vast en dien de actuele versie in. Pas daarna kan de bon gereedgemeld worden."],
  "feature.signature": ["Ondertekening", "Open eerst het rapport en de opgenomen bijlagen. Vul je naam in, controleer je opmerkingen en teken de getoonde rapportversie. Sla de handtekening daarna op."],
  "feature.review": ["Rapport controleren", "Bekijk alle controletabs en de actuele handtekeningen en kosten. Keur een compleet rapport goed of vraag een correctie met een duidelijke reden."],
  "feature.customer-report": ["Klantrapport", "Dit is de vastgelegde versie voor de klant. Open de PDF om de gedeelde werkzaamheden, opmerkingen en ondertekening te controleren."],
  "feature.invoice": ["Factuurvoorbeeld", "Controleer de PDF en de bedragen. Een concept heeft nog geen definitief factuurnummer. Maak het pas definitief als de gegevens kloppen."],
  "feature.payment": ["Betalingen", "Bekijk geregistreerde betalingen of boek een ontvangen betaling via de aparte actie. Controleer klant, factuur, bedrag en datum voordat je bevestigt."],
  "feature.contacts": ["Contactpersonen", "Bekijk wie bij deze klant of opdracht betrokken is. Gebruik de vastgelegde contactgegevens om de juiste persoon te bereiken."],
  "feature.templates": ["Templates", "Bewaar terugkerende werkzaamheden en checklists als template. Publiceer een gecontroleerde versie voordat je die voor nieuwe opdrachten gebruikt."],
  "feature.categories": ["Categorieën", "Groepeer taken met een herkenbare categorie en codeprefix. Kies de juiste categorie wanneer je een standaardtaak toevoegt."],
  "feature.branding": ["Huisstijl", "Stel het logo en de kleuren van je organisatie in. Controleer het voorbeeld en sla de huisstijl op voor de portalen en nieuwe documenten."],
  "feature.account-setup": ["Je klantomgeving instellen", "Controleer de gegevens van je klantaccount en kies je voorkeuren. Doorloop de stappen en bevestig de gegevens als ze kloppen."],
  "feature.customer-visit": ["Afspraak bekijken", "Bekijk de planning, werkzaamheden en gedeelde documenten van deze afspraak. Geef aanvullende instructies door via het daarvoor bestemde veld."],
  "feature.customer-object": ["Object bekijken", "Bekijk de gegevens en afspraken van deze locatie. Gebruik de beschikbare acties om een instructie door te geven of een dienst aan te vragen."],
  "feature.customer-request": ["Aanvraag en offerte", "Bekijk de aangevraagde werkzaamheden en de voorgestelde prijs. Controleer de details voordat je een offerte accepteert of een wijziging doorgeeft."],
} as const;

export type GuideKey = keyof typeof guideCatalogue;
export function isGuideKey(value: string): value is GuideKey { return Object.hasOwn(guideCatalogue,value); }

/** Only fixed function headings are mapped; resource names never become keys. */
export const sectionGuideKeys: Record<string, GuideKey> = {
  "Mijn tickets": "staff.tickets", "Gekoppelde tickets": "backoffice.meldingen",
  "Taken": "feature.tasks", "Werkzaamheden": "feature.tasks", "Taken & resultaten": "feature.tasks", "Uitgevoerde werkzaamheden": "feature.tasks", "Jouw bijdrage": "feature.tasks",
  "Checklists": "feature.checklists", "Basischecklists": "feature.checklists", "Controles": "feature.checklists",
  "Medewerkers": "feature.people", "Medewerkers & uitvoering": "feature.people", "Reisinformatie": "feature.travel",
  "Werk en reis": "feature.time", "Werk- en reisuren": "feature.time", "WERKTIJD": "feature.time",
  "Instructies": "feature.instructions", "Instructies voor deze uitvoering": "feature.instructions", "Voorbereiding & instructies": "feature.instructions",
  "Notities": "feature.notes", "Alle notities": "feature.notes", "Notitie of bestand toevoegen": "feature.notes", "Laatste opmerking": "feature.notes",
  "Foto’s en documenten": "feature.files", "Alle bijlagen": "feature.files", "Bijlagen": "feature.files", "Documenten bekijken": "feature.files",
  "Belangrijke acties": "feature.history", "Actietijdlijn": "feature.history", "Wijzigingsgeschiedenis": "feature.history", "Statusverloop": "feature.history", "TIJDLIJN": "feature.history",
  "Materiaal & onkosten": "feature.materials", "Materiaalverbruik": "feature.materials", "Materiaal": "feature.materials", "Onkosten": "feature.materials",
  "Meerwerk": "feature.extra", "Toegestaan meerwerk": "feature.extra", "Gekoppelde werkzaamheden": "feature.related", "Terugkerend werk": "feature.related",
  "Kostenoverzicht": "feature.costs", "Totaaloverzicht": "feature.costs", "Oorspronkelijke opdracht": "feature.costs", "Opdracht & meerwerk": "feature.costs", "Facturatie & afspraken": "feature.costs",
  "Opleverrapport": "feature.delivery", "Rapport & ondertekening": "feature.delivery", "Rapport & handtekening": "feature.delivery",
  "Handtekening opdrachtgever": "feature.signature", "Handtekening medewerker": "feature.signature", "Werkrapport": "feature.history", "Handtekeningen": "feature.signature", "Rapportcontrole": "feature.review", "GOEDKEURING": "feature.review", "Oplevering": "feature.review",
  "Klantrapport": "feature.customer-report", "Factuurvoorbeeld": "feature.invoice", "Bedragen en bronregels": "feature.invoice", "Facturen & PDF": "feature.invoice",
  "Betalingen": "feature.payment", "Betaling boeken": "feature.payment", "Betaaloverzicht": "feature.payment", "Contactpersonen": "feature.contacts", "Klant & locatie": "feature.contacts",
  "Templates": "feature.templates", "Categorieën": "feature.categories", "Huisstijl": "feature.branding",
  "Correctie doorgeven": "staff.uren", "Verlof aanvragen": "staff.verlof", "Pushmeldingen instellen": "staff.instellingen", "Je klantomgeving instellen": "feature.account-setup",
};
