-- ─── Sprint 3: Sequentiële codes ─────────────────────────────────────────────
-- Adds auto-generated, unique, prefixed codes to customers, objects, personnel,
-- and assignments. Codes are generated by a PL/pgSQL trigger so application code
-- never needs to supply them.
--
-- Prefixes:  KLA (customers)  OBJ (objects)  MED (personnel)  OPD (assignments)
-- Format:    <PREFIX>-<zero-padded-seq>   e.g. KLA-0001, OPD-00042

-- ─── Sequence registry ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS code_sequences (
  entity     text    PRIMARY KEY,
  prefix     text    NOT NULL,
  last_value bigint  NOT NULL DEFAULT 0,
  padding    int     NOT NULL DEFAULT 4
);

INSERT INTO code_sequences (entity, prefix, last_value, padding) VALUES
  ('customers',   'KLA', 0, 4),
  ('objects',     'OBJ', 0, 4),
  ('personnel',   'MED', 0, 4),
  ('assignments', 'OPD', 0, 5)
ON CONFLICT (entity) DO NOTHING;

-- ─── Atomic sequence function ─────────────────────────────────────────────────
-- Uses SELECT … FOR UPDATE to guarantee no two concurrent inserts get the same
-- value even under high concurrency.

CREATE OR REPLACE FUNCTION next_entity_code(p_entity text)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  v_prefix   text;
  v_padding  int;
  v_next_val bigint;
BEGIN
  UPDATE code_sequences
  SET    last_value = last_value + 1
  WHERE  entity = p_entity
  RETURNING prefix, last_value, padding
  INTO   v_prefix, v_next_val, v_padding;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Unknown code sequence entity: %', p_entity;
  END IF;

  RETURN v_prefix || '-' || lpad(v_next_val::text, v_padding, '0');
END;
$$;

-- ─── Add missing columns ──────────────────────────────────────────────────────

ALTER TABLE personnel   ADD COLUMN IF NOT EXISTS code varchar(20);
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS code varchar(20);

-- ─── Backfill existing rows ───────────────────────────────────────────────────
-- Customers and objects may already have user-entered codes; only backfill NULLs.
-- Personnel and assignments had no code column, so all rows need a code.

UPDATE customers   SET code = next_entity_code('customers')   WHERE code IS NULL;
UPDATE objects     SET code = next_entity_code('objects')     WHERE code IS NULL;
UPDATE personnel   SET code = next_entity_code('personnel');
UPDATE assignments SET code = next_entity_code('assignments');

-- ─── Enforce NOT NULL + UNIQUE ────────────────────────────────────────────────

-- customers: code was already UNIQUE (migration 001), just add NOT NULL
ALTER TABLE customers ALTER COLUMN code SET NOT NULL;

-- objects: add UNIQUE (not present in migration 001) + NOT NULL
ALTER TABLE objects ALTER COLUMN code SET NOT NULL;
DO $$ BEGIN
  ALTER TABLE objects ADD CONSTRAINT objects_code_unique UNIQUE (code);
EXCEPTION WHEN duplicate_table THEN NULL;
END $$;

-- personnel: brand-new column
ALTER TABLE personnel ALTER COLUMN code SET NOT NULL;
ALTER TABLE personnel ADD CONSTRAINT personnel_code_unique UNIQUE (code);

-- assignments: brand-new column
ALTER TABLE assignments ALTER COLUMN code SET NOT NULL;
ALTER TABLE assignments ADD CONSTRAINT assignments_code_unique UNIQUE (code);

-- ─── Trigger functions ────────────────────────────────────────────────────────
-- Each BEFORE INSERT trigger sets NEW.code if the application did not supply one.
-- This allows the application to omit code entirely; the DB fills it in.

CREATE OR REPLACE FUNCTION trg_customers_set_code()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.code IS NULL THEN
    NEW.code := next_entity_code('customers');
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_objects_set_code()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.code IS NULL THEN
    NEW.code := next_entity_code('objects');
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_personnel_set_code()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.code IS NULL THEN
    NEW.code := next_entity_code('personnel');
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION trg_assignments_set_code()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.code IS NULL THEN
    NEW.code := next_entity_code('assignments');
  END IF;
  RETURN NEW;
END;
$$;

-- ─── Attach triggers ──────────────────────────────────────────────────────────

DROP TRIGGER IF EXISTS customers_set_code   ON customers;
DROP TRIGGER IF EXISTS objects_set_code     ON objects;
DROP TRIGGER IF EXISTS personnel_set_code   ON personnel;
DROP TRIGGER IF EXISTS assignments_set_code ON assignments;

CREATE TRIGGER customers_set_code
  BEFORE INSERT ON customers
  FOR EACH ROW EXECUTE FUNCTION trg_customers_set_code();

CREATE TRIGGER objects_set_code
  BEFORE INSERT ON objects
  FOR EACH ROW EXECUTE FUNCTION trg_objects_set_code();

CREATE TRIGGER personnel_set_code
  BEFORE INSERT ON personnel
  FOR EACH ROW EXECUTE FUNCTION trg_personnel_set_code();

CREATE TRIGGER assignments_set_code
  BEFORE INSERT ON assignments
  FOR EACH ROW EXECUTE FUNCTION trg_assignments_set_code();
