-- ============================================================
-- Sprint 3 — Facturatie module
-- Run this in the Supabase SQL Editor (project dashboard → SQL Editor)
-- ============================================================

-- ── 1. Register invoices in code_sequences ────────────────────────────────────

INSERT INTO code_sequences (entity, prefix, last_value, padding)
VALUES ('invoices', 'FACT', 0, 4)
ON CONFLICT (entity) DO NOTHING;

-- ── 2. invoices table ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS invoices (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Auto-generated by DB trigger trg_invoices_set_number
  -- Format: FACT-YYYY-NNNN  (year of creation + zero-padded sequence)
  invoice_number   varchar(30) NOT NULL UNIQUE DEFAULT '',

  customer_id      uuid        NOT NULL REFERENCES customers(id)   ON DELETE RESTRICT,
  assignment_id    uuid        NOT NULL REFERENCES assignments(id) ON DELETE RESTRICT,

  -- Financial fields (all in EUR)
  amount           numeric(12, 2) NOT NULL DEFAULT 0,  -- ex-VAT subtotal
  vat_percentage   numeric(5,  2) NOT NULL DEFAULT 21, -- e.g. 21.00
  vat_amount       numeric(12, 2) NOT NULL DEFAULT 0,  -- computed: amount * vat_percentage / 100
  total_amount     numeric(12, 2) NOT NULL DEFAULT 0,  -- amount + vat_amount

  -- Status: draft → sent → paid  (or cancelled from draft/sent)
  status           varchar(20) NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft', 'sent', 'paid', 'cancelled')),

  due_date         date        NOT NULL,
  paid_date        date,

  notes            text,

  created_by       uuid,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- ── 3. Indexes ────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS invoices_customer_id_idx   ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS invoices_assignment_id_idx ON invoices(assignment_id);
CREATE INDEX IF NOT EXISTS invoices_status_idx        ON invoices(status);
CREATE INDEX IF NOT EXISTS invoices_due_date_idx      ON invoices(due_date);

-- ── 4. Auto-number trigger ─────────────────────────────────────────────────────
-- Generates FACT-<YYYY>-<seq> on INSERT if invoice_number is blank.

CREATE OR REPLACE FUNCTION trg_invoices_set_number()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_year text;
  v_seq  bigint;
  v_pad  int;
BEGIN
  IF NEW.invoice_number IS NULL OR NEW.invoice_number = '' THEN
    v_year := EXTRACT(YEAR FROM now())::text;

    UPDATE code_sequences
    SET    last_value = last_value + 1
    WHERE  entity = 'invoices'
    RETURNING last_value, padding INTO v_seq, v_pad;

    NEW.invoice_number := 'FACT-' || v_year || '-' || lpad(v_seq::text, v_pad, '0');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS invoices_set_number ON invoices;

CREATE TRIGGER invoices_set_number
  BEFORE INSERT ON invoices
  FOR EACH ROW EXECUTE FUNCTION trg_invoices_set_number();

-- ── 5. updated_at trigger ─────────────────────────────────────────────────────

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'invoices_updated_at'
  ) THEN
    CREATE TRIGGER invoices_updated_at
      BEFORE UPDATE ON invoices
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END;
$$;

-- ── 6. Row-Level Security ─────────────────────────────────────────────────────

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

-- Backoffice uses service_role key (bypasses RLS).
-- Only management/administration roles access invoices in the backoffice.
-- Customer-portal will need its own read policy in a future migration.

-- ── 7. Permissions ────────────────────────────────────────────────────────────

INSERT INTO permissions (resource, action, description)
VALUES
  ('invoices', 'read',  'View invoices list and detail pages'),
  ('invoices', 'write', 'Create and manage invoices'),
  ('invoices', 'send',  'Mark invoices as sent to customers')
ON CONFLICT (resource, action) DO NOTHING;

-- ── 8. Grant permissions to roles ─────────────────────────────────────────────

-- Management: all invoice permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'Management'
  AND p.resource = 'invoices'
ON CONFLICT DO NOTHING;

-- Administration: read + write + send
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'Administration'
  AND p.resource = 'invoices'
  AND p.action IN ('read', 'write', 'send')
ON CONFLICT DO NOTHING;
