-- ============================================================
-- Migration 008: Sprint 3 — Offerte- en goedkeuringsflow
-- Run this manually in the Supabase SQL Editor.
-- ============================================================

-- ── 1. Add OFF prefix to code_sequences ──────────────────────────────────────

INSERT INTO code_sequences (prefix, last_sequence, year)
VALUES ('OFF', 0, EXTRACT(YEAR FROM NOW())::int)
ON CONFLICT (prefix, year) DO NOTHING;

-- ── 2. Create quotes table ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS quotes (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Auto-generated by trigger trg_quotes_set_number — never set by app code
  quote_number     varchar(30) NOT NULL UNIQUE DEFAULT '',

  assignment_id    uuid NOT NULL REFERENCES assignments(id) ON DELETE RESTRICT,
  customer_id      uuid NOT NULL REFERENCES customers(id)   ON DELETE RESTRICT,

  -- Proposed amount in EUR (excl. VAT)
  amount           numeric(12, 2) NOT NULL DEFAULT 0,

  -- Quote expiry date (YYYY-MM-DD)
  validity_date    date NOT NULL,

  -- Lifecycle: draft → sent → approved | rejected | expired
  status           varchar(20) NOT NULL DEFAULT 'draft'
                   CHECK (status IN ('draft', 'sent', 'approved', 'rejected', 'expired')),

  -- Internal notes — not shown to customers
  notes            text,

  -- Populated when management rejects a quote
  rejection_reason text,

  -- Audit fields
  created_by       uuid,
  approved_by      uuid,
  approved_at      timestamptz,

  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- ── 3. updated_at trigger ────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION trg_set_quotes_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_quotes_updated_at ON quotes;
CREATE TRIGGER trg_quotes_updated_at
  BEFORE UPDATE ON quotes
  FOR EACH ROW EXECUTE FUNCTION trg_set_quotes_updated_at();

-- ── 4. Auto-numbering trigger (OFF-YYYY-NNNN) ────────────────────────────────

CREATE OR REPLACE FUNCTION trg_fn_quotes_set_number()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_year  int  := EXTRACT(YEAR FROM now())::int;
  v_seq   int;
BEGIN
  -- Upsert the sequence row for the current year
  INSERT INTO code_sequences (prefix, year, last_sequence)
  VALUES ('OFF', v_year, 0)
  ON CONFLICT (prefix, year) DO NOTHING;

  -- Atomically increment and retrieve
  UPDATE code_sequences
  SET last_sequence = last_sequence + 1
  WHERE prefix = 'OFF' AND year = v_year
  RETURNING last_sequence INTO v_seq;

  NEW.quote_number := 'OFF-' || v_year || '-' || LPAD(v_seq::text, 4, '0');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_quotes_set_number ON quotes;
CREATE TRIGGER trg_quotes_set_number
  BEFORE INSERT ON quotes
  FOR EACH ROW EXECUTE FUNCTION trg_fn_quotes_set_number();

-- ── 5. Indexes ───────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_quotes_assignment_id  ON quotes (assignment_id);
CREATE INDEX IF NOT EXISTS idx_quotes_customer_id    ON quotes (customer_id);
CREATE INDEX IF NOT EXISTS idx_quotes_status         ON quotes (status);
CREATE INDEX IF NOT EXISTS idx_quotes_validity_date  ON quotes (validity_date);

-- ── 6. Enable RLS ────────────────────────────────────────────────────────────

ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;

-- Backoffice uses service_role key — bypass RLS for all management operations.
-- Customer portal (future) will get separate restrictive policies.

-- ── 7. Add permissions ───────────────────────────────────────────────────────

INSERT INTO permissions (resource, action, description)
VALUES
  ('quotes', 'read',    'Offertes bekijken'),
  ('quotes', 'write',   'Offertes aanmaken en bewerken'),
  ('quotes', 'approve', 'Offertes goedkeuren of afwijzen')
ON CONFLICT (resource, action) DO NOTHING;

-- ── 8. Grant permissions to roles ────────────────────────────────────────────

-- Management: all quote permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Management'
  AND p.resource = 'quotes'
ON CONFLICT DO NOTHING;

-- Administration: all quote permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Administration'
  AND p.resource = 'quotes'
ON CONFLICT DO NOTHING;

-- Planning: read-only
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Planning'
  AND p.resource = 'quotes'
  AND p.action   = 'read'
ON CONFLICT DO NOTHING;

-- Teamlead: read-only
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Teamlead'
  AND p.resource = 'quotes'
  AND p.action   = 'read'
ON CONFLICT DO NOTHING;
