-- ============================================================
-- Migration 008: Sprint 3 — Offerte- en goedkeuringsflow
-- Run this manually in the Supabase SQL Editor.
-- ============================================================

-- ── 1. Register quotes in code_sequences ────────────────────────────────────

INSERT INTO code_sequences (entity, prefix, last_value, padding)
VALUES ('quotes', 'OFF', 0, 4)
ON CONFLICT (entity) DO NOTHING;

-- ── 2. Create quotes table ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS quotes (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Auto-generated by trigger trg_quotes_set_number — never set by app code
  -- Format: OFF-YYYY-NNNN
  quote_number     varchar(30) NOT NULL UNIQUE DEFAULT '',

  assignment_id    uuid NOT NULL REFERENCES assignments(id) ON DELETE RESTRICT,
  customer_id      uuid NOT NULL REFERENCES customers(id)   ON DELETE RESTRICT,

  -- Proposed amount in EUR (excl. VAT)
  amount           numeric(12, 2) NOT NULL DEFAULT 0,

  -- Quote expiry date (YYYY-MM-DD)
  validity_date    date NOT NULL,

  -- Lifecycle: draft → sent → approved | rejected | expired
  status           varchar(20) NOT NULL DEFAULT 'draft'
                   CHECK (status IN ('draft', 'sent', 'approved', 'rejected', 'expired')),

  -- Internal notes — not shown to customers
  notes            text,

  -- Populated when management rejects a quote
  rejection_reason text,

  -- Audit fields
  created_by       uuid,
  approved_by      uuid,
  approved_at      timestamptz,

  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- ── 3. updated_at trigger ────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION trg_set_quotes_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_quotes_updated_at ON quotes;
CREATE TRIGGER trg_quotes_updated_at
  BEFORE UPDATE ON quotes
  FOR EACH ROW EXECUTE FUNCTION trg_set_quotes_updated_at();

-- ── 4. Auto-numbering trigger (OFF-YYYY-NNNN) ────────────────────────────────
-- Follows the same pattern as trg_invoices_set_number in migration 007.

CREATE OR REPLACE FUNCTION trg_quotes_set_number()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_year text;
  v_seq  bigint;
  v_pad  int;
BEGIN
  IF NEW.quote_number IS NULL OR NEW.quote_number = '' THEN
    v_year := EXTRACT(YEAR FROM now())::text;

    UPDATE code_sequences
    SET    last_value = last_value + 1
    WHERE  entity = 'quotes'
    RETURNING last_value, padding INTO v_seq, v_pad;

    NEW.quote_number := 'OFF-' || v_year || '-' || lpad(v_seq::text, v_pad, '0');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS quotes_set_number ON quotes;
CREATE TRIGGER quotes_set_number
  BEFORE INSERT ON quotes
  FOR EACH ROW EXECUTE FUNCTION trg_quotes_set_number();

-- ── 5. Indexes ───────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_quotes_assignment_id  ON quotes (assignment_id);
CREATE INDEX IF NOT EXISTS idx_quotes_customer_id    ON quotes (customer_id);
CREATE INDEX IF NOT EXISTS idx_quotes_status         ON quotes (status);
CREATE INDEX IF NOT EXISTS idx_quotes_validity_date  ON quotes (validity_date);

-- ── 6. Enable RLS ────────────────────────────────────────────────────────────

ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;

-- Backoffice uses service_role key — bypasses RLS for all management operations.
-- Customer portal (future) will get separate restrictive policies.

-- ── 7. Add permissions ───────────────────────────────────────────────────────

INSERT INTO permissions (resource, action, description)
VALUES
  ('quotes', 'read',    'Offertes bekijken'),
  ('quotes', 'write',   'Offertes aanmaken en bewerken'),
  ('quotes', 'approve', 'Offertes goedkeuren of afwijzen')
ON CONFLICT (resource, action) DO NOTHING;

-- ── 8. Grant permissions to roles ────────────────────────────────────────────

-- Management: all quote permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Management'
  AND p.resource = 'quotes'
ON CONFLICT DO NOTHING;

-- Administration: all quote permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Administration'
  AND p.resource = 'quotes'
ON CONFLICT DO NOTHING;

-- Planning: read-only
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Planning'
  AND p.resource = 'quotes'
  AND p.action   = 'read'
ON CONFLICT DO NOTHING;

-- Teamlead: read-only
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Teamlead'
  AND p.resource = 'quotes'
  AND p.action   = 'read'
ON CONFLICT DO NOTHING;
