"use client";
import { useMemo, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Mail, Pencil, Plus, RefreshCw, Search, ShieldCheck, ShieldOff } from "lucide-react";
import { toast } from "sonner";
import { PageHeading } from "@/components/fieldgrid/page-heading";
import { ContentTabs } from "@/components/fieldgrid/content-tabs";
import { ActionIcon } from "@/components/fieldgrid/action-icon";
import { EmptyState } from "@/components/fieldgrid/empty-state";
import { ListPagination, useListPagination } from "@/components/fieldgrid/list-pagination";
import { WorkOrderDialog } from "@/components/fieldgrid/work-orders/dialog";
import type { SupportMember, SupportSnapshot } from "@/lib/platform/team-model";
import { changeSupportMember, inviteSupportMember } from "./actions";
import "./team.css";

const brand = { primaryColor: "#222C35", accentColor: "#41AC42" };
const deliveryLabels = { pending: "In wachtrij", sending: "Uitkomst nog onbekend", sent: "Verzonden", failed: "Verzending mislukt", uncertain: "Providerontvangst onzeker", suppressed: "Niet verstuurd" };
const auditLabels: Record<string, string> = { invite: "Uitgenodigd", update: "Profiel bijgewerkt", revoke: "Toegang ingetrokken", resend: "Opnieuw uitgenodigd" };
const scopeLabel = (member: SupportMember, data: SupportSnapshot) => member.allTenants ? "Alle actieve ticketorganisaties" : member.tenantIds.map(id => data.tenants.find(tenant => tenant.id === id)?.name ?? "Organisatie niet actief").join(", ");

export function SupportTeam({ initial }: { initial: SupportSnapshot }) {
  const router = useRouter(), [query, setQuery] = useState(""), [tab, setTab] = useState("users");
  const [editing, setEditing] = useState<SupportMember | "new" | null>(null), [revoking, setRevoking] = useState<SupportMember | null>(null), [pending, start] = useTransition();
  const [descending, setDescending] = useState(false);
  const rows = useMemo(() => initial.members.filter(member => `${member.name} ${member.email}`.toLocaleLowerCase("nl").includes(query.toLocaleLowerCase("nl"))).sort((a, b) => a.name.localeCompare(b.name, "nl") * (descending ? -1 : 1)), [initial.members, query, descending]);
  const pagination = useListPagination(rows);
  const change = (input: unknown) => start(async () => {
    try {
    const result = await changeSupportMember(input);
    if (!result.ok) toast.error(result.error); else {
      if (result.warning) toast.warning(result.warning); else toast.success("Supportteam bijgewerkt.");
      setRevoking(null); router.refresh();
    }
    } catch { toast.error("Opslaan is niet bevestigd. Vernieuw het supportteam en controleer de actuele status."); }
  });
  return <div className="fg-team"><PageHeading eyebrow="PLATFORM / TOEGANG" title="Supportteam" help="Supportmedewerkers gebruiken OTP en krijgen uitsluitend gedeelde supporttickets binnen hun toegewezen bereik. Platformbeheer en tenantdossiers blijven afzonderlijke bevoegdheden." actions={<><label className="fg-search"><Search size={16}/><input aria-label="Supportmedewerkers zoeken" placeholder="Naam of e-mailadres…" value={query} onChange={event => { setQuery(event.target.value); pagination.setPage(1); }}/></label><ActionIcon label="Supportteam vernieuwen" icon={<RefreshCw size={18}/>} onClick={() => router.refresh()}/><ActionIcon label="Supportmedewerker uitnodigen" className="primary-button" icon={<Plus size={18}/>} onClick={() => setEditing("new")}/></>}/>
    <ContentTabs label="Supportteam" value={tab} onValueChange={setTab} tabs={[
      { id: "users", title: "Medewerkers", content: <><section className="panel resource-table-panel"><div className="table-scroll"><table className="resource-table"><thead><tr><th scope="col" aria-sort={descending ? "descending" : "ascending"}><button type="button" onClick={() => setDescending(!descending)}>Naam {descending ? "↓" : "↑"}</button></th><th scope="col">E-mailadres</th><th scope="col">Supportbereik</th><th scope="col">Toegang / uitnodiging</th><th scope="col">Acties</th></tr></thead><tbody>{pagination.items.map(member => <tr key={member.id}><td><button className="text-link" onClick={() => setEditing(member)}><strong>{member.name}</strong></button></td><td>{member.email}</td><td>{scopeLabel(member, initial)}</td><td>{member.status === "active" ? "Actief" : "Ingetrokken"}<small className="fg-team-muted">{deliveryLabels[member.deliveryStatus]}</small></td><td><div className="resource-header-actions"><ActionIcon label={`Bewerk ${member.name}`} icon={<Pencil size={16}/>} onClick={() => setEditing(member)}/><ActionIcon label={`Nodig ${member.name} opnieuw uit`} icon={<Mail size={16}/>} disabled={pending || member.status !== "active" || ["pending", "sending", "uncertain"].includes(member.deliveryStatus)} onClick={() => change({ command: "resend", userId: member.id, version: member.version, requestId: crypto.randomUUID() })}/><ActionIcon label={`Trek toegang van ${member.name} in`} icon={<ShieldOff size={16}/>} disabled={pending || member.status !== "active"} onClick={() => setRevoking(member)}/></div></td></tr>)}</tbody></table></div>{!rows.length && <EmptyState title={initial.members.length ? "Geen supportmedewerkers gevonden" : "Nog geen supportmedewerkers"} description={initial.members.length ? "Pas de zoekterm aan." : "Gebruik de plusknop bovenaan om een supportmedewerker uit te nodigen."}/>}</section><ListPagination {...pagination} noun="medewerkers" preferenceKey="platform-support-team" onPageChange={pagination.setPage} onPageSizeChange={pagination.setPageSize}/></> },
      { id: "rights", title: "Rechten", content: <section className="fg-team-surface"><h2>Supportmedewerker</h2><p>Deze vaste rol geeft vier bevoegdheden binnen het gekozen organisatiebereik. Een organisatie moet actief zijn en de ticketmodule gebruiken.</p><div className="fg-team-rights">{[["Lezen", "Expliciet gedeelde supportgesprekken bekijken."], ["Beantwoorden", "Antwoorden versturen aan de tenant."], ["Interne notities", "Notities voor bevoegde Fieldgrid-supportmedewerkers."], ["Afhandelen", "Toewijzen, prioriteren, opvolgen, oplossen en sluiten."]].map(([title, text]) => <article key={title}><ShieldCheck size={20}/><h3>{title}</h3><p>{text}</p></article>)}</div><p>Tenantbeheer, gebruikersbeheer, supportconfiguratie, HR-inhoud en interne tenantnotities zijn afzonderlijke bevoegdheden. Het toewijzen van een ticket verruimt het supportbereik niet.</p></section> },
      { id: "audit", title: "Activiteit", content: <section className="panel resource-table-panel"><div className="table-scroll"><table className="resource-table"><thead><tr><th scope="col">Medewerker</th><th scope="col">Wijziging</th><th scope="col">Datum</th></tr></thead><tbody>{initial.audit.map(event => <tr key={event.id}><td>{event.name}</td><td>{auditLabels[event.action] ?? "Supportprofiel gewijzigd"}</td><td>{new Intl.DateTimeFormat("nl-NL", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Amsterdam" }).format(new Date(event.createdAt))}</td></tr>)}</tbody></table></div>{!initial.audit.length && <EmptyState title="Nog geen teamwijzigingen" description="Uitnodigingen en toegangswijzigingen worden hier geregistreerd."/>}<p className="fg-team-audit-note">De laatste 50 wijzigingen.</p></section> },
    ]}/>
    {editing && <SupportEditor member={editing === "new" ? null : editing} data={initial} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); router.refresh(); }}/>} 
    {revoking && <WorkOrderDialog title="Supporttoegang intrekken" size="compact" eyebrow="PLATFORM / TOEGANG" tenant={brand} description={`De supporttoegang van ${revoking.name} wordt bij de volgende aanvraag geweigerd. Andere afzonderlijke accountrollen blijven behouden.`} onClose={() => setRevoking(null)} busy={pending}><div className="fg-team-form"><p>Ook oude sessies, open gesprekken en herhaalde opdrachten worden opnieuw gecontroleerd.</p><div className="resource-header-actions"><button className="secondary-button" onClick={() => setRevoking(null)} disabled={pending}>Annuleren</button><button className="primary-button" disabled={pending} onClick={() => change({ command: "revoke", userId: revoking.id, version: revoking.version, requestId: crypto.randomUUID() })}>{pending ? "Intrekken…" : "Toegang intrekken"}</button></div></div></WorkOrderDialog>}
  </div>;
}

function SupportEditor({ member, data, onClose, onSaved }: { member: SupportMember | null; data: SupportSnapshot; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(member?.name ?? ""), [email, setEmail] = useState(member?.email ?? ""), [all, setAll] = useState(member?.allTenants ?? true), [ids, setIds] = useState(member?.tenantIds ?? []), [active, setActive] = useState(member?.status !== "revoked");
  const [error, setError] = useState(""), [pending, start] = useTransition(), request = useRef({ signature: "", id: "" });
  return <WorkOrderDialog title={member ? "Supportmedewerker bewerken" : "Supportmedewerker uitnodigen"} eyebrow="PLATFORM / TOEGANG" size="compact" tenant={brand} description="De medewerker logt in met een e-mailcode en krijgt uitsluitend supporttoegang binnen het gekozen bereik." onClose={onClose} dirty={name !== (member?.name ?? "") || email !== (member?.email ?? "") || all !== (member?.allTenants ?? true) || active !== (member?.status !== "revoked") || JSON.stringify([...ids].sort()) !== JSON.stringify([...(member?.tenantIds ?? [])].sort())} busy={pending}>
    <form className="fg-team-form" onSubmit={event => { event.preventDefault(); setError(""); const input = { name, allTenants: all, tenantIds: all ? [] : ids }; const value = member ? { ...input, command: "update", userId: member.id, version: member.version, status: active ? "active" : "revoked" } : { ...input, email }; const signature = JSON.stringify(value); if (signature !== request.current.signature) request.current = { signature, id: crypto.randomUUID() }; start(async () => { try { const result = await (member ? changeSupportMember : inviteSupportMember)({ ...value, requestId: request.current.id }); if (!result.ok) { setError(result.error); return; } if (result.warning) toast.warning(result.warning); else toast.success(member ? "Supportprofiel opgeslagen." : "Supportmedewerker uitgenodigd."); onSaved(); } catch { setError("Opslaan is niet bevestigd. Je invoer is bewaard; probeer hetzelfde verzoek opnieuw."); } }); }}>
      <div className="fg-team-fields"><label>Naam<input aria-label="Naam supportmedewerker" required minLength={2} maxLength={160} value={name} onChange={event => setName(event.target.value)} disabled={pending}/></label><label>E-mailadres<input aria-label="E-mailadres supportmedewerker" type="email" required maxLength={320} value={email} onChange={event => setEmail(event.target.value)} disabled={pending || Boolean(member)}/></label></div>
      <fieldset><legend>Supportbereik</legend><label className="fg-team-check"><input type="checkbox" checked={all} onChange={event => setAll(event.target.checked)} disabled={pending}/>Alle actieve organisaties met tickets, inclusief toekomstige organisaties</label>{!all && <div className="fg-team-choices">{data.tenants.map(tenant => <label className="fg-team-check" key={tenant.id}><input type="checkbox" checked={ids.includes(tenant.id)} disabled={pending} onChange={event => setIds(current => event.target.checked ? [...current, tenant.id] : current.filter(id => id !== tenant.id))}/>{tenant.name}</label>)}</div>}{!all && !data.tenants.length && <p>Er zijn nog geen actieve organisaties met de ticketmodule.</p>}</fieldset>
      {member && <label className="fg-team-check"><input type="checkbox" checked={active} disabled={pending} onChange={event => setActive(event.target.checked)}/>Actieve supporttoegang</label>}
      <p className="fg-team-muted">Rol: Supportmedewerker — lezen, antwoorden, interne Fieldgrid-notities en afhandelen. Voor deze wijziging moet je in de afgelopen 15 minuten met OTP zijn ingelogd.</p>
      {error && <p role="alert" className="ticket-error">{error}</p>}<footer className="resource-header-actions"><button type="button" className="secondary-button" onClick={onClose} disabled={pending}>Annuleren</button><button className="primary-button" disabled={pending || !all && !ids.length}>{pending ? "Opslaan…" : member ? "Profiel opslaan" : "Uitnodiging versturen"}</button></footer>
    </form>
  </WorkOrderDialog>;
}
