"use client";
import {useState,useTransition} from "react";
import {submitPublicRequest} from "./actions";
export function PublicRequestForm(){
 const [id]=useState(()=>crypto.randomUUID()),[pending,start]=useTransition(),[error,setError]=useState(""),[done,setDone]=useState(false);
 if(done)return <div role="status"><h2>Je aanvraag is ontvangen</h2><p>Het bedrijf beoordeelt je vraag en neemt contact met je op. Dit is nog geen bevestiging van een afspraak of prijs.</p></div>;
 return <form className="commercial-public-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);f.set("id",id);start(async()=>{try{const r=await submitPublicRequest(f);if(r.ok)setDone(true);else setError(r.error);}catch{setError("De verbinding is onderbroken. Probeer dezelfde aanvraag opnieuw; deze wordt niet dubbel geregistreerd.");}});}}>
 <label>Naam / organisatie<input name="name" autoComplete="name" required minLength={2} maxLength={180}/></label><label>E-mailadres<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Telefoon<input name="phone" type="tel" autoComplete="tel" maxLength={40}/></label><label>Onderwerp<input name="subject" required minLength={2} maxLength={180}/></label><label>Dienst / soort werkzaamheden<input name="discipline" required minLength={2} maxLength={100}/></label><label>Soort werk<select name="work_kind"><option value="once">Eenmalig</option><option value="recurring">Terugkerend</option><option value="extra">Aanvullend werk</option></select></label><label>Wat kunnen we voor je doen?<textarea name="description" required minLength={3} maxLength={10000}/></label><label>Bekende uitvoeringslocatie<input name="location" maxLength={1000}/><small>Het bedrijf bevestigt later de juiste locatie.</small></label><label>Gewenste datum<input name="date" type="date"/></label><label>Gewenste frequentie (bij terugkerend werk)<input name="frequency" maxLength={300}/></label><label hidden aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="form-note">Vermeld geen alarmcodes, sleutelcodes of andere vertrouwelijke toegangsgegevens.</p>{error&&<p role="alert" className="auth-message error">{error}</p>}<button className="primary-button" disabled={pending}>{pending?"Versturen…":"Aanvraag versturen"}</button></form>;
}
