"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Eye, MoreHorizontal, Plus, Search, Settings2, X } from "lucide-react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { brandThemeStyle } from "@/lib/branding/palette";
import { ticketPaths, ticketWorkspaceLabels, type TicketAccess, type TicketListData, type TicketOptions, type TicketQuery, type TicketRow } from "@/lib/tickets/model";
import { runTicketCommand } from "@/app/tickets/actions";
import { TicketCreate } from "./create";
import { ticketAssigneeLabel, ticketContextLabel, ticketDate, ticketNextActor, ticketPriorityLabels, ticketStatusLabels, ticketTone } from "./presentation";
import { CompactFilterMenu } from "../compact-filter-menu";
import { PageHeading } from "../page-heading";
import { ListPagination } from "../list-pagination";
import "./tickets.css";

export function TicketList({ access, data, options, query, create = false, contextId }: { access: TicketAccess; data: TicketListData; options: TicketOptions; query: TicketQuery; create?: boolean; contextId?: string }) {
  const router = useRouter(), path = usePathname(), params = useSearchParams();
  const [creating, setCreating] = useState(create && access.canCreate), [pending, start] = useTransition(), [error, setError] = useState("");
  const staff = access.workspace === "staff", platform = access.workspace === "platform", base = ticketPaths[access.workspace];
  const href = (patch: Record<string, string | number | null>) => {
    const next = new URLSearchParams(params);
    next.delete("new");
    for (const [key, value] of Object.entries(patch)) { if (value === null || value === "") next.delete(key); else next.set(key, String(value)); }
    if (!("page" in patch)) next.delete("page");
    return `${path}${next.size ? `?${next}` : ""}`;
  };
  const back = `${path}${params.size ? `?${params}` : ""}`;
  const detail = (row: TicketRow) => `${base}/${row.id}?return=${encodeURIComponent(back)}`;
  const assign = (row: TicketRow) => start(async () => {
    try { const result = await runTicketCommand(access.workspace, "assign", { id: row.id, version: row.version, assigneeId: access.userId }, crypto.randomUUID()); if (!result.ok) setError(result.error); else router.refresh(); }
    catch { setError("De toewijzing is niet bevestigd. Vernieuw de lijst en probeer opnieuw."); }
  });
  const views = [
    ["all", "Alle tickets", null], ...(!staff ? [["mine", "Aan mij", null]] : []), ["needs_reply", staff ? "Jouw reactie nodig" : "Reactie nodig", data.counts.needsReply],
    ...(!staff && access.workspace !== "support" ? [["unassigned", "Niet toegewezen", data.counts.unassigned], ["overdue", "Termijn verstreken", data.counts.overdue]] : []), ...(platform ? [["critical", "Kritiek", null]] : []), ...(!staff ? [["archived", "Archief", null]] : []),
  ];
  const apply = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); router.push(href(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, String(value)])))); };
  const filterLabels: Record<string, string> = { search: "Zoeken", status: "Status", priority: "Prioriteit", categoryId: "Categorie", assigneeId: "Behandelaar", tenantId: "Organisatie", from: "Vanaf", to: "Tot en met" };
  const active = Object.entries(query).filter(([key, value]) => filterLabels[key] && value);
  const label = (key: string, value: string) => key === "status" ? ticketStatusLabels[value] : key === "priority" ? ticketPriorityLabels[value] : key === "categoryId" ? data.categories.find(item => item.id === value)?.name ?? "Categorie" : key === "assigneeId" ? data.assignees.find(item => item.id === value)?.label ?? "Behandelaar" : key === "tenantId" ? data.tenants.find(item => item.id === value)?.label ?? "Organisatie" : value;
  return <div className="ticket-workspace" aria-busy={pending}>
    <PageHeading eyebrow={staff ? "Hulp & meldingen" : platform ? "Fieldgrid / support" : "Opvolging & contact"} title={staff ? "Mijn tickets" : ticketWorkspaceLabels[access.workspace]} help={staff ? `Jouw vragen en meldingen aan ${access.tenant?.name ?? "je organisatie"}.` : access.workspace === "tenant" ? "Behandel personeelsvragen binnen jouw toegestane categorieën en bereik." : platform ? "Behandel de supportvragen die organisaties bewust met Fieldgrid delen." : "Stel vragen aan Fieldgrid en volg de terugkoppeling."} actions={<>
      <Link className="secondary-button" href={`${base}/instellingen`}><Settings2 size={15}/>{access.canConfigure || access.canDelegate ? "Instellingen" : "Notificaties"}</Link>
      <CompactFilterMenu activeCount={active.length} contentClassName={`ticket-filter-popover${staff ? " ps-staff-popover" : ""}`} contentStyle={brandThemeStyle(access.tenant?.primaryColor, access.tenant?.accentColor)}><form className="ticket-form" onSubmit={apply}><div className="ticket-filter-grid"><label className="ticket-search">Zoeken<Search size={16}/><input key={query.search} name="search" defaultValue={query.search} placeholder="Nummer of onderwerp…" aria-label="Zoek tickets"/></label><label>Sortering<select aria-label="Sortering" name="sort" defaultValue={query.sort}>{[["attention", "Aandacht eerst"], ["activity", "Laatste activiteit"], ["created", "Aanmaakdatum"], ["number", "Nummer"], ["subject", "Onderwerp"], ["priority", "Prioriteit"], ["deadline", "Volgende termijn"]].map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label><label>Richting<select aria-label="Sorteerrichting" name="direction" defaultValue={query.direction}><option value="desc">Aflopend</option><option value="asc">Oplopend</option></select></label><label>Status<select aria-label="Status" name="status" defaultValue={query.status ?? ""}><option value="">Alle statussen</option>{Object.entries(ticketStatusLabels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><label>Categorie<select aria-label="Categorie" name="categoryId" defaultValue={query.categoryId ?? ""}><option value="">Alle categorieën</option>{data.categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{!staff && <><label>Prioriteit<select aria-label="Prioriteit" name="priority" defaultValue={query.priority ?? ""}><option value="">Alle prioriteiten</option>{Object.entries(ticketPriorityLabels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><label>Behandelaar<select aria-label="Behandelaar" name="assigneeId" defaultValue={query.assigneeId ?? ""}><option value="">Alle behandelaars</option>{data.assignees.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label></>}{platform && <label>Organisatie<select aria-label="Organisatie" name="tenantId" defaultValue={query.tenantId ?? ""}><option value="">Alle toegestane organisaties</option>{data.tenants.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>}<label>Vanaf<input type="date" name="from" defaultValue={query.from}/></label><label>Tot en met<input type="date" name="to" defaultValue={query.to}/></label></div><footer><Link className="text-link" href={base}>Filters wissen</Link><button className="primary-button">Toepassen</button></footer></form></CompactFilterMenu>
      {access.canCreate && <button className="primary-button" onClick={() => setCreating(true)}><Plus size={16}/>{access.workspace === "support" ? "Nieuw supportticket" : "Nieuwe melding"}</button>}
    </>}/>
    <nav className="ticket-views" aria-label="Ticketweergave">{views.map(([key, name, count]) => <Link key={String(key)} href={href({ view: String(key) })} aria-current={query.view === key ? "page" : undefined}>{name}{typeof count === "number" && <b>{count}</b>}</Link>)}</nav>
    {active.length > 0 && <div className="ticket-chips" aria-label="Actieve filters">{active.map(([key, value]) => <Link key={key} href={href({ [key]: null })} aria-label={`${filterLabels[key]} verwijderen`}>{filterLabels[key]}: {label(key, String(value))}<X size={12}/></Link>)}</div>}
    {error && <p className="ticket-error" role="alert">{error}</p>}
    {staff ? <div className="ticket-staff-list">{data.items.map(row => <Link className="ticket-staff-card" key={row.id} href={detail(row)}><small>{row.unread && <i className="ticket-unread"/>}{row.number} · {row.category.name}</small><strong>{row.subject}</strong><footer><span className="ticket-status" data-tone={ticketTone(row.status)}>{ticketStatusLabels[row.status]}</span><small>{ticketDate(row.lastVisibleActivityAt, row.timezone)}</small></footer>{row.nextActor && <p className="ticket-muted">{ticketNextActor(row.nextActor, access.workspace)}</p>}</Link>)}</div> : <section className="ticket-panel ticket-table-panel" aria-label="Tickets"><div className="table-scroll"><table className="ticket-table"><thead><tr>{[...(platform ? ["Organisatie"] : []), "Ticket / onderwerp", "Categorie / context", ...(access.workspace === "tenant" ? ["Melder"] : []), "Status / volgende stap", "Prioriteit", "Behandelaar", "Activiteit / termijn", "Acties"].map(name => <th key={name} scope="col">{name}</th>)}</tr></thead><tbody>{data.items.map(row => <tr key={row.id}>{platform && <td>{row.tenantName}</td>}<td><Link href={detail(row)}><strong>{row.unread && <i className="ticket-unread"/>}{row.number}</strong><strong>{row.subject}</strong></Link></td><td>{row.category.name}<small>{ticketContextLabel(row)}</small></td>{access.workspace === "tenant" && <td>{row.reporter?.label ?? "—"}</td>}<td><span className="ticket-status" data-tone={ticketTone(row.status)}>{ticketStatusLabels[row.status]}</span><small>{ticketNextActor(row.nextActor, access.workspace)}</small></td><td><span className="ticket-status" data-tone={ticketTone(row.priority)}>{ticketPriorityLabels[row.priority]}</span></td><td>{ticketAssigneeLabel(row)}</td><td title={`Tijden in ${row.timezone}`}>{ticketDate(row.lastVisibleActivityAt, row.timezone)}{row.deadlineAt && <small>Vóór {ticketDate(row.deadlineAt, row.timezone)}</small>}</td><td><div className="ticket-actions"><Link className="resource-action" href={detail(row)} aria-label={`Bekijk ${row.number}`}><Eye size={15}/></Link><Popover><PopoverTrigger asChild><button className="resource-action" aria-label={`Meer acties voor ${row.number}`}><MoreHorizontal size={15}/></button></PopoverTrigger><PopoverContent className="resource-more-content" align="end"><Link href={detail(row)}>Bekijk gesprek</Link>{row.allowedActions.includes("assign") && <button disabled={pending} onClick={() => assign(row)}>Aan mij toewijzen</button>}{row.allowedActions.includes("resolve") && <Link href={`${detail(row)}&action=resolve`}>Oplossen</Link>}</PopoverContent></Popover></div></td></tr>)}{!data.items.length && <tr><td colSpan={platform ? 9 : access.workspace === "tenant" ? 9 : 8} className="ticket-empty">Geen tickets voor deze selectie.{active.length > 0 && <> <Link className="text-link" href={base}>Filters wissen</Link></>}</td></tr>}</tbody></table></div></section>}
    {staff && !data.items.length && <div className="ticket-panel ticket-empty">Geen tickets voor deze selectie.{active.length > 0 && <> <Link className="text-link" href={base}>Filters wissen</Link></>}</div>}
    <ListPagination total={data.total} page={data.page} pageSize={data.pageSize} noun="tickets" busy={pending} preferenceKey={`tickets:${access.tenant?.id ?? "platform"}:${access.userId}:${access.workspace}`} href={href({ page: data.page })}/>
    {creating && <TicketCreate access={access} options={options} contextId={contextId} onClose={() => setCreating(false)} onSaved={id => { setCreating(false); router.push(`${base}/${id}`); router.refresh(); }}/>}
  </div>;
}
