import {afterEach,beforeEach,expect,it,vi} from 'vitest';
vi.mock('server-only',()=>({}));vi.mock('next/cache',()=>({revalidatePath:vi.fn()}));
const m=vi.hoisted(()=>({guard:vi.fn(),admin:vi.fn(),rpc:vi.fn(),from:vi.fn(),txt:vi.fn(),cname:vi.fn(),domain:{host:'app.example.nl',verification_token:'fixture-token'}}));
vi.mock('@/lib/platform/data',()=>({requirePlatformAdmin:m.guard}));vi.mock('@/lib/supabase/admin',()=>({createAdminClient:m.admin}));vi.mock('node:dns/promises',()=>({resolveTxt:m.txt,resolveCname:m.cname}));vi.mock('@/lib/tenancy/hostname',()=>({tenantAppUrl:()=> 'https://fixture.fieldgrid.nl/app'}));
import {managePlatformWorkspaceDomain} from '@/app/platform/domain-actions';
const tenantId='10000000-0000-4000-8000-000000000001',id='10000000-0000-4000-8000-000000000002';
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('DEPLOY_TARGET','production');m.guard.mockResolvedValue({user:{id:'platform-fixture'}});m.admin.mockReturnValue({from:m.from,rpc:m.rpc});m.rpc.mockResolvedValue({error:null});m.txt.mockResolvedValue([['fieldgrid-verification=fixture-token']]);m.cname.mockResolvedValue(['fixture.fieldgrid.nl']);m.from.mockImplementation((table:string)=>{const q={select:()=>q,eq:vi.fn(()=>q),single:async()=>({data:table==='tenants'?{slug:'fixture',status:'active'}:m.domain,error:null})};return q;});});
it('checks live platform access before privileged reads or DNS',async()=>{m.guard.mockRejectedValue(Error('Geen toegang'));expect(await managePlatformWorkspaceDomain({tenantId,operation:'register',host:'app.example.nl'})).toEqual({ok:false,error:'Geen toegang'});expect(m.admin).not.toHaveBeenCalled();expect(m.txt).not.toHaveBeenCalled();});
it('registers a normalized host in this exact environment without allowing another environment',async()=>{expect(await managePlatformWorkspaceDomain({tenantId,operation:'register',host:'APP.example.nl',environment:'staging'})).toEqual({ok:true});expect(m.rpc).toHaveBeenCalledWith('platform_workspace_domain_command',{target_tenant:tenantId,actor_user_id:'platform-fixture',operation:'register',input:{environment:'production',host:'app.example.nl'}});});
it('requires exact DNS ownership and canonical CNAME before verification or activation',async()=>{for(const operation of ['verify','activate']){m.cname.mockResolvedValueOnce(['other.fieldgrid.nl']);expect((await managePlatformWorkspaceDomain({tenantId,id,operation})).ok).toBe(false);}expect(m.rpc).not.toHaveBeenCalled();expect(await managePlatformWorkspaceDomain({tenantId,id,operation:'verify'})).toEqual({ok:true});expect(m.rpc).toHaveBeenCalledWith('platform_workspace_domain_command',expect.objectContaining({input:{environment:'production',id,verificationToken:'fixture-token'}}));});
it('keeps pending domains closed on DNS errors and refuses local mutation',async()=>{m.txt.mockRejectedValue(Error('ENOTFOUND'));expect((await managePlatformWorkspaceDomain({tenantId,id,operation:'verify'})).ok).toBe(false);expect(m.rpc).not.toHaveBeenCalled();vi.stubEnv('DEPLOY_TARGET','local');expect((await managePlatformWorkspaceDomain({tenantId,operation:'register',host:'app.example.nl'})).ok).toBe(false);expect(m.rpc).not.toHaveBeenCalled();});

afterEach(()=>vi.unstubAllEnvs());
it('rechecks the browser platform session after DNS I/O before a privileged change',async()=>{m.guard.mockResolvedValueOnce({user:{id:'platform-fixture'}}).mockRejectedValueOnce(Error('Toegang ingetrokken'));expect(await managePlatformWorkspaceDomain({tenantId,id,operation:'verify'})).toEqual({ok:false,error:'Toegang ingetrokken'});expect(m.txt).toHaveBeenCalled();expect(m.rpc).not.toHaveBeenCalled();});
