import { beforeEach,describe,expect,it,vi } from "vitest";
const mocks=vi.hoisted(()=>({actor:vi.fn(),rpc:vi.fn(),file:vi.fn(),report:vi.fn(),quote:vi.fn()}));
vi.mock("@/lib/objects/auth",()=>({getObjectActor:mocks.actor}));
vi.mock("@/lib/files/private-download",()=>({privateFileHeaders:{"Cache-Control":"private, no-store"}}));
vi.mock("@/app/api/customer-files/[kind]/[id]/route",()=>({GET:mocks.file}));
vi.mock("@/lib/customer-portal/report-download",()=>({customerReportResponse:mocks.report}));
vi.mock("@/app/api/files/commercial/[id]/route",()=>({GET:mocks.quote}));
import { GET } from "./route";
const tenant="10000000-0000-4000-8000-000000000001",account="10000000-0000-4000-8000-000000000002",id="10000000-0000-4000-8000-000000000003";
const pdf=()=>new Response("%PDF-fixture",{headers:{"content-type":"application/pdf","cache-control":"private, no-store","content-disposition":"inline; filename=test.pdf"}});
const request=(kind="report",query=`account=${account}`)=>GET(new Request(`https://fixture.staging.fieldgrid.nl/api/customer-portal/files/${kind}/${id}?${query}`),{params:Promise.resolve({kind,id})});
beforeEach(()=>{vi.resetAllMocks();mocks.actor.mockResolvedValue({tenant:{id:tenant},db:{rpc:mocks.rpc}});mocks.rpc.mockResolvedValue({data:true,error:null});for(const file of [mocks.file,mocks.report,mocks.quote])file.mockImplementation(pdf);});
describe("account-bound customer PDF proxy",()=>{
 it.each(["report","invoice","quote"])("delivers %s bytes only after account authorization before and after I/O",async kind=>{const response=await request(kind);expect(response.status).toBe(200);expect(await response.text()).toBe("%PDF-fixture");expect(response.headers.get("content-type")).toBe("application/pdf");expect(response.headers.get("content-disposition")).toBe("attachment; filename=test.pdf");expect(mocks.rpc).toHaveBeenCalledTimes(2);expect(mocks.rpc).toHaveBeenNthCalledWith(2,"customer_portal_file_authorize",{target_tenant:tenant,target_account:account,kind,target_id:id});});
 it("does not fetch any file for another account",async()=>{mocks.rpc.mockResolvedValueOnce({data:false,error:null});expect((await request()).status).toBe(404);expect(mocks.report).not.toHaveBeenCalled();});
 it("discards generated bytes after revocation during I/O",async()=>{mocks.report.mockImplementation(async()=>{mocks.rpc.mockResolvedValue({data:false,error:null});return pdf();});const response=await request();expect(response.status).toBe(404);expect(await response.text()).not.toContain("%PDF");});
 it("allows a standard inline viewer without retaining supplied tokens or assets",async()=>{const response=await request("quote",`account=${account}&preview=1&token=untrusted&asset=logo`);expect(response.headers.get("content-disposition")).toBe("inline; filename=test.pdf");const forwarded=new URL(mocks.quote.mock.calls[0][0].url);expect(forwarded.searchParams.get("asset")).toBe("pdf");expect(forwarded.searchParams.get("portal")).toBe("true");expect(forwarded.searchParams.has("token")).toBe(false);});
 it.each(["",`account=${account}&account=${account}`,"account=invalid"])("rejects ambiguous account query %s",async query=>{expect((await request("report",query)).status).toBe(404);expect(mocks.actor).not.toHaveBeenCalled();});
});
