"use client";
import {useState,useTransition,useRef} from "react";
import {useRouter} from "next/navigation";
import {QuoteDocument} from "@/components/fieldgrid/commercial/document";
import {money,commercialDate,priceBases,requestLabels,quoteLabels,type QuoteSnapshot} from "@/lib/commercial/model";
import {customerCommercialAction} from "./actions";
type RequestRow={id:string;request_number:string;subject:string;description:string;status:string;object:string;created_at:string;events:Array<{id:string;kind:string;body:string;at:string}>};
type QuoteRow={id:string;quote_number:string;revision:number;status:string;expires_at:string;superseded_at:string|null;archived_at:string|null;snapshot:QuoteSnapshot};
export type CustomerCommercialData={objects:Array<{id:string;name:string;customer:string}>;requests:RequestRow[];quotes:QuoteRow[]};
export function CustomerCommercial({data,timezone}:{data:CustomerCommercialData;timezone:string}){
 const router=useRouter();const [tab,setTab]=useState("requests"),[creating,setCreating]=useState(false),[request,setRequest]=useState<RequestRow|null>(null),[quote,setQuote]=useState<QuoteRow|null>(null),[pending,start]=useTransition(),[error,setError]=useState("");const ids=useRef(new Map<string,string>());const [now]=useState(()=>Date.now());
 const act=(command:string,input:Record<string,unknown>)=>{const key=command+JSON.stringify(input);let id=ids.current.get(key);if(!id){id=crypto.randomUUID();ids.current.set(key,id);}start(async()=>{try{const r=await customerCommercialAction(command,input,id!);if(!r.ok){setError(r.error);return;}setError("");setCreating(false);setQuote(null);setRequest(null);router.refresh();}catch{setError("Je actie kon niet worden bevestigd. Probeer dezelfde actie opnieuw.");}});};
 return <div className="commercial-page"><div className="commercial-detail-actions"><button className="secondary-button" aria-pressed={tab==="requests"} onClick={()=>setTab("requests")}>Aanvragen</button><button className="secondary-button" aria-pressed={tab==="quotes"} onClick={()=>setTab("quotes")}>Offertes</button><button className="primary-button" disabled={!data.objects.length} onClick={()=>setCreating(true)}>Nieuwe aanvraag</button></div>{error&&<p className="auth-message error" role="alert">{error}</p>}
 {creating&&<section className="dossier-card"><h2>Nieuwe aanvraag bij je object</h2><form className="commercial-action-form" onSubmit={e=>{e.preventDefault();act("intake",Object.fromEntries(new FormData(e.currentTarget)));}}><label>Object<select name="object_id" required>{data.objects.map(o=><option value={o.id} key={o.id}>{o.customer} · {o.name}</option>)}</select></label><label>Onderwerp<input name="subject" required minLength={2} maxLength={180}/></label><label>Dienst / werkzaamheden<input name="discipline" required minLength={2} maxLength={100}/></label><label>Soort werk<select name="work_kind"><option value="once">Eenmalig</option><option value="recurring">Terugkerend</option><option value="extra">Aanvullend werk</option></select></label><label className="wide">Je vraag<textarea name="description" required minLength={3} maxLength={10000}/></label><label>Gewenste datum<input type="date" name="date"/></label><label>Gewenste frequentie<input name="frequency" maxLength={300}/></label><p className="form-note wide">Gaat het om een instructie voor een al geplande afspraak? Gebruik dan Mijn afspraken, zodat je verzoek aan het juiste bezoek gekoppeld blijft.</p><button className="primary-button" disabled={pending}>Aanvraag versturen</button><button className="secondary-button" type="button" onClick={()=>confirm("Niet opgeslagen aanvraag weggooien?")&&setCreating(false)}>Annuleren</button></form></section>}
 <section className="panel resource-table-panel"><div className="table-scroll" tabIndex={0} role="region" aria-label="Mijn commerciële overzicht"><table className="resource-table"><thead><tr><th>Nummer / onderwerp</th><th>Object</th><th>Status</th>{tab==="quotes"&&<th>Bedrag excl. btw / prijsbasis</th>}<th>Datum</th><th>Acties</th></tr></thead><tbody>{tab==="requests"?data.requests.map(r=><tr key={r.id}><td>{r.request_number}<small>{r.subject}</small></td><td>{r.object||"Locatie nog vaststellen"}</td><td>{requestLabels[r.status]||r.status}</td><td>{commercialDate(r.created_at,timezone)}</td><td><button className="resource-action" onClick={()=>{setRequest(r);setQuote(null);}}>Bekijk</button></td></tr>):data.quotes.map(q=><tr key={q.id}><td>{q.quote_number} · v{q.revision}<small>{q.snapshot.subject}</small></td><td>{q.snapshot.object?.name}</td><td>{q.superseded_at?"Vervangen":q.status==="awaiting_acceptance"&&Date.parse(q.expires_at)<=now?"Verlopen":quoteLabels[q.status]}</td><td>{money(q.snapshot.subtotal_cents??0)} · {priceBases[q.snapshot.price_basis]}</td><td>Geldig tot {commercialDate(q.expires_at,timezone)}</td><td><button className="resource-action" onClick={()=>{setQuote(q);setRequest(null);}}>Bekijk</button></td></tr>)}</tbody></table></div>{!(tab==="requests"?data.requests:data.quotes).length&&<p className="resource-empty">Er zijn nog geen registraties op deze pagina.</p>}</section>
 {request&&<section className="dossier-card"><h2>{request.subject}</h2><p className="commercial-prewrap">{request.description}</p>{request.events.filter(e=>e.body).map(e=><div className="dossier-event" key={e.id}><p>{e.body}</p><small>{commercialDate(e.at,timezone,true)}</small></div>)}{!["rejected","withdrawn"].includes(request.status)&&<form className="commercial-public-form" onSubmit={e=>{e.preventDefault();act("reply",{id:request.id,body:new FormData(e.currentTarget).get("body")});}}><label>Aanvullende informatie<textarea name="body" required minLength={3} maxLength={5000}/></label><button className="primary-button" disabled={pending}>Reactie versturen</button></form>}<button className="secondary-button" onClick={()=>setRequest(null)}>Sluiten</button></section>}
 {quote&&<section className="dossier-card"><QuoteDocument snapshot={quote.snapshot} timezone={timezone} logoUrl={quote.snapshot.brand?.logo_source?`/api/files/commercial/${quote.id}?asset=logo&portal=true`:null} attachmentHref={id=>`/api/files/commercial/${id}?portal=true`}/><a className="secondary-button" href={`/api/files/commercial/${quote.id}?asset=pdf&portal=true`}>Offerte-PDF</a>{quote.status==="awaiting_acceptance"&&!quote.superseded_at&&!quote.archived_at&&Date.parse(quote.expires_at)>now&&<form className="commercial-action-form" onSubmit={e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));act("decide",{...values,id:quote.id,revision:quote.revision,confirmed:values.confirmed==="on"});}}><label>Je naam<input name="name" required minLength={2} maxLength={180}/></label><label>Besluit<select name="decision"><option value="accepted">Akkoord geven</option><option value="change_requested">Wijziging vragen</option><option value="rejected">Afwijzen</option></select></label><label className="wide">Toelichting (verplicht bij wijzigen of afwijzen)<textarea name="evidence" maxLength={3000}/></label><label className="commercial-check wide"><input type="checkbox" name="confirmed" required/>Mijn besluit betreft deze versie, werkzaamheden, bedragen en voorwaarden.</label><button className="primary-button" disabled={pending}>Besluit bevestigen</button></form>}<button className="secondary-button" onClick={()=>setQuote(null)}>Sluiten</button></section>}
 </div>;
}
