"use client";
import { useCallback, useEffect, useState, useTransition } from "react";
import { readWorkOrderExceptions, saveWorkOrderException } from "@/app/app/work-order-actions";
import type { WorkOrderExceptionData } from "@/lib/work-orders/model";
const labels = { no_access: "Geen toegang", absence: "Medewerker uitgevallen", material: "Materiaal ontbreekt", unsafe: "Onveilige situatie", damage: "Schade", customer_cancelled: "Klant heeft afgezegd", customer_absent: "Klant niet aanwezig", delay: "Vertraging", other: "Andere bijzonderheid" };
export function WorkOrderExceptions({ orderId, attachments = [], allowCustomerAbsent = true }: { orderId: string; attachments?: Array<{ id: string; file_name: string }>; allowCustomerAbsent?: boolean }) {
  const [data, setData] = useState<WorkOrderExceptionData | null>(null), [error, setError] = useState(""), [creating, setCreating] = useState(false), [pending, startTransition] = useTransition(), [commandId, setCommandId] = useState(() => crypto.randomUUID());
  const load = useCallback(async () => { const r = await readWorkOrderExceptions(orderId); if (r.ok) setData(r.data); else setError(r.error); }, [orderId]);
  useEffect(() => { const t = setTimeout(() => void load(), 0); return () => clearTimeout(t); }, [load]);
  return <section className="wo-card"><div className="section-heading"><h2>Meldingen bij deze uitvoering</h2><button className="resource-action" onClick={() => setCreating(!creating)}>Melding toevoegen</button></div>
    {error && <p role="alert" className="wo-error">{error}</p>}
    {creating && <form className="dossier-form" onChange={() => setCommandId(crypto.randomUUID())} onSubmit={e => { e.preventDefault(); const form = e.currentTarget, f = new FormData(form); startTransition(async () => { const r = await saveWorkOrderException({ mutationId: commandId, action: "create", orderId, kind: String(f.get("kind")), description: String(f.get("description")), blocking: f.get("blocking") === "on", attachmentId: String(f.get("attachmentId") || "") }); if (!r.ok) setError(r.error); else { setCreating(false); setError(""); setCommandId(crypto.randomUUID()); await load(); } }); }}>
      <label>Wat is er aan de hand?<select name="kind">{Object.entries(labels).filter(([key]) => allowCustomerAbsent || key !== "customer_absent").map(([key, l]) => <option value={key} key={key}>{l}</option>)}</select></label><label className="wide">Toelichting<textarea name="description" required minLength={3} maxLength={3000}/></label><label className="check"><input name="blocking" type="checkbox"/>Dit blokkeert de afronding van het werk</label><label>Bijlage uit deze bon<select name="attachmentId"><option value="">Geen bijlage</option>{attachments.map(a => <option value={a.id} key={a.id}>{a.file_name}</option>)}</select></label><p className="dossier-muted wide">De verantwoordelijke planner ontvangt de melding. Persoons- en toegangscodes horen hier niet thuis.</p><button className="primary-button" disabled={pending}>{pending ? "Opslaan…" : "Melding opslaan"}</button>
    </form>}
    {data?.items.length === 0 && <p className="dossier-muted">Geen uitvoeringsmeldingen.</p>}
    {data?.items.map(item => <article className="wo-record" key={item.id}><header><h3>{labels[item.kind]}{item.blocking && item.state === "open" ? " · Blokkeert afronding" : ""}</h3><span className="wo-status">{item.state === "open" ? "Openstaand" : "Afgehandeld"}</span></header><p className="wo-prewrap">{item.description}</p><small>{new Date(item.createdAt).toLocaleString("nl-NL")}</small>{item.attachmentId && <a href={`/api/files/attachment/${item.attachmentId}`} target="_blank" rel="noreferrer">Bijlage openen</a>}{item.resolution && <p>Afhandeling: {item.resolution}</p>}{data.canManage && item.state === "open" && <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); startTransition(async () => { const r = await saveWorkOrderException({ mutationId: crypto.randomUUID(), action: "resolve", orderId, id: item.id, version: item.version, resolution: String(f.get("resolution")) }); if (!r.ok) setError(r.error); else { setError(""); await load(); } }); }}><label>Afhandeling<textarea name="resolution" required minLength={3} maxLength={3000}/></label><button className="resource-action" disabled={pending}>Afhandelen</button></form>}</article>)}
  </section>;
}
