"use client";
import { useRef, useState, useTransition } from "react";
import Link from "next/link";
import { Download, FilePlus2, Send } from "lucide-react";
import { toast } from "sonner";
import type { WorkOrderDossier } from "@/lib/work-orders/model";
import { financialMoney as money, orderFinancialSummary, agreedTaskAmount } from "@/lib/work-orders/financial-summary";
import { createInvoice, sendInvoice } from "@/app/app/finance-actions";
import { ContentSection } from "../content-section";
import { HelpTip } from "../help-tip";

export function WorkOrderFinancial({ data, onRefresh, financeEnabled = true }: { data: WorkOrderDossier; onRefresh: () => void; financeEnabled?: boolean }) {
  const [error, setError] = useState(""), [pending, start] = useTransition(), request = useRef(crypto.randomUUID());
  const summary = orderFinancialSummary(data), invoices = data.financial?.invoices ?? [];
  const period = data.tasks.some(task => ["week", "month"].includes(String((task.commercial_snapshot as Record<string, unknown> | undefined)?.price_basis ?? "")));
  const makeInvoice = (invoiceId?: string) => start(async () => {
    setError(""); const form = new FormData();
    if (invoiceId) form.set("invoiceId", invoiceId); else { form.set("requestId", request.current); form.set("workOrderIds", data.order.id); }
    const result = await createInvoice(form);
    if (!result.ok) { setError(result.error); return; }
    toast.success(invoiceId ? "Factuur-PDF beschikbaar" : "Factuur aangemaakt"); onRefresh();
  });
  const send = (invoiceId: string) => start(async () => {
    setError(""); const form = new FormData(); form.set("invoiceId", invoiceId);
    const result = await sendInvoice(form); if (!result.ok) { setError(result.error); return; }
    toast.success("Factuur naar het afgesproken factuuradres verzonden"); onRefresh();
  });
  const rows = data.tasks.filter(task => !task.is_extra_work);
  return <>
    <ContentSection className="wo-section" title="Oorspronkelijke opdracht" help="De oorspronkelijke vastgelegde taakprijzen blijven behouden. Arbeidsuren en het aantal medewerkers veranderen deze prijs niet."><div className="wo-finance-rows">{rows.map(task => <article key={task.id}><div><strong>{task.task_name}</strong><small>{task.quantity} {task.unit} · {task.unit_price_cents == null ? "Tarief niet beschikbaar" : `${money(task.unit_price_cents)} per ${task.unit}`}</small></div><strong>{task.unit_price_cents == null ? "—" : money(agreedTaskAmount(task, task.quantity))}</strong></article>)}{!rows.length && <p>Geen oorspronkelijke taakregels vastgelegd.</p>}</div><div className="wo-section-total"><span>Oorspronkelijke prijs</span><strong>{money(summary.originalCents)}</strong></div>{period && <p className="dossier-muted">Deze opdracht hoort bij een periodeafspraak. De periode wordt vanuit de geaccepteerde offerte gefactureerd.</p>}</ContentSection>
    <ContentSection className="wo-section" title="Meerwerk" help="Alleen goedgekeurd en uitgevoerd meerwerk telt mee in het totaal. Voorstellen blijven apart zichtbaar."><div className="wo-finance-rows">{data.tasks.filter(task => task.is_extra_work).map(task => <article key={task.id}><div><strong>{task.task_name}</strong><small>{({ approved: "Goedgekeurd", pending: "Ter beoordeling", proposed: "Voorgesteld", rejected: "Afgewezen" } as Record<string, string>)[task.extra_work_status ?? ""] ?? "Ter beoordeling"} · {task.executed_quantity ?? 0} van {task.quantity} {task.unit} uitgevoerd</small></div><strong>{task.unit_price_cents == null ? "—" : money(agreedTaskAmount(task, task.quantity))}</strong></article>)}{!data.tasks.some(task => task.is_extra_work) && <p>Geen meerwerk toegevoegd.</p>}</div><div className="wo-section-total"><span>Goedgekeurd en uitgevoerd</span><strong>{money(summary.approvedExtraCents)}</strong></div>{summary.proposedExtraCents > 0 && <p className="dossier-muted">Nog ter beoordeling: {money(summary.proposedExtraCents)}</p>}</ContentSection>
    <div className="wo-grid"><ContentSection className="wo-section" title="Materiaal"><div className="wo-finance-rows">{(data.financial?.materials ?? []).map(item => <article key={item.id}><div><strong>{item.description}</strong><small>{item.quantity} {item.unit} · {item.customerVisible ? "Klantzichtbaar" : "Intern"}{item.unitPriceCents == null && " · prijs nog niet vastgelegd"}</small></div><strong>{item.unitPriceCents == null ? "—" : money(Math.round(item.quantity * item.unitPriceCents))}</strong></article>)}{!data.financial?.materials.length && <p>Geen materiaalverbruik geregistreerd.</p>}</div><div className="wo-section-total"><span>Klantzichtbare materialen</span><strong>{money(summary.materialCents)}</strong></div></ContentSection><ContentSection className="wo-section" title="Onkosten"><div className="wo-finance-rows">{(data.financial?.expenses ?? []).map(item => <article key={item.id}><div><strong>{item.description}</strong><small>{item.customerVisible ? "Klantzichtbaar" : "Intern"}</small></div><strong>{money(item.amountCents)}</strong></article>)}{!data.financial?.expenses.length && <p>Geen onkosten geregistreerd.</p>}</div><div className="wo-section-total"><span>Klantzichtbare onkosten</span><strong>{money(summary.expenseCents)}</strong></div></ContentSection></div>
    <ContentSection className="wo-section" title="Totaaloverzicht" help="Het opdrachtoverzicht en een definitieve factuur zijn afzonderlijke registraties. Materiaal en onkosten in het rapport zijn geen automatisch factuurrecht."><dl className="wo-finance-totals"><div><dt>Oorspronkelijke opdracht</dt><dd>{money(summary.originalCents)}</dd></div><div><dt>Goedgekeurd en uitgevoerd meerwerk</dt><dd>{money(summary.approvedExtraCents)}</dd></div><div><dt>Geregistreerde klantzichtbare materialen</dt><dd>{money(summary.materialCents)}</dd></div><div><dt>Geregistreerde klantzichtbare onkosten</dt><dd>{money(summary.expenseCents)}</dd></div><div className="wo-finance-grand"><dt>Opdracht en geregistreerde extra kosten</dt><dd>{money(summary.totalCents)}</dd></div><div><dt>Definitief gefactureerd, inclusief btw</dt><dd>{money(summary.issuedCents)}</dd></div></dl>{summary.unpricedMaterials > 0 && <p className="dossier-muted">{summary.unpricedMaterials} materiaalregel(s) hebben nog geen vastgelegde prijs en zijn niet in het bedrag opgenomen.</p>}</ContentSection>
    <ContentSection className="wo-section" title="Facturen & PDF" help="Een factuur kan pas worden vastgelegd na rapportcontrole en de benodigde akkoorden. Bestaande documenten worden gedownload of verzonden via de beveiligde factuurregistratie." actions={<><Link className="secondary-button" href="/app/facturen">Open facturen</Link>{financeEnabled && !period && <button className="primary-button" disabled={pending || data.order.status !== "invoice_ready"} onClick={() => makeInvoice()}><FilePlus2 size={15}/>Factuur en PDF maken</button>}</>}>
      {!financeEnabled && <p className="dossier-muted">Facturatie is niet ingeschakeld voor deze organisatie.</p>}{error && <p className="wo-error" role="alert">{error}</p>}
      <div className="wo-finance-rows">{invoices.map(invoice => <article key={invoice.id}><div><Link href={`/app/facturen?record=${invoice.id}`}><strong>{invoice.number ?? "Conceptfactuur"}</strong></Link><small>{({ draft: "Concept", final: "Definitief", sent: "Verzonden", paid: "Betaald", overdue: "Verlopen", credited: "Gecrediteerd" } as Record<string, string>)[invoice.status] ?? "Vastgelegd"} · factuurtotaal {money(invoice.totalCents)} · betaald {money(invoice.paidCents)}</small></div><div className="resource-actions">{invoice.number && (invoice.pdfAvailable ? <><a className="resource-action" href={`/api/files/invoice/${invoice.id}`}><Download size={14}/>Download PDF</a><button className="resource-action" disabled={pending} onClick={() => send(invoice.id)}><Send size={14}/>Verstuur</button></> : <button className="resource-action" disabled={pending} onClick={() => makeInvoice(invoice.id)}><FilePlus2 size={14}/>PDF herstellen</button>)}</div></article>)}{!invoices.length && <p className="dossier-muted">Nog geen facturen voor deze werkbon. <HelpTip label="Wanneer is facturatie beschikbaar?">Laat eerst het complete opleverrapport controleren. De factuur bevat alleen nog factureerbare, goedgekeurde taakhoeveelheden; materiaal en onkosten blijven als afzonderlijke registraties zichtbaar.</HelpTip></p>}</div>
    </ContentSection>
  </>;
}
