"use client";
import Image from "next/image";
import type { WorkOrderDossier } from "@/lib/work-orders/model";
import type { ReportVersion, WorkOrderReport } from "@/lib/work-orders/report-model";
import { reportStateLabels, signatureModeLabels } from "@/lib/work-orders/report-model";
import { historyActor, historyMessage } from "@/lib/work-orders/history";
import { orderFinancialSummary, financialMoney as money, agreedTaskAmount } from "@/lib/work-orders/financial-summary";
import { executionLabels } from "@/lib/dossiers/status";
import { ContentTabs } from "../content-tabs";
import { ContentSection } from "../content-section";
import { ListPagination, useListPagination } from "../list-pagination";
import { TaskExecution } from "../task-execution";
import { ChecklistPanel } from "./checklists";
import { ReportDocument, ReportSignatures } from "./report-document";

/** Management receives the live internal dossier through its own guarded RPC.
 * The immutable customer report remains an explicitly separate projection. */
export function ReportReviewDetails({ dossier, report, current }: { dossier: WorkOrderDossier; report: WorkOrderReport; current?: ReportVersion }) {
 const date=(at:string)=>new Intl.DateTimeFormat("nl-NL",{dateStyle:"short",timeStyle:"short",timeZone:current?.snapshot.timezone??"Europe/Amsterdam"}).format(new Date(at));
 const notes=useListPagination(dossier.reports),history=useListPagination(dossier.history),files=useListPagination(dossier.attachments),times=useListPagination(dossier.times);
 const summary=orderFinancialSummary(dossier);
 const costs=<><ContentSection title="Opdracht & meerwerk"><div className="wo-finance-rows">{dossier.tasks.map(task=><article key={task.id}><div><strong>{task.task_name}</strong><small>{task.is_extra_work?`Meerwerk · ${task.extra_work_status==="approved"?"Goedgekeurd":task.extra_work_status==="rejected"?"Afgewezen":"Ter beoordeling"}`:"Oorspronkelijke opdracht"} · {task.executed_quantity??(task.completed_at?task.quantity:0)} van {task.quantity} {task.unit} uitgevoerd</small></div><strong>{task.unit_price_cents==null?"—":money(agreedTaskAmount(task, task.quantity))}</strong></article>)}</div></ContentSection>
 <div className="wo-grid"><ContentSection title="Materiaal"><div className="wo-finance-rows">{dossier.financial?.materials.map(item=><article key={item.id}><div><strong>{item.description}</strong><small>{item.quantity} {item.unit} · {item.customerVisible?"Klantzichtbaar":"Intern"}</small></div><strong>{item.unitPriceCents==null?"Prijs ontbreekt":money(Math.round(item.quantity*item.unitPriceCents))}</strong></article>)}{!dossier.financial?.materials.length&&<p>Geen materiaal geregistreerd.</p>}</div></ContentSection><ContentSection title="Onkosten"><div className="wo-finance-rows">{dossier.financial?.expenses.map(item=><article key={item.id}><div><strong>{item.description}</strong><small>{item.customerVisible?"Klantzichtbaar":"Intern"}</small></div><strong>{money(item.amountCents)}</strong></article>)}{!dossier.financial?.expenses.length&&<p>Geen onkosten geregistreerd.</p>}</div></ContentSection></div>
 <ContentSection title="Kostenoverzicht"><dl className="wo-finance-totals"><div><dt>Oorspronkelijke opdracht</dt><dd>{money(summary.originalCents)}</dd></div><div><dt>Goedgekeurd uitgevoerd meerwerk</dt><dd>{money(summary.approvedExtraCents)}</dd></div><div><dt>Klantzichtbaar materiaal</dt><dd>{money(summary.materialCents)}</dd></div><div><dt>Klantzichtbare onkosten</dt><dd>{money(summary.expenseCents)}</dd></div><div className="wo-finance-grand"><dt>Totaal excl. btw</dt><dd>{money(summary.totalCents)}</dd></div></dl>{summary.proposedExtraCents>0&&<p>Meerwerk ter beoordeling: {money(summary.proposedExtraCents)}</p>}{summary.unpricedMaterials>0&&<p>{summary.unpricedMaterials} materiaalregel(s) zonder vastgelegde prijs.</p>}</ContentSection></>;
 return <ContentTabs label="Rapportcontroleonderdelen" tabs={[
 {id:"overzicht",title:"Overzicht",content:<><ContentSection title="Oplevering"><dl className="wo-facts"><div><dt>Opdrachtgever</dt><dd>{dossier.order.customer}</dd></div><div><dt>Object</dt><dd>{dossier.order.object}</dd></div><div><dt>Rapport</dt><dd>{reportStateLabels[report.state]??"Controleren"}{current&&` · versie ${current.version}`}</dd></div><div><dt>Klantondertekening</dt><dd>{signatureModeLabels[report.policy.mode]} · {current?.signatures.some(signature=>signature.kind==="customer")?"Ontvangen":current?.waiver?"Gemotiveerd vrijgesteld":"Niet ontvangen"}</dd></div><div><dt>Werkzaamheden</dt><dd>{dossier.tasks.filter(task=>task.completed_at).length} van {dossier.tasks.length} vastgelegd</dd></div><div><dt>Controlebewijs</dt><dd>{dossier.checklists.length} checklists · {dossier.attachments.length} bijlagen</dd></div></dl>{current&&<p className="wo-prewrap">{current.snapshot.summary}</p>}</ContentSection><ContentSection title="Medewerkers & uitvoering"><div className="wo-assignment-list">{dossier.assignments.map(assignment=><article key={assignment.id} className="wo-assignment-record"><div><strong>{assignment.name}</strong><small>{assignment.actualStart?date(assignment.actualStart):"Nog niet gestart"}{assignment.actualEnd&&` – ${date(assignment.actualEnd)}`}</small></div><span className="wo-status">{assignment.status==="completed"?"Werkzaamheden afgerond":executionLabels[assignment.status]??"Ingepland"}</span></article>)}</div></ContentSection><ContentSection title="Werk- en reisuren"><div className="wo-finance-rows">{times.items.map(time=><article key={time.id}><div><strong>{time.name}</strong><small>{time.kind==="work"?"Werk":time.kind==="travel"?"Reis":time.kind==="break"?"Pauze":"Registratie"} · {time.start?date(time.start):"—"}{time.end&&` – ${date(time.end)}`}</small></div><span className="wo-status">{time.end?"Gestopt":"Lopend"}</span></article>)}{!times.total&&<p>Geen uren geregistreerd.</p>}</div></ContentSection><ListPagination total={times.total} page={times.page} pageSize={times.pageSize} onPageChange={times.setPage} onPageSizeChange={times.setPageSize} noun="registraties" preferenceKey={`review:${dossier.order.id}:times`}/></>},
 {id:"uitvoering",title:"Taken & checklists",content:<><ContentSection title="Taken & resultaten"><div className="wo-task-records">{dossier.tasks.map(task=><details className="wo-task-detail" key={task.id}><summary><div><strong>{task.task_name}</strong><small>{task.executed_quantity??(task.completed_at?task.quantity:0)} van {task.quantity} {task.unit} · {executionLabels[task.execution_state]??"Gepland"}</small></div></summary><div className="wo-task-detail-body"><TaskExecution task={{...task,unit_price_cents:undefined}} editable={false} reviewed={report.state==="approved"}/></div></details>)}</div></ContentSection><ContentSection title="Checklists"><ChecklistPanel orderId={dossier.order.id} checklists={dossier.checklists} attachments={dossier.attachments} editable={false}/></ContentSection></>},
 {id:"tijdlijn",title:"Notities & acties",content:<><ContentSection title="Alle notities"><div className="review-note-list">{notes.items.map(note=><article key={note.id}><header><time dateTime={note.created_at}>{date(note.created_at)} · {historyActor(note.author??null)}</time><span className="wo-status">{note.customer_visible?"Klantzichtbaar na controle":"Intern"}</span></header><p className="wo-prewrap">{note.body}</p></article>)}{!notes.total&&<p>Geen notities ontvangen.</p>}</div></ContentSection><ListPagination total={notes.total} page={notes.page} pageSize={notes.pageSize} onPageChange={notes.setPage} onPageSizeChange={notes.setPageSize} noun="notities" preferenceKey={`review:${dossier.order.id}:notes`}/><ContentSection title="Actietijdlijn"><div className="wo-timeline">{history.items.map(event=><article key={event.id}><time dateTime={event.at}>{date(event.at)}</time><strong>{historyMessage(event.event)}</strong>{event.note&&<p className="wo-prewrap">{event.note}</p>}<small>{historyActor(event.actor)}</small></article>)}{!history.total&&<p>Nog geen acties vastgelegd.</p>}</div></ContentSection><ListPagination total={history.total} page={history.page} pageSize={history.pageSize} onPageChange={history.setPage} onPageSizeChange={history.setPageSize} noun="acties" preferenceKey={`review:${dossier.order.id}:history`}/></>},
 {id:"bijlagen",title:"Foto’s & documenten",content:<><ContentSection title="Alle bijlagen"><div className="review-asset-grid">{files.items.map(file=><a className="review-asset" href={`/api/files/attachment/${file.id}`} target="_blank" rel="noreferrer" key={file.id}>{/^image\/(jpeg|png|webp)$/.test(file.mime_type)?<Image src={`/api/files/attachment/${file.id}`} width={480} height={320} alt={file.file_name} unoptimized/>:<span className="review-document">Document openen</span>}<strong>{file.file_name}</strong><small>{date(file.created_at)} · {file.customerVisible?"Klantzichtbaar":"Intern"}</small></a>)}{!files.total&&<p>Geen foto’s of documenten ontvangen.</p>}</div></ContentSection><ListPagination total={files.total} page={files.page} pageSize={files.pageSize} onPageChange={files.setPage} onPageSizeChange={files.setPageSize} noun="bijlagen" preferenceKey={`review:${dossier.order.id}:files`}/></>},
 {id:"handtekeningen",title:"Handtekeningen",content:current?<ReportSignatures report={current}/>:<ContentSection title="Handtekeningen"><p>Er is nog geen vastgelegde rapportversie.</p></ContentSection>},
 ...(dossier.finance?[{id:"kosten",title:"Kosten",content:costs}]:[]),
 {id:"klant",title:"Klantrapport",content:current?<ReportDocument report={current}/>:<ContentSection title="Klantrapport"><p>Nog geen ingediend rapport.</p></ContentSection>},
 ]}/>;
}
