"use client";
import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { PageHeading } from "../page-heading";
import { ContentSection } from "../content-section";
import { EmptyState } from "../empty-state";
import { ActionIcon } from "../action-icon";
import { CompactFilterMenu } from "../compact-filter-menu";
import { ListPagination, useListPagination } from "../list-pagination";
import { Popover, PopoverContent, PopoverTrigger, PopoverClose } from "@/components/ui/popover";
import { Plus, Trash2, ArrowLeft, Pencil, Eye, Send, Archive } from "lucide-react";
import type { TenantContext } from "@/lib/auth/context";
import type { ChecklistQuestion, WorkOrderOptions, WorkTemplate } from "@/lib/work-orders/model";
import { mutateWorkTemplate } from "@/app/app/work-order-actions";
import { WorkOrderDialog } from "./dialog";
import "./templates.css";
import { WorkOrderSignatureSettings } from "./settings";

const typeLabels = { check: "Vinkje", boolean: "Ja / nee", choice: "Keuzelijst", text: "Tekst", number: "Getal", photo: "Foto" };
const states = { draft: "Concept", published: "Gepubliceerd", archived: "Gearchiveerd" };
const blankQuestion = (): ChecklistQuestion => ({ id: crypto.randomUUID(), section: "", label: "", help: "", type: "check", options: [], unit: "", required: true, proof: false, allowNA: false, customerVisible: true });
const library = [{ name: "Algemene oplevercontrole", definition: { questions: [
  { ...blankQuestion(), id: "finished", label: "Werkplek netjes achtergelaten" },
  { ...blankQuestion(), id: "damage", label: "Schade of bijzonderheden aangetroffen", type: "boolean" as const },
  { ...blankQuestion(), id: "damage-note", label: "Beschrijf de bijzonderheid", type: "text" as const, proof: true, condition: { questionId: "damage", equals: true } },
] } }];

export function WorkOrderTemplates({ tenant, options }: { tenant: TenantContext; options: WorkOrderOptions }) {
  const params=useSearchParams();
  const [selected, setSelected] = useState<WorkTemplate | null>(null), [create, setCreate] = useState<"work_order" | "checklist" | null>(null), [error, setError] = useState(""), [pending, startTransition] = useTransition(), [kind, setKind] = useState(params.get("kind")==="checklist"?"checklist":"all");
  const router = useRouter(),rows=options.templates.filter(t=>kind==="all"||t.kind===kind),pagination=useListPagination(rows);
  const mutate = (t: WorkTemplate, command: "publish" | "archive") => {
    if (!window.confirm(command === "publish" ? "Publiceer deze versie? De inhoud blijft daarna bewaard; wijzigingen krijgen een nieuwe versie." : "Archiveer deze versie? Bestaande werkbonnen behouden hun checklist en afspraken.")) return;
    startTransition(async () => { const r = await mutateWorkTemplate({ commandId: crypto.randomUUID(), command, template: t }); if (!r.ok) setError(r.error); else router.refresh(); });
  };
  return <div className="wo-workspace"><PageHeading eyebrow="CATALOGUS" title="Werkbon- en checklisttemplates" help="Herbruikbare werkinstructies. Een gepubliceerde versie blijft bewaard bij de werkbon." actions={<><CompactFilterMenu activeCount={kind!=="all"?1:0}><label>Type<select value={kind} onChange={e=>{setKind(e.target.value);pagination.setPage(1);}}><option value="all">Alle templates</option><option value="work_order">Werkbonnen</option><option value="checklist">Checklists</option></select></label></CompactFilterMenu><Popover><PopoverTrigger asChild><ActionIcon className="primary-button" label="Voeg toe" icon={<Plus size={16}/>}/></PopoverTrigger><PopoverContent className="resource-more-content" align="end"><PopoverClose asChild><button onClick={()=>setCreate("checklist")}>Nieuwe checklist</button></PopoverClose><PopoverClose asChild><button onClick={()=>setCreate("work_order")}>Nieuwe werkbontemplate</button></PopoverClose></PopoverContent></Popover></>}/><Link href="/app/taken" className="dossier-back"><ArrowLeft size={16}/>Taken & tarieven</Link>
    {error && <p role="alert" className="wo-error">{error}</p>}
    <ContentSection title="Templates" bodyClassName="resource-table-panel">
      <div className="table-scroll"><table className="resource-table"><thead><tr><th>Naam</th><th>Type</th><th>Versie</th><th>Status</th><th>Acties</th></tr></thead><tbody>{pagination.items.map(t => <tr key={t.revisionId}><td><button type="button" className="text-link cell-main" onClick={() => setSelected(t)}>{t.name}</button></td><td>{t.kind === "work_order" ? "Werkbon" : "Checklist"}</td><td>{t.version}</td><td>{states[t.state]}</td><td><div className="resource-actions"><ActionIcon className="resource-action" label={t.state === "draft" ? "Bewerk" : "Bekijk / nieuwe versie"} icon={t.state === "draft" ? <Pencil size={15}/> : <Eye size={15}/>} onClick={() => setSelected(t)}/>{t.state === "draft" && <ActionIcon className="resource-action" label="Publiceer" icon={<Send size={15}/>} disabled={pending} onClick={() => mutate(t, "publish")}/>}{t.state !== "archived" && <ActionIcon className="resource-action" label="Archiveer" icon={<Archive size={15}/>} disabled={pending} onClick={() => mutate(t, "archive")}/>}</div></td></tr>)}{!rows.length && <tr><td colSpan={5}><EmptyState title="Nog geen templates" description="Maak een eigen template met de plusknop of neem een basischecklist over."/></td></tr>}</tbody></table></div>
    </ContentSection><ListPagination total={pagination.total} page={pagination.page} pageSize={pagination.pageSize} onPageChange={pagination.setPage} onPageSizeChange={pagination.setPageSize} noun="templates" preferenceKey={`backoffice:${tenant.id}:work-order-templates`}/>
    <ContentSection title="Basischecklists" help="Neem een eigen conceptkopie over en pas die aan. Latere platformwijzigingen wijzigen jouw versie niet.">{library.map(t => <button key={t.name} className="resource-action" onClick={() => setSelected({ id: "", revisionId: "", name: t.name, kind: "checklist", version: 0, state: "draft", definition: t.definition })}>Kopieer {t.name}</button>)}</ContentSection>
    <WorkOrderSignatureSettings/>
    {(selected || create) && <TemplateEditor key={selected?.revisionId || create} tenant={tenant} options={options} existing={selected} kind={create || selected!.kind} close={() => { setSelected(null); setCreate(null); }} saved={() => { setSelected(null); setCreate(null); router.refresh(); }}/>} </div>;
}

function TemplateEditor({ tenant, options, existing, kind, close, saved }: { tenant: TenantContext; options: WorkOrderOptions; existing: WorkTemplate | null; kind: "work_order" | "checklist"; close: () => void; saved: () => void }) {
  const [name, setName] = useState(existing?.name ?? ""), [definition, setDefinition] = useState<WorkTemplate["definition"]>(existing?.definition ?? (kind === "checklist" ? { questions: [blankQuestion()] } : { discipline: "", requiredPersonnel: 1, ...(options.canManageSignature ? { signatureMode: "none" as const } : {}), tasks: [], checklistRevisionIds: [] })), [error, setError] = useState(""), [dirty, setDirty] = useState(false), [pending, startTransition] = useTransition();
  const [commandId, setCommandId] = useState(() => crypto.randomUUID());
  const change = (next: WorkTemplate["definition"]) => { setDefinition(next); setDirty(true); setCommandId(crypto.randomUUID()); };
  const updateQuestion = (index: number, patch: Partial<ChecklistQuestion>) => change({ ...definition, questions: definition.questions?.map((q, i) => i === index ? { ...q, ...patch } : q) });
  const submit = () => startTransition(async () => { const r = await mutateWorkTemplate({ commandId, command: "save", template: { revisionId: existing?.revisionId || null, editVersion: existing?.editVersion, name, kind, definition } }); if (!r.ok) setError(r.error); else saved(); });
  const cancel = () => { if (!dirty || window.confirm("Je wijzigingen zijn nog niet opgeslagen. Wil je het formulier sluiten?")) close(); };
  return <WorkOrderDialog title={existing ? `${existing.name} · versie ${existing.version || "nieuw"}` : kind === "checklist" ? "Nieuwe checklisttemplate" : "Nieuwe werkbontemplate"} description="Maak een concept. Publiceer het pas nadat alle regels zijn gecontroleerd." tenant={tenant} onClose={close} dirty={dirty} busy={pending}>
    <form className="dossier-form wo-template-form" onSubmit={e => { e.preventDefault(); submit(); }}>
      {error && <p role="alert" className="wo-error wide">{error}</p>}
      {existing && existing.state !== "draft" && <p className="dossier-notice wide">Deze versie blijft ongewijzigd. Opslaan maakt een nieuwe conceptversie. Bestaande bonnen behouden hun huidige versie.</p>}
      <label className="wide">Naam<input value={name} required minLength={2} maxLength={180} onChange={e => { setName(e.target.value); setDirty(true); setCommandId(crypto.randomUUID()); }}/></label>
      {kind === "work_order" ? <>
        <label>Dienst / discipline<input value={definition.discipline || ""} list="template-disciplines" onChange={e => change({ ...definition, discipline: e.target.value })}/><datalist id="template-disciplines">{options.disciplines.map(d => <option key={d}>{d}</option>)}</datalist></label>
        <label>Benodigde medewerkers<input type="number" min={1} max={100} value={definition.requiredPersonnel || 1} onChange={e => change({ ...definition, requiredPersonnel: Number(e.target.value) })}/></label>
        {options.canManageSignature ? <><label>Klantondertekening<select value={definition.signatureMode || ""} onChange={e => change({ ...definition, signatureMode: e.target.value ? e.target.value as "none" | "optional" | "required" : undefined })}><option value="">Tenantstandaard overnemen</option><option value="none">Niet nodig</option><option value="optional">Optioneel</option><option value="required">Verplicht</option></select></label>
        <label className="check"><input type="checkbox" checked={definition.employeeSignatureRequired || false} onChange={e => change({ ...definition, employeeSignatureRequired: e.target.checked })}/>Ook medewerkerondertekening verplicht</label></> : <p className="wide dossier-muted">Ondertekenafspraken blijven overgenomen. Alleen beheer kan die afspraak wijzigen.</p>}
        <div className="wide wo-list"><h3>Catalogustaken</h3>{definition.tasks?.map((t, i) => <section className="wo-task-row" key={i}><label>Taak<select value={t.revisionId} required onChange={e => change({ ...definition, tasks: definition.tasks!.map((x, j) => j === i ? { ...x, revisionId: e.target.value } : x) })}><option value="">Kies taak</option>{options.tasks.map(x => <option value={x.revisionId} key={x.revisionId}>{x.code} · {x.name} · {x.durationMinutes} min</option>)}</select></label><label>Hoeveelheid<input type="number" min="0.001" step="0.001" value={t.quantity} onChange={e => change({ ...definition, tasks: definition.tasks!.map((x, j) => j === i ? { ...x, quantity: Number(e.target.value) } : x) })}/></label><label>Instructie<textarea value={t.instructions || ""} onChange={e => change({ ...definition, tasks: definition.tasks!.map((x, j) => j === i ? { ...x, instructions: e.target.value } : x) })}/></label><button type="button" className="resource-action" onClick={() => change({ ...definition, tasks: definition.tasks!.filter((_, j) => j !== i) })}><Trash2 size={14}/>Regel verwijderen</button></section>)}<button type="button" className="resource-action" onClick={() => change({ ...definition, tasks: [...(definition.tasks || []), { revisionId: "", quantity: 1, instructions: "" }] })}>Taak toevoegen</button></div>
        <section className="wide wo-list"><h3>Checklists</h3>{options.templates.filter(t => t.kind === "checklist" && t.state === "published").map(t => <label className="check" key={t.revisionId}><input type="checkbox" checked={definition.checklistRevisionIds?.includes(t.revisionId) || false} onChange={e => change({ ...definition, checklistRevisionIds: e.target.checked ? [...(definition.checklistRevisionIds || []), t.revisionId] : definition.checklistRevisionIds?.filter(id => id !== t.revisionId) })}/>{t.name} · v{t.version}</label>)}</section>
      </> : <div className="wide wo-list">{definition.questions?.map((q, i) => <section className="wo-template-question" key={q.id}>
        <header><h3>Vraag {i + 1}</h3><button type="button" className="resource-action" onClick={() => change({ ...definition, questions: definition.questions!.filter((_, j) => j !== i) })}><Trash2 size={14}/>Verwijder</button></header>
        <label>Sectie<input value={q.section} onChange={e => updateQuestion(i, { section: e.target.value })}/></label><label>Vraag<input value={q.label} required minLength={2} onChange={e => updateQuestion(i, { label: e.target.value })}/></label>
        <label>Toelichting<input value={q.help} onChange={e => updateQuestion(i, { help: e.target.value })}/></label><label>Antwoordtype<select value={q.type} onChange={e => updateQuestion(i, { type: e.target.value as ChecklistQuestion["type"] })}>{Object.entries(typeLabels).map(([v, l]) => <option value={v} key={v}>{l}</option>)}</select></label>
        {q.type === "choice" && <label>Opties, één per regel<textarea value={q.options.join("\n")} onChange={e => updateQuestion(i, { options: e.target.value.split("\n") })}/></label>}{q.type === "number" && <label>Eenheid<input value={q.unit} onChange={e => updateQuestion(i, { unit: e.target.value })}/></label>}
        <div className="wo-template-flags">{([['required','Verplicht'],['proof','Bewijsfoto verplicht'],['allowNA','Niet van toepassing met reden toestaan'],['customerVisible','In klantrapport']] as const).map(([key, label]) => <label className="check" key={key}><input type="checkbox" checked={q[key]} onChange={e => updateQuestion(i, { [key]: e.target.checked })}/>{label}</label>)}</div>
        {i > 0 && <><label>Alleen tonen na antwoord op<select value={q.condition?.questionId || ""} onChange={e => updateQuestion(i, { condition: e.target.value ? { questionId: e.target.value, equals: true } : undefined })}><option value="">Altijd tonen</option>{definition.questions!.slice(0, i).filter(x => ['check','boolean','choice'].includes(x.type)).map(x => <option value={x.id} key={x.id}>{x.label || 'Vraag zonder titel'}</option>)}</select></label>{q.condition && <label>Wanneer antwoord gelijk is aan{definition.questions!.find(x => x.id === q.condition!.questionId)?.type === "choice" ? <select value={String(q.condition.equals)} onChange={e => updateQuestion(i, { condition: { ...q.condition!, equals: e.target.value } })}><option value="">Kies antwoord</option>{definition.questions!.find(x => x.id === q.condition!.questionId)?.options.map(o => <option key={o}>{o}</option>)}</select> : <select value={String(q.condition.equals)} onChange={e => updateQuestion(i, { condition: { ...q.condition!, equals: e.target.value === "true" } })}><option value="true">Ja / aangevinkt</option><option value="false">Nee / niet aangevinkt</option></select>}</label>}</>}
      </section>)}<button type="button" className="resource-action" onClick={() => change({ ...definition, questions: [...(definition.questions || []), blankQuestion()] })}>Vraag toevoegen</button><p className="dossier-muted">Ondertekening is een afzonderlijke afrondstap in de personeelsapp, geen checklistvraag.</p></div>}
      <footer className="wizard-footer wide"><button type="button" className="secondary-button" disabled={pending} onClick={cancel}>Annuleren</button><button className="primary-button" disabled={pending}>{pending ? "Opslaan…" : existing?.state && existing.state !== "draft" ? "Nieuwe conceptversie opslaan" : "Concept opslaan"}</button></footer>
    </form>
  </WorkOrderDialog>;
}
