"use client";
import {useEffect,useRef,useState,useTransition,type FormEvent} from "react";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {toast} from "sonner";
import {Download,History,Send,Plus} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import type {TenantContext} from "@/lib/auth/context";
import type {Row} from "@/lib/objects/model";
import {localDateTime,localToInstant} from "@/lib/planning/time";
import {commercialAction,readCommercialDetail,retryCommercialMessages,createNextCommercialVisit,cancelCommercialBooking} from "@/app/app/commercial-actions";
import {sendCommercialQuote,uploadCommercialAttachment,createCommercialBooking} from "@/app/app/commercial-delivery-actions";
import {createInvoice} from "@/app/app/finance-actions";
import {reviewObjectRequest} from "@/app/app/objecten/actions";
import {commercialDate,money,requestLabels,quoteLabels,type CommercialDetail,type CommercialOptions,type SourceKind,type VisitDetail,type QuoteLine} from "@/lib/commercial/model";
import {CommercialDialog} from "./dialog";
import {QuoteDocument} from "./document";
import {LineEditor} from "./wizard";

const eventLabels:Record<string,string>={"request.received":"Aanvraag ontvangen","request.updated":"Aanvraag bijgewerkt","request.review":"Beoordeling gestart","request.waiting_info":"Informatie nodig","request.rejected":"Aanvraag afgewezen","request.withdrawn":"Aanvraag ingetrokken","request.note":"Interne notitie","request.inspection":"Opname aangemaakt","request.direct_order":"Directe opdracht aangemaakt","request.archived":"Aanvraag gearchiveerd","quote.draft_saved":"Concept opgeslagen","quote.published":"Offerteversie vastgelegd","quote.revised":"Nieuwe conceptversie","quote.accepted":"Akkoord geregistreerd","quote.rejected":"Offerte afgewezen","quote.change_requested":"Wijziging gevraagd","quote.email_sent":"E-mail aangenomen door verzendprovider","quote.reminder_sent":"Herinnering aangenomen door verzendprovider","quote.converted":"Opdracht aangemaakt","quote.archived":"Offerte gearchiveerd","quote.followup":"Opvolging bijgewerkt","booking.link_created":"Boekingslink geregistreerd","booking.confirmed":"Tijdvak geboekt","booking.cancelled":"Boeking / link geannuleerd","request.information_requested":"Informatie gevraagd","request.customer_reply":"Reactie van klant","quote.visit_created":"Vervolgbezoek klaargezet"};

export function CommercialDetailPanel({id,source,tenant,options,onClose,onChanged,onEdit,onQuote,initialAction=""}:{id:string;source:SourceKind;tenant:TenantContext;options:CommercialOptions;onClose:()=>void;onChanged:()=>void;onEdit:(r:Row<"requests">|Row<"quotes">)=>void;onQuote:(r:Row<"requests">)=>void;initialAction?:string}){
 const params=useSearchParams();const quoteHref=(id:string)=>{const p=new URLSearchParams(params);p.set("record",id);p.set("recordKind","quote");p.delete("action");return `/app/aanvragen?${p}`;};
 const [detail,setDetail]=useState<CommercialDetail|VisitDetail|null>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0),[pending,start]=useTransition(),[mode,setMode]=useState(initialAction),[tab,setTab]=useState("overview"),[lines,setLines]=useState<QuoteLine[]>([]),[bookingUrl,setBookingUrl]=useState("");
 const [now]=useState(()=>Date.now());const ids=useRef(new Map<string,string>());const actionId=(key:string)=>{let value=ids.current.get(key);if(!value){value=crypto.randomUUID();ids.current.set(key,value);}return value;};
 useEffect(()=>{let live=true;void readCommercialDetail(id,source).then(r=>{if(!live)return;if(r.ok){setDetail(r.data);setError("");}else setError(r.error);}).catch(()=>{if(live)setError("De verbinding is onderbroken. Probeer opnieuw te laden.");});return()=>{live=false;};},[id,source,refresh]);
 const changed=()=>{setRefresh(n=>n+1);onChanged();ids.current.clear();setMode("");};
 const perform=(command:string,payload:Record<string,unknown>)=>{setError("");start(async()=>{try{const result=await commercialAction(command,payload,actionId(command+JSON.stringify(payload)));if(!result.ok){setError(result.error);return;}toast.success("Opgeslagen");changed();if(result.data.deleted)onClose();}catch{setError("De verbinding is onderbroken. Je kunt dezelfde actie veilig opnieuw proberen.");}});};
 const date=(s:string|null|undefined,time=false)=>commercialDate(s,tenant.timezone,time);
 if(!detail)return <CommercialDialog title="Dossier openen" description="De actuele brongegevens worden opgehaald." tenant={tenant} onClose={onClose} busy={pending}><div className="commercial-form-body">{error?<p role="alert">{error}<button onClick={()=>setRefresh(n=>n+1)}>Opnieuw laden</button></p>:<p role="status">Laden…</p>}</div></CommercialDialog>;
 if("proposals"in detail){const r=detail.record;return <CommercialDialog title={r.title} description="Verzoek bij een bestaande afspraak. Dezelfde registratie als in het objectdossier." tenant={tenant} onClose={onClose} busy={pending}><div className="commercial-form-body"><p className="commercial-prewrap">{r.body}</p><p>{r.response}</p><div className="commercial-detail-actions"><Link className="secondary-button" href={`/app/objecten/${r.object_id}?tab=instructies#request-${r.id}`}>Objectdossier</Link><Link className="secondary-button" href={`/app/werkbonnen/${r.work_order_id}`}>Concrete werkbon</Link></div>{detail.proposals.map(p=><section className="dossier-card" key={p.id}><h3>Meerwerkvoorstel · versie {p.version}</h3><p>{p.scope}</p><strong>{money(Math.round(p.quantity*p.price_cents))} excl. btw · per bezoek</strong><p>{p.accepted_at?`Akkoord op ${date(p.accepted_at,true)}`:"Nog geen akkoord"}</p></section>)}
 {!r.work_order_task_id&&r.state!=="withdrawn"&&<form className="commercial-action-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);f.set("id",r.id);f.set("objectId",r.object_id);f.set("version",String(r.version));start(async()=>{const result=await reviewObjectRequest(f);if(result.ok){toast.success("Beoordeling opgeslagen");changed();}else setError(result.error);});}}><h3 className="wide">Beoordeel het bezoekverzoek</h3><label>Uitkomst<select name="decision"><option value="review">In beoordeling</option><option value="regular">Binnen bestaande afspraak — geen extra bedrag</option><option value="proposal">Aanvullend betaald werk — klantakkoord nodig</option><option value="rejected">Niet uitvoerbaar</option></select></label><label>Catalogustaak<select name="taskRevisionId"><option value="">Kies een taak</option>{options.tasks.map(t=><option value={t.id} key={t.id}>{t.code} · {t.name}</option>)}</select></label><label>Aantal<input type="number" min="0.001" step="0.001" name="quantity" defaultValue="1"/></label><label>Prijs per eenheid excl. btw<input type="number" min="0" step="0.01" name="price" defaultValue="0"/></label><label className="wide">Interne beoordeling<textarea name="reason" minLength={3} required/></label><label className="wide">Terugkoppeling aan klant<textarea name="response"/></label><p className="dossier-notice wide">Een instructie is geen betaalakkoord. Een meerwerkvoorstel wordt via het bestaande klantportaal bevestigd en uitsluitend op deze afspraak uitgevoerd.</p><button className="primary-button" disabled={pending}>Beoordeling opslaan</button></form>}{error&&<p className="auth-message error" role="alert">{error}</p>}</div></CommercialDialog>;}
 const r=detail.record;const q="quote_number"in r?r:null;const request="request_number"in r?r:null;const title=q?.subject||request?.subject||"Commercieel dossier";const active=!r.archived_at;const quoteOpen=q&&q.status==="awaiting_acceptance"&&!q.superseded_at&&!!q.expires_at&&Date.parse(q.expires_at)>now;
 const websiteNotes=detail.events.filter(e=>e.details&&typeof e.details==="object"&&!Array.isArray(e.details)&&typeof e.details.website_notes_part==="number").sort((a,b)=>Number((a.details as Record<string,unknown>).website_notes_part)-Number((b.details as Record<string,unknown>).website_notes_part)).map(e=>e.body).join("");
 const edit=()=>onEdit(r);
 const send=(reminder:boolean)=>{setError("");start(async()=>{const result=await sendCommercialQuote(id,actionId(reminder?"reminder":"send"),reminder);if(result.ok){toast.success("Verzending door provider aangenomen");changed();}else setError(result.error);});};
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const v=Object.fromEntries(f);const base={id:r.id,version:r.version};
  if(mode==="decision")perform("decide",{...base,decision:v.decision,name:v.name,channel:v.channel,received_at:localToInstant(String(v.received_at),tenant.timezone),evidence:v.evidence,confirmed:v.confirmed==="on"});
  else if(mode==="status")perform("request_status",{...base,status:v.status,reason:v.reason,followup_on:v.followup_on});
  else if(mode==="note")perform("note",{...base,reason:v.reason});
  else if(mode==="direct")perform("request_direct",{...base,reason:v.reason,lines});
  else if(mode==="convert")perform("convert",{...base,durations:Object.fromEntries(Object.entries(v).filter(([k])=>k.startsWith("duration:")).map(([k,v])=>[k.slice(9),v]))});
  else if(mode==="visit")start(async()=>{const result=await createNextCommercialVisit(id,String(v.day),actionId("visit"+String(v.day)));if(result.ok)changed();else setError(result.error);});
  else if(mode==="period"){f.set("quoteId",id);f.set("requestId",actionId("period"+String(v.periodStart)));start(async()=>{const result=await createInvoice(f);if(result.ok){toast.success("Periodefactuur aangemaakt");changed();}else setError(result.error);});}
  else if(mode==="information")perform("information",{...base,reason:v.reason,followup_on:v.followup_on});
  else if(mode==="followup")perform("quote_followup",{...base,owner_id:v.owner_id,next_action:v.next_action,followup_on:v.followup_on});
  else if(mode==="booking"){f.set("commandId",actionId("booking"+JSON.stringify(v)));start(async()=>{const result=await createCommercialBooking(f);if(result.ok){setBookingUrl(result.url);setRefresh(n=>n+1);onChanged();}else setError(result.error);});}
 };
 return <CommercialDialog title={title} description={`${q?.quote_number||request?.request_number} ${q?`· versie ${q.revision}`:""} · ${(q?quoteLabels:requestLabels)[r.status]||r.status}`} tenant={tenant} onClose={onClose} busy={pending}>
 <div className="commercial-detail-actions">
 <button className="secondary-button" disabled={!active||pending} onClick={edit}>{q&&q.status!=="draft"?"Nieuwe conceptversie":"Bewerken"}</button>
 {request&&active&&!['rejected','withdrawn'].includes(request.status)&&<>{!detail.quotes.length&&<button className="primary-button" onClick={()=>onQuote(request)}><Plus size={15}/>Offerte opstellen</button>}<button className="secondary-button" onClick={()=>setMode("status")}>Beoordeling / informatievraag</button><button className="secondary-button" onClick={()=>setMode("information")}>Informatie opvragen</button><button className="secondary-button" onClick={()=>setMode("note")}>Interne notitie</button><button className="secondary-button" onClick={()=>setMode("inspection")}>Opname plannen</button><button className="secondary-button" onClick={()=>setMode("direct")}>Directe opdracht</button></>}
 {q&&active&&q.status==="draft"&&<button className="primary-button" disabled={pending} onClick={()=>send(false)}><Send size={15}/>Offerte verzenden</button>}
 {quoteOpen&&active&&<><button className="secondary-button" disabled={pending} onClick={()=>send(false)}>Verzenden / opnieuw proberen</button>{q.sent_at&&<button className="secondary-button" disabled={pending} onClick={()=>send(true)}>Herinnering sturen</button>}<button className="primary-button" onClick={()=>setMode("decision")}>Akkoord registreren</button><button className="secondary-button" onClick={()=>setMode("followup")}>Opvolging aanpassen</button></>}
 {q?.status==="accepted"&&active&&!q.operation_id&&<button className="primary-button" onClick={()=>setMode("convert")}>Omzetten naar opdracht</button>}
 {q?.operation_id&&<Link className="primary-button" href={`/app/planning?order=${q.operation_id}`}>Naar planning / Inplannen</Link>}
 {q?.operation_id&&q.work_kind==="recurring"&&<button className="secondary-button" onClick={()=>setMode("visit")}>Volgend bezoek klaarzetten</button>}
 {q?.status==="accepted"&&["week","month"].includes(q.price_basis)&&tenant.roles.some(r=>["tenant_admin","management","finance"].includes(r))&&tenant.enabledServices.includes("finance")&&<button className="secondary-button" onClick={()=>setMode("period")}>Periodefactuur maken</button>}
 {q?.pdf_path&&<a className="secondary-button" href={`/api/files/commercial/${id}?asset=pdf`}><Download size={15}/>PDF downloaden</a>}
 {active&&<button className="resource-action" onClick={()=>setMode("archive")}>Archiveren</button>}
 </div>
 {error&&<p className="auth-message error" role="alert">{error}</p>}
 {mode==="quote"&&request&&!detail.quotes.length&&<div className="dossier-notice">Neem de aanvraag over in een offerte. <button className="resource-action" onClick={()=>onQuote(request)}>Offerte opstellen</button></div>}
 {mode==="send"&&quoteOpen&&<p className="dossier-notice">Gebruik de verzendactie hierboven. Een link of vastgelegde versie is nog geen bewijs van verzending.</p>}
 {mode==="archive"&&<div className="dossier-notice">Historie en gekoppelde opdrachten blijven behouden. Openstaande klantlinks worden geblokkeerd.<button className="resource-action danger" disabled={pending} onClick={()=>perform(q?"quote_archive":"request_archive",{id,version:r.version})}>Archiveren bevestigen</button></div>}
 {mode==="inspection"&&request&&<div className="dossier-notice">Een opname is een aparte afspraak voor inventarisatie, zonder akkoord op het uit te voeren werk.<button className="primary-button" disabled={pending} onClick={()=>perform("inspection",{id,version:r.version})}>Opname aanmaken</button></div>}
 {["decision","status","note","direct","convert","followup","booking","information","visit","period"].includes(mode)&&<form key={mode} className="commercial-action-form" onSubmit={submit}>
 <h3 className="wide">{{visit:"Volgend bezoek binnen het geaccepteerde patroon",period:"Volledige factuurperiode bevestigen",information:"Informatie opvragen bij klant",decision:"Klantbesluit registreren",status:"Beoordeling vastleggen",note:"Interne notitie",direct:"Directe opdracht op bestaande afspraak",convert:"Geaccepteerd werk omzetten",followup:"Opvolging",booking:"Boekingslink voor deze afspraak"}[mode]}</h3>
 {mode==="decision"&&q&&<><p className="dossier-notice wide">Je registreert een besluit over {q.quote_number} v{q.revision}: {money(q.subtotal_cents)} excl. btw. Controleer het aangeboden document hieronder.</p><label>Besluit<select name="decision"><option value="accepted">Akkoord</option><option value="change_requested">Wijziging gevraagd</option><option value="rejected">Afgewezen</option></select></label><label>Naam beslisser<input name="name" required minLength={2} maxLength={180}/></label><label>Kanaal<select name="channel"><option value="email">E-mail</option><option value="phone">Telefonisch</option><option value="in_person">Persoonlijk</option></select></label><label>Ontvangen op<input type="datetime-local" required name="received_at" defaultValue={localDateTime(new Date().toISOString(),tenant.timezone)}/></label><label className="wide">Toelichting / verwijzing naar akkoordbewijs<textarea name="evidence" required minLength={3}/></label><label className="commercial-check wide"><input type="checkbox" name="confirmed" required/>Ik bevestig dat het besluit deze offerteversie, werkzaamheden, bedragen en voorwaarden betreft.</label></>}
 {mode==="status"&&<><label>Status<select name="status"><option value="review">In beoordeling</option><option value="waiting_info">Wacht op informatie</option><option value="rejected">Afgewezen</option><option value="withdrawn">Ingetrokken</option></select></label><label>Opvolgdatum<input name="followup_on" type="date" defaultValue={r.followup_on||""}/></label></>}
 {["status","note","direct","information"].includes(mode)&&<label className="wide">{mode==="direct"?"Bestaande prijsafspraak / reden waarom geen offerte nodig is":mode==="information"?"Vraag aan de klant (wordt per e-mail verstuurd)":"Toelichting (intern)"}<textarea name="reason" required minLength={mode==="direct"?10:3}/></label>}
 {mode==="direct"&&<LineEditor lines={lines} onChange={setLines} options={options}/>}
 {mode==="visit"&&<><label>Gewenste bezoekdatum<input type="date" name="day" required/></label><p className="dossier-notice wide">De geaccepteerde taken en prijsafspraken blijven behouden. Je plant dit bezoek daarna op het bestaande planbord. Dezelfde datum wordt niet dubbel aangemaakt.</p></>}
 {mode==="period"&&q&&<><label>Start factuurperiode<input type="date" name="periodStart" required defaultValue={(q.terms as Record<string,string>).starts_on||""}/></label><p className="dossier-notice wide">De periode volgt de afgesproken startdatum en prijsbasis. Alleen volledig verstreken weken/maanden met gecontroleerde uitvoering kunnen worden gefactureerd. Het overeengekomen periodebedrag wordt eenmaal gefactureerd, niet per bezoek. Een gedeeltelijke periode vereist een afzonderlijke prijsafspraak.</p><label className="commercial-check wide"><input type="checkbox" name="confirmed" required/>Ik heb de uitvoering gecontroleerd en bevestig dat het volledige overeengekomen periodebedrag verschuldigd is.</label></>}
 {mode==="information"&&<label>Opvolgdatum<input name="followup_on" type="date" required/></label>}
 {mode==="convert"&&q&&(q.lines as unknown as QuoteLine[]).filter(l=>!l.duration_minutes).map(l=><label key={l.id}>Planningduur per eenheid: {l.description}<input type="number" name={`duration:${l.id}`} required min="1" max="43200"/></label>)}
 {mode==="convert"&&q&&<p className="dossier-notice wide">Er komt één nog in te plannen opdracht met de geaccepteerde werkzaamheden en prijsafspraken. Er wordt geen personeel toegewezen en geen factuur aangemaakt.{q.work_kind==="recurring"&&" Het bezoekpatroon wordt bewaard; de planner bevestigt de concrete bezoeken."}</p>}
 {mode==="followup"&&<><label>Behandelaar<select name="owner_id" defaultValue={r.owner_id||""} required>{options.owners.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Volgende actie<input name="next_action" defaultValue={r.next_action} required minLength={2}/></label><label>Opvolgdatum<input type="date" name="followup_on" defaultValue={r.followup_on||""}/></label></>}
 {mode==="booking"&&<><label>Afspraak<select name="workOrderId" required>{detail.operations.filter(w=>!w.start&&w.status==="planned"&&w.bookable).map(w=><option key={w.id} value={w.id}>{w.number} · {w.kind==="inspection"?"Opname / inventarisatie":"Uitvoering goedgekeurd werk"}</option>)}</select></label><label>Capaciteit<input name="capacity" type="number" min="1" max="20" defaultValue="1" required/></label><label>Vanaf<input type="datetime-local" name="start" required/></label><label>Tot<input type="datetime-local" name="end" required/></label><p className="dossier-notice wide">De klant kiest een beschikbaar aankomstvenster. De planner bevestigt daarna de personeelsinzet. Deze boeking is geen offerteakkoord.</p>{bookingUrl&&<div className="wide"><a className="text-link" href={bookingUrl} target="_blank" rel="noreferrer">Geregistreerde boekingslink openen</a><button type="button" className="resource-action" onClick={()=>void navigator.clipboard.writeText(bookingUrl).then(()=>toast.success("Link gekopieerd"))}>Link kopiëren</button><small>Een gekopieerde link is nog niet verzonden.</small></div>}</>}
 <footer className="wide"><button type="button" className="secondary-button" onClick={()=>setMode("")}>Annuleren</button><button className="primary-button" disabled={pending}>{pending?"Bezig…":"Bevestigen en opslaan"}</button></footer></form>}
 <Tabs value={tab} onValueChange={setTab} className="commercial-detail-tabs"><TabsList aria-label="Dossieronderdelen"><TabsTrigger value="overview">Overzicht</TabsTrigger><TabsTrigger value="documents">Documenten</TabsTrigger><TabsTrigger value="communication">Communicatie</TabsTrigger><TabsTrigger value="history"><History size={14}/>Tijdlijn en versies</TabsTrigger></TabsList>
 <div className="commercial-detail-body"><TabsContent value="overview">
 <div className="commercial-detail-links">{r.customer_id&&<Link className="text-link" href={`/app/klanten?record=${r.customer_id}`}>Klant 360</Link>}{r.object_id?<Link className="text-link" href={`/app/objecten/${r.object_id}`}>Object 360</Link>:<span className="dossier-notice">Object nog vaststellen — nodig voor aanbieding en uitvoering.</span>}</div>
 {q&&detail.preview?<QuoteDocument snapshot={detail.preview} logoUrl={q.logo_path?`/api/files/commercial/${q.id}?asset=logo`:null} timezone={tenant.timezone} attachmentHref={id=>`/api/files/commercial/${id}`}/>:request&&<section className="dossier-card"><h3>Oorspronkelijke klantvraag</h3><p className="commercial-prewrap">{request.description}</p>{websiteNotes&&<section><h3>Extra opmerkingen van de websiteaanvraag</h3><p className="commercial-prewrap">{websiteNotes}</p></section>}<dl className="commercial-facts"><div><dt>Ontvangen</dt><dd>{date(request.created_at,true)}</dd></div><div><dt>Dienst</dt><dd>{request.discipline}</dd></div><div><dt>Volgende actie</dt><dd>{request.next_action||"Afgehandeld"}</dd></div><div><dt>Deadline</dt><dd>{date(request.followup_on)}</dd></div></dl>{Object.entries((request.preferences??{}) as Record<string,unknown>).filter(([key,value])=>["date","window","frequency","location"].includes(key)&&typeof value==="string").map(([key,value])=><p key={key}>{{date:"Gewenste datum",window:"Tijdvenster",frequency:"Frequentie",location:"Locatie nog vaststellen"}[key]||key}: {String(value)}</p>)}</section>}
 {!!detail.quotes.length&&request&&<section className="dossier-card"><h3>Gekoppelde offertes</h3>{detail.quotes.map(q=><Link className="dossier-event" key={q.id} href={quoteHref(q.id)} scroll={false}><strong>{q.quote_number} v{q.revision}</strong><span>{quoteLabels[q.status]||q.status} · {money(q.total_cents)} incl. btw</span></Link>)}</section>}
 <section className="dossier-card"><h3>Opnames, opdrachten en planning</h3>{detail.operations.map(w=><div className="dossier-event" key={w.id}><div><strong>{w.number} · {w.kind==="inspection"?"Opname":"Uitvoering"}</strong><small>{w.start?date(w.start,true):"Nog niet gepland"}</small></div><Link className="resource-action" href={`/app/planning?order=${w.id}`}>Naar planning</Link><Link className="resource-action" href={`/app/werkbonnen/${w.id}`}>Werkbon</Link>{w.booking_active&&!w.start&&<button className="resource-action danger" disabled={pending} onClick={()=>{const reason=prompt("Waarom annuleer je deze boeking of boekingslink? De opdracht en het offerteakkoord blijven behouden.");if(reason)start(async()=>{const result=await cancelCommercialBooking(w.id,reason,actionId("cancel-booking"+w.id+reason));if(result.ok)changed();else setError(result.error);});}}>Boeking / link annuleren</button>}</div>)}{!detail.operations.length&&<p>Nog geen operationele opdracht. Offerteakkoord en planning zijn afzonderlijke stappen.</p>}{detail.operations.some(w=>!w.start&&w.status==="planned"&&w.bookable)&&<button className="secondary-button" onClick={()=>setMode("booking")}>Boekingslink maken</button>}</section>
 </TabsContent><TabsContent value="documents"><section className="dossier-card"><h3>Bijlagen</h3>{detail.attachments.map(a=><p key={a.id}><a className="text-link" href={`/api/files/commercial/${a.id}`}>{a.title}</a> · {a.public_in_offer?"Openbare offertebijlage":"Intern dossier"}</p>)}{(!q||q.status==="draft")&&active&&<form className="commercial-action-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);f.set("entityId",id);f.set("kind",q?"quote":"request");f.set("public",q?"true":"false");start(async()=>{const result=await uploadCommercialAttachment(f);if(result.ok){toast.success("Bijlage opgeslagen");changed();}else setError(result.error);});}}><label>Titel<input name="title" required minLength={2}/></label><label>Bestand<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" required/></label><p className="dossier-notice wide">Maximaal 10 MB. Geen alarmcodes, sleutelkluiscodes of privégegevens. Malwarecontrole is niet aangesloten.{q&&" Deze bijlage wordt onderdeel van de aangeboden versie."}</p><button className="primary-button" disabled={pending}>Bijlage uploaden</button></form>}</section></TabsContent>
 <TabsContent value="communication"><section className="dossier-card"><h3>Verzendregistratie</h3><p>Verzending en klantakkoord zijn afzonderlijke gebeurtenissen. “Aangenomen” betekent dat de verzendprovider het bericht heeft geaccepteerd, niet dat het is bezorgd of gelezen.</p>{detail.deliveries.map(d=><article className="dossier-event" key={d.id}><div><strong>{d.subject||"E-mail"}</strong><small>{d.recipient} · {({sent:"Aangenomen door provider",failed:"Verzendfout",processing:"In verwerking",uncertain:"Provideruitkomst onzeker",suppressed:"Geblokkeerd door notificatiebeleid",unreachable:"Niet bereikbaar",cancelled:"Ingetrokken",queued:"Wacht op verzending"} as Record<string,string>)[d.status]} · {d.attempts} poging(en)</small>{d.error&&<p>{d.error}</p>}</div></article>)}{!detail.deliveries.length&&<p>Nog geen verzending bevestigd.</p>}<button className="secondary-button" disabled={pending} onClick={()=>start(async()=>{const result=await retryCommercialMessages(id,q?"quote":"request");if(result.ok)changed();else setError(result.error);})}>Openstaande gebeurtenisberichten opnieuw proberen</button><small>Onzekere verzendingen worden niet automatisch herhaald. Voor de offertemail gebruik je de verzendactie bovenaan.</small></section></TabsContent>
 <TabsContent value="history">{q&&<section className="dossier-card"><h3>Offerteversies</h3>{detail.quotes.map(v=><article className="dossier-event" key={v.id}><div><strong>{v.quote_number} · v{v.revision}</strong><small>{quoteLabels[v.status]||v.status}{v.superseded_at?" · vervangen":""} · {date(v.created_at,true)}</small>{v.accepted_at&&<small>Akkoord door {v.accepted_by_name} op {date(v.accepted_at,true)} · {v.acceptance_channel}</small>}</div><Link className="resource-action" href={quoteHref(v.id)} scroll={false}>Deze versie bekijken</Link>{v.pdf_path&&<a className="resource-action" href={`/api/files/commercial/${v.id}?asset=pdf`}>PDF</a>}</article>)}</section>}<section className="dossier-card"><h3>Gebeurtenissen</h3>{detail.events.map(e=><article className="dossier-event" key={e.id}><div><strong>{eventLabels[e.kind]||e.kind}</strong><small>{date(e.created_at,true)} · {e.actor||"Klant / systeem"} · {e.visibility==="internal"?"Intern":"Klantcommunicatie"}</small>{e.body&&<p className="commercial-prewrap">{e.body}</p>}</div></article>)}</section></TabsContent></div></Tabs>
 </CommercialDialog>;
}
