"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {readCommercialList} from "@/app/app/commercial-actions";
import {commercialDate,money,priceBases,requestLabels,quoteLabels,type CommercialList} from "@/lib/commercial/model";

/** The dossier projects the same paged records as the commercial workspace. */
export function CommercialDossierPanel({customerId,objectId,timezone}:{customerId:string;objectId?:string;timezone:string}){
 const [tab,setTab]=useState("requests"),[page,setPage]=useState(1),[data,setData]=useState<CommercialList|null>(null),[error,setError]=useState("");
 useEffect(()=>{let live=true;void readCommercialList({tab,page,customer:customerId,object:objectId||""}).then(r=>{if(!live)return;if(r.ok){setData(r.data);setError("");}else setError(r.error);}).catch(()=>{if(live)setError("Het dossier kon niet worden geladen. Open het tabblad opnieuw om te proberen.");});return()=>{live=false;};},[customerId,objectId,tab,page]);
 const back=objectId?`/app/objecten/${objectId}?tab=commercieel`:`/app/klanten/${customerId}?tab=offertes`;
 const base=`customer=${customerId}${objectId?`&object=${objectId}`:""}&return=${encodeURIComponent(back)}`;
 return <section className="dossier-card commercial-dossier-panel"><div className="object-section-title"><div><h2>Aanvragen & Offertes</h2><p>Dezelfde klantvragen, versiehistorie en opdrachten als in de commerciële werkvoorraad.</p></div><div className="object-actions"><Link className="secondary-button" href={`/app/aanvragen?${base}&new=request`}>Nieuwe aanvraag</Link><Link className="primary-button" href={`/app/aanvragen?${base}&tab=quotes&new=quote`}>Nieuwe offerte</Link></div></div><Tabs value={tab} onValueChange={v=>{setTab(v);setPage(1);}}><TabsList aria-label="Commercieel dossier"><TabsTrigger value="requests">Aanvragen</TabsTrigger><TabsTrigger value="quotes">Offertes</TabsTrigger></TabsList></Tabs>
 {error&&<p className="auth-message error" role="alert">{error}</p>}<div className="table-scroll"><table className="resource-table"><thead><tr><th>Nummer / onderwerp</th><th>Object</th><th>Status</th>{tab==="quotes"&&<th>Bedrag / versie</th>}<th>Vervolg</th><th>Acties</th></tr></thead><tbody>{data?.rows.map(r=><tr key={`${r.source_kind}:${r.id}`}><td><strong>{r.number}</strong><small>{r.subject}</small></td><td>{r.object||"Object nog vaststellen"}</td><td>{(tab==="quotes"?quoteLabels:requestLabels)[r.status]||r.status}</td>{tab==="quotes"&&<td>{money(r.subtotal_cents??0)} excl. btw<small>{priceBases[r.price_basis||"once"]} · v{r.revision}</small></td>}<td>{r.next_action}<small>{commercialDate(r.followup_on,timezone)}</small>{r.operation_id&&<Link href={`/app/planning?order=${r.operation_id}`}>Planning</Link>}</td><td><Link className="resource-action" href={`/app/aanvragen?${base}&tab=${tab}&record=${r.id}&recordKind=${r.source_kind}`}>Bekijk</Link></td></tr>)}</tbody></table></div>{!data?.rows.length&&!error&&<p className="dossier-empty">{data?"Nog geen registraties bij deze selectie.":"Dossier laden…"}</p>}<footer className="object-pagination"><span>{data?.total??0} registraties</span><button className="resource-action" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Vorige</button><button className="resource-action" disabled={page*25>=(data?.total??0)} onClick={()=>setPage(p=>p+1)}>Volgende</button></footer></section>;
}
