"use client";
import {useEffect,useRef,useState,useTransition,type FormEvent} from "react";
import {ChevronLeft,ChevronRight,Plus,Trash2} from "lucide-react";
import {toast} from "sonner";
import type {TenantContext} from "@/lib/auth/context";
import type {Row} from "@/lib/objects/model";
import {commercialAction,readCommercialOptions} from "@/app/app/commercial-actions";
import {sendCommercialQuote,uploadCommercialAttachment} from "@/app/app/commercial-delivery-actions";
import {emptyOptions,emptyTerms,workKinds,priceBases,priorities,sources,previewPrices,money,type CommercialOptions,type QuoteLine,type QuoteTerms,type QuoteSnapshot} from "@/lib/commercial/model";
import {localToInstant,tenantToday} from "@/lib/planning/time";
import {ObjectWizard} from "@/components/fieldgrid/objects/forms";
import {CommercialDialog} from "./dialog";
import {QuoteDocument} from "./document";

export function LineEditor({lines,onChange,options}:{lines:QuoteLine[];onChange:(lines:QuoteLine[])=>void;options:CommercialOptions}){
 const change=(id:string,patch:Partial<QuoteLine>)=>onChange(lines.map(l=>l.id===id?{...l,...patch}:l));
 return <div className="commercial-lines-editor wide"><label>Taak uit Taken & tarieven<select value="" onChange={e=>{const t=options.tasks.find(t=>t.id===e.target.value);if(t)onChange([...lines,{id:crypto.randomUUID(),task_revision_id:t.id,task_code:t.code,description:t.name,quantity:1,unit:t.unit,price_cents:t.price_cents,vat_basis_points:t.vat_basis_points,discount_basis_points:0,duration_minutes:t.duration_minutes}]);}}><option value="">Kies een catalogustaak om toe te voegen…</option>{options.tasks.map(t=><option key={t.id} value={t.id}>{t.code} · {t.name} · {money(t.price_cents)}</option>)}</select></label>
 {lines.map((l,i)=><fieldset className="commercial-line" key={l.id}><legend>Regel {i+1}{l.task_code?` · ${l.task_code}`:" · Handmatig"}</legend><label className="wide">Omschrijving<input value={l.description} minLength={2} maxLength={3000} onChange={e=>change(l.id,{description:e.target.value})}/></label><label>Aantal<input type="number" min="0.001" max="1000000" step="0.001" value={l.quantity} onChange={e=>change(l.id,{quantity:e.target.value})}/></label><label>Eenheid<input value={l.unit} maxLength={60} onChange={e=>change(l.id,{unit:e.target.value})} list="commercial-units"/></label><label>Tarief excl. btw<input type="number" min="0" step="0.01" value={l.price_cents/100} onChange={e=>change(l.id,{price_cents:Math.round(Number(e.target.value)*100)})}/></label><label>Btw %<input type="number" min="0" max="100" step="0.01" value={l.vat_basis_points/100} onChange={e=>change(l.id,{vat_basis_points:Math.round(Number(e.target.value)*100)})}/></label><label>Korting %<input type="number" min="0" max="100" step="0.01" value={l.discount_basis_points/100} onChange={e=>change(l.id,{discount_basis_points:Math.round(Number(e.target.value)*100)})}/></label><label>Duur per eenheid (minuten)<input type="number" min="1" max="43200" value={l.duration_minutes??""} onChange={e=>change(l.id,{duration_minutes:e.target.value?Number(e.target.value):null})}/></label><button type="button" className="resource-action danger" onClick={()=>onChange(lines.filter(x=>x.id!==l.id))}><Trash2 size={14}/>Regel verwijderen</button></fieldset>)}
 <datalist id="commercial-units">{["uur","bezoek","uitvoering","m²","stuk","task","hour","item"].map(u=><option key={u} value={u}/>)}</datalist>
 <button type="button" className="secondary-button" disabled={lines.length>=100} onClick={()=>onChange([...lines,{id:crypto.randomUUID(),description:"",quantity:1,unit:"uitvoering",price_cents:0,vat_basis_points:0,discount_basis_points:0,duration_minutes:null}])}><Plus size={15}/>Handmatige regel</button><p className="form-note">Catalogustarieven blijven ongewijzigd. Controleer bij een handmatige regel zelf de toepasselijke btw.</p></div>;
}

export function CommercialWizard({kind,tenant,userId,initialOptions,onClose,onSaved,record,request,customerId="",objectId=""}:{kind:"request"|"quote";tenant:TenantContext;userId:string;initialOptions:CommercialOptions;onClose:()=>void;onSaved:(id:string,kind:"request"|"quote")=>void;record?:Row<"requests">|Row<"quotes">;request?:Row<"requests">;customerId?:string;objectId?:string}){
 const q=record&&"quote_number"in record?record:null;const r=record&&"request_number"in record?record:request;
 const [id]=useState(()=>record?.id||crypto.randomUUID());const [commandId,setCommandId]=useState(()=>crypto.randomUUID());const [version,setVersion]=useState(record?.version??0);
 const [step,setStep]=useState(1),[pending,start]=useTransition(),[error,setError]=useState(""),[dirty,setDirty]=useState(false);
 const [options,setOptions]=useState(initialOptions??emptyOptions),[lookup,setLookup]=useState(""),[newObject,setNewObject]=useState(false),[optionError,setOptionError]=useState("");
 const [customer,setCustomer]=useState(record?.customer_id||r?.customer_id||customerId),[object,setObject]=useState(record?.object_id||r?.object_id||objectId),[contact,setContact]=useState(record?.contact_id||r?.contact_id||"");
 const [prospect,setProspect]=useState(false),[prospectData,setProspectData]=useState({name:"",email:"",phone:"",contact:""});
 const [subject,setSubject]=useState(record?.subject||r?.subject||""),[description,setDescription]=useState(r?.description||""),[discipline,setDiscipline]=useState(r?.discipline||"");
 const [workKind,setWorkKind]=useState(q?.work_kind||r?.work_kind||"once"),[source,setSource]=useState(r?.source||"backoffice"),[priority,setPriority]=useState(r?.priority||"normal");
 const [owner,setOwner]=useState(record?.owner_id||userId),[nextAction,setNextAction]=useState(r?.next_action||"Aanvraag beoordelen"),[followup,setFollowup]=useState(record?.followup_on||tenantToday(tenant.timezone));
 const [preferences,setPreferences]=useState((r?.preferences??{}) as Record<string,string>);
 const [terms,setTerms]=useState<QuoteTerms>({...emptyTerms,...(q?.terms as Partial<QuoteTerms>??{}),...(!q?{scope:r?.description||"",discipline:r?.discipline||""}:{})});
 const [basis,setBasis]=useState(q?.price_basis||"once"),[lines,setLines]=useState<QuoteLine[]>(q?.lines as unknown as QuoteLine[]??[]),[expires,setExpires]=useState(()=>q?.expires_at?.slice(0,10)||new Date(Date.now()+14*86400000).toISOString().slice(0,10)),[files,setFiles]=useState<File[]>([]);
 const sequence=useRef(0);const steps=kind==="request"?["Klant en object","Werk en voorkeuren","Controleren en opvolging"]:["Herkomst en koppelingen","Werk en regels","Afspraken en document","Controleren"];
 useEffect(()=>{const n=++sequence.current;const timer=setTimeout(async()=>{try{const res=await readCommercialOptions(lookup,customer);if(n!==sequence.current)return;if(res.ok){setOptions(res.data);setOptionError("");}else setOptionError(res.error);}catch{if(n===sequence.current)setOptionError("De keuzes konden niet worden geladen. Probeer de zoekopdracht opnieuw.");}},250);return()=>{clearTimeout(timer);sequence.current=n+1;};},[lookup,customer]);
 const changeCustomer=(value:string)=>{setCustomer(value);setObject("");setContact("");setDirty(true);};
 const term=(key:keyof QuoteTerms,value:string)=>setTerms(v=>({...v,[key]:value}));
 const field=(label:string,value:string,set:(v:string)=>void,props:React.InputHTMLAttributes<HTMLInputElement>={})=><label>{label}<input value={value} onChange={e=>set(e.target.value)} {...props}/></label>;
 const choice=(label:string,value:string,set:(v:string)=>void,items:Array<[string,string]>,blank?:string)=><label>{label}<select required={label==="Klant"||label==="Behandelaar"} value={value} onChange={e=>set(e.target.value)}>{blank!==undefined&&<option value="">{blank}</option>}{items.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>;
 const submit=(event:FormEvent<HTMLFormElement>,send=false)=>{event.preventDefault();setError("");start(async()=>{
  try{
   const payload=kind==="request"?{id,version,customer_id:prospect?"":customer,object_id:object,contact_id:contact,prospect:prospect?prospectData:undefined,subject,description,discipline,source,priority,work_kind:workKind,owner_id:owner,next_action:nextAction,followup_on:followup,preferences}:{id,version,request_id:q?.request_id||request?.id||"",customer_id:customer,object_id:object,contact_id:contact,subject,work_kind:workKind,price_basis:basis,owner_id:owner,followup_on:followup,lines,terms,expires_at:expires?localToInstant(`${expires}T23:59`,tenant.timezone):""};
   const saved=await commercialAction(`${kind}_save`,payload,commandId);if(!saved.ok){setError(saved.error);setCommandId(crypto.randomUUID());return;}
   setDirty(false);setVersion(version+1);setCommandId(crypto.randomUUID());
   if(kind==="request"&&saved.data.customer_id){setCustomer(String(saved.data.customer_id));setContact(String(saved.data.contact_id||""));setProspect(false);}
   for(const file of files){const form=new FormData();form.set("entityId",id);form.set("kind",kind);form.set("file",file);form.set("title",file.name);form.set("public",kind==="quote"?"true":"false");const upload=await uploadCommercialAttachment(form);if(!upload.ok){setError(`De ${kind==="quote"?"offerte":"aanvraag"} is opgeslagen, maar een bijlage niet: ${upload.error}`);return;}}
   setFiles([]);
   if(send&&kind==="quote"){const sent=await sendCommercialQuote(id,crypto.randomUUID(),false);if(!sent.ok){toast.error(`Offerte opgeslagen. ${sent.error}`);onSaved(id,kind);return;}}
   toast.success(send?"Offerte aangeboden voor verzending":kind==="request"?"Aanvraag opgeslagen":"Concept opgeslagen");onSaved(id,kind);
  }catch{setError("Opslaan is niet gelukt. Je invoer is behouden. Controleer de gegevens en probeer opnieuw.");}
 });};
 let preview:QuoteSnapshot|null=null;try{const c=options.customers.find(c=>c.id===customer),o=options.objects.find(o=>o.id===object),ct=options.contacts.find(c=>c.id===contact);preview={schema:1,quote_number:q?.quote_number||"CONCEPT",revision:q?.revision||1,subject,work_kind:workKind as QuoteSnapshot["work_kind"],price_basis:basis as QuoteSnapshot["price_basis"],terms,expires_at:expires,customer:{id:customer,name:c?.name||"Klant nog kiezen",number:c?.customer_number||"",billing_address:(c?.billing_address??{}) as Record<string,unknown>},contact:{name:ct?.full_name||c?.name||"",email:ct?.email||c?.billing_email||""},object:{id:object,name:o?.name||"",number:"",address:(o?.address??{}) as Record<string,unknown>},brand:options.brand??{name:tenant.name,slug:tenant.slug,primary:tenant.primaryColor,accent:tenant.accentColor,logo_source:tenant.logoPath,sender_email:null,sender_name:null,footer:null,white_label:tenant.whiteLabelEnabled,business:{}},attachments:files.map((f,i)=>({id:String(i),title:f.name,sha256:"",mime_type:f.type})),...previewPrices(lines)};}catch{/* Invalid draft values remain editable. */}
 return <CommercialDialog title={`${record?"Bewerk":kind==="quote"?"Nieuwe":"Nieuwe"} ${kind==="quote"?"offerte":"aanvraag"}`} description={q?`${q.quote_number} · conceptversie ${q.revision}`:"Van klantvraag naar een duidelijke afspraak."} tenant={tenant} onClose={onClose} dirty={dirty} busy={pending}>
 <ol className="wizard-progress">{steps.map((s,i)=><li className={i<step?"active":""} aria-current={i+1===step?"step":undefined} key={s}><span>{i+1}</span><small>{s}</small></li>)}</ol>
 <form className="commercial-wizard" noValidate onChange={()=>setDirty(true)} onSubmit={e=>submit(e,(e.nativeEvent as SubmitEvent).submitter?.getAttribute("value")==="send")}>
 <div className="commercial-form-body">
 <fieldset hidden={step!==1}><legend>Klant en uitvoeringslocatie</legend>{request&&<p className="dossier-notice wide">Vanuit {request.request_number}: {request.subject||request.description}</p>}
 {!record&&kind==="request"&&<label className="wide">Relatie<select value={prospect?"new":"existing"} onChange={e=>{setProspect(e.target.value==="new");changeCustomer("");}}><option value="existing">Bestaande klant</option><option value="new">Nieuwe prospect</option></select></label>}
 {prospect?<><label>Naam prospect<input required minLength={2} value={prospectData.name} onChange={e=>{setProspectData(v=>({...v,name:e.target.value}));setLookup(e.target.value);}}/></label>{field("Contactpersoon",prospectData.contact,v=>setProspectData(p=>({...p,contact:v})))}{field("E-mail",prospectData.email,v=>setProspectData(p=>({...p,email:v})),{type:"email"})}{field("Telefoon",prospectData.phone,v=>setProspectData(p=>({...p,phone:v})),{type:"tel"})}{lookup.length>1&&options.customers.length>0&&<div className="dossier-notice wide"><strong>Mogelijk bestaande relaties</strong>{options.customers.slice(0,5).map(c=><button key={c.id} type="button" className="resource-action" onClick={()=>{setProspect(false);changeCustomer(c.id);}}>{c.name} hergebruiken</button>)}<small>Overeenkomsten worden niet automatisch samengevoegd.</small></div>}<p className="form-note wide">De prospect wordt samen met deze aanvraag opgeslagen. Een uitvoeringslocatie kun je daarna toevoegen.</p></>:<>{field("Klant zoeken",lookup,setLookup,{placeholder:"Naam, nummer of e-mail…"})}{choice("Klant",customer,changeCustomer,options.customers.map(c=>[c.id,c.name]),"Kies een klant")}{choice("Contactpersoon",contact,setContact,options.contacts.map(c=>[c.id,`${c.full_name}${c.email?` · ${c.email}`:""}`]),"Algemeen klantcontact")}{choice("Object",object,setObject,options.objects.filter(o=>o.customer_id===customer).map(o=>[o.id,o.name]),"Object later vaststellen")}<button type="button" className="secondary-button" disabled={!customer} onClick={()=>setNewObject(true)}><Plus size={15}/>Nieuw object</button>{!object&&<p className="dossier-notice wide">Intake mag zonder object. Voor het aanbieden van de offerte en het plannen van werk kies je eerst de definitieve locatie.</p>}</>}{optionError&&<p role="alert" className="auth-message error wide">{optionError}</p>}</fieldset>
 <fieldset hidden={step!==2}><legend>Werkzaamheden en voorkeuren</legend>{field("Onderwerp",subject,setSubject,{required:true,minLength:2,maxLength:180})}{choice("Soort werk",workKind,setWorkKind,Object.entries(workKinds))}
 {kind==="request"?<><label className="wide">Oorspronkelijke klantvraag<textarea required minLength={3} maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)} readOnly={!!record}/></label>{field("Dienst / discipline",discipline,setDiscipline,{required:true,list:"commercial-disciplines"})}{choice("Bron",source,setSource,Object.entries(sources).filter(([s])=>!["website","portal","email_link"].includes(s)))}{choice("Prioriteit",priority,setPriority,Object.entries(priorities))}{field("Gewenste datum",preferences.date||"",v=>setPreferences(p=>({...p,date:v})),{type:"date"})}{field("Gewenst tijdvenster",preferences.window||"",v=>setPreferences(p=>({...p,window:v})))}{workKind==="recurring"&&field("Gewenste frequentie",preferences.frequency||"",v=>setPreferences(p=>({...p,frequency:v})))}{!object&&field("Bekende locatie / vervolgactie",preferences.location||"",v=>setPreferences(p=>({...p,location:v})))}</>:<>{field("Dienst / discipline",terms.discipline,v=>term("discipline",v),{list:"commercial-disciplines"})}<label className="wide">Introductie<textarea value={terms.introduction} onChange={e=>term("introduction",e.target.value)}/></label><label className="wide">Omvang van de werkzaamheden<textarea value={terms.scope} onChange={e=>term("scope",e.target.value)} maxLength={10000}/></label><LineEditor lines={lines} onChange={setLines} options={options}/></>}
 <datalist id="commercial-disciplines">{[...new Set(options.tasks.map(t=>t.discipline))].map(d=><option key={d} value={d}/>)}</datalist></fieldset>
 {kind==="quote"&&<fieldset hidden={step!==3}><legend>Afspraken en document</legend>{field("Geldig tot",expires,setExpires,{type:"date"})}{choice("Prijsbasis",basis,setBasis,Object.entries(priceBases))}{choice("Prijsafspraak",terms.pricing_method,v=>term("pricing_method",v),[["fixed","Vaste prijs"],["estimate","Indicatieve prijs"],["actual","Nacalculatie"]])}{field("Bezoekfrequentie",terms.frequency,v=>term("frequency",v),{placeholder:"Bijvoorbeeld 3 bezoeken per week"})}{field("Gewenste start",terms.starts_on||"",v=>term("starts_on",v),{type:"date"})}{field("Einde looptijd",terms.ends_on||"",v=>term("ends_on",v),{type:"date"})}{([["included","Inbegrepen werkzaamheden"],["excluded","Uitsluitingen"],["preparation","Voorbereiding door klant"],["conditions","Voorwaarden"]] as const).map(([k,label])=><label className="wide" key={k}>{label}<textarea value={terms[k]} onChange={e=>term(k,e.target.value)} maxLength={10000}/></label>)}</fieldset>}
 <fieldset hidden={step!==steps.length}><legend>Controleren en opvolging</legend>{kind==="request"?<div className="wizard-summary wide"><div><strong>{subject||"Onderwerp ontbreekt"}</strong><p>{prospect?prospectData.name:options.customers.find(c=>c.id===customer)?.name||"Klant ontbreekt"} · {options.objects.find(o=>o.id===object)?.name||"Object nog vaststellen"}</p><p className="commercial-prewrap">{description}</p><p>{workKinds[workKind as keyof typeof workKinds]} · {discipline}</p></div></div>:preview?<div className="wide"><QuoteDocument snapshot={preview} timezone={tenant.timezone} logoUrl={tenant.logoPath?`/api/branding/${tenant.id}/email-logo`:null}/></div>:<p className="dossier-notice wide">Controleer de aantallen en prijzen om het voorbeeld te bekijken.</p>}
 {choice("Behandelaar",owner,setOwner,options.owners.map(o=>[o.id,o.name]))}{field("Opvolgdatum",followup,setFollowup,{type:"date"})}{kind==="request"&&field("Volgende actie",nextAction,setNextAction,{required:true,minLength:2,maxLength:300})}
 <label className="wide">{kind==="quote"?"Openbare bijlagen bij de offerte":"Foto’s en bijlagen bij de aanvraag"}<input type="file" accept=".pdf,.png,.jpg,.jpeg" multiple onChange={e=>setFiles([...e.target.files??[]])}/><small>PDF, JPG of PNG, maximaal 10 MB per bestand. Geen toegangscodes of vertrouwelijke objectgegevens. {kind==="quote"&&"Deze bestanden worden met de ontvanger gedeeld."}</small></label>
 {kind==="quote"&&<p className="dossier-notice wide">Een concept mag onvolledig zijn. Aanbieden vereist klant, ontvanger, object, dienst, werkzaamheden, regels en geldigheid. Offerteakkoord is geen planning of betaalbevestiging.</p>}</fieldset>
 {error&&<p className="auth-message error" role="alert">{error}</p>}
 </div><footer className="wizard-footer"><button type="button" className="secondary-button" disabled={pending} onClick={()=>step>1?setStep(step-1):(!dirty||confirm("Niet opgeslagen invoer weggooien?"))&&onClose()}><ChevronLeft size={16}/>{step===1?"Annuleren":"Vorige"}</button>{kind==="quote"&&<button className="secondary-button" type="submit" disabled={pending||!customer||subject.trim().length<2}>Opslaan als concept</button>}{step<steps.length?<button key="next" type="button" className="primary-button" disabled={pending} onClick={e=>{const fields=e.currentTarget.form?.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>("fieldset:not([hidden]) input,fieldset:not([hidden]) select,fieldset:not([hidden]) textarea");if(fields&&[...fields].every(f=>f.reportValidity())){setError("");setStep(step+1);}}}>Volgende<ChevronRight size={16}/></button>:<button key="submit" type="submit" value={kind==="quote"?"send":"save"} className="primary-button" disabled={pending}>{pending?"Bezig…":kind==="quote"?"Verzenden":"Aanvraag opslaan"}</button>}</footer>
 </form>{newObject&&<ObjectWizard tenant={tenant} customers={options.customers} customerId={customer} onClose={()=>setNewObject(false)} onSaved={async id=>{const result=await readCommercialOptions(lookup,customer);if(result.ok)setOptions(result.data);setObject(id);setDirty(true);}}/>}
 </CommercialDialog>;
}
