"use client";
import { useEffect,useId,useRef,useState,useTransition } from "react";
import { Download,FileText,Send } from "lucide-react";
import { customerCommercialSchema,type CustomerCommercial,type CustomerCommercialCommand } from "@/lib/customer-portal/commercial-model";
import { customerDate } from "@/lib/customer-portal/presentation";
import { money,requestLabels,quoteLabels } from "@/lib/commercial/model";
import type { CustomerFormResult } from "./forms";
import { CustomerDialog } from "./dialog";

export function CustomerCommercialDetail({accountId,requestId,timezone,customerName,close,save}:{accountId:string;requestId:string;timezone:string;customerName:string;close:()=>void;save:(action:CustomerCommercialCommand,id:string)=>Promise<CustomerFormResult>}){
 const [detail,setDetail]=useState<CustomerCommercial|null>(null),[error,setError]=useState(""),[revision,setRevision]=useState(0),[selected,setSelected]=useState<string|null>(null),[body,setBody]=useState(""),[decision,setDecision]=useState<"accepted"|"rejected"|"change_requested">("accepted"),[name,setName]=useState(customerName),[confirmed,setConfirmed]=useState(false),[pending,start]=useTransition();
 const [initializedVersion,setInitializedVersion]=useState<string|null>(null),keys=useRef(new Map<string,string>()),formId=useId();
 const quote=detail?.quotes.find(item=>item.id===selected),dirty=!!body.trim()||confirmed;
 useEffect(()=>{
  const abort=new AbortController();
  void (async()=>{try{const response=await fetch(`/api/customer-portal/request?${new URLSearchParams({account:accountId,request:requestId})}`,{signal:abort.signal,credentials:"same-origin",cache:"no-store",redirect:"error"});if(!response.ok){if(response.status===403)setDetail(null);throw new Error();}const value=customerCommercialSchema.parse(await response.json());if(value.request.id!==requestId)throw new Error();if(!abort.signal.aborted){setDetail(value);setError("");}}catch{if(!abort.signal.aborted)setError("De actuele aanvraag kon niet worden geladen. Controleer opnieuw voordat je verdergaat.");}})();
  return()=>abort.abort();
 },[accountId,requestId,revision]);
 const cancel=()=>{if(!pending&&(!dirty||window.confirm("Je reactie is nog niet verstuurd. Toch sluiten?")))close();};
 const choose=(id:string|null)=>{if(dirty&&!window.confirm("Je reactie is nog niet verstuurd. Toch verdergaan?"))return;setSelected(id);setBody("");setConfirmed(false);setInitializedVersion(null);setError("");};
 const fileHref=quote?`/api/customer-portal/files/quote/${quote.id}?${new URLSearchParams({account:accountId})}`:"";
 const submit=()=>{
  if(!detail)return;
  if(quote&&initializedVersion&&initializedVersion!==`${quote.id}:${quote.version}`){setError("Deze offerte is gewijzigd. Lees de actuele offerte en bevestig opnieuw.");setConfirmed(false);setInitializedVersion(null);return;}
  const action:CustomerCommercialCommand=quote?{command:"decide",input:{id:quote.id,version:quote.version,revision:quote.revision,decision,name,evidence:body,confirmed:true}}:{command:"reply",input:{id:requestId,version:detail.request.version,body}};
  if(quote&&!confirmed){setError("Bevestig dat je deze offerteversie hebt gelezen.");return;}
  const key=JSON.stringify(action);let commandId=keys.current.get(key);if(!commandId){commandId=crypto.randomUUID();keys.current.set(key,commandId);}
  start(async()=>{try{const result=await save(action,commandId);if(!result.ok){setError(result.error);return;}setBody("");setConfirmed(false);setInitializedVersion(null);setRevision(value=>value+1);}catch{setError("Je reactie kon niet worden bevestigd. Je invoer blijft staan.");}});
 };
 return <CustomerDialog guideKey="feature.customer-request" title={quote?`Offerte ${quote.number}`:detail?.request.subject??"Aanvraag & offerte"} kicker="Diensten & aanvragen" close={close} dirty={dirty} busy={pending} footer={<><button className="button" type="button" onClick={cancel} disabled={pending}>Sluiten</button>{quote?.hasPdf&&<a className="button" href={fileHref}><Download/>PDF opslaan</a>}{((quote?.canDecide)||(!quote&&detail?.request.canReply))&&<button className="button primary" form={formId} disabled={pending}><Send/>{pending?"Opslaan…":quote?"Besluit bevestigen":"Reactie versturen"}</button>}</>}>
  {error&&<div className="form-error" role="alert"><p>{error}</p><button className="button" type="button" onClick={()=>setRevision(value=>value+1)} disabled={pending}>Actuele gegevens controleren</button></div>}
  {!detail?<p role="status">Aanvraag laden…</p>:<>
   <div className="detail-tabs"><button className={!quote?"active":""} type="button" onClick={()=>choose(null)} disabled={pending}>Aanvraag</button>{detail.quotes.map(item=><button key={item.id} className={selected===item.id?"active":""} type="button" onClick={()=>choose(item.id)} disabled={pending}>Offerte v{item.revision}</button>)}</div>
   {!quote?<><div className="row"><strong>{detail.request.number}</strong><span className="chip gray">{requestLabels[detail.request.status]??detail.request.status}</span></div><p className="preserved section-gap">{detail.request.description}</p><div className="messages section-gap">{detail.events.map(event=><article className="message" key={event.id}><strong>{event.author}</strong><small>{customerDate(event.at,timezone,true)}</small><p className="preserved">{event.body}</p></article>)}</div>{detail.request.canReply&&<form id={formId} onSubmit={event=>{event.preventDefault();submit();}}><label className="field"><span>Aanvullende informatie</span><textarea required minLength={3} maxLength={5000} rows={4} value={body} onChange={event=>setBody(event.target.value)} disabled={pending}/></label></form>}{!detail.quotes.length&&<p className="meta section-gap">Er is nog geen offerte aangeboden voor deze aanvraag.</p>}</>:<>
    <div className="row"><strong>Versie {quote.revision}</strong><span className="chip gray">{quoteLabels[quote.status]??quote.status}</span></div><p className="meta">Geldig tot {customerDate(quote.expiresAt,timezone,true)}</p>
    {quote.snapshot&&<article className="invoice-paper section-gap"><h3>{quote.snapshot.subject}</h3><p>{quote.snapshot.supplier.name}</p><div className="details section-gap"><div><small>Klant</small><strong>{quote.snapshot.customer.name}</strong></div><div><small>Object</small><strong>{quote.snapshot.object.name||"In overleg"}</strong></div></div><div className="section-gap">{quote.snapshot.lines.map((line,index)=><div className="ticket-row" key={index}><div><strong>{line.description}</strong><small>{line.quantity} {line.unit} × {money(line.price)}</small></div><strong>{money(line.net)}</strong></div>)}</div><div className="details section-gap"><div><small>Subtotaal</small><strong>{money(quote.snapshot.subtotal)}</strong></div><div><small>Btw</small><strong>{money(quote.snapshot.vat)}</strong></div><div><small>Totaal</small><strong>{money(quote.snapshot.total)}</strong></div></div>{Object.entries(quote.snapshot.terms).filter(([,value])=>value).map(([key,value])=><div key={key} className="section-gap"><h4>{({introduction:"Toelichting",scope:"Werkzaamheden",included:"Inbegrepen",excluded:"Niet inbegrepen",preparation:"Voorbereiding",conditions:"Voorwaarden",frequency:"Frequentie",starts_on:"Startdatum",ends_on:"Einddatum",pricing_method:"Prijsafspraak",discipline:"Dienst"} as Record<string,string>)[key]??key}</h4><p className="preserved">{value}</p></div>)}</article>}
    {quote.hasPdf&&<a className="button section-gap" href={`${fileHref}&preview=1`} target="_blank" rel="noopener noreferrer"><FileText/>PDF bekijken</a>}
    {quote.canDecide?<form id={formId} onSubmit={event=>{event.preventDefault();submit();}} className="section-gap"><label className="field"><span>Jouw besluit</span><select value={decision} onChange={event=>{setDecision(event.target.value as typeof decision);setConfirmed(false);}} disabled={pending}><option value="accepted">Offerte accepteren</option><option value="change_requested">Wijziging aanvragen</option><option value="rejected">Offerte afwijzen</option></select></label><label className="field"><span>Jouw naam *</span><input required minLength={2} maxLength={180} value={name} onChange={event=>setName(event.target.value)} disabled={pending}/></label><label className="field"><span>Toelichting{decision!=="accepted"?" *":""}</span><textarea rows={3} minLength={decision!=="accepted"?3:undefined} required={decision!=="accepted"} maxLength={3000} value={body} onChange={event=>setBody(event.target.value)} disabled={pending}/></label><label className="check-option"><input type="checkbox" checked={confirmed} required onChange={event=>{setConfirmed(event.target.checked);setInitializedVersion(`${quote.id}:${quote.version}`);}} disabled={pending}/><span>Ik heb offerte {quote.number}, versie {quote.revision}, inclusief voorwaarden gelezen en bevestig mijn besluit.</span></label></form>:<p className="banner section-gap">Deze offerteversie kan niet meer worden beantwoord.</p>}
   </>}
  </>}
 </CustomerDialog>;
}
