"use client";
import Link from "next/link";
import { GuideBanner } from "@/components/fieldgrid/guides/guide";
import { TenantThemeProvider } from "../tenant-theme";
import { PageHeading } from "../page-heading";

import { FieldgridBrand } from "../brand";
import { AccountMenu } from "../account-menu";
import { ActionIcon } from "../action-icon";
import { EmptyState } from "../empty-state";
import { ContentTabs } from "../content-tabs";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { useState, useSyncExternalStore, type ReactNode } from "react";
import { Bell, Building2, CalendarDays, Check, ChevronRight, Clock3, Download, Eye, FileText, Info, LockKeyhole, Mail, MapPin, MoreHorizontal, Newspaper, Phone, Plus, Settings2, ShieldCheck, Sparkles, Ticket, UserRound, Wallet } from "lucide-react";
import { CompactFilterMenu } from "@/components/fieldgrid/compact-filter-menu";
import { portalThemeStyle } from "@/lib/branding/palette";
import { money,requestLabels } from "@/lib/commercial/model";
import type { CustomerPreferences,CustomerProfileInput,CustomerView,CustomerWorkspace } from "@/lib/customer-portal/model";
import { customerDate,customerInitials,customerInvoiceLabel,customerInvoiceOverdue,customerInvoicePayable,customerTime,customerVisitFinished,customerVisitLabel,type CustomerActivity,type CustomerInvoice,type CustomerNews,type CustomerReport,type CustomerResources } from "@/lib/customer-portal/presentation";
import { customerObjectTypes } from "./fields";
import { CustomerProfileForm,type CustomerFormResult } from "./forms";
import { CustomerPreferencesForm } from "./preferences";
import "./customer-portal.css";
import "./consistency.css";

export const customerNavigation=[
 ["dashboard",CalendarDays,"Cockpit"],["objects",Building2,"Mijn objecten"],["appointments",Clock3,"Mijn afspraken"],["reports",FileText,"Rapporten"],
 ["invoices",Wallet,"Facturen"],["requests",Sparkles,"Diensten & aanvragen"],["tickets",Ticket,"Tickets"],["news",Newspaper,"Nieuws"],["profile",UserRound,"Mijn gegevens"],
] as const;
const customerTicketRoutes=[["tenant",UserRound,"Jouw accountmanager","Planning, dienstverlening en facturen"],["platform",Settings2,"Technische support","Inloggen, storingen en het portaal"]] as const;
const customerMobileNavigation=[["dashboard",CalendarDays,"Cockpit"],["objects",Building2,"Objecten"],["appointments",Clock3,"Afspraken"],["invoices",Wallet,"Facturen"],["more",MoreHorizontal,"Meer"] as const] as const;
type ExtraView="notifications"|"more";
export type CustomerPortalAvailability={tickets?:boolean;activity?:boolean;payments?:boolean;documents?:boolean};
export type CustomerPortalActions={
 navigate:(view:CustomerView|ExtraView)=>void;openObject:(id:string)=>void;newObject:()=>void;openVisit:(id:string,notes?:boolean)=>void;
 openReport:(report:CustomerReport)=>void;openInvoice:(invoice:CustomerInvoice)=>void;request:(service?:string,objectId?:string)=>void;openRequest:(id:string)=>void;
 newTicket:(route?:"tenant"|"platform")=>void;openTicket:(id:string)=>void;openNews:(news:CustomerNews)=>void;openActivity:(activity:CustomerActivity)=>void;readAll:()=>void;
 preferences:()=>void;pay:(ids:string[])=>void;
 chooseAccount?:()=>void;
 saveProfile:(value:CustomerProfileInput,versions:{account:number;customer:number;contact:number},id:string)=>Promise<CustomerFormResult>;
 savePreferences:(value:CustomerPreferences,version:number,id:string)=>Promise<CustomerFormResult&{preferenceVersion?:number}>;
};
const onlineSubscribe=(notify:()=>void)=>{window.addEventListener("online",notify);window.addEventListener("offline",notify);return()=>{window.removeEventListener("online",notify);window.removeEventListener("offline",notify);};};
const onlineSnapshot=()=>navigator.onLine,onlineServer=()=>true;
export function CustomerPortal({workspace,tenantId,resources,view,preferences,preferenceVersion,actions,children,stale=false,availability={}}:{
 workspace:CustomerWorkspace;tenantId:string;resources:CustomerResources;view:CustomerView|ExtraView;preferences:CustomerPreferences;preferenceVersion:number;actions:CustomerPortalActions;children?:ReactNode;stale?:boolean;availability?:CustomerPortalAvailability;
}) {
 const {tenant,profile,account,objects,visits}=workspace,online=useSyncExternalStore(onlineSubscribe,onlineSnapshot,onlineServer);
 const logo=tenant.hasLogo?`/api/branding/${tenantId}/email-logo`:null,style=portalThemeStyle(tenant.primaryColor,tenant.accentColor);
 const brand=(mobile=false)=><span className={`wordmark ${mobile?"mobile-brand":""}`}><FieldgridBrand tenantName={tenant.name} logoUrl={logo}/></span>;
 const activeTickets=availability.tickets===false?0:resources.tickets.filter(ticket=>!["resolved","closed"].includes(ticket.status)).length;
 const nav=(items:typeof customerNavigation[number][])=>items.map(([id,Icon,label])=><button key={id} type="button" className={view===id?"active":""} title={label} aria-current={view===id?"page":undefined} onClick={()=>actions.navigate(id)}><Icon aria-hidden="true"/><span>{label}</span>{id==="tickets"&&activeTickets>0&&<span className="nav-count">{activeTickets}</span>}</button>);
 return <TenantThemeProvider primary={tenant.primaryColor} accent={tenant.accentColor}><div className="customer-portal" style={style}><div className="customer-portal-root"><aside className="sidebar"><div className="brand-block">{brand()}<small>KLANTPORTAAL</small></div>
  <nav className="nav-group" aria-label="Hoofdnavigatie"><Link href="/klant/updates"><Sparkles/><span>Wat is er nieuw?</span></Link>{nav(customerNavigation.slice(0,6))}</nav><div className="nav-label">Contact & organisatie</div><nav className="nav-group" aria-label="Contact en organisatie">{nav(customerNavigation.slice(6))}</nav>
  <div className="sidebar-bottom"><div className="tenant-caption">Mijn account</div><button type="button" className="person full" onClick={()=>actions.navigate("profile")}><span className="avatar">{customerInitials(profile.fullName)}</span><div><strong>{profile.fullName}</strong><small>Klant</small></div></button></div>
 </aside><div className="shell"><header className="topbar"><div className="header-left">{brand(true)}
  <span className={`connection-indicator ${!online||stale?"offline":""}`} role="status" aria-label={!online?"Offline":stale?"Gegevens opnieuw controleren":"Online"} title={!online?"Offline":stale?"Gegevens opnieuw controleren":"Online"}><i/></span>
  <div className="breadcrumb">Mijn omgeving <span>/</span> <b>{customerNavigation.find(([id])=>id===view)?.[2]??(view==="more"?"Meer":"Meldingen")}</b></div></div>
  <div className="top-actions"><CustomerNotificationMenu resources={resources} actions={actions} available={availability.activity!==false}/>
  <AccountMenu name={profile.fullName} email={profile.email} role="Klant" triggerLabel="Profielmenu openen" profileLabel="Mijn gegevens" preferencesLabel="Notificaties" onProfile={()=>actions.navigate("profile")} onPreferences={actions.preferences} additionalActions={actions.chooseAccount?[{label:"Ander klantaccount kiezen",icon:<Building2/>,onSelect:actions.chooseAccount}]:[]}/>
  </div></header><main className="page customer-page" id="customer-main-content"><GuideBanner guideKey={`customer.${view === "requests" ? "services" : view}`}/>{!online&&<div className="banner"><Info/><p>Je bent offline. Je invoer blijft in dit venster staan; opslaan en actuele gegevens vereisen verbinding.</p></div>}
   {view==="dashboard"&&<Cockpit workspace={workspace} resources={resources} actions={actions} availability={availability}/>}
   {view==="objects"&&<><PageHead title="Mijn objecten" description="Alle locaties en vaste instructies overzichtelijk bij elkaar." actions={account.canCreateObjects&&tenant.planning?<ActionIcon className="button primary" label="Object toevoegen" icon={<Plus/>} onClick={actions.newObject}/>:undefined}/><div className="objects-grid">{objects.map(object=><ObjectCard key={object.id} object={object} visits={visits} timezone={tenant.timezone} open={()=>actions.openObject(object.id)}/>)}{!objects.length&&<Empty title="Voeg je eerste object toe" text={tenant.planning?"Vul een locatie in om diensten aan te vragen.":"Objecten zijn niet beschikbaar in je organisatie."}>{account.canCreateObjects&&tenant.planning&&<Action primary onClick={actions.newObject}>Object toevoegen</Action>}</Empty>}</div></>}
   {view==="appointments"&&<Appointments workspace={workspace} actions={actions}/>}
   {view==="reports"&&<><PageHead title="Rapporten" description="Bekijk de resultaten van uitgevoerde werkzaamheden."/>{availability.documents===false&&<div className="banner"><Info/><p>Je vrijgegeven rapportsamenvattingen zijn beschikbaar. PDF downloaden is nog niet beschikbaar in dit portaal.</p></div>}<div className="card report-list">{resources.reports.map(report=><article className="document-row" key={report.id}><span className="object-icon"><FileText/></span><div className="grow"><h3>{report.title}</h3><p>{objects.find(object=>object.id===report.objectId)?.name}</p><small>{customerDate(report.approvedAt,tenant.timezone,true)} · {report.number}</small></div><Chip green>Beschikbaar</Chip><div className="document-actions"><ActionIcon label="Bekijken" title={`Rapport ${report.number} bekijken`} icon={<Eye/>} onClick={()=>actions.openReport(report)}/>{availability.documents!==false&&<a className="fg-action-icon" href={`/api/customer-portal/files/report/${report.id}?account=${workspace.account.id}`} aria-label={`PDF downloaden ${report.number}`} title={`PDF downloaden ${report.number}`}><Download aria-hidden="true"/></a>}</div></article>)}{!resources.reports.length&&<Empty title="Nog geen rapporten" text="Na uitvoering vind je hier de vrijgegeven rapporten."/>}</div><div className="section-heading section-gap"><h2>Gedeelde documenten</h2></div><div className="card report-list">{resources.documents.map(document=><article className="document-row" key={document.id}><span className="object-icon"><FileText/></span><div className="grow"><h3>{document.title}</h3><p>Versie {document.version}{document.date?` · ${customerDate(document.date,tenant.timezone)}`:""}</p></div><a className="fg-action-icon" href={`/api/customer-portal/files/document/${document.id}?account=${workspace.account.id}&preview=1`} target="_blank" rel="noopener noreferrer" aria-label="Bekijken" title={`${document.title} bekijken`}><Eye aria-hidden="true"/></a><a className="fg-action-icon" href={`/api/customer-portal/files/document/${document.id}?account=${workspace.account.id}`} aria-label="Opslaan" title={`${document.title} opslaan`}><Download aria-hidden="true"/></a></article>)}{!resources.documents.length&&<Empty title="Nog geen gedeelde documenten" text="Documenten voor jouw objecten verschijnen hier zodra ze met je zijn gedeeld."/>}</div></>}
   {view==="invoices"&&<Invoices resources={resources} workspace={workspace} actions={actions} availability={availability}/>}
   {view==="requests"&&<Requests workspace={workspace} resources={resources} actions={actions}/>}
   {view==="tickets"&&<><PageHead title="Tickets" description="Een vraag over je dienstverlening of hulp bij het portaal?" actions={tenant.tickets&&availability.tickets!==false?<ActionIcon className="button primary" label="Nieuw ticket" icon={<Plus/>} onClick={()=>actions.newTicket()}/>:undefined}/>{availability.tickets===false?<div className="card card-pad"><h2>Tickets nog niet beschikbaar</h2><p>De klantgebonden ticketkoppeling is nog niet aangesloten. Bestaande gesprekken worden hier daarom nog niet getoond.</p>{tenant.phone&&<a className="button section-gap" href={`tel:${tenant.phone.replace(/[^+0-9]/g,"")}`}><Phone/>Neem contact op</a>}</div>:<><div className="ticket-routes">{tenant.tickets&&customerTicketRoutes.map(([route,Icon,title,description])=><button type="button" className="card route-card" key={route} onClick={()=>actions.newTicket(route)}><span className="object-icon"><Icon/></span><div><h3>{title}</h3><p>{description}</p><small>{route==="tenant"?tenant.name:"Technische ondersteuning"}</small></div><ChevronRight/></button>)}</div><div className="section-heading section-gap"><h2>Mijn gesprekken</h2></div><div className="card">{resources.tickets.map(ticket=><button type="button" className="ticket-row" key={ticket.id} onClick={()=>actions.openTicket(ticket.id)}><div><small>{ticket.number} · {ticket.route==="platform"?"Technische ondersteuning":"Accountmanager"}</small><h3>{ticket.subject}</h3><p>{ticket.lastMessage.slice(0,95)}</p></div><Chip green={["resolved","closed"].includes(ticket.status)}>{ticketStatus(ticket.status)}</Chip><ChevronRight/></button>)}{!resources.tickets.length&&<Empty title="Geen tickets" text={tenant.tickets?"Je gesprekken met je accountmanager en support verschijnen hier.":"Tickets zijn niet beschikbaar in je organisatie."}/>}</div></>}</>}
   {view==="news"&&<><PageHead title="Nieuws" description={`Updates en praktische informatie van ${tenant.name}.`}/><div className="news-grid">{resources.news.map(news=><article className="card news-card" key={news.id}><div className="row"><span className="news-label">{news.category}</span><small>{customerDate(news.createdAt,tenant.timezone)}</small></div><div className="news-card-symbol"><Sparkles/></div><h2>{news.title}</h2><p>{news.summary}</p><div className="row"><button className="text-button" type="button" onClick={()=>actions.openNews(news)}>Lees bericht <ChevronRight/></button>{news.readAt&&<Chip green>Gelezen</Chip>}</div></article>)}{!resources.news.length&&<Empty title="Nog geen nieuws" text="Nieuwe updates van je organisatie verschijnen hier."/>}</div></>}
   {view==="profile"&&<><PageHead title="Mijn gegevens" description="Je contactgegevens, factuuradres en e-mailvoorkeuren."/><div className="profile-columns"><CustomerProfileForm profile={profile} allowed={account.canEditProfile} accountVersion={account.version} save={actions.saveProfile}/><CustomerPreferencesForm value={preferences} version={preferenceVersion} save={actions.savePreferences}/></div></>}
   {view==="notifications"&&<><PageHead title="Meldingen" description="Alles wat er speelt rondom jouw objecten." actions={availability.activity!==false?<Action onClick={actions.readAll}><Check/>Alles gelezen</Action>:undefined}/><div className="card card-pad">{availability.activity===false?<><h2>Meldingen nog niet beschikbaar</h2><p>Het klantgebonden overzicht wordt nog aangesloten. Je kunt vrijgegeven nieuws nu al lezen via Nieuws.</p><button className="button section-gap" type="button" onClick={()=>actions.navigate("news")}>Nieuws bekijken</button></>:<>{resources.activity.map(activity=><div className={`notice-row ${activity.readAt?"":"unread"}`} key={activity.id}><span className="object-icon"><Bell/></span><div className="grow"><h3>{activity.title}</h3><p>{activity.summary}</p><button className="text-button" type="button" onClick={()=>actions.openActivity(activity)}>Bekijken</button></div>{!activity.readAt&&<Chip green>Nieuw</Chip>}</div>)}{!resources.activity.length&&<Empty title="Helemaal bij" text="Nieuwe updates verschijnen hier."/>}</>}</div></>}
   {view==="more"&&<><PageHead title="Meer" description="Alles voor jouw organisatie."/><div className="more-grid"><Link className="card more-item" href="/klant/updates"><Sparkles/><strong>Wat is er nieuw?</strong></Link>{customerNavigation.filter(([id])=>!["dashboard","objects","appointments","invoices"].includes(id)).map(([id,Icon,label])=><button type="button" className="card more-item" key={id} onClick={()=>actions.navigate(id)}><Icon/><strong>{label}</strong></button>)}</div></>}
  </main><footer className="portal-footer"><span>{tenant.name} · Zorg voor jouw objecten</span>{!tenant.whiteLabel&&<span>Powered by Fieldgrid</span>}</footer></div>
  <nav className="bottomnav" aria-label="Mobiele navigatie">{customerMobileNavigation.map(([id,Icon,label])=><button type="button" key={id} className={view===id?"active":""} aria-current={view===id?"page":undefined} onClick={()=>actions.navigate(id)}><Icon/><span>{label}</span></button>)}</nav>{children}
 </div></div></TenantThemeProvider>;
}
function CustomerNotificationMenu({resources,actions,available}:{resources:CustomerResources;actions:CustomerPortalActions;available:boolean}){
 const [open,setOpen]=useState(false);
 const navigate=(action:()=>void)=>{setOpen(false);action();};
 return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button className="shell-account-button customer-notification-button" type="button" aria-label={`Meldingen${resources.unread?`, ${resources.unread} ongelezen`:""}`}><Bell/>{resources.unread>0&&<i className="unread-dot"/>}</button></PopoverTrigger><PopoverContent className="nt-bell-panel customer-notification-menu" align="end" collisionPadding={12}>
  <div className="customer-notification-heading"><strong>Mijn meldingen</strong><button type="button" onClick={()=>navigate(actions.preferences)}>Voorkeuren</button></div>
  {available?resources.activity.length?<div className="customer-notification-items">{resources.activity.slice(0,5).map(activity=><button key={activity.id} type="button" className={activity.readAt?"":"unread"} onClick={()=>navigate(()=>actions.openActivity(activity))}><strong>{activity.title}</strong><span>{activity.summary}</span></button>)}</div>:<EmptyState title="Helemaal bij" description="Nieuwe updates verschijnen hier."/>:<p>Meldingen zijn nog niet beschikbaar voor dit account.</p>}
  <button className="customer-notifications-all" type="button" onClick={()=>navigate(()=>actions.navigate("notifications"))}>Alles bekijken</button>
 </PopoverContent></Popover>;
}
function PageHead({title,description,actions}:{title:string;description:string;actions?:ReactNode}){return <PageHeading eyebrow="MIJN OMGEVING" title={title} help={description} actions={actions} className="page-heading"/>;}
function Action({children,onClick,primary=false,small=false,disabled=false}:{children:ReactNode;onClick:()=>void;primary?:boolean;small?:boolean;disabled?:boolean}){return <button type="button" className={`button ${primary?"primary":""} ${small?"small":""}`} onClick={onClick} disabled={disabled}>{children}</button>;}
function Chip({children,green=false,red=false}:{children:ReactNode;green?:boolean;red?:boolean}){return <span className={`chip ${red?"red":green?"green":"gray"}`}>{children}</span>;}
function Empty({title,text,children}:{title:string;text:string;children?:ReactNode}){return <EmptyState title={title} description={text}>{children}</EmptyState>;}
function ObjectCard({object,visits,timezone,open,compact=false}:{object:CustomerWorkspace["objects"][number];visits:CustomerWorkspace["visits"];timezone:string;open:()=>void;compact?:boolean}){
 const next=visits.find(visit=>visit.objectId===object.id&&!customerVisitFinished(visit));
 return <button className={`card object-card ${compact?"compact":""}`} type="button" onClick={open}><div className="object-card-top"><span className="object-icon"><Building2/></span><Chip>{customerObjectTypes[object.type]}</Chip></div><h3>{object.name}</h3><p>{object.street}<br/>{object.postalCode} {object.city}</p><div className="object-card-bottom"><span>{compact?(next?`Volgende: ${customerDate(next.start,timezone)}`:"Geen afspraak"):`${object.services.length} diensten`}</span><ChevronRight/></div></button>;
}
function Cockpit({workspace,resources,actions,availability}:{workspace:CustomerWorkspace;resources:CustomerResources;actions:CustomerPortalActions;availability:CustomerPortalAvailability}){
 const {objects,visits,profile,tenant,account}=workspace,upcoming=visits.filter(visit=>!customerVisitFinished(visit)),next=upcoming[0],open=resources.invoices.filter(invoice=>invoice.balance>0&&invoice.status!=="credited"),nextObject=objects.find(object=>object.id===next?.objectId);
 const metrics=[[objects.length,"Mijn objecten",Building2,"objects",objects.length?"In goede handen":"Voeg je eerste object toe"],[upcoming.length,"Geplande afspraken",CalendarDays,"appointments","De komende periode"],[money(open.reduce((sum,invoice)=>sum+invoice.balance,0)),"Openstaande facturen",Wallet,"invoices",`${open.length} facturen te betalen`],[resources.reports.length,"Rapporten beschikbaar",FileText,"reports","Inzicht in uitgevoerd werk"]] as const;
 return <><PageHead title={`Welkom terug, ${profile.fullName.split(/\s+/)[0]}.`} description="Alles rondom jouw objecten, op één plek." actions={tenant.planning?<ActionIcon className="button primary" label="Dienst aanvragen" icon={<Plus/>} onClick={()=>actions.request()}/>:undefined}/>
  <div className="cockpit-metrics">{metrics.map(([count,label,Icon,view,description])=><button className="card metric" key={view} type="button" onClick={()=>actions.navigate(view)}><div className="metric-label">{label}<Icon/></div><strong>{count}</strong><small>{description}</small></button>)}</div>
  <div className="cockpit-layout"><div className="cockpit-main"><section className="card next-visit"><div className="section-heading"><div><span className="eyebrow">Eerstvolgende afspraak</span><h2>{nextObject?.name??"Je eerste afspraak begint hier"}</h2></div>{next?<Chip green>{customerVisitLabel(next)}</Chip>:<CalendarDays/>}</div>
   {next&&nextObject?<><p className="location"><MapPin/>{nextObject.street}, {nextObject.postalCode} {nextObject.city}</p><div className="next-visit-details"><DateTile value={next.start} timezone={tenant.timezone}/><div><strong>{customerDate(next.start,tenant.timezone,true)}</strong><p>{customerTime(next.start,tenant.timezone)} – {customerTime(next.end,tenant.timezone)} · {next.service}</p></div></div><div className="team-row"><span className="avatar mini">{customerInitials(tenant.name).slice(0,1)}</span><span>{tenant.name} <small>· Uitvoerend team</small></span></div><div className="next-visit-footer"><Action primary onClick={()=>actions.openVisit(next.id)}><Eye/>Afspraak bekijken</Action><Action onClick={()=>actions.openVisit(next.id,true)}><Plus/>Instructie toevoegen</Action></div></>:<><p className="section-gap">Vraag een dienst aan. Je accountmanager stemt de planning met je af.</p><div className="section-gap"><Action primary onClick={()=>actions.navigate("requests")}>Bekijk diensten</Action></div></>}
  </section><section><div className="section-heading"><h2>Mijn objecten <span className="count-label">{objects.length}</span></h2><button className="text-button" type="button" onClick={()=>actions.navigate("objects")}>Alle objecten <ChevronRight/></button></div><div className="object-preview-grid">{objects.slice(0,3).map(object=><ObjectCard key={object.id} object={object} visits={visits} timezone={tenant.timezone} compact open={()=>actions.openObject(object.id)}/>)}{!objects.length&&<Empty title="Nog geen objecten" text="Voeg je eerste locatie toe.">{account.canCreateObjects&&tenant.planning&&<Action primary onClick={actions.newObject}><Plus/>Object toevoegen</Action>}</Empty>}</div></section>
   <section className="card"><div className="card-pad section-heading"><h2>Recente activiteit</h2><Clock3/></div><div className="activity-list">{availability.activity===false?<p className="card-pad">Het klantgebonden activiteitsoverzicht is nog niet aangesloten.</p>:<>{resources.activity.slice(0,3).map(activity=><button className="activity-item" key={activity.id} type="button" onClick={()=>actions.openActivity(activity)}><span className="activity-symbol"><Bell/></span><div><strong>{activity.title}</strong><small>{activity.summary}</small></div><ChevronRight/></button>)}{!resources.activity.length&&<Empty title="Nog geen activiteit" text="Je updates verschijnen hier."/>}</>}</div></section>
  </div><aside className="cockpit-side"><section className="card accountmanager"><div className="accountmanager-top"><span className="avatar manager-avatar">{customerInitials(tenant.name).slice(0,1)}</span><div><span className="eyebrow">Jouw accountmanager</span><h3>{tenant.name}</h3><p>Jouw aanspreekpunt</p></div></div><p>Een vraag, extra wens of iets afstemmen? We helpen je graag verder.</p>{tenant.tickets&&availability.tickets!==false&&<Action onClick={()=>actions.newTicket("tenant")}><Ticket/>Stel een vraag</Action>}{tenant.phone&&<div className="manager-contact"><Phone/><a href={`tel:${tenant.phone.replace(/[^+0-9]/g,"")}`}>{tenant.phone}</a></div>}</section>
   <section className="card news-highlight"><span className="news-label"><Newspaper/> Nieuws</span><h2>{resources.news[0]?.title??"Updates van je organisatie"}</h2><p>{resources.news[0]?.summary??"Praktische informatie verschijnt hier zodra je organisatie een bericht deelt."}</p>{resources.news[0]&&<button className="text-button" type="button" onClick={()=>actions.openNews(resources.news[0])}>Lees het bericht <ChevronRight/></button>}<div className="news-decoration" aria-hidden="true"><Sparkles/></div></section>
   <section className="card quick-actions"><h3>Snel geregeld</h3>{account.canCreateObjects&&tenant.planning&&<button type="button" onClick={actions.newObject}><Building2/>Object toevoegen<ChevronRight/></button>}<button type="button" onClick={()=>actions.navigate("reports")}><FileText/>Rapport downloaden<ChevronRight/></button><button type="button" onClick={actions.preferences}><Mail/>Mijn e-mailvoorkeuren<ChevronRight/></button></section>
  </aside></div></>;
}
function DateTile({value,timezone}:{value:string|null;timezone:string}){return <div className="date-tile"><small>{value?new Intl.DateTimeFormat("nl-NL",{timeZone:timezone,month:"short"}).format(new Date(value)):"—"}</small><b>{value?new Intl.DateTimeFormat("nl-NL",{timeZone:timezone,day:"numeric"}).format(new Date(value)):"—"}</b></div>;}
function Appointments({workspace,actions}:{workspace:CustomerWorkspace;actions:CustomerPortalActions}){
 const [past,setPast]=useState(false),[filter,setFilter]=useState(""),{objects,visits,tenant}=workspace,list=visits.filter(visit=>customerVisitFinished(visit)===past&&(!filter||visit.objectId===filter));
 const content=<div className="card appointment-list customer-tab-surface">{list.map(visit=>{const object=objects.find(object=>object.id===visit.objectId);return <article className="card appointment-card" key={visit.id}><div className="appointment-date"><b>{visit.start?new Intl.DateTimeFormat("nl-NL",{timeZone:tenant.timezone,day:"numeric"}).format(new Date(visit.start)):"—"}</b><span>{visit.start?new Intl.DateTimeFormat("nl-NL",{timeZone:tenant.timezone,month:"short"}).format(new Date(visit.start)):"Nog onbekend"}</span></div><div className="appointment-main"><div className="row"><strong className="appointment-time">{customerTime(visit.start,tenant.timezone)} – {customerTime(visit.end,tenant.timezone)}</strong><Chip green>{customerVisitLabel(visit)}</Chip></div><h2>{object?.name}</h2><p>{visit.service} · {customerDate(visit.start,tenant.timezone,true)}</p><small>{object?.street}, {object?.postalCode} {object?.city}</small><div className="appointment-actions"><Action small onClick={()=>actions.openVisit(visit.id)}>Afspraak bekijken</Action>{!past&&<Action small onClick={()=>actions.openVisit(visit.id,true)}><Plus/>Instructie toevoegen</Action>}</div></div></article>;})}
  {!list.length&&<div className="card"><Empty title="Geen afspraken" text="Er staan geen afspraken in deze selectie.">{tenant.planning&&<Action primary onClick={()=>actions.request()}>Dienst aanvragen</Action>}</Empty></div>}</div>;
 return <><PageHead title="Mijn afspraken" description="Je planning, instructies en uitgevoerde werkzaamheden." actions={<CompactFilterMenu activeCount={filter?1:0}><label className="field"><span>Object</span><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="">Alle objecten</option>{objects.map(object=><option key={object.id} value={object.id}>{object.name}</option>)}</select></label></CompactFilterMenu>}/>
  <ContentTabs label="Afspraken" value={past?"past":"upcoming"} onValueChange={value=>setPast(value==="past")} tabs={[{id:"upcoming",title:"Komende afspraken",content:!past?content:null},{id:"past",title:"Uitgevoerd",content:past?content:null}]}/></>;
}
function Invoices({resources,workspace,actions,availability}:{resources:CustomerResources;workspace:CustomerWorkspace;actions:CustomerPortalActions;availability:CustomerPortalAvailability}){
 const [filter,setFilter]=useState("all"),[selected,setSelected]=useState<string[]>([]),{invoices}=resources,open=invoices.filter(invoice=>invoice.balance>0&&invoice.status!=="credited"),payable=invoices.filter(customerInvoicePayable),selection=payable.filter(invoice=>selected.includes(invoice.id));
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:workspace.tenant.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(resources.now));
 const list=invoices.filter(invoice=>filter==="all"||(filter==="open"?invoice.balance>0&&invoice.status!=="credited":invoice.balance===0&&invoice.status!=="credited"));
 const content=<div className="card invoice-list">{list.map(invoice=><article className="invoice-row" key={invoice.id}><label className="invoice-check"><input type="checkbox" aria-label={`Selecteer ${invoice.number}`} disabled={!customerInvoicePayable(invoice)} checked={selection.some(item=>item.id===invoice.id)} onChange={event=>setSelected(event.target.checked?[...selected,invoice.id]:selected.filter(id=>id!==invoice.id))}/></label><div className="invoice-info"><button type="button" className="link-button" onClick={()=>actions.openInvoice(invoice)}>{invoice.number}</button><p>{invoice.description}</p><small>{invoice.objectIds.map(id=>workspace.objects.find(object=>object.id===id)?.name).filter(Boolean).join(", ")} · {customerDate(invoice.issuedOn,workspace.tenant.timezone)}</small></div><div className="invoice-due"><small>Vervaldatum</small><span className={customerInvoiceOverdue(invoice,today)?"overdue":""}>{customerDate(invoice.dueOn,workspace.tenant.timezone)}</span></div><div className="invoice-amount"><strong>{money(invoice.balance||invoice.total)}</strong><Chip red={customerInvoiceOverdue(invoice,today)} green={invoice.balance===0&&invoice.status!=="credited"}>{customerInvoiceOverdue(invoice,today)?"Verlopen":customerInvoiceLabel(invoice)}</Chip></div><ActionIcon label={`Factuur ${invoice.number} bekijken`} icon={<Eye/>} onClick={()=>actions.openInvoice(invoice)}/></article>)}{!list.length&&<Empty title="Geen facturen" text="Je vindt hier de facturen die voor jou beschikbaar zijn."/>}</div>;
 return <><PageHead title="Facturen" description="Bekijk je facturen en betaal eenvoudig meerdere tegelijk."/><div className="invoice-summary"><div><small>Openstaand</small><strong>{money(open.reduce((sum,invoice)=>sum+invoice.balance,0))}</strong><span>{open.length} facturen</span></div><div><small>Waarvan verlopen</small><strong>{money(open.filter(invoice=>customerInvoiceOverdue(invoice,today)).reduce((sum,invoice)=>sum+invoice.balance,0))}</strong><span>Betaling nog niet ontvangen</span></div><div className="invoice-help"><ShieldCheck/><p>{availability.payments===false?"Online betalen is nog niet beschikbaar in dit portaal.":resources.paymentEnabled?"Betaal één of meerdere facturen in één keer via Mollie.":"Je organisatie heeft online betalen nog niet aangesloten. Neem bij vragen contact op."}</p></div></div>
  {payable.length>0&&<div className="filterbar invoice-selection-controls"><button className="text-button" type="button" onClick={()=>setSelected(selection.length===payable.length?[]:payable.map(invoice=>invoice.id))}>{selection.length===payable.length?"Selectie wissen":"Selecteer alle openstaande"}</button></div>}
  <ContentTabs label="Facturen" value={filter} onValueChange={setFilter} tabs={[["all","Alle facturen"],["open","Openstaand"],["paid","Betaald"]].map(([id,title])=>({id,title,content:filter===id?content:null}))}/>

  <div className="payment-bar"><div><strong>{selection.length?`${selection.length} facturen geselecteerd`:"Selecteer facturen om te betalen"}</strong><small>{selection.length?"Resterend bedrag inclusief btw":"Een betaling telt pas na bevestiging van de betaalprovider."}</small></div><strong className="payment-total">{money(selection.reduce((sum,invoice)=>sum+invoice.balance,0))}</strong><Action primary disabled={!resources.paymentEnabled||!selection.length} onClick={()=>actions.pay(selection.map(invoice=>invoice.id))}><LockKeyhole/>Betalen</Action></div>
 </>;
}
function Requests({workspace,resources,actions}:{workspace:CustomerWorkspace;resources:CustomerResources;actions:CustomerPortalActions}){
 return <><PageHead title="Diensten & aanvragen" description="Wat kunnen we voor jouw objecten betekenen?" actions={workspace.tenant.planning?<ActionIcon className="button primary" label="Nieuwe aanvraag" icon={<Plus/>} onClick={()=>actions.request()}/>:undefined}/><div className="services-grid">{resources.services.map((service,index)=><button className="card service-card" type="button" key={service.name} onClick={()=>actions.request(service.name)}><span className="object-icon">{index%2?<Sparkles/>:<Building2/>}</span><h2>{service.name}</h2><p>{service.description}</p><span className="service-cta">Voorstel aanvragen <ChevronRight/></span></button>)}</div><div className="section-heading section-gap"><h2>Mijn aanvragen</h2><small>{resources.requests.length} aanvragen</small></div><div className="card">{resources.requests.map(request=><button className="ticket-row" type="button" key={request.id} onClick={()=>actions.openRequest(request.id)}><div><small>{request.number}</small><h3>{request.subject}</h3><p>{request.objectIds.map(id=>workspace.objects.find(object=>object.id===id)?.name).filter(Boolean).join(", ")||"Locatie later vaststellen"} · {request.frequency}</p></div><Chip>{requestLabels[request.status]??request.status}</Chip><ChevronRight/></button>)}{!resources.requests.length&&<Empty title="Nog geen aanvragen" text="Kies een dienst of bespreek je wensen met je accountmanager."/>}</div></>;
}
function ticketStatus(status:string){return({new:"Nieuw",triage:"In beoordeling",in_progress:"In behandeling",waiting_reporter:"Wacht op jouw reactie",waiting_internal:"In behandeling",resolved:"Opgelost",closed:"Gesloten"} as Record<string,string>)[status]??"In behandeling";}
