"use client";
import { useEffect,useId,useRef,useState,useTransition } from "react";
import { Download,Send } from "lucide-react";
import { customerTicketDetailSchema,customerTicketOptionsSchema,type CustomerTicketCommand,type CustomerTicketDetail,type CustomerTicketOptions } from "@/lib/customer-portal/ticket-model";
import type { CustomerWorkspace } from "@/lib/customer-portal/model";
import { customerDate } from "@/lib/customer-portal/presentation";
import { ticketStatusLabels,type TicketStatus } from "@/lib/tickets/model";
import { TicketFilePicker,type DraftTicketFile } from "@/components/fieldgrid/tickets/files";
import { CustomerDialog } from "./dialog";
import type { CustomerFormResult } from "./forms";

type Save=(action:CustomerTicketCommand,id:string)=>Promise<CustomerFormResult&{detail?:CustomerTicketDetail}>;
export function CustomerTicketDialog({accountId,tenantId,workspace,ticketId,route="tenant",close,save}:{accountId:string;tenantId:string;workspace:CustomerWorkspace;ticketId?:string;route?:"tenant"|"platform";close:()=>void;save:Save}){
 const [detail,setDetail]=useState<CustomerTicketDetail|null>(null),[options,setOptions]=useState<CustomerTicketOptions>([]),[category,setCategory]=useState(""),[subject,setSubject]=useState(""),[objectId,setObjectId]=useState(""),[body,setBody]=useState(""),[reason,setReason]=useState(""),[status,setStatus]=useState<"closed"|"cancelled"|"in_progress"|null>(null),[error,setError]=useState(""),[revision,setRevision]=useState(0),[pending,start]=useTransition(),[files,setFiles]=useState<DraftTicketFile[]>([]),[draftId]=useState(()=>crypto.randomUUID());
 const keys=useRef(new Map<string,string>()),formId=useId(),dirty=!!subject.trim()||!!body.trim()||!!reason.trim()||files.length>0;
 useEffect(()=>{const abort=new AbortController();void(async()=>{try{const response=await fetch(`/api/customer-portal/tickets?${new URLSearchParams({account:accountId,...(ticketId?{ticket:ticketId}:{})})}`,{signal:abort.signal,credentials:"same-origin",cache:"no-store",redirect:"error"});if(!response.ok){if(response.status===403)setDetail(null);throw new Error();}const value=await response.json();if(abort.signal.aborted)return;if(ticketId)setDetail(customerTicketDetailSchema.parse(value));else{const categories=customerTicketOptionsSchema.parse(value).filter(item=>item.route===route);setOptions(categories);setCategory(current=>current||categories[0]?.id||"");}setError("");}catch{if(!abort.signal.aborted)setError("Het ticket kon niet worden geladen. Controleer je actuele toegang en probeer opnieuw.");}})();return()=>abort.abort();},[accountId,ticketId,route,revision]);
 const cancel=()=>{if(!pending&&(!dirty||window.confirm("Je bericht is nog niet verstuurd. Toch sluiten?")))close();};
 const submit=()=>{
  if(files.some(file=>file.status!=="clean"||!file.id)){setError("Wacht totdat alle bijlagen zijn gecontroleerd, of verwijder een geweigerde bijlage.");return;}
  const attachment_ids=files.map(file=>file.id!),action:CustomerTicketCommand=detail?(status?{command:"status",input:{ticket_id:detail.id,expected_revision:detail.version,status,reason}}:{command:"reply",input:{ticket_id:detail.id,expected_revision:detail.version,body,attachment_ids}}):{command:"create",input:{category_id:category,title:subject,body,object_id:objectId||null,attachment_ids}};
  const key=JSON.stringify(action);let commandId=keys.current.get(key);if(!commandId){commandId=crypto.randomUUID();keys.current.set(key,commandId);}
  start(async()=>{try{const result=await save(action,commandId);if(!result.ok){setError(result.error);return;}setBody("");setSubject("");setReason("");setStatus(null);setFiles([]);setError("");if(result.detail)setDetail(result.detail);else setRevision(value=>value+1);}catch{setError("Je bericht kon niet worden bevestigd. Je invoer blijft staan.");}});
 };
 const selectedCategory=detail?.categoryId||category;
 return <CustomerDialog title={detail?.subject??(ticketId?"Ticket laden":route==="platform"?"Vraag aan Fieldgrid":"Vraag aan je accountmanager")} kicker={detail?.number??"Nieuw ticket"} close={close} dirty={dirty} busy={pending} footer={<><button className="button" type="button" onClick={cancel} disabled={pending}>Sluiten</button>{((!ticketId&&!detail)||detail?.canReply||status)&&<button className="button primary" form={formId} disabled={pending||(!detail&&!category)}><Send/>{pending?"Opslaan…":status?"Wijziging bevestigen":detail?"Reactie versturen":"Ticket versturen"}</button>}</>}>
  {error&&<div className="form-error" role="alert"><p>{error}</p><button className="button" type="button" disabled={pending} onClick={()=>setRevision(value=>value+1)}>Opnieuw controleren</button></div>}
  {detail?<><div className="row"><span>{detail.route==="platform"?"Fieldgrid":workspace.tenant.name}</span><span className="chip gray">{ticketStatusLabels[detail.status as TicketStatus]??detail.status}</span></div><div className="messages section-gap">{detail.messages.map(message=><article className={`message ${message.own?"mine":""}`} key={message.id}><strong>{message.author}</strong><small>{customerDate(message.at,workspace.tenant.timezone,true)}</small><p className="preserved">{message.body}</p>{message.files.map(file=><div className="section-gap" key={file.id}>{file.scanState==="clean"?<a className="button small" href={`/api/tickets/files/${file.id}?workspace=customer`}><Download/>{file.name}</a>:<span className="meta">{file.name} · {file.scanState==="pending"||file.scanState==="processing"?"Wordt gecontroleerd":"Niet beschikbaar"}</span>}</div>)}</article>)}</div><div className="row section-gap">{detail.canClose&&<button className="button" type="button" onClick={()=>setStatus("closed")} disabled={pending}>Oplossing bevestigen</button>}{detail.canReopen&&<button className="button" type="button" onClick={()=>setStatus("in_progress")} disabled={pending}>Ticket heropenen</button>}{detail.canCancel&&<button className="button" type="button" onClick={()=>setStatus("cancelled")} disabled={pending}>Ticket intrekken</button>}</div></>:ticketId?<p role="status">Ticket laden…</p>:<p className="form-intro">{route==="platform"?"Stel je technische vraag over het portaal aan Fieldgrid.":"Je accountmanager helpt je met planning, dienstverlening en facturen."}</p>}
  {((!ticketId&&!detail)||detail?.canReply||status)&&<form id={formId} className="section-gap" onSubmit={event=>{event.preventDefault();submit();}}>
   {!detail&&!ticketId&&<><label className="field"><span>Categorie *</span><select required value={category} onChange={event=>setCategory(event.target.value)} disabled={pending||files.length>0}>{options.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Onderwerp *</span><input required minLength={3} maxLength={180} value={subject} onChange={event=>setSubject(event.target.value)} disabled={pending}/></label><label className="field"><span>Object (optioneel)</span><select value={objectId} onChange={event=>setObjectId(event.target.value)} disabled={pending}><option value="">Algemene vraag</option>{workspace.objects.map(object=><option key={object.id} value={object.id}>{object.name}</option>)}</select></label></>}
   {status?<><h3>{status==="closed"?"Bevestig dat je vraag is opgelost":status==="in_progress"?"Waarom wil je het ticket heropenen?":"Waarom wil je het ticket intrekken?"}</h3><label className="field"><span>Toelichting{status!=="closed"?" *":""}</span><textarea value={reason} onChange={event=>setReason(event.target.value)} rows={3} required={status!=="closed"} minLength={status!=="closed"?3:undefined} maxLength={2000} disabled={pending}/></label><button className="text-button" type="button" onClick={()=>setStatus(null)} disabled={pending}>Terug naar gesprek</button></>:<><label className="field"><span>{detail?"Jouw reactie":"Bericht"} *</span><textarea required minLength={3} maxLength={20000} rows={4} value={body} onChange={event=>setBody(event.target.value)} disabled={pending}/></label>{selectedCategory&&<TicketFilePicker workspace="customer" tenantId={tenantId} categoryId={selectedCategory} ticketId={detail?.id} audience="reporter" draftId={draftId} files={files} setFiles={setFiles} disabled={pending}/>}</>}
  </form>}
 </CustomerDialog>;
}
