INSERT INTO notification_event_settings (
  event_key,
  event_group,
  audience,
  title,
  description,
  email_enabled,
  push_enabled,
  in_app_enabled,
  email_subject,
  email_preheader,
  email_body,
  push_title,
  push_body,
  shortcodes
)
VALUES
  (
    'kb_article_published',
    'knowledgebase',
    'mixed',
    'Nieuwe handleiding: {{article.title}}',
    '{{article.summary}}',
    true,
    false,
    true,
    'Nieuwe Fieldgrid handleiding: {{article.title}}',
    'Er staat een nieuwe handleiding klaar.',
    '<p>Er staat een nieuwe Fieldgrid handleiding klaar: <strong>{{article.title}}</strong>.</p><p>{{article.summary}}</p>',
    'Nieuwe handleiding',
    '{{article.title}}',
    '["article.title","article.summary","href"]'::jsonb
  ),
  (
    'kb_article_updated',
    'knowledgebase',
    'mixed',
    'Handleiding bijgewerkt: {{article.title}}',
    '{{article.summary}}',
    false,
    false,
    true,
    'Fieldgrid handleiding bijgewerkt: {{article.title}}',
    'Een handleiding is bijgewerkt.',
    '<p>De Fieldgrid handleiding <strong>{{article.title}}</strong> is bijgewerkt.</p><p>{{article.summary}}</p>',
    'Handleiding bijgewerkt',
    '{{article.title}}',
    '["article.title","article.summary","href"]'::jsonb
  ),
  (
    'kb_article_featured',
    'knowledgebase',
    'mixed',
    'Belangrijke handleiding: {{article.title}}',
    '{{article.summary}}',
    true,
    true,
    true,
    'Belangrijke Fieldgrid handleiding: {{article.title}}',
    'Een belangrijke handleiding is uitgelicht.',
    '<p>Een belangrijke Fieldgrid handleiding is uitgelicht: <strong>{{article.title}}</strong>.</p><p>{{article.summary}}</p>',
    'Belangrijke handleiding',
    '{{article.title}}',
    '["article.title","article.summary","href"]'::jsonb
  ),
  (
    'roadmap_request_submitted',
    'roadmap',
    'management',
    'Nieuwe roadmapwens: {{roadmap.title}}',
    'Er is een nieuwe featurewens ingediend.',
    true,
    false,
    true,
    'Nieuwe roadmapwens: {{roadmap.title}}',
    'Er is een nieuwe featurewens ingediend.',
    '<p>Er is een nieuwe featurewens ingediend: <strong>{{roadmap.title}}</strong>.</p>',
    'Nieuwe roadmapwens',
    '{{roadmap.title}}',
    '["roadmap.title","roadmap.priority","href"]'::jsonb
  ),
  (
    'roadmap_status_changed',
    'roadmap',
    'management',
    'Roadmapstatus gewijzigd: {{roadmap.title}}',
    'Status: {{roadmap.from_status}} naar {{roadmap.to_status}}.',
    true,
    false,
    true,
    'Roadmapstatus gewijzigd: {{roadmap.title}}',
    'Een roadmapitem heeft een nieuwe status.',
    '<p>De status van <strong>{{roadmap.title}}</strong> is gewijzigd van {{roadmap.from_status}} naar {{roadmap.to_status}}.</p><p>{{roadmap.note}}</p>',
    'Roadmapstatus gewijzigd',
    '{{roadmap.title}}',
    '["roadmap.title","roadmap.from_status","roadmap.to_status","roadmap.note","href"]'::jsonb
  ),
  (
    'roadmap_comment_added',
    'roadmap',
    'management',
    'Nieuwe roadmapreactie: {{roadmap.title}}',
    '{{comment.body}}',
    false,
    false,
    true,
    'Nieuwe roadmapreactie: {{roadmap.title}}',
    'Er is een nieuwe reactie geplaatst.',
    '<p>Er is een nieuwe reactie geplaatst bij <strong>{{roadmap.title}}</strong>.</p><p>{{comment.body}}</p>',
    'Nieuwe roadmapreactie',
    '{{roadmap.title}}',
    '["roadmap.title","comment.body","href"]'::jsonb
  ),
  (
    'roadmap_item_done',
    'roadmap',
    'management',
    'Roadmapitem afgerond: {{roadmap.title}}',
    'Een roadmapitem is afgerond.',
    true,
    true,
    true,
    'Roadmapitem afgerond: {{roadmap.title}}',
    'Een roadmapitem is afgerond.',
    '<p>Het roadmapitem <strong>{{roadmap.title}}</strong> is afgerond.</p>',
    'Roadmapitem afgerond',
    '{{roadmap.title}}',
    '["roadmap.title","href"]'::jsonb
  ),
  (
    'release_published',
    'releases',
    'mixed',
    'Nieuwe release: {{release.version}}',
    '{{release.summary}}',
    true,
    true,
    true,
    'Nieuwe Fieldgrid release: {{release.version}}',
    'Er is een nieuwe release gepubliceerd.',
    '<p>Er is een nieuwe Fieldgrid release gepubliceerd: <strong>{{release.version}} - {{release.title}}</strong>.</p><p>{{release.summary}}</p>',
    'Nieuwe Fieldgrid release',
    '{{release.version}} - {{release.title}}',
    '["release.version","release.title","release.summary","href"]'::jsonb
  ),
  (
    'release_featured',
    'releases',
    'mixed',
    'Uitgelichte release: {{release.version}}',
    '{{release.summary}}',
    true,
    true,
    true,
    'Uitgelichte Fieldgrid release: {{release.version}}',
    'Een release is uitgelicht.',
    '<p>Een Fieldgrid release is uitgelicht: <strong>{{release.version}} - {{release.title}}</strong>.</p><p>{{release.summary}}</p>',
    'Uitgelichte release',
    '{{release.version}} - {{release.title}}',
    '["release.version","release.title","release.summary","href"]'::jsonb
  ),
  (
    'release_highlight_active',
    'releases',
    'mixed',
    '{{highlight.title}}',
    '{{highlight.message}}',
    true,
    true,
    true,
    '{{highlight.title}}',
    'Een release-highlight is actief.',
    '<p>{{highlight.message}}</p>',
    '{{highlight.title}}',
    '{{highlight.message}}',
    '["release.version","release.title","highlight.title","highlight.message","href"]'::jsonb
  )
ON CONFLICT (event_key) DO UPDATE SET
  event_group = EXCLUDED.event_group,
  audience = EXCLUDED.audience,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  email_subject = EXCLUDED.email_subject,
  email_preheader = EXCLUDED.email_preheader,
  email_body = EXCLUDED.email_body,
  push_title = EXCLUDED.push_title,
  push_body = EXCLUDED.push_body,
  shortcodes = EXCLUDED.shortcodes,
  updated_at = now();
