-- Fieldgrid notification and e-mail content refresh.
-- Source: fieldgrid-notificaties-en-emailtemplates-v1.md, 7 July 2026.

INSERT INTO notification_event_settings (
  event_key,
  event_group,
  audience,
  title,
  description,
  email_enabled,
  push_enabled,
  in_app_enabled,
  email_subject,
  email_preheader,
  email_body,
  push_title,
  push_body,
  shortcodes
)
VALUES
  (
    'assignment_assigned',
    'planning',
    'personnel',
    $fgnotif$Nieuwe werkbon$fgnotif$,
    $fgnotif$Werkbon {{assignment.code}} is ingepland voor {{object.name}}.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Nieuwe werkbon ingepland: {{assignment.code}}$fgnotif$,
    $fgnotif$Er is een nieuwe werkbon voor u ingepland.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een nieuwe werkbon voor u ingepland.</p><p>Werkbongegevens:</p><ul><li>Werkbon: {{assignment.code}}</li><li>Object: {{object.name}}</li><li>Adres: {{object.address}}</li><li>Datum: {{assignment.date}}</li><li>Tijd: {{assignment.start}} - {{assignment.end}}</li></ul><p>Open de werkbon in de personeelsapp voor alle details, taken en instructies.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Nieuwe werkbon$fgnotif$,
    $fgnotif${{object.name}} op {{assignment.date}} om {{assignment.start}}.$fgnotif$,
    '["recipient.name","organization.name","assignment.code","assignment.date","assignment.start","assignment.end","object.name","object.address","href"]'::jsonb
  ),
  (
    'assignment_cancelled_personnel',
    'planning',
    'personnel',
    $fgnotif$Werkbon geannuleerd$fgnotif$,
    $fgnotif$Werkbon {{assignment.number}} is niet meer aan u toegewezen.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Werkbon {{assignment.number}} is geannuleerd$fgnotif$,
    $fgnotif$Werkbon {{assignment.number}} voor {{object.name}} is geannuleerd of niet meer aan u toegewezen.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Werkbon {{assignment.number}} voor {{object.name}} is geannuleerd of niet meer aan u toegewezen.</p><p>U hoeft voor deze werkbon niet naar de locatie te gaan.</p><p>Controleer uw actuele planning in de personeelsapp.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Planning bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon geannuleerd$fgnotif$,
    $fgnotif$U hoeft niet naar {{object.name}} voor werkbon {{assignment.number}}.$fgnotif$,
    '["recipient.name","organization.name","assignment.number","object.name","href"]'::jsonb
  ),
  (
    'assignment_completed',
    'planning',
    'customer',
    $fgnotif$Werkbon afgerond$fgnotif$,
    $fgnotif$Werkbon {{assignment.code}} is afgerond.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Werkbon {{assignment.code}} is afgerond$fgnotif$,
    $fgnotif$De werkzaamheden zijn afgerond.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>De werkzaamheden voor werkbon {{assignment.code}} zijn afgerond.</p><p>Opdracht: {{assignment.title}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon afgerond$fgnotif$,
    $fgnotif$Werkbon {{assignment.code}} is afgerond.$fgnotif$,
    '["recipient.name","organization.name","assignment.code","assignment.title","href"]'::jsonb
  ),
  (
    'assignment_en_route',
    'planning',
    'customer',
    $fgnotif$Medewerker onderweg$fgnotif$,
    $fgnotif$Onze medewerker is onderweg voor werkbon {{assignment.code}}.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Medewerker onderweg voor {{assignment.code}}$fgnotif$,
    $fgnotif$Onze medewerker is onderweg naar de locatie.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Onze medewerker is onderweg naar {{object.name}}.</p><p>Werkbon: {{assignment.code}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Medewerker onderweg$fgnotif$,
    $fgnotif$Onze medewerker is onderweg naar de locatie.$fgnotif$,
    '["recipient.name","organization.name","assignment.code","object.name","href"]'::jsonb
  ),
  (
    'assignment_interest_invited',
    'planning',
    'personnel',
    $fgnotif$Open opdracht beschikbaar$fgnotif$,
    $fgnotif$Kunt u werken bij {{object.name}} op {{assignment.date}}? Geef uw reactie door.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Open opdracht beschikbaar$fgnotif$,
    $fgnotif$Kunt u werken bij {{object.name}} op {{assignment.date}}?$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Kunt u werken bij {{object.name}} op {{assignment.date}}? Geef uw reactie door.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Open opdracht$fgnotif$,
    $fgnotif$Geef aan of u beschikbaar bent voor {{object.name}}.$fgnotif$,
    '["object.name","assignment.date","assignment.start","href"]'::jsonb
  ),
  (
    'assignment_interest_poll',
    'planning',
    'personnel',
    $fgnotif$Open opdracht beschikbaar$fgnotif$,
    $fgnotif$Kunt u werken bij {{object.name}} op {{assignment.date}}? Geef uw reactie door.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Open opdracht beschikbaar$fgnotif$,
    $fgnotif$Kunt u werken bij {{object.name}} op {{assignment.date}}?$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Kunt u werken bij {{object.name}} op {{assignment.date}}? Geef uw reactie door.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Open opdracht$fgnotif$,
    $fgnotif$Geef aan of u beschikbaar bent voor {{object.name}}.$fgnotif$,
    '["object.name","assignment.date","assignment.start","href"]'::jsonb
  ),
  (
    'assignment_interest_reminder',
    'planning',
    'personnel',
    $fgnotif$Werkbon komt eraan$fgnotif$,
    $fgnotif$Werkbon {{assignment.code}} bij {{object.name}} start om {{assignment.start}}.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Werkbon komt eraan$fgnotif$,
    $fgnotif$Werkbon {{assignment.code}} bij {{object.name}} start om {{assignment.start}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Werkbon {{assignment.code}} bij {{object.name}} start om {{assignment.start}}.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon om {{assignment.start}}$fgnotif$,
    $fgnotif${{object.name}} - open de app voor taken en instructies.$fgnotif$,
    '["assignment.code","assignment.start","object.name","href"]'::jsonb
  ),
  (
    'assignment_not_completed',
    'planning',
    'management',
    $fgnotif$Werkbon niet afgerond$fgnotif$,
    $fgnotif${{personnel.name}} heeft werkbon {{assignment.code}} afgemeld. Reden: {{reason}}$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Werkbon {{assignment.code}} is niet afgerond$fgnotif$,
    $fgnotif$Werkbon {{assignment.code}} is niet afgerond.$fgnotif$,
    $fgnotif$<p>Werkbon {{assignment.code}} is niet afgerond.</p><p>Medewerker: {{personnel.name}}<br>Object: {{object.name}}<br>Reden:<br>{{reason}}</p><p>Controleer de werkbon en bepaal de vervolgstap.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p>$fgnotif$,
    $fgnotif$Werkbon niet afgerond$fgnotif$,
    $fgnotif${{assignment.code}} bij {{object.name}} vraagt opvolging.$fgnotif$,
    '["personnel.name","assignment.code","object.name","reason","href"]'::jsonb
  ),
  (
    'assignment_not_completed_backoffice',
    'planning',
    'management',
    $fgnotif$Werkbon niet afgerond$fgnotif$,
    $fgnotif${{personnel.name}} heeft werkbon {{assignment.number}} afgemeld. Reden: {{reason}}$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Werkbon {{assignment.number}} is niet afgerond$fgnotif$,
    $fgnotif$Werkbon {{assignment.number}} is niet afgerond.$fgnotif$,
    $fgnotif$<p>Werkbon {{assignment.number}} is niet afgerond.</p><p>Medewerker: {{personnel.name}}<br>Object: {{object.name}}<br>Reden:<br>{{reason}}</p><p>Controleer de werkbon en bepaal de vervolgstap.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p>$fgnotif$,
    $fgnotif$Werkbon niet afgerond$fgnotif$,
    $fgnotif${{assignment.number}} bij {{object.name}} vraagt opvolging.$fgnotif$,
    '["personnel.name","assignment.number","object.name","reason","href"]'::jsonb
  ),
  (
    'assignment_personnel_linked',
    'planning',
    'personnel',
    $fgnotif$Werkbon gekoppeld$fgnotif$,
    $fgnotif$Werkbon {{assignment.code}} is aan u gekoppeld. De planning volgt nog.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Werkbon gekoppeld: {{assignment.code}}$fgnotif$,
    $fgnotif$Er is een nieuwe werkbon voor u ingepland.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een nieuwe werkbon voor u ingepland.</p><p>Werkbongegevens:</p><ul><li>Werkbon: {{assignment.code}}</li><li>Object: {{object.name}}</li><li>Adres: {{object.address}}</li><li>Datum: {{assignment.date}}</li><li>Tijd: {{assignment.start}} - {{assignment.end}}</li></ul><p>Open de werkbon in de personeelsapp voor alle details, taken en instructies.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon gekoppeld$fgnotif$,
    $fgnotif$Planning heeft u gekoppeld aan werkbon {{assignment.code}}.$fgnotif$,
    '["recipient.name","organization.name","assignment.code","assignment.title","object.name","href"]'::jsonb
  ),
  (
    'assignment_planned_personnel',
    'planning',
    'personnel',
    $fgnotif$Nieuwe werkbon$fgnotif$,
    $fgnotif$Werkbon {{assignment.number}} is ingepland voor {{object.name}}.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Nieuwe werkbon ingepland: {{assignment.number}}$fgnotif$,
    $fgnotif$Er is een nieuwe werkbon voor u ingepland.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een nieuwe werkbon voor u ingepland.</p><p>Werkbongegevens:</p><ul><li>Werkbon: {{assignment.number}}</li><li>Object: {{object.name}}</li><li>Adres: {{object.address}}</li><li>Datum: {{assignment.date}}</li><li>Tijd: {{assignment.start_time}} - {{assignment.end_time}}</li></ul><p>Open de werkbon in de personeelsapp voor alle details, taken en instructies.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Nieuwe werkbon$fgnotif$,
    $fgnotif${{object.name}} op {{assignment.date}} om {{assignment.start_time}}.$fgnotif$,
    '["recipient.name","organization.name","assignment.number","assignment.date","assignment.start_time","assignment.end_time","object.name","object.address","href"]'::jsonb
  ),
  (
    'assignment_reminder_personnel',
    'planning',
    'personnel',
    $fgnotif$Werkbon komt eraan$fgnotif$,
    $fgnotif$Werkbon {{assignment.number}} bij {{object.name}} start om {{assignment.start_time}}.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Werkbon komt eraan$fgnotif$,
    $fgnotif$Werkbon {{assignment.number}} bij {{object.name}} start om {{assignment.start_time}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Werkbon {{assignment.number}} bij {{object.name}} start om {{assignment.start_time}}.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon om {{assignment.start_time}}$fgnotif$,
    $fgnotif${{object.name}} - open de app voor taken en instructies.$fgnotif$,
    '["assignment.number","assignment.start_time","object.name","href"]'::jsonb
  ),
  (
    'assignment_rescheduled',
    'planning',
    'personnel',
    $fgnotif$Werkbon gewijzigd$fgnotif$,
    $fgnotif$Controleer werkbon {{assignment.code}} opnieuw. Er is iets gewijzigd.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Werkbon {{assignment.code}} is gewijzigd$fgnotif$,
    $fgnotif$Er is iets gewijzigd aan werkbon {{assignment.code}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is iets gewijzigd aan werkbon {{assignment.code}}.</p><p>Object: {{object.name}}<br>Datum: {{assignment.date}}<br>Tijd: {{assignment.start}} - {{assignment.end}}</p><p>Controleer de werkbon opnieuw in de personeelsapp voordat u vertrekt.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon gewijzigd$fgnotif$,
    $fgnotif$Controleer werkbon {{assignment.code}} opnieuw in de app.$fgnotif$,
    '["recipient.name","organization.name","assignment.code","assignment.date","assignment.start","assignment.end","object.name","href"]'::jsonb
  ),
  (
    'assignment_seen',
    'planning',
    'management',
    $fgnotif$Werkbon gezien$fgnotif$,
    $fgnotif$Werkbon {{assignment.code}} is geopend door {{personnel.name}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Werkbon {{assignment.code}} is gezien$fgnotif$,
    $fgnotif${{personnel.name}} heeft werkbon {{assignment.code}} geopend.$fgnotif$,
    $fgnotif$<p>{{personnel.name}} heeft werkbon {{assignment.code}} geopend.</p><p>Opdracht: {{assignment.title}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p>$fgnotif$,
    $fgnotif$Werkbon gezien$fgnotif$,
    $fgnotif${{personnel.name}} heeft werkbon {{assignment.code}} geopend.$fgnotif$,
    '["assignment.code","personnel.name","href"]'::jsonb
  ),
  (
    'assignment_started',
    'planning',
    'management',
    $fgnotif$Werkbon gestart$fgnotif$,
    $fgnotif${{personnel.name}} is gestart met werkbon {{assignment.code}} bij {{object.name}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Werkbon gestart$fgnotif$,
    $fgnotif${{personnel.name}} is gestart met werkbon {{assignment.code}} bij {{object.name}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>{{personnel.name}} is gestart met werkbon {{assignment.code}} bij {{object.name}}.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon gestart$fgnotif$,
    $fgnotif${{personnel.name}} is gestart met werkbon {{assignment.code}} bij {{object.name}}.$fgnotif$,
    '["personnel.name","assignment.code","object.name","href"]'::jsonb
  ),
  (
    'assignment_started_backoffice',
    'planning',
    'management',
    $fgnotif$Werkbon gestart$fgnotif$,
    $fgnotif${{personnel.name}} is gestart met werkbon {{assignment.number}} bij {{object.name}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Werkbon gestart$fgnotif$,
    $fgnotif${{personnel.name}} is gestart met werkbon {{assignment.number}} bij {{object.name}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>{{personnel.name}} is gestart met werkbon {{assignment.number}} bij {{object.name}}.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon gestart$fgnotif$,
    $fgnotif${{personnel.name}} is gestart met werkbon {{assignment.number}} bij {{object.name}}.$fgnotif$,
    '["personnel.name","assignment.number","object.name","href"]'::jsonb
  ),
  (
    'assignment_updated_personnel',
    'planning',
    'personnel',
    $fgnotif$Werkbon gewijzigd$fgnotif$,
    $fgnotif$Controleer werkbon {{assignment.number}} opnieuw. Er is iets gewijzigd.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Werkbon {{assignment.number}} is gewijzigd$fgnotif$,
    $fgnotif$Er is iets gewijzigd aan werkbon {{assignment.number}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is iets gewijzigd aan werkbon {{assignment.number}}.</p><p>Object: {{object.name}}<br>Datum: {{assignment.date}}<br>Tijd: {{assignment.start_time}} - {{assignment.end_time}}</p><p>Controleer de werkbon opnieuw in de personeelsapp voordat u vertrekt.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Werkbon gewijzigd$fgnotif$,
    $fgnotif$Controleer werkbon {{assignment.number}} opnieuw in de app.$fgnotif$,
    '["recipient.name","organization.name","assignment.number","assignment.date","assignment.start_time","assignment.end_time","object.name","href"]'::jsonb
  ),
  (
    'availability_reminder_personnel',
    'operations',
    'personnel',
    $fgnotif$Beschikbaarheid invullen$fgnotif$,
    $fgnotif$Vul uw beschikbaarheid in, zodat planning weet wanneer u kunt werken.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Beschikbaarheid invullen$fgnotif$,
    $fgnotif$Vul uw beschikbaarheid in, zodat planning weet wanneer u kunt werken.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Vul uw beschikbaarheid in, zodat planning weet wanneer u kunt werken.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Beschikbaarheid nodig$fgnotif$,
    $fgnotif$Geef uw beschikbaarheid door in de personeelsapp.$fgnotif$,
    '["recipient.name","href"]'::jsonb
  ),
  (
    'custom_domain_dns_attention',
    'platform',
    'management',
    $fgnotif$Domeincontrole nodig$fgnotif$,
    $fgnotif${{domain.name}} is nog niet klaar voor gebruik. Controleer de DNS-instellingen.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Domeincontrole nodig voor {{domain.name}}$fgnotif$,
    $fgnotif$Het domein {{domain.name}} is nog niet klaar voor gebruik.$fgnotif$,
    $fgnotif$<p>Het domein {{domain.name}} is nog niet klaar voor gebruik.</p><p>Controleer of de DNS-records goed staan ingesteld. Zodra de DNS klopt, kan Fieldgrid het domein veilig koppelen.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">DNS-instructies bekijken</a></p>$fgnotif$,
    $fgnotif$Domeincontrole nodig$fgnotif$,
    $fgnotif${{domain.name}} is nog niet klaar voor gebruik. Controleer de DNS-instellingen.$fgnotif$,
    '["domain.name","href"]'::jsonb
  ),
  (
    'customer_assignment_requested',
    'customer_portal',
    'management',
    $fgnotif$Nieuwe aanvraag$fgnotif$,
    $fgnotif${{customer.name}} heeft een aanvraag ingediend voor {{object.name}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe aanvraag van {{customer.name}}$fgnotif$,
    $fgnotif$Er is een nieuwe aanvraag binnengekomen.$fgnotif$,
    $fgnotif$<p>Er is een nieuwe aanvraag binnengekomen.</p><p>Klant: {{customer.name}}<br>Object: {{object.name}}<br>Aanvraag: {{assignment.title}}<br>Gewenste datum: {{assignment.date}}</p><p>Bekijk de aanvraag in Fieldgrid om deze te beoordelen, een offerte te maken of direct te plannen.</p><p><a href="{{backofficeHref}}" style="color:#0f766e;text-decoration:underline">Aanvraag openen</a></p>$fgnotif$,
    $fgnotif$Nieuwe aanvraag$fgnotif$,
    $fgnotif${{customer.name}} vraagt werk aan voor {{object.name}}.$fgnotif$,
    '["customer.name","object.name","assignment.title","assignment.date","backofficeHref"]'::jsonb
  ),
  (
    'customer_portal_invite',
    'account',
    'customer',
    $fgnotif$Toegang tot het klantenportaal van {{organization.name}}$fgnotif$,
    $fgnotif$Uw account staat klaar. Log in met het tijdelijke wachtwoord en kies daarna uw eigen wachtwoord.$fgnotif$,
    true,
    false,
    false,
    $fgnotif$Toegang tot het klantenportaal van {{organization.name}}$fgnotif$,
    $fgnotif$Uw account staat klaar. Log in met het tijdelijke wachtwoord en kies daarna uw eigen wachtwoord.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een account voor u aangemaakt in het klantenportaal van {{organization.name}}.</p><p>Via het klantenportaal kunt u aanvragen indienen, objecten bekijken, offertes beoordelen, rapportages openen, facturen bekijken en betalingen volgen.</p><p>Gebruik onderstaand tijdelijk wachtwoord om voor de eerste keer in te loggen:</p><p>{{temporary_password}}</p><p>Na de eerste login vragen wij u direct een eigen wachtwoord te kiezen.</p><p><a href="{{portal.login_url}}" style="color:#0f766e;text-decoration:underline">Inloggen op het klantenportaal</a></p><p>Heeft u deze uitnodiging niet verwacht? Neem dan contact op met {{organization.name}}.</p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Toegang tot het klantenportaal van {{organization.name}}$fgnotif$,
    $fgnotif$Uw account staat klaar. Log in met het tijdelijke wachtwoord en kies daarna uw eigen wachtwoord.$fgnotif$,
    '["recipient.name","organization.name","temporary_password","portal.login_url"]'::jsonb
  ),
  (
    'customer_request_submitted_backoffice',
    'customer_portal',
    'management',
    $fgnotif$Nieuwe aanvraag$fgnotif$,
    $fgnotif${{customer.name}} heeft een aanvraag ingediend voor {{object.name}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe aanvraag van {{customer.name}}: {{assignment.number}}$fgnotif$,
    $fgnotif$Er is een nieuwe aanvraag binnengekomen.$fgnotif$,
    $fgnotif$<p>Er is een nieuwe aanvraag binnengekomen.</p><p>Klant: {{customer.name}}<br>Object: {{object.name}}<br>Aanvraag: {{assignment.number}}<br>Gewenste datum: {{assignment.date}}</p><p>Bekijk de aanvraag in Fieldgrid om deze te beoordelen, een offerte te maken of direct te plannen.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Aanvraag openen</a></p>$fgnotif$,
    $fgnotif$Nieuwe aanvraag$fgnotif$,
    $fgnotif${{customer.name}} vraagt werk aan voor {{object.name}}.$fgnotif$,
    '["customer.name","object.name","assignment.number","assignment.date","href"]'::jsonb
  ),
  (
    'customer_request_submitted_confirmation',
    'customer_portal',
    'customer',
    $fgnotif$Aanvraag ontvangen$fgnotif$,
    $fgnotif$Uw aanvraag {{assignment.number}} voor {{object.name}} is ontvangen.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Uw aanvraag is ontvangen: {{assignment.number}}$fgnotif$,
    $fgnotif$Bedankt voor uw aanvraag.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Bedankt voor uw aanvraag.</p><p>Wij hebben uw aanvraag voor {{object.name}} ontvangen en nemen deze in behandeling.</p><p>Samenvatting:</p><ul><li>Aanvraag: {{assignment.number}}</li><li>Object: {{object.name}}</li><li>Gewenste datum: {{assignment.date}}</li><li>Omschrijving: {{assignment.title}}</li></ul><p>U kunt de status volgen in het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Aanvraag bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Aanvraag ontvangen$fgnotif$,
    $fgnotif$We hebben uw aanvraag voor {{object.name}} ontvangen.$fgnotif$,
    '["recipient.name","organization.name","assignment.number","assignment.date","assignment.title","object.name","href"]'::jsonb
  ),
  (
    'customer_ticket_backoffice_reply',
    'communication',
    'customer',
    $fgnotif$Nieuwe ticketreactie$fgnotif$,
    $fgnotif$Er is gereageerd op ticket {{ticket.number}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Reactie op uw ticket: {{ticket.subject}}$fgnotif$,
    $fgnotif$Er is een reactie geplaatst op uw ticket.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een reactie geplaatst op uw ticket.</p><p>Ticket: {{ticket.number}}<br>Onderwerp: {{ticket.subject}}</p><p>U kunt de reactie bekijken en beantwoorden in het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Reactie op ticket$fgnotif$,
    $fgnotif$Bekijk de reactie op {{ticket.subject}}.$fgnotif$,
    '["recipient.name","organization.name","ticket.number","ticket.subject","href"]'::jsonb
  ),
  (
    'customer_ticket_created',
    'communication',
    'management',
    $fgnotif$Nieuw klantticket$fgnotif$,
    $fgnotif${{customer.name}} heeft een ticket aangemaakt: {{ticket.subject}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw klantticket: {{ticket.subject}}$fgnotif$,
    $fgnotif$Er is een nieuw ticket aangemaakt door {{customer.name}}.$fgnotif$,
    $fgnotif$<p>Er is een nieuw ticket aangemaakt door {{customer.name}}.</p><p>Onderwerp: {{ticket.subject}}<br>Ticket: {{ticket.number}}<br>Object: {{object.name}}</p><p>Bekijk het ticket en reageer via Fieldgrid.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p>$fgnotif$,
    $fgnotif$Nieuw klantticket$fgnotif$,
    $fgnotif${{customer.name}} heeft een ticket aangemaakt: {{ticket.subject}}.$fgnotif$,
    '["customer.name","ticket.subject","ticket.department","backofficeHref"]'::jsonb
  ),
  (
    'customer_ticket_replied',
    'communication',
    'management',
    $fgnotif$Nieuwe klantreactie$fgnotif$,
    $fgnotif${{customer.name}} heeft gereageerd op ticket {{ticket.subject}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe reactie van {{customer.name}}$fgnotif$,
    $fgnotif$Er is een nieuw ticket aangemaakt door {{customer.name}}.$fgnotif$,
    $fgnotif$<p>Er is een nieuw ticket aangemaakt door {{customer.name}}.</p><p>Onderwerp: {{ticket.subject}}<br>Ticket: {{ticket.number}}<br>Object: {{object.name}}</p><p>Bekijk het ticket en reageer via Fieldgrid.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p>$fgnotif$,
    $fgnotif$Nieuwe klantreactie$fgnotif$,
    $fgnotif${{customer.name}} heeft gereageerd op een ticket.$fgnotif$,
    '["customer.name","ticket.subject","ticket.department","backofficeHref"]'::jsonb
  ),
  (
    'document_shared_customer',
    'communication',
    'customer',
    $fgnotif$Nieuw document$fgnotif$,
    $fgnotif${{document.name}} is beschikbaar in het klantenportaal.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw document beschikbaar: {{document.name}}$fgnotif$,
    $fgnotif$U kunt het document veilig bekijken in het klantenportaal.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een document met u gedeeld:</p><p>{{document.name}}</p><p>U kunt het document veilig bekijken in het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Document openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Nieuw document$fgnotif$,
    $fgnotif${{document.name}} is beschikbaar in het klantenportaal.$fgnotif$,
    '["recipient.name","organization.name","document.name","href"]'::jsonb
  ),
  (
    'document_shared_personnel',
    'communication',
    'personnel',
    $fgnotif$Nieuw document$fgnotif$,
    $fgnotif${{document.name}} is beschikbaar in de personeelsapp.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw document$fgnotif$,
    $fgnotif${{document.name}} is beschikbaar in de personeelsapp.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>{{document.name}} is beschikbaar in de personeelsapp.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Nieuw document$fgnotif$,
    $fgnotif${{document.name}} staat klaar in de app.$fgnotif$,
    '["document.name","href"]'::jsonb
  ),
  (
    'email_provider_test_failed',
    'platform',
    'management',
    $fgnotif$E-mailtest mislukt$fgnotif$,
    $fgnotif$Controleer de mailinstellingen. De testmail kon niet worden verzonden.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$E-mailtest mislukt voor {{organization.name}}$fgnotif$,
    $fgnotif$De e-mailtest voor {{organization.name}} is mislukt.$fgnotif$,
    $fgnotif$<p>De e-mailtest voor {{organization.name}} is mislukt.</p><p>Controleer:</p><ul><li>afzenderadres;</li><li>API-key of SMTP-gegevens;</li><li>domeinvalidatie;</li><li>SPF/DKIM/DMARC;</li><li>actieve provider;</li><li>verzendlogs.</li></ul><p>Foutmelding:<br>{{error.message}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Mailinstellingen openen</a></p>$fgnotif$,
    $fgnotif$E-mailtest mislukt$fgnotif$,
    $fgnotif$Controleer de mailinstellingen. De testmail kon niet worden verzonden.$fgnotif$,
    '["organization.name","error.message","href"]'::jsonb
  ),
  (
    'email_provider_test_success',
    'platform',
    'management',
    $fgnotif$Testmail verzonden$fgnotif$,
    $fgnotif$De e-mailinstellingen zijn succesvol getest.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Testmail verzonden$fgnotif$,
    $fgnotif$De e-mailinstellingen zijn succesvol getest.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>De e-mailinstellingen zijn succesvol getest.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Testmail verzonden$fgnotif$,
    $fgnotif$De e-mailinstellingen zijn succesvol getest.$fgnotif$,
    '["recipient.name","href","organization.name"]'::jsonb
  ),
  (
    'invoice_paid',
    'customer_portal',
    'customer',
    $fgnotif$Betaling ontvangen$fgnotif$,
    $fgnotif$De betaling voor factuur {{invoice.number}} is ontvangen.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Betaling ontvangen voor factuur {{invoice.number}}$fgnotif$,
    $fgnotif$Bedankt. De betaling voor factuur {{invoice.number}} is ontvangen.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Bedankt. De betaling voor factuur {{invoice.number}} is ontvangen.</p><p>Bedrag: {{invoice.amount}}<br>Betaald op: {{invoice.paid_date}}</p><p>U kunt de betaling terugvinden in het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Betaling bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Betaling ontvangen$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} is betaald.$fgnotif$,
    '["recipient.name","organization.name","invoice.number","invoice.amount","invoice.paid_date","href"]'::jsonb
  ),
  (
    'invoice_sent',
    'customer_portal',
    'customer',
    $fgnotif$Nieuwe factuur$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} van {{invoice.amount}} staat klaar.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Factuur {{invoice.number}} van {{organization.name}}$fgnotif$,
    $fgnotif$Bekijk uw factuur en betaal eenvoudig online via het klantenportaal.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er staat een nieuwe factuur voor u klaar.</p><p>Factuurgegevens:</p><ul><li>Factuurnummer: {{invoice.number}}</li><li>Bedrag: {{invoice.amount}}</li><li>Vervaldatum: {{invoice.due_date}}</li></ul><p>U kunt de factuur bekijken en, indien online betalen actief is, direct betalen via het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Factuur bekijken en betalen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Nieuwe factuur$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} staat klaar in het klantenportaal.$fgnotif$,
    '["recipient.name","organization.name","invoice.number","invoice.amount","invoice.due_date","href"]'::jsonb
  ),
  (
    'invoice_sent_customer',
    'customer_portal',
    'customer',
    $fgnotif$Nieuwe factuur$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} van {{invoice.amount}} staat klaar.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Factuur {{invoice.number}} van {{organization.name}}$fgnotif$,
    $fgnotif$Bekijk uw factuur en betaal eenvoudig online via het klantenportaal.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er staat een nieuwe factuur voor u klaar.</p><p>Factuurgegevens:</p><ul><li>Factuurnummer: {{invoice.number}}</li><li>Bedrag: {{invoice.amount}}</li><li>Vervaldatum: {{invoice.due_date}}</li></ul><p>U kunt de factuur bekijken en, indien online betalen actief is, direct betalen via het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Factuur bekijken en betalen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Nieuwe factuur$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} staat klaar in het klantenportaal.$fgnotif$,
    '["recipient.name","organization.name","invoice.number","invoice.amount","invoice.due_date","href"]'::jsonb
  ),
  (
    'kb_article_featured',
    'knowledgebase',
    'mixed',
    $fgnotif$Belangrijke uitleg$fgnotif$,
    $fgnotif${{article.title}}$fgnotif$,
    true,
    true,
    true,
    $fgnotif$Belangrijke Fieldgrid-uitleg: {{article.title}}$fgnotif$,
    $fgnotif$Wij raden aan deze uitleg kort door te nemen.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een belangrijke Fieldgrid-uitleg uitgelicht:</p><p>{{article.title}}</p><p>{{article.summary}}</p><p>Wij raden aan deze uitleg kort door te nemen.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Uitleg openen</a></p><p>Met vriendelijke groet,<br>Fieldgrid</p>$fgnotif$,
    $fgnotif$Belangrijke Fieldgrid-uitleg$fgnotif$,
    $fgnotif$Bekijk: {{article.title}}$fgnotif$,
    '["article.title","article.summary","href"]'::jsonb
  ),
  (
    'kb_article_published',
    'knowledgebase',
    'mixed',
    $fgnotif$Nieuwe uitleg beschikbaar$fgnotif$,
    $fgnotif${{article.title}}$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe Fieldgrid-uitleg: {{article.title}}$fgnotif$,
    $fgnotif$Deze uitleg helpt u om Fieldgrid makkelijker te gebruiken.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er staat een nieuwe Fieldgrid-uitleg klaar:</p><p>{{article.title}}</p><p>{{article.summary}}</p><p>Deze uitleg helpt u om Fieldgrid makkelijker te gebruiken.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Uitleg openen</a></p><p>Met vriendelijke groet,<br>Fieldgrid</p>$fgnotif$,
    $fgnotif$Nieuwe Fieldgrid-uitleg$fgnotif$,
    $fgnotif${{article.title}}$fgnotif$,
    '["article.title","article.summary","href"]'::jsonb
  ),
  (
    'kb_article_updated',
    'knowledgebase',
    'mixed',
    $fgnotif$Uitleg bijgewerkt$fgnotif$,
    $fgnotif${{article.title}} is bijgewerkt.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Fieldgrid-uitleg bijgewerkt: {{article.title}}$fgnotif$,
    $fgnotif$Er is een nieuwe update in Fieldgrid.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>De volgende Fieldgrid-uitleg is bijgewerkt:</p><p>{{article.title}}</p><p>{{article.summary}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Uitleg bekijken</a></p><p>Met vriendelijke groet,<br>Fieldgrid</p>$fgnotif$,
    $fgnotif$Uitleg bijgewerkt$fgnotif$,
    $fgnotif${{article.title}} is bijgewerkt.$fgnotif$,
    '["article.title","article.summary","href"]'::jsonb
  ),
  (
    'leave_approved_personnel',
    'operations',
    'personnel',
    $fgnotif$Verlof goedgekeurd$fgnotif$,
    $fgnotif$Uw verlof voor {{leave.period}} is goedgekeurd.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Uw verlofaanvraag is goedgekeurd$fgnotif$,
    $fgnotif$Uw verlofaanvraag is goedgekeurd.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Uw verlofaanvraag is goedgekeurd.</p><p>Type: {{leave.type}}<br>Periode: {{leave.period}}</p><p>Uw verlof is verwerkt in de planning.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Mijn verlof bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Verlof goedgekeurd$fgnotif$,
    $fgnotif$Uw verlofaanvraag is goedgekeurd.$fgnotif$,
    '["recipient.name","organization.name","leave.type","leave.period","href"]'::jsonb
  ),
  (
    'leave_decision',
    'operations',
    'personnel',
    $fgnotif$Verlofaanvraag beoordeeld$fgnotif$,
    $fgnotif$Uw verlofaanvraag voor {{leave.period}} is {{leave.decision}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Verlofaanvraag {{leave.decision}}$fgnotif$,
    $fgnotif$Uw verlofaanvraag is goedgekeurd.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Uw verlofaanvraag is goedgekeurd.</p><p>Type: {{leave.type}}<br>Periode: {{leave.period}}</p><p>Uw verlof is verwerkt in de planning.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Mijn verlof bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Verlofaanvraag beoordeeld$fgnotif$,
    $fgnotif$Uw verlofaanvraag is {{leave.decision}}.$fgnotif$,
    '["recipient.name","organization.name","leave.period","leave.type","leave.decision","href"]'::jsonb
  ),
  (
    'leave_rejected_personnel',
    'operations',
    'personnel',
    $fgnotif$Verlof afgewezen$fgnotif$,
    $fgnotif$Uw verlof voor {{leave.period}} is afgewezen.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Uw verlofaanvraag is afgewezen$fgnotif$,
    $fgnotif$Uw verlofaanvraag is afgewezen.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Uw verlofaanvraag is afgewezen.</p><p>Type: {{leave.type}}<br>Periode: {{leave.period}}</p><p>Reden of toelichting:<br>{{reason}}</p><p>Neem contact op met planning of uw leidinggevende als u vragen heeft.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Mijn verlof bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Verlof afgewezen$fgnotif$,
    $fgnotif$Bekijk de toelichting in de personeelsapp.$fgnotif$,
    '["recipient.name","organization.name","leave.type","leave.period","reason","href"]'::jsonb
  ),
  (
    'leave_requested',
    'operations',
    'management',
    $fgnotif$Nieuwe verlofaanvraag$fgnotif$,
    $fgnotif${{personnel.name}} heeft verlof aangevraagd voor {{leave.period}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe verlofaanvraag van {{personnel.name}}$fgnotif$,
    $fgnotif${{personnel.name}} heeft een verlofaanvraag ingediend.$fgnotif$,
    $fgnotif$<p>{{personnel.name}} heeft een verlofaanvraag ingediend.</p><p>Type: {{leave.type}}<br>Periode: {{leave.period}}<br>Toelichting:<br>{{reason}}</p><p>Controleer de aanvraag en keur deze goed of wijs deze af.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Verlofaanvraag bekijken</a></p>$fgnotif$,
    $fgnotif$Nieuwe verlofaanvraag$fgnotif$,
    $fgnotif${{personnel.name}} heeft verlof aangevraagd voor {{leave.period}}.$fgnotif$,
    '["personnel.name","leave.type","leave.period","reason","href"]'::jsonb
  ),
  (
    'leave_requested_backoffice',
    'operations',
    'management',
    $fgnotif$Nieuwe verlofaanvraag$fgnotif$,
    $fgnotif${{personnel.name}} heeft verlof aangevraagd voor {{leave.period}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe verlofaanvraag van {{personnel.name}}$fgnotif$,
    $fgnotif${{personnel.name}} heeft een verlofaanvraag ingediend.$fgnotif$,
    $fgnotif$<p>{{personnel.name}} heeft een verlofaanvraag ingediend.</p><p>Type: {{leave.type}}<br>Periode: {{leave.period}}<br>Toelichting:<br>{{reason}}</p><p>Controleer de aanvraag en keur deze goed of wijs deze af.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Verlofaanvraag bekijken</a></p>$fgnotif$,
    $fgnotif$Nieuwe verlofaanvraag$fgnotif$,
    $fgnotif${{personnel.name}} heeft verlof aangevraagd voor {{leave.period}}.$fgnotif$,
    '["personnel.name","leave.type","leave.period","reason","href"]'::jsonb
  ),
  (
    'news_published',
    'communication',
    'mixed',
    $fgnotif$Nieuw bericht$fgnotif$,
    $fgnotif${{news.title}}$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw bericht: {{news.title}}$fgnotif$,
    $fgnotif$Er is een nieuwe update in Fieldgrid.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een nieuw bericht gepubliceerd:</p><p>{{news.title}}</p><p>{{news.summary}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Bericht bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Nieuw bericht$fgnotif$,
    $fgnotif${{news.title}}$fgnotif$,
    '["recipient.name","organization.name","news.title","news.summary","href"]'::jsonb
  ),
  (
    'open_assignment_interested_backoffice',
    'planning',
    'management',
    $fgnotif$Interesse ontvangen$fgnotif$,
    $fgnotif${{personnel.name}} heeft interesse in werkbon {{assignment.number}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Interesse ontvangen$fgnotif$,
    $fgnotif${{personnel.name}} heeft interesse in werkbon {{assignment.number}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>{{personnel.name}} heeft interesse in werkbon {{assignment.number}}.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Interesse op open opdracht$fgnotif$,
    $fgnotif${{personnel.name}} reageerde op {{assignment.number}}.$fgnotif$,
    '["personnel.name","assignment.number","object.name","href"]'::jsonb
  ),
  (
    'open_assignment_invite_personnel',
    'planning',
    'personnel',
    $fgnotif$Open opdracht beschikbaar$fgnotif$,
    $fgnotif$Kunt u werken bij {{object.name}} op {{assignment.date}}? Geef uw reactie door.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$Open opdracht beschikbaar$fgnotif$,
    $fgnotif$Kunt u werken bij {{object.name}} op {{assignment.date}}?$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Kunt u werken bij {{object.name}} op {{assignment.date}}? Geef uw reactie door.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Open opdracht$fgnotif$,
    $fgnotif$Geef aan of u beschikbaar bent voor {{object.name}}.$fgnotif$,
    '["object.name","assignment.date","assignment.start_time","href"]'::jsonb
  ),
  (
    'open_assignment_reserve_personnel',
    'planning',
    'personnel',
    $fgnotif$U staat als reserve$fgnotif$,
    $fgnotif$U staat als reserve voor werkbon {{assignment.number}} bij {{object.name}}. Planning neemt contact op als u nodig bent.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$U staat als reserve$fgnotif$,
    $fgnotif$U staat als reserve voor werkbon {{assignment.number}} bij {{object.name}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>U staat als reserve voor werkbon {{assignment.number}} bij {{object.name}}. Planning neemt contact op als u nodig bent.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Reserve voor opdracht$fgnotif$,
    $fgnotif$U staat als reserve voor {{object.name}}.$fgnotif$,
    '["assignment.number","object.name","href"]'::jsonb
  ),
  (
    'open_assignment_selected_personnel',
    'planning',
    'personnel',
    $fgnotif$U bent ingepland$fgnotif$,
    $fgnotif$U bent geselecteerd voor werkbon {{assignment.number}} bij {{object.name}}.$fgnotif$,
    false,
    true,
    true,
    $fgnotif$U bent ingepland voor werkbon {{assignment.number}}$fgnotif$,
    $fgnotif$U bent geselecteerd en ingepland voor werkbon {{assignment.number}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>U bent geselecteerd en ingepland voor werkbon {{assignment.number}}.</p><p>Object: {{object.name}}<br>Datum: {{assignment.date}}<br>Tijd: {{assignment.start_time}} - {{assignment.end_time}}</p><p>Bekijk de werkbon in de personeelsapp voor alle details.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Werkbon openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$U bent ingepland$fgnotif$,
    $fgnotif$Werkbon {{assignment.number}} staat nu in uw planning.$fgnotif$,
    '["recipient.name","organization.name","assignment.number","assignment.date","assignment.start_time","assignment.end_time","object.name","href"]'::jsonb
  ),
  (
    'organization_environment_created',
    'platform',
    'management',
    $fgnotif$Nieuwe organisatieomgeving$fgnotif$,
    $fgnotif${{organization.name}} is aangemaakt en vraagt controle.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe organisatieomgeving aangemaakt: {{organization.name}}$fgnotif$,
    $fgnotif$Er is een nieuwe organisatieomgeving aangemaakt.$fgnotif$,
    $fgnotif$<p>Er is een nieuwe organisatieomgeving aangemaakt.</p><p>Organisatie: {{organization.name}}<br>Pakket: {{plan.name}}<br>Status: {{organization.status}}</p><p>Controleer onboarding, modules, domeinen, eigenaarstoegang en mailinstellingen.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Organisatie openen</a></p>$fgnotif$,
    $fgnotif$Nieuwe organisatieomgeving$fgnotif$,
    $fgnotif${{organization.name}} is aangemaakt en vraagt controle.$fgnotif$,
    '["organization.name","plan.name","organization.status","href"]'::jsonb
  ),
  (
    'organization_onboarding_attention',
    'platform',
    'management',
    $fgnotif$Onboarding vraagt aandacht$fgnotif$,
    $fgnotif${{organization.name}} heeft een onboardingstap die aandacht nodig heeft.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Onboarding vraagt aandacht: {{organization.name}}$fgnotif$,
    $fgnotif$De onboarding van {{organization.name}} vraagt aandacht.$fgnotif$,
    $fgnotif$<p>De onboarding van {{organization.name}} vraagt aandacht.</p><p>Stap: {{onboarding.step}}<br>Status: {{onboarding.status}}<br>Melding: {{onboarding.message}}</p><p>Controleer de oorzaak en probeer de stap pas opnieuw nadat het probleem is opgelost.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Onboarding openen</a></p>$fgnotif$,
    $fgnotif$Onboarding vraagt aandacht$fgnotif$,
    $fgnotif${{organization.name}} heeft een onboardingstap die aandacht nodig heeft.$fgnotif$,
    '["organization.name","onboarding.step","onboarding.status","onboarding.message","href"]'::jsonb
  ),
  (
    'password_reset_code',
    'account',
    'mixed',
    $fgnotif$Wachtwoord opnieuw instellen voor {{portal.name}}$fgnotif$,
    $fgnotif$Gebruik deze herstelcode om een nieuw wachtwoord te kiezen.$fgnotif$,
    true,
    false,
    false,
    $fgnotif$Wachtwoord opnieuw instellen voor {{portal.name}}$fgnotif$,
    $fgnotif$Gebruik deze herstelcode om een nieuw wachtwoord te kiezen.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een verzoek gedaan om uw wachtwoord voor {{portal.name}} opnieuw in te stellen.</p><p>Gebruik deze herstelcode:</p><p>{{reset.code}}</p><p>De code is 30 minuten geldig.</p><p><a href="{{reset.url}}" style="color:#0f766e;text-decoration:underline">Resetpagina openen</a></p><p>Heeft u dit niet aangevraagd? Dan hoeft u niets te doen. Uw huidige wachtwoord blijft geldig.</p><p>Met vriendelijke groet,<br>Fieldgrid</p>$fgnotif$,
    $fgnotif$Wachtwoord opnieuw instellen voor {{portal.name}}$fgnotif$,
    $fgnotif$Gebruik deze herstelcode om een nieuw wachtwoord te kiezen.$fgnotif$,
    '["recipient.name","portal.name","reset.code","reset.url"]'::jsonb
  ),
  (
    'payment_received_customer',
    'customer_portal',
    'customer',
    $fgnotif$Betaling ontvangen$fgnotif$,
    $fgnotif$De betaling voor factuur {{invoice.number}} is ontvangen.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Betaling ontvangen voor factuur {{invoice.number}}$fgnotif$,
    $fgnotif$Bedankt. De betaling voor factuur {{invoice.number}} is ontvangen.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Bedankt. De betaling voor factuur {{invoice.number}} is ontvangen.</p><p>Bedrag: {{invoice.amount}}<br>Status: {{payment.status}}</p><p>U kunt de betaling terugvinden in het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Betaling bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Betaling ontvangen$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} is betaald.$fgnotif$,
    '["recipient.name","organization.name","invoice.number","invoice.amount","payment.status","href"]'::jsonb
  ),
  (
    'payment_reminder',
    'customer_portal',
    'customer',
    $fgnotif$Factuur staat nog open$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} is nog niet betaald.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Betalingsherinnering voor factuur {{invoice.number}}$fgnotif$,
    $fgnotif$Deze factuur staat nog open. Heeft u al betaald? Dan kunt u dit bericht negeren.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Volgens onze administratie staat onderstaande factuur nog open.</p><p>Factuurgegevens:</p><ul><li>Factuurnummer: {{invoice.number}}</li><li>Bedrag: {{invoice.amount}}</li><li>Vervaldatum: {{invoice.due_date}}</li></ul><p>Wij verzoeken u vriendelijk het openstaande bedrag te voldoen.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Factuur bekijken en betalen</a></p><p>Heeft u de factuur inmiddels betaald? Dan kunt u dit bericht als niet verzonden beschouwen.</p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Factuurherinnering$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} staat nog open.$fgnotif$,
    '["recipient.name","organization.name","invoice.number","invoice.amount","invoice.due_date","href"]'::jsonb
  ),
  (
    'payment_reminder_customer',
    'customer_portal',
    'customer',
    $fgnotif$Factuur staat nog open$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} is nog niet betaald.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Betalingsherinnering voor factuur {{invoice.number}}$fgnotif$,
    $fgnotif$Deze factuur staat nog open. Heeft u al betaald? Dan kunt u dit bericht negeren.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Volgens onze administratie staat onderstaande factuur nog open.</p><p>Factuurgegevens:</p><ul><li>Factuurnummer: {{invoice.number}}</li><li>Bedrag: {{invoice.amount}}</li><li>Vervaldatum: {{invoice.due_date}}</li></ul><p>Wij verzoeken u vriendelijk het openstaande bedrag te voldoen.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Factuur bekijken en betalen</a></p><p>Heeft u de factuur inmiddels betaald? Dan kunt u dit bericht als niet verzonden beschouwen.</p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Factuurherinnering$fgnotif$,
    $fgnotif$Factuur {{invoice.number}} staat nog open.$fgnotif$,
    '["recipient.name","organization.name","invoice.number","invoice.amount","invoice.due_date","href"]'::jsonb
  ),
  (
    'personnel_assignment_question_created',
    'communication',
    'management',
    $fgnotif$Vraag over werkbon$fgnotif$,
    $fgnotif${{personnel.name}} heeft een vraag gesteld over {{assignment.code}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Vraag over {{assignment.code}}$fgnotif$,
    $fgnotif${{personnel.name}} heeft een nieuw ticket aangemaakt.$fgnotif$,
    $fgnotif$<p>{{personnel.name}} heeft een nieuw ticket aangemaakt.</p><p>Onderwerp: {{ticket.subject}}<br>Ticket: {{ticket.number}}</p><p>Bekijk het ticket en reageer via Fieldgrid.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p>$fgnotif$,
    $fgnotif$Vraag over werkbon$fgnotif$,
    $fgnotif${{personnel.name}} heeft een vraag gesteld over {{assignment.code}}.$fgnotif$,
    '["personnel.name","assignment.code","assignment.title","ticket.subject","backofficeHref"]'::jsonb
  ),
  (
    'personnel_portal_invite',
    'account',
    'personnel',
    $fgnotif$Toegang tot de personeelsapp van {{organization.name}}$fgnotif$,
    $fgnotif$Uw account staat klaar. Log in met het tijdelijke wachtwoord en kies daarna uw eigen wachtwoord.$fgnotif$,
    true,
    false,
    false,
    $fgnotif$Toegang tot de personeelsapp van {{organization.name}}$fgnotif$,
    $fgnotif$Uw account staat klaar. Log in met het tijdelijke wachtwoord en kies daarna uw eigen wachtwoord.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een account voor u aangemaakt in de personeelsapp van {{organization.name}}.</p><p>In de personeelsapp ziet u uw planning, werkbonnen, open opdrachten, beschikbaarheid, verlof, documenten, meldingen en tickets.</p><p>Gebruik onderstaand tijdelijk wachtwoord om voor de eerste keer in te loggen:</p><p>{{temporary_password}}</p><p>Na de eerste login vragen wij u direct een eigen wachtwoord te kiezen.</p><p><a href="{{portal.login_url}}" style="color:#0f766e;text-decoration:underline">Inloggen op de personeelsapp</a></p><p>Bewaar dit tijdelijke wachtwoord niet. Het is alleen bedoeld voor de eerste login.</p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Toegang tot de personeelsapp van {{organization.name}}$fgnotif$,
    $fgnotif$Uw account staat klaar. Log in met het tijdelijke wachtwoord en kies daarna uw eigen wachtwoord.$fgnotif$,
    '["recipient.name","organization.name","temporary_password","portal.login_url"]'::jsonb
  ),
  (
    'personnel_ticket_backoffice_reply',
    'communication',
    'personnel',
    $fgnotif$Nieuwe ticketreactie$fgnotif$,
    $fgnotif$Er is gereageerd op ticket {{ticket.number}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Reactie op uw ticket: {{ticket.subject}}$fgnotif$,
    $fgnotif$Er is een reactie geplaatst op uw ticket.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een reactie geplaatst op uw ticket.</p><p>Ticket: {{ticket.number}}<br>Onderwerp: {{ticket.subject}}</p><p>U kunt de reactie bekijken en beantwoorden in de personeelsapp.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Reactie op ticket$fgnotif$,
    $fgnotif$Bekijk de reactie in de personeelsapp.$fgnotif$,
    '["recipient.name","organization.name","ticket.number","ticket.subject","href"]'::jsonb
  ),
  (
    'personnel_ticket_created',
    'communication',
    'management',
    $fgnotif$Nieuw personeelsticket$fgnotif$,
    $fgnotif${{personnel.name}} heeft een ticket aangemaakt: {{ticket.subject}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw personeelsticket: {{ticket.subject}}$fgnotif$,
    $fgnotif${{personnel.name}} heeft een nieuw ticket aangemaakt.$fgnotif$,
    $fgnotif$<p>{{personnel.name}} heeft een nieuw ticket aangemaakt.</p><p>Onderwerp: {{ticket.subject}}<br>Ticket: {{ticket.number}}</p><p>Bekijk het ticket en reageer via Fieldgrid.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p>$fgnotif$,
    $fgnotif$Nieuw personeelsticket$fgnotif$,
    $fgnotif${{personnel.name}} heeft een ticket aangemaakt: {{ticket.subject}}.$fgnotif$,
    '["personnel.name","ticket.number","ticket.subject","href"]'::jsonb
  ),
  (
    'portal_invite',
    'account',
    'customer',
    $fgnotif$Portaaltoegang aangemaakt$fgnotif$,
    $fgnotif$Er is portaaltoegang aangemaakt voor een gebruiker.$fgnotif$,
    true,
    false,
    false,
    $fgnotif$Toegang tot {{portal.name}}$fgnotif$,
    $fgnotif$Uw account staat klaar. Log in met het tijdelijke wachtwoord en kies daarna uw eigen wachtwoord.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een account voor u aangemaakt in het klantenportaal van {{organization.name}}.</p><p>Via het klantenportaal kunt u aanvragen indienen, objecten bekijken, offertes beoordelen, rapportages openen, facturen bekijken en betalingen volgen.</p><p>Gebruik onderstaand tijdelijk wachtwoord om voor de eerste keer in te loggen:</p><p>{{temporary_password}}</p><p>Na de eerste login vragen wij u direct een eigen wachtwoord te kiezen.</p><p><a href="{{portal.login_url}}" style="color:#0f766e;text-decoration:underline">Inloggen op het klantenportaal</a></p><p>Heeft u deze uitnodiging niet verwacht? Neem dan contact op met {{organization.name}}.</p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Toegang tot het klantenportaal van {{organization.name}}$fgnotif$,
    $fgnotif$Uw account staat klaar. Log in met het tijdelijke wachtwoord en kies daarna uw eigen wachtwoord.$fgnotif$,
    '["recipient.name","organization.name","temporary_password","portal.login_url","portal.name"]'::jsonb
  ),
  (
    'quote_accepted_backoffice',
    'customer_portal',
    'management',
    $fgnotif$Offerte geaccepteerd$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} geaccepteerd.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Offerte {{quote.number}} is geaccepteerd$fgnotif$,
    $fgnotif$Offerte {{quote.number}} is geaccepteerd door {{customer.name}}.$fgnotif$,
    $fgnotif$<p>Offerte {{quote.number}} is geaccepteerd door {{customer.name}}.</p><p>Klant: {{customer.name}}<br>Object: {{object.name}}<br>Offertebedrag: {{quote.amount}}</p><p>De opdracht kan nu verder worden gepland of administratief verwerkt.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Offerte openen</a></p>$fgnotif$,
    $fgnotif$Offerte akkoord$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} geaccepteerd.$fgnotif$,
    '["customer.name","object.name","quote.number","quote.amount","href"]'::jsonb
  ),
  (
    'quote_approved_by_customer',
    'customer_portal',
    'management',
    $fgnotif$Offerte geaccepteerd$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} geaccepteerd.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Offerte {{quote.number}} is geaccepteerd$fgnotif$,
    $fgnotif$Offerte {{quote.number}} is geaccepteerd door {{customer.name}}.$fgnotif$,
    $fgnotif$<p>Offerte {{quote.number}} is geaccepteerd door {{customer.name}}.</p><p>Klant: {{customer.name}}<br>Opdracht: {{assignment.title}}<br>Offertebedrag: {{quote.amount}}</p><p>De opdracht kan nu verder worden gepland of administratief verwerkt.</p><p><a href="{{backofficeHref}}" style="color:#0f766e;text-decoration:underline">Offerte openen</a></p>$fgnotif$,
    $fgnotif$Offerte akkoord$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} geaccepteerd.$fgnotif$,
    '["customer.name","assignment.title","quote.number","quote.amount","backofficeHref"]'::jsonb
  ),
  (
    'quote_expired',
    'customer_portal',
    'customer',
    $fgnotif$Offerte verlopen$fgnotif$,
    $fgnotif$Offerte {{quote.number}} is verlopen. Neem contact op als u een nieuwe offerte wilt.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Offerte {{quote.number}} is verlopen$fgnotif$,
    $fgnotif$Neem contact met ons op als u de werkzaamheden alsnog wilt laten uitvoeren.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Offerte {{quote.number}} is verlopen.</p><p>Offertegegevens:</p><ul><li>Object: {{object.name}}</li><li>Bedrag: {{quote.amount}}</li><li>Geldig tot: {{quote.valid_until}}</li></ul><p>Wilt u de werkzaamheden alsnog laten uitvoeren of wilt u een nieuwe prijsopgave ontvangen? Neem dan contact met ons op.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Offertes bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Offerte verlopen$fgnotif$,
    $fgnotif$Offerte {{quote.number}} is verlopen. Neem contact op als u een nieuwe offerte wilt.$fgnotif$,
    '["recipient.name","organization.name","quote.number","quote.amount","quote.valid_until","object.name","href"]'::jsonb
  ),
  (
    'quote_expired_customer',
    'customer_portal',
    'customer',
    $fgnotif$Offerte verlopen$fgnotif$,
    $fgnotif$Offerte {{quote.number}} is verlopen. Neem contact op als u een nieuwe offerte wilt.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Offerte {{quote.number}} is verlopen$fgnotif$,
    $fgnotif$Neem contact met ons op als u de werkzaamheden alsnog wilt laten uitvoeren.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Offerte {{quote.number}} is verlopen.</p><p>Offertegegevens:</p><ul><li>Object: {{object.name}}</li><li>Bedrag: {{quote.amount}}</li><li>Geldig tot: {{quote.valid_until}}</li></ul><p>Wilt u de werkzaamheden alsnog laten uitvoeren of wilt u een nieuwe prijsopgave ontvangen? Neem dan contact met ons op.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Offertes bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Offerte verlopen$fgnotif$,
    $fgnotif$Offerte {{quote.number}} is verlopen. Neem contact op als u een nieuwe offerte wilt.$fgnotif$,
    '["recipient.name","organization.name","quote.number","quote.amount","quote.valid_until","object.name","href"]'::jsonb
  ),
  (
    'quote_rejected_backoffice',
    'customer_portal',
    'management',
    $fgnotif$Offerte afgewezen$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} afgewezen.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Offerte {{quote.number}} is afgewezen$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} afgewezen.$fgnotif$,
    $fgnotif$<p>{{customer.name}} heeft offerte {{quote.number}} afgewezen.</p><p>Object: {{object.name}}<br>Reden of toelichting:<br>{{reason}}</p><p>Controleer of opvolging nodig is.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Offerte openen</a></p>$fgnotif$,
    $fgnotif$Offerte afgewezen$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} afgewezen.$fgnotif$,
    '["customer.name","object.name","quote.number","reason","href"]'::jsonb
  ),
  (
    'quote_rejected_by_customer',
    'customer_portal',
    'management',
    $fgnotif$Offerte afgewezen$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} afgewezen.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Offerte {{quote.number}} is afgewezen$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} afgewezen.$fgnotif$,
    $fgnotif$<p>{{customer.name}} heeft offerte {{quote.number}} afgewezen.</p><p>Opdracht: {{assignment.title}}<br>Reden of toelichting:<br>{{reason}}</p><p>Controleer of opvolging nodig is.</p><p><a href="{{backofficeHref}}" style="color:#0f766e;text-decoration:underline">Offerte openen</a></p>$fgnotif$,
    $fgnotif$Offerte afgewezen$fgnotif$,
    $fgnotif${{customer.name}} heeft offerte {{quote.number}} afgewezen.$fgnotif$,
    '["customer.name","assignment.title","quote.number","reason","backofficeHref"]'::jsonb
  ),
  (
    'quote_sent_customer',
    'customer_portal',
    'customer',
    $fgnotif$Nieuwe offerte beschikbaar$fgnotif$,
    $fgnotif$Offerte {{quote.number}} staat klaar voor {{object.name}}.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Uw offerte {{quote.number}} staat klaar$fgnotif$,
    $fgnotif$Bekijk de offerte en geef eenvoudig akkoord via het klantenportaal.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er staat een nieuwe offerte voor u klaar.</p><p>Offertegegevens:</p><ul><li>Offertenummer: {{quote.number}}</li><li>Object: {{object.name}}</li><li>Bedrag: {{quote.amount}}</li><li>Geldig tot: {{quote.valid_until}}</li></ul><p>U kunt de offerte bekijken en direct akkoord geven of afwijzen via het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Offerte bekijken</a></p><p>Heeft u vragen over de offerte? Reageer dan via een ticket in het klantenportaal of neem contact met ons op.</p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Offerte staat klaar$fgnotif$,
    $fgnotif$Bekijk offerte {{quote.number}} in het klantenportaal.$fgnotif$,
    '["recipient.name","organization.name","quote.number","quote.amount","quote.valid_until","object.name","href"]'::jsonb
  ),
  (
    'quote_sent_to_customer',
    'customer_portal',
    'customer',
    $fgnotif$Nieuwe offerte beschikbaar$fgnotif$,
    $fgnotif$Offerte {{quote.number}} staat klaar.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Uw offerte {{quote.number}} staat klaar$fgnotif$,
    $fgnotif$Bekijk de offerte en geef eenvoudig akkoord via het klantenportaal.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er staat een nieuwe offerte voor u klaar.</p><p>Offertenummer: {{quote.number}}<br>Opdracht: {{assignment.title}}<br>Bedrag: {{quote.amount}}<br>Geldig tot: {{quote.valid_until}}</p><p>U kunt de offerte bekijken en direct akkoord geven of afwijzen via het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Offerte bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Offerte staat klaar$fgnotif$,
    $fgnotif$Bekijk offerte {{quote.number}} in het klantenportaal.$fgnotif$,
    '["recipient.name","organization.name","quote.number","quote.amount","quote.valid_until","assignment.title","href"]'::jsonb
  ),
  (
    'release_featured',
    'knowledgebase',
    'mixed',
    $fgnotif$Belangrijke release$fgnotif$,
    $fgnotif${{release.version}} - {{release.title}}$fgnotif$,
    true,
    true,
    true,
    $fgnotif$Belangrijke Fieldgrid-release: {{release.version}}$fgnotif$,
    $fgnotif$Er is een belangrijke Fieldgrid-release uitgelicht.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een belangrijke Fieldgrid-release uitgelicht.</p><p>{{release.version}} - {{release.title}}</p><p>{{release.summary}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Release bekijken</a></p><p>Met vriendelijke groet,<br>Fieldgrid</p>$fgnotif$,
    $fgnotif$Belangrijke Fieldgrid-release$fgnotif$,
    $fgnotif$Bekijk wat er is gewijzigd.$fgnotif$,
    '["release.version","release.title","release.summary","href"]'::jsonb
  ),
  (
    'release_highlight_active',
    'knowledgebase',
    'mixed',
    $fgnotif${{highlight.title}}$fgnotif$,
    $fgnotif${{highlight.message}}$fgnotif$,
    false,
    true,
    true,
    $fgnotif${{highlight.title}}$fgnotif$,
    $fgnotif$Deze wijziging hoort bij release {{release.version}} - {{release.title}}.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>{{highlight.message}}</p><p>Deze wijziging hoort bij release {{release.version}} - {{release.title}}.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Meer bekijken</a></p><p>Met vriendelijke groet,<br>Fieldgrid</p>$fgnotif$,
    $fgnotif${{highlight.title}}$fgnotif$,
    $fgnotif${{highlight.message}}$fgnotif$,
    '["release.version","release.title","highlight.title","highlight.message","href"]'::jsonb
  ),
  (
    'release_published',
    'knowledgebase',
    'mixed',
    $fgnotif$Nieuwe release$fgnotif$,
    $fgnotif${{release.version}} - {{release.title}}$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe Fieldgrid-release: {{release.version}}$fgnotif$,
    $fgnotif$Er is een nieuwe Fieldgrid-release gepubliceerd.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een nieuwe Fieldgrid-release gepubliceerd.</p><p>{{release.version}} - {{release.title}}</p><p>{{release.summary}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Release bekijken</a></p><p>Met vriendelijke groet,<br>Fieldgrid</p>$fgnotif$,
    $fgnotif$Nieuwe Fieldgrid-release$fgnotif$,
    $fgnotif${{release.version}} - {{release.title}}$fgnotif$,
    '["release.version","release.title","release.summary","href"]'::jsonb
  ),
  (
    'report_approved',
    'operations',
    'personnel',
    $fgnotif$Rapport goedgekeurd$fgnotif$,
    $fgnotif$Uw rapport voor werkbon {{assignment.code}} is goedgekeurd.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Rapport goedgekeurd voor werkbon {{assignment.code}}$fgnotif$,
    $fgnotif$Uw rapport voor werkbon {{assignment.code}} is goedgekeurd.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Uw rapport voor werkbon {{assignment.code}} is goedgekeurd.</p><p>Object: {{object.name}}<br>Datum: {{assignment.date}}</p><p>Bedankt voor het correct afronden van de rapportage.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Mijn rapportage bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Rapport goedgekeurd$fgnotif$,
    $fgnotif$Uw rapport voor werkbon {{assignment.code}} is goedgekeurd.$fgnotif$,
    '["recipient.name","organization.name","assignment.code","assignment.date","object.name","href"]'::jsonb
  ),
  (
    'report_approved_personnel',
    'operations',
    'personnel',
    $fgnotif$Rapport goedgekeurd$fgnotif$,
    $fgnotif$Uw rapport voor werkbon {{assignment.number}} is goedgekeurd.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Rapport goedgekeurd voor werkbon {{assignment.number}}$fgnotif$,
    $fgnotif$Uw rapport voor werkbon {{assignment.number}} is goedgekeurd.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Uw rapport voor werkbon {{assignment.number}} is goedgekeurd.</p><p>Object: {{object.name}}<br>Datum: {{assignment.date}}</p><p>Bedankt voor het correct afronden van de rapportage.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Mijn rapportage bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Rapport goedgekeurd$fgnotif$,
    $fgnotif$Uw rapport voor werkbon {{assignment.number}} is goedgekeurd.$fgnotif$,
    '["recipient.name","organization.name","assignment.number","assignment.date","object.name","href"]'::jsonb
  ),
  (
    'report_available_customer',
    'customer_portal',
    'customer',
    $fgnotif$Rapport beschikbaar$fgnotif$,
    $fgnotif$Het rapport voor {{object.name}} staat klaar.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Rapport beschikbaar voor {{object.name}}$fgnotif$,
    $fgnotif$Het rapport voor {{object.name}} staat klaar in het klantenportaal.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Het rapport voor {{object.name}} staat klaar in het klantenportaal.</p><p>Opdracht: {{assignment.number}}<br>Datum: {{assignment.date}}</p><p>U kunt het rapport bekijken, inclusief de informatie die met u gedeeld is.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Rapport bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Rapport beschikbaar$fgnotif$,
    $fgnotif$Bekijk het rapport voor {{object.name}}.$fgnotif$,
    '["recipient.name","organization.name","object.name","assignment.number","assignment.date","href"]'::jsonb
  ),
  (
    'report_available_to_customer',
    'customer_portal',
    'customer',
    $fgnotif$Rapport beschikbaar$fgnotif$,
    $fgnotif$Het rapport voor {{assignment.code}} staat klaar.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Rapport beschikbaar voor {{assignment.code}}$fgnotif$,
    $fgnotif$Het rapport voor {{object.name}} staat klaar in het klantenportaal.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Het rapport voor opdracht {{assignment.code}} staat klaar in het klantenportaal.</p><p>Opdracht: {{assignment.title}}</p><p>U kunt het rapport bekijken, inclusief de informatie die met u gedeeld is.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Rapport bekijken</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Rapport beschikbaar$fgnotif$,
    $fgnotif$Bekijk het rapport voor {{assignment.code}}.$fgnotif$,
    '["recipient.name","organization.name","assignment.code","assignment.title","href"]'::jsonb
  ),
  (
    'report_rejected',
    'operations',
    'personnel',
    $fgnotif$Rapport vraagt aanpassing$fgnotif$,
    $fgnotif$Rapport voor {{assignment.code}} is nog niet goedgekeurd. Reden: {{reason}}$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Rapport vraagt aanpassing: {{assignment.code}}$fgnotif$,
    $fgnotif$Uw rapport voor werkbon {{assignment.code}} vraagt nog een aanpassing.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Uw rapport voor werkbon {{assignment.code}} vraagt nog een aanpassing.</p><p>Object: {{object.name}}</p><p>Reden:<br>{{reason}}</p><p>Open de werkbon of rapportage in de personeelsapp en pas de informatie aan waar nodig.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Rapportage openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Rapport aanpassen$fgnotif$,
    $fgnotif$Uw rapport voor {{assignment.code}} vraagt nog aandacht.$fgnotif$,
    '["recipient.name","organization.name","assignment.code","object.name","reason","href"]'::jsonb
  ),
  (
    'report_rejected_personnel',
    'operations',
    'personnel',
    $fgnotif$Rapport vraagt aanpassing$fgnotif$,
    $fgnotif$Rapport voor {{assignment.number}} is nog niet goedgekeurd. Reden: {{reason}}$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Rapport vraagt aanpassing: {{assignment.number}}$fgnotif$,
    $fgnotif$Uw rapport voor werkbon {{assignment.number}} vraagt nog een aanpassing.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Uw rapport voor werkbon {{assignment.number}} vraagt nog een aanpassing.</p><p>Object: {{object.name}}</p><p>Reden:<br>{{reason}}</p><p>Open de werkbon of rapportage in de personeelsapp en pas de informatie aan waar nodig.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Rapportage openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Rapport aanpassen$fgnotif$,
    $fgnotif$Uw rapport voor {{assignment.number}} vraagt nog aandacht.$fgnotif$,
    '["recipient.name","organization.name","assignment.number","object.name","reason","href"]'::jsonb
  ),
  (
    'report_submitted',
    'operations',
    'management',
    $fgnotif$Rapport ingediend$fgnotif$,
    $fgnotif${{personnel.name}} heeft een rapport ingediend voor {{assignment.code}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw rapport ingediend voor {{assignment.code}}$fgnotif$,
    $fgnotif$Er is een nieuw rapport ingediend.$fgnotif$,
    $fgnotif$<p>Er is een nieuw rapport ingediend.</p><p>Opdracht: {{assignment.code}}<br>Object: {{object.name}}<br>Medewerker: {{personnel.name}}</p><p>Controleer het rapport voordat het klantzichtbaar of factureerbaar wordt.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Rapport bekijken</a></p>$fgnotif$,
    $fgnotif$Rapport ingediend$fgnotif$,
    $fgnotif${{personnel.name}} heeft een rapport ingediend voor {{assignment.code}}.$fgnotif$,
    '["assignment.code","object.name","personnel.name","href"]'::jsonb
  ),
  (
    'report_submitted_backoffice',
    'operations',
    'management',
    $fgnotif$Rapport ingediend$fgnotif$,
    $fgnotif${{personnel.name}} heeft een rapport ingediend voor {{assignment.number}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw rapport ingediend voor {{assignment.number}}$fgnotif$,
    $fgnotif$Er is een nieuw rapport ingediend.$fgnotif$,
    $fgnotif$<p>Er is een nieuw rapport ingediend.</p><p>Opdracht: {{assignment.number}}<br>Object: {{object.name}}<br>Medewerker: {{personnel.name}}</p><p>Controleer het rapport voordat het klantzichtbaar of factureerbaar wordt.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Rapport bekijken</a></p>$fgnotif$,
    $fgnotif$Rapport ingediend$fgnotif$,
    $fgnotif${{personnel.name}} heeft een rapport ingediend voor {{assignment.number}}.$fgnotif$,
    '["assignment.number","object.name","personnel.name","href"]'::jsonb
  ),
  (
    'roadmap_comment_added',
    'knowledgebase',
    'mixed',
    $fgnotif$Nieuwe reactie op roadmapitem$fgnotif$,
    $fgnotif$Er is gereageerd op {{roadmap.title}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe reactie op roadmapitem$fgnotif$,
    $fgnotif$Er is een nieuwe update in Fieldgrid.$fgnotif$,
    $fgnotif$<p>Er is een nieuwe reactie geplaatst bij:</p><p>{{roadmap.title}}</p><p>Reactie:<br>{{comment.body}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Roadmapitem openen</a></p>$fgnotif$,
    $fgnotif$Nieuwe reactie op roadmapitem$fgnotif$,
    $fgnotif$Er is gereageerd op {{roadmap.title}}.$fgnotif$,
    '["roadmap.title","comment.body","href"]'::jsonb
  ),
  (
    'roadmap_item_done',
    'knowledgebase',
    'mixed',
    $fgnotif$Roadmapitem afgerond$fgnotif$,
    $fgnotif${{roadmap.title}} is afgerond.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Roadmapitem afgerond: {{roadmap.title}}$fgnotif$,
    $fgnotif$Goed nieuws: het volgende roadmapitem is afgerond.$fgnotif$,
    $fgnotif$<p>Goed nieuws: het volgende roadmapitem is afgerond.</p><p>{{roadmap.title}}</p><p>U kunt het item bekijken in Fieldgrid.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Roadmapitem bekijken</a></p>$fgnotif$,
    $fgnotif$Roadmapitem afgerond$fgnotif$,
    $fgnotif${{roadmap.title}} is afgerond.$fgnotif$,
    '["roadmap.title","href"]'::jsonb
  ),
  (
    'roadmap_request_submitted',
    'knowledgebase',
    'management',
    $fgnotif$Nieuwe roadmapwens$fgnotif$,
    $fgnotif${{roadmap.title}}$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuwe wens ingediend: {{roadmap.title}}$fgnotif$,
    $fgnotif$Er is een nieuwe wens ingediend voor de roadmap.$fgnotif$,
    $fgnotif$<p>Er is een nieuwe wens ingediend voor de roadmap.</p><p>Wens: {{roadmap.title}}<br>Prioriteit: {{roadmap.priority}}</p><p>Bekijk de wens en bepaal de vervolgstap.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Roadmapitem openen</a></p>$fgnotif$,
    $fgnotif$Nieuwe roadmapwens$fgnotif$,
    $fgnotif${{roadmap.title}}$fgnotif$,
    '["roadmap.title","roadmap.priority","href"]'::jsonb
  ),
  (
    'roadmap_status_changed',
    'knowledgebase',
    'mixed',
    $fgnotif$Roadmap bijgewerkt$fgnotif$,
    $fgnotif${{roadmap.title}} is verplaatst naar {{roadmap.to_status}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Status gewijzigd: {{roadmap.title}}$fgnotif$,
    $fgnotif$De status van een roadmapitem is gewijzigd.$fgnotif$,
    $fgnotif$<p>De status van een roadmapitem is gewijzigd.</p><p>Item: {{roadmap.title}}<br>Van: {{roadmap.from_status}}<br>Naar: {{roadmap.to_status}}</p><p>{{roadmap.note}}</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Roadmapitem bekijken</a></p>$fgnotif$,
    $fgnotif$Roadmap bijgewerkt$fgnotif$,
    $fgnotif${{roadmap.title}} is verplaatst naar {{roadmap.to_status}}.$fgnotif$,
    '["roadmap.title","roadmap.from_status","roadmap.to_status","roadmap.note","href"]'::jsonb
  ),
  (
    'support_access_expired',
    'platform',
    'management',
    $fgnotif$Supporttoegang verlopen$fgnotif$,
    $fgnotif$De tijdelijke supporttoegang voor {{support.name}} is verlopen.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Supporttoegang verlopen$fgnotif$,
    $fgnotif$De tijdelijke supporttoegang voor {{support.name}} is verlopen.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>De tijdelijke supporttoegang voor {{support.name}} is verlopen.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Openen in Fieldgrid</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Supporttoegang verlopen$fgnotif$,
    $fgnotif$De tijdelijke supporttoegang voor {{support.name}} is verlopen.$fgnotif$,
    '["support.name","recipient.name","href","organization.name"]'::jsonb
  ),
  (
    'support_access_granted',
    'platform',
    'management',
    $fgnotif$Tijdelijke supporttoegang actief$fgnotif$,
    $fgnotif$Supporttoegang is actief tot {{support.expires_at}}.$fgnotif$,
    true,
    false,
    true,
    $fgnotif$Tijdelijke supporttoegang gestart$fgnotif$,
    $fgnotif$Er is tijdelijke supporttoegang gestart voor uw organisatieomgeving in Fieldgrid.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is tijdelijke supporttoegang gestart voor uw organisatieomgeving in Fieldgrid.</p><p>Supportmedewerker: {{support.name}}<br>Geldig tot: {{support.expires_at}}<br>Reden: {{support.reason}}</p><p>Deze toegang is tijdelijk en wordt vastgelegd in het activiteitenlog.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Supporttoegang bekijken</a></p><p>Met vriendelijke groet,<br>Fieldgrid</p>$fgnotif$,
    $fgnotif$Tijdelijke supporttoegang actief$fgnotif$,
    $fgnotif$Supporttoegang is actief tot {{support.expires_at}}.$fgnotif$,
    '["support.expires_at","recipient.name","support.name","support.reason","href"]'::jsonb
  ),
  (
    'ticket_created_customer_backoffice',
    'communication',
    'management',
    $fgnotif$Nieuw klantticket$fgnotif$,
    $fgnotif${{customer.name}} heeft een ticket aangemaakt: {{ticket.subject}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw klantticket: {{ticket.subject}}$fgnotif$,
    $fgnotif$Er is een nieuw ticket aangemaakt door {{customer.name}}.$fgnotif$,
    $fgnotif$<p>Er is een nieuw ticket aangemaakt door {{customer.name}}.</p><p>Onderwerp: {{ticket.subject}}<br>Ticket: {{ticket.number}}<br>Object: {{object.name}}</p><p>Bekijk het ticket en reageer via Fieldgrid.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p>$fgnotif$,
    $fgnotif$Nieuw klantticket$fgnotif$,
    $fgnotif${{customer.name}} heeft een ticket aangemaakt: {{ticket.subject}}.$fgnotif$,
    '["customer.name","object.name","ticket.number","ticket.subject","href"]'::jsonb
  ),
  (
    'ticket_created_personnel_backoffice',
    'communication',
    'management',
    $fgnotif$Nieuw personeelsticket$fgnotif$,
    $fgnotif${{personnel.name}} heeft een ticket aangemaakt: {{ticket.subject}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Nieuw personeelsticket: {{ticket.subject}}$fgnotif$,
    $fgnotif${{personnel.name}} heeft een nieuw ticket aangemaakt.$fgnotif$,
    $fgnotif$<p>{{personnel.name}} heeft een nieuw ticket aangemaakt.</p><p>Onderwerp: {{ticket.subject}}<br>Ticket: {{ticket.number}}</p><p>Bekijk het ticket en reageer via Fieldgrid.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p>$fgnotif$,
    $fgnotif$Nieuw personeelsticket$fgnotif$,
    $fgnotif${{personnel.name}} heeft een ticket aangemaakt: {{ticket.subject}}.$fgnotif$,
    '["personnel.name","ticket.number","ticket.subject","href"]'::jsonb
  ),
  (
    'ticket_reply_customer',
    'communication',
    'customer',
    $fgnotif$Nieuwe ticketreactie$fgnotif$,
    $fgnotif$Er is gereageerd op ticket {{ticket.number}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Reactie op uw ticket: {{ticket.subject}}$fgnotif$,
    $fgnotif$Er is een reactie geplaatst op uw ticket.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een reactie geplaatst op uw ticket.</p><p>Ticket: {{ticket.number}}<br>Onderwerp: {{ticket.subject}}</p><p>U kunt de reactie bekijken en beantwoorden in het klantenportaal.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Reactie op ticket$fgnotif$,
    $fgnotif$Bekijk de reactie op {{ticket.subject}}.$fgnotif$,
    '["recipient.name","organization.name","ticket.number","ticket.subject","href"]'::jsonb
  ),
  (
    'ticket_reply_personnel',
    'communication',
    'personnel',
    $fgnotif$Nieuwe ticketreactie$fgnotif$,
    $fgnotif$Er is gereageerd op ticket {{ticket.number}}.$fgnotif$,
    false,
    false,
    true,
    $fgnotif$Reactie op uw ticket: {{ticket.subject}}$fgnotif$,
    $fgnotif$Er is een reactie geplaatst op uw ticket.$fgnotif$,
    $fgnotif$<p>Beste {{recipient.name}},</p><p>Er is een reactie geplaatst op uw ticket.</p><p>Ticket: {{ticket.number}}<br>Onderwerp: {{ticket.subject}}</p><p>U kunt de reactie bekijken en beantwoorden in de personeelsapp.</p><p><a href="{{href}}" style="color:#0f766e;text-decoration:underline">Ticket openen</a></p><p>Met vriendelijke groet,<br>{{organization.name}}</p>$fgnotif$,
    $fgnotif$Reactie op ticket$fgnotif$,
    $fgnotif$Bekijk de reactie in de personeelsapp.$fgnotif$,
    '["recipient.name","organization.name","ticket.number","ticket.subject","href"]'::jsonb
  )
ON CONFLICT (event_key) DO UPDATE SET
  event_group = EXCLUDED.event_group,
  audience = EXCLUDED.audience,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  email_enabled = EXCLUDED.email_enabled,
  push_enabled = EXCLUDED.push_enabled,
  in_app_enabled = EXCLUDED.in_app_enabled,
  email_subject = EXCLUDED.email_subject,
  email_preheader = EXCLUDED.email_preheader,
  email_body = EXCLUDED.email_body,
  push_title = EXCLUDED.push_title,
  push_body = EXCLUDED.push_body,
  shortcodes = EXCLUDED.shortcodes,
  updated_at = now();
