-- ============================================================================
-- Bind cross-system authorization activation to opaque reservation tokens.
--
-- PostgreSQL timestamps retain microseconds while JavaScript Date values retain
-- milliseconds. They therefore cannot safely serve as compare-and-set tokens
-- across the Auth finalization boundary. These nullable UUIDs are generated by
-- PostgreSQL, replaced whenever the same flow reclaims an interrupted invite,
-- and cleared atomically when authorization becomes active.
--
-- Existing tenant invitation sources are assigned a token so their creating
-- flow can reclaim them. Existing platform users and personnel rows remain
-- unattributed. Rollback is forward-only: retain the columns and constraints;
-- removing them would re-open stale or cross-flow activation.
-- ============================================================================

DO $fieldgrid_invitation_reservation_prerequisites$
BEGIN
  IF pg_catalog.to_regclass('public.tenant_users') IS NULL
     OR pg_catalog.to_regclass('public.platform_users') IS NULL
     OR pg_catalog.to_regclass('public.personnel') IS NULL THEN
    RAISE EXCEPTION
      'tenant_users, platform_users and personnel must exist before reservation tokens are added';
  END IF;

  IF NOT EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint AS constraint_row
     WHERE constraint_row.conrelid = 'public.tenant_users'::regclass
       AND constraint_row.conname =
         'tenant_users_invitation_source_state_check'
       AND constraint_row.contype = 'c'
       AND constraint_row.convalidated IS TRUE
  ) THEN
    RAISE EXCEPTION
      'tenant invitation source contract must precede reservation tokens';
  END IF;

  IF EXISTS (
    SELECT 1
      FROM pg_catalog.pg_attribute AS attribute_row
     WHERE attribute_row.attrelid IN (
             'public.tenant_users'::regclass,
             'public.platform_users'::regclass,
             'public.personnel'::regclass
           )
       AND attribute_row.attname IN (
             'invitation_source',
             'invitation_reservation_id'
           )
       AND attribute_row.attnum > 0
       AND attribute_row.attisdropped IS FALSE
       AND NOT (
         attribute_row.attrelid = 'public.tenant_users'::regclass
         AND attribute_row.attname = 'invitation_source'
       )
  ) OR EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint AS constraint_row
     WHERE constraint_row.conname IN (
             'tenant_users_invitation_reservation_check',
             'platform_users_invitation_reservation_check',
             'personnel_invitation_reservation_check'
           )
       AND constraint_row.conrelid IN (
             'public.tenant_users'::regclass,
             'public.platform_users'::regclass,
             'public.personnel'::regclass
           )
  ) THEN
    RAISE EXCEPTION
      'authorization invitation reservation contract already exists outside migration history';
  END IF;
END;
$fieldgrid_invitation_reservation_prerequisites$;

LOCK TABLE
  public.tenant_users,
  public.platform_users,
  public.personnel
IN ACCESS EXCLUSIVE MODE;

ALTER TABLE public.tenant_users
  ADD COLUMN invitation_reservation_id uuid;

ALTER TABLE public.platform_users
  ADD COLUMN invitation_source varchar(64),
  ADD COLUMN invitation_reservation_id uuid;

ALTER TABLE public.personnel
  ADD COLUMN invitation_reservation_id uuid;

UPDATE public.tenant_users
   SET invitation_reservation_id = gen_random_uuid()
 WHERE invitation_source IS NOT NULL;

ALTER TABLE public.tenant_users
  ADD CONSTRAINT tenant_users_invitation_reservation_check
  CHECK (
    (invitation_source IS NULL AND invitation_reservation_id IS NULL)
    OR (
      invitation_source IS NOT NULL
      AND invitation_reservation_id IS NOT NULL
    )
  );

ALTER TABLE public.platform_users
  ADD CONSTRAINT platform_users_invitation_reservation_check
  CHECK (
    (invitation_source IS NULL AND invitation_reservation_id IS NULL)
    OR (
      invitation_source = 'platform_user_invite'
      AND invitation_reservation_id IS NOT NULL
      AND status = 'inactive'
    )
  );

ALTER TABLE public.personnel
  ADD CONSTRAINT personnel_invitation_reservation_check
  CHECK (
    invitation_reservation_id IS NULL
    OR (
      user_id IS NULL
      AND invite_sent_at IS NOT NULL
    )
  );

COMMENT ON COLUMN public.tenant_users.invitation_reservation_id IS
  'Opaque owner token for an invited tenant authorization; replaced on reclaim and cleared on activation.';
COMMENT ON COLUMN public.platform_users.invitation_source IS
  'Durable owner of an inactive platform authorization reservation; cleared on activation.';
COMMENT ON COLUMN public.platform_users.invitation_reservation_id IS
  'Opaque owner token for an inactive platform authorization; replaced on reclaim and cleared on activation.';
COMMENT ON COLUMN public.personnel.invitation_reservation_id IS
  'Opaque owner token for a personnel Auth link; cleared atomically when user_id is linked.';

DO $fieldgrid_invitation_reservation_closure$
DECLARE
  exact_uuid_column_count integer;
  exact_platform_source_count integer;
  exact_constraint_count integer;
  tenant_constraint_definition text;
  platform_constraint_definition text;
  personnel_constraint_definition text;
BEGIN
  SELECT COUNT(*)::integer
    INTO exact_uuid_column_count
    FROM pg_catalog.pg_attribute AS attribute_row
    JOIN pg_catalog.pg_type AS type_row
      ON type_row.oid = attribute_row.atttypid
   WHERE (attribute_row.attrelid, attribute_row.attname) IN (
           ('public.tenant_users'::regclass, 'invitation_reservation_id'),
           ('public.platform_users'::regclass, 'invitation_reservation_id'),
           ('public.personnel'::regclass, 'invitation_reservation_id')
         )
     AND attribute_row.attnum > 0
     AND attribute_row.attisdropped IS FALSE
     AND attribute_row.attnotnull IS FALSE
     AND attribute_row.atthasdef IS FALSE
     AND type_row.typname = 'uuid';

  SELECT COUNT(*)::integer
    INTO exact_platform_source_count
    FROM pg_catalog.pg_attribute AS attribute_row
    JOIN pg_catalog.pg_type AS type_row
      ON type_row.oid = attribute_row.atttypid
   WHERE attribute_row.attrelid = 'public.platform_users'::regclass
     AND attribute_row.attname = 'invitation_source'
     AND attribute_row.attnum > 0
     AND attribute_row.attisdropped IS FALSE
     AND attribute_row.attnotnull IS FALSE
     AND attribute_row.atthasdef IS FALSE
     AND type_row.typname = 'varchar'
     AND attribute_row.atttypmod = 68;

  SELECT COUNT(*)::integer,
         pg_catalog.max(
           CASE WHEN constraint_row.conname =
             'tenant_users_invitation_reservation_check'
           THEN pg_catalog.pg_get_constraintdef(constraint_row.oid, true) END
         ),
         pg_catalog.max(
           CASE WHEN constraint_row.conname =
             'platform_users_invitation_reservation_check'
           THEN pg_catalog.pg_get_constraintdef(constraint_row.oid, true) END
         ),
         pg_catalog.max(
           CASE WHEN constraint_row.conname =
             'personnel_invitation_reservation_check'
           THEN pg_catalog.pg_get_constraintdef(constraint_row.oid, true) END
         )
    INTO exact_constraint_count,
         tenant_constraint_definition,
         platform_constraint_definition,
         personnel_constraint_definition
    FROM pg_catalog.pg_constraint AS constraint_row
   WHERE (constraint_row.conrelid, constraint_row.conname) IN (
           (
             'public.tenant_users'::regclass,
             'tenant_users_invitation_reservation_check'
           ),
           (
             'public.platform_users'::regclass,
             'platform_users_invitation_reservation_check'
           ),
           (
             'public.personnel'::regclass,
             'personnel_invitation_reservation_check'
           )
         )
     AND constraint_row.contype = 'c'
     AND constraint_row.convalidated IS TRUE;

  IF exact_uuid_column_count <> 3
     OR exact_platform_source_count <> 1
     OR exact_constraint_count <> 3
     OR tenant_constraint_definition IS NULL
     OR platform_constraint_definition IS NULL
     OR personnel_constraint_definition IS NULL
     OR pg_catalog.strpos(
          tenant_constraint_definition,
          'invitation_reservation_id'
        ) = 0
     OR pg_catalog.strpos(platform_constraint_definition, 'platform_user_invite') = 0
     OR pg_catalog.strpos(platform_constraint_definition, 'inactive') = 0
     OR pg_catalog.strpos(personnel_constraint_definition, 'user_id IS NULL') = 0
     OR pg_catalog.strpos(personnel_constraint_definition, 'invite_sent_at IS NOT NULL') = 0 THEN
    RAISE EXCEPTION 'authorization invitation reservation contract is not exact';
  END IF;

  IF EXISTS (
    SELECT 1
      FROM public.tenant_users AS tenant_user
     WHERE (tenant_user.invitation_source IS NULL) <>
           (tenant_user.invitation_reservation_id IS NULL)
  ) OR EXISTS (
    SELECT 1
      FROM public.platform_users AS platform_user
     WHERE platform_user.invitation_source IS NOT NULL
        OR platform_user.invitation_reservation_id IS NOT NULL
  ) OR EXISTS (
    SELECT 1
      FROM public.personnel AS personnel_row
     WHERE personnel_row.invitation_reservation_id IS NOT NULL
  ) THEN
    RAISE EXCEPTION 'authorization invitation reservation backfill is not exact';
  END IF;
END;
$fieldgrid_invitation_reservation_closure$;
