import {
  Activity,
  Archive,
  Bell,
  BookOpen,
  Boxes,
  Building2,
  Calendar,
  CalendarClock,
  ClipboardList,
  CreditCard,
  FileCheck2,
  FileText,
  FolderOpen,
  Globe2,
  LayoutDashboard,
  Lightbulb,
  Megaphone,
  PackageSearch,
  Rocket,
  Settings,
  ShieldCheck,
  Ticket,
  UserCog,
  Users,
  type LucideIcon,
} from "lucide-react";

import type { FieldgridRouteIcon } from "./route-registry";

export const FIELDGRID_ROUTE_ICONS: Record<FieldgridRouteIcon, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  bell: Bell,
  book: BookOpen,
  boxes: Boxes,
  building: Building2,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  clipboard: ClipboardList,
  "credit-card": CreditCard,
  dashboard: LayoutDashboard,
  "file-check": FileCheck2,
  "file-text": FileText,
  folder: FolderOpen,
  globe: Globe2,
  lightbulb: Lightbulb,
  megaphone: Megaphone,
  "package-search": PackageSearch,
  rocket: Rocket,
  settings: Settings,
  shield: ShieldCheck,
  ticket: Ticket,
  "user-cog": UserCog,
  users: Users,
};
