"use client";
import { useEffect, useRef, useState, useTransition } from "react";
import Link from "next/link";
import { Plus, Pencil, Archive, RotateCcw, Search, ArrowDownAZ } from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import type { TenantContext } from "@/lib/auth/context";
import type { WorkspaceData } from "@/lib/data/workspace";
import { loadTaskCatalogue, saveTaskCatalogue, type CatalogueCommand } from "@/lib/tasks/actions";
import type { CatalogueTask, TaskCatalogueData, TaskCategory } from "@/lib/tasks/model";
import { allowExtraWork } from "@/app/app/operations-actions";
import { ActionIcon } from "../action-icon";
import { EmptyState } from "../empty-state";
import { ContentTabs } from "../content-tabs";
import { PageHeading } from "../page-heading";
import { ListPagination, useListPagination } from "../list-pagination";
import { WorkOrderDialog } from "../work-orders/dialog";
import "./catalogue.css";

const euro=(value:number)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"}).format(value/100);
export function TaskCatalogue({tenant,workspace}:{tenant:TenantContext;workspace:WorkspaceData}) {
 const router=useRouter(),[data,setData]=useState<TaskCatalogueData|null>(null),[error,setError]=useState(""),[pending,start]=useTransition(),[search,setSearch]=useState("");
 const [tab,setTab]=useState("taken");
 const [taskSort,setTaskSort]=useState({field:"name",direction:1});
 const [categorySort,setCategorySort]=useState({field:"name",direction:1});
 const [dialog,setDialog]=useState<"task"|"category"|null>(null),[task,setTask]=useState<CatalogueTask|null>(null),[category,setCategory]=useState<TaskCategory|null>(null);
 const load=async()=>{const result=await loadTaskCatalogue();if(result.ok){setData(result.data);setError("");}else setError(result.error);};
 useEffect(()=>{let active=true;void loadTaskCatalogue().then(result=>{if(!active)return;if(result.ok)setData(result.data);else setError(result.error);});return()=>{active=false;};},[tenant.id]);
 const openTask=(value:CatalogueTask|null)=>{setTask(value);setDialog("task");};const openCategory=(value:TaskCategory|null)=>{setCategory(value);setDialog("category");};
 const run=(input:CatalogueCommand)=>start(async()=>{const result=await saveTaskCatalogue({...input,mutationId:crypto.randomUUID()});if(!result.ok){setError(result.error);return;}toast.success("Opgeslagen");await load();router.refresh();});
 const canManage=tenant.roles.some(role=>["tenant_admin","management","planner"].includes(role));
 const tasks=(data?.tasks.filter(t=>`${t.code} ${t.name} ${t.discipline}`.toLowerCase().includes(search.toLowerCase()))??[]).sort((a,b)=>{
  const value=(t:CatalogueTask):string|number=>taskSort.field==="category"?data?.categories.find(c=>c.id===t.categoryId)?.name??"":taskSort.field==="duration"?t.duration??0:taskSort.field==="price"?t.priceCents??0:taskSort.field==="active"?Number(t.active):t.name;
  const left=value(a),right=value(b);return (typeof left==="number"&&typeof right==="number"?left-right:String(left).localeCompare(String(right),"nl",{numeric:true}))*taskSort.direction;
 });
 const categoriesRows=(data?.categories.filter(c=>`${c.name} ${c.prefix}`.toLowerCase().includes(search.toLowerCase()))??[]).sort((a,b)=>{
  const value=(c:TaskCategory):string|number=>categorySort.field==="prefix"?c.prefix:categorySort.field==="next"?c.next_number:categorySort.field==="active"?Number(c.active):c.name;
  const left=value(a),right=value(b);return (typeof left==="number"&&typeof right==="number"?left-right:String(left).localeCompare(String(right),"nl",{numeric:true}))*categorySort.direction;
 });
 const taskPages=useListPagination(tasks), categoryPages=useListPagination(categoriesRows);
 const taskFields:Record<string,string>={"Code & taak":"name",Categorie:"category",Duur:"duration",Tarief:"price",Status:"active"};
 const categoryFields:Record<string,string>={Categorie:"name",Prefix:"prefix","Volgende code":"next",Status:"active"};
 const sortHead=(label:string,category=false)=>{const field=(category?categoryFields:taskFields)[label],sort=category?categorySort:taskSort;return <th key={label} scope="col" aria-sort={field?sort.field===field?sort.direction===1?"ascending":"descending":"none":undefined}>{field?<button onClick={()=>{(category?setCategorySort:setTaskSort)(current=>({field,direction:current.field===field?-current.direction:1}));(category?categoryPages:taskPages).setPage(1);}}>{label}<ArrowDownAZ size={13}/></button>:label}</th>;};
 const taskList=<><section className="panel resource-table-panel" aria-label="Taken"><div className="table-scroll"><table className="resource-table"><thead><tr>{["Code & taak","Categorie","Duur",...(data?.finance?["Tarief"]:[]),"Afspraken","Status","Acties"].map(label=>sortHead(label))}</tr></thead><tbody>{taskPages.items.map(t=><tr key={t.id}><td>{canManage?<button className="text-link" onClick={()=>openTask(t)}><strong>{t.name}</strong></button>:t.name}<small>{t.code} · {t.discipline}</small>{t.description&&<small>{t.description}</small>}</td><td>{data?.categories.find(c=>c.id===t.categoryId)?.name??"Zonder categorie"}</td><td>{t.duration??"—"} min</td>{data?.finance&&<td>{typeof t.priceCents==="number"?euro(t.priceCents):"—"}</td>}<td><div className="catalogue-tags">{t.extraWork&&<span>Meerwerk</span>}{t.requiresSignature&&<span>Handtekening</span>}{t.requiresPhoto&&<span>Foto</span>}{!t.extraWork&&!t.requiresSignature&&!t.requiresPhoto&&"Standaard"}</div></td><td><span className="resource-status">{t.active?"Actief":"Gearchiveerd"}</span></td><td><div className="catalogue-row-actions"><ActionIcon className="resource-action" label="Bewerk" title={`Bewerk ${t.name}`} icon={<Pencil size={14}/>} disabled={!canManage} onClick={()=>openTask(t)}/><ActionIcon className="resource-action" label={t.active?"Archiveer":"Activeer"} title={`${t.active?"Archiveer":"Activeer"} ${t.name}`} icon={t.active?<Archive size={14}/>:<RotateCcw size={14}/>} disabled={pending||!canManage} onClick={()=>run({action:"task_active",id:t.id,version:t.version,active:!t.active})}/></div></td></tr>)}</tbody></table></div>{data&&!tasks.length&&<EmptyState title={search?"Geen taken voor deze zoekopdracht":"Nog geen taken"} description={search?"Pas je zoekopdracht aan om andere taken te vinden.":"Gebruik de plusknop bovenaan om de eerste taak toe te voegen."}/>}</section><ListPagination total={taskPages.total} page={taskPages.page} pageSize={taskPages.pageSize} onPageChange={taskPages.setPage} onPageSizeChange={taskPages.setPageSize} noun="taken" preferenceKey={`backoffice:${tenant.id}:tasks`}/></>;
 const categories=<><section className="panel resource-table-panel" aria-label="Categorieën"><div className="table-scroll"><table className="resource-table"><thead><tr>{["Categorie","Prefix","Volgende code","Status","Acties"].map(label=>sortHead(label,true))}</tr></thead><tbody>{categoryPages.items.map(c=><tr key={c.id}><td>{canManage?<button className="text-link" onClick={()=>openCategory(c)}><strong>{c.name}</strong></button>:c.name}</td><td>{c.prefix}</td><td>{c.prefix}-{String(c.next_number).padStart(3,"0")}</td><td>{c.active?"Actief":"Gearchiveerd"}</td><td><div className="catalogue-row-actions"><ActionIcon className="resource-action" label="Bewerk" title={`Bewerk ${c.name}`} icon={<Pencil size={14}/>} disabled={!canManage} onClick={()=>openCategory(c)}/><ActionIcon className="resource-action" label={c.active?"Archiveer":"Activeer"} title={`${c.active?"Archiveer":"Activeer"} ${c.name}`} icon={c.active?<Archive size={14}/>:<RotateCcw size={14}/>} disabled={pending||!canManage} onClick={()=>run({action:"category_active",id:c.id,version:c.version,active:!c.active})}/></div></td></tr>)}</tbody></table></div>{data&&!categoriesRows.length&&<EmptyState title={search?"Geen categorieën voor deze zoekopdracht":"Nog geen categorieën"} description={search?"Pas je zoekopdracht aan om andere categorieën te vinden.":"Gebruik de plusknop bovenaan om de eerste categorie toe te voegen."}/>}</section><ListPagination total={categoryPages.total} page={categoryPages.page} pageSize={categoryPages.pageSize} onPageChange={categoryPages.setPage} onPageSizeChange={categoryPages.setPageSize} noun="categorieën" preferenceKey={`backoffice:${tenant.id}:task-categories`}/></>;
 const extraWork=<section className="panel catalogue-form-panel" aria-label="Meerwerk"><p className="form-note">Koppel een toegestane taakversie aan een concrete werkbon. De medewerker kan deze vervolgens als meerwerk toevoegen.</p><form className="workspace-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);start(async()=>{const result=await allowExtraWork(form);if(result.ok){toast.success("Meerwerk gekoppeld");router.refresh();}else setError(result.error);});}}><label>Werkbon<select aria-label="Werkbon" name="workOrderId" required defaultValue=""><option value="" disabled>Kies werkbon</option>{workspace.workOrders.filter(o=>!["invoice_ready","invoiced","cancelled","approved"].includes(o.status)).map(o=><option key={o.id} value={o.id}>{o.work_order_number}</option>)}</select></label><label>Meerwerktaak<select aria-label="Meerwerktaak" name="ruleId" required defaultValue=""><option value="" disabled>Kies meerwerk</option>{workspace.extraWorkRules.map(r=>{const revision=workspace.taskRevisions.find(v=>v.id===r.task_revision_id);const t=workspace.tasks.find(t=>t.id===revision?.task_id);return <option key={r.id} value={r.id}>{t?.code} · {t?.name}{revision?.valid_until?" · eerdere versie":""}</option>;})}</select></label><div className="catalogue-form-actions wide"><button className="primary-button" disabled={pending||!canManage}>Meerwerk koppelen</button></div></form></section>;
 const add=()=>{if(tab==="categorieen"||!data?.categories.some(c=>c.active)){openCategory(null);return;}openTask(null);};
 return <div className="task-catalogue"><PageHeading eyebrow="CATALOGUS" title="Taken & tarieven" help="Beheer taken, categorieën en versievaste afspraken voor planning en facturatie." actions={<div className="catalogue-search-actions">{["taken","categorieen"].includes(tab)&&<><label className="page-list-search"><Search size={16}/><input type="search" aria-label="Taken en categorieën zoeken" value={search} onChange={e=>{setSearch(e.target.value);taskPages.setPage(1);categoryPages.setPage(1);}} placeholder={tab==="taken"?"Code, taak of discipline…":"Categorie of prefix…"}/></label><ActionIcon className="primary-button" label="Voeg toe" title={tab==="categorieen"?"Nieuwe categorie":"Nieuwe taak"} icon={<Plus size={16}/>} disabled={!canManage||!data} onClick={add}/></>}{tab==="templates"&&<Link className="primary-button" href="/app/taken/templates">Templates beheren</Link>}</div>}/>{error&&<p className="wo-error" role="alert">{error}<button className="text-link" onClick={()=>void load()}>Vernieuw</button></p>}{!data&&!error&&<p role="status">Taken laden…</p>}<ContentTabs label="Taakbeheer" value={tab} onValueChange={setTab} tabs={[{id:"taken",title:"Taken",content:taskList},{id:"categorieen",title:"Categorieën",content:categories},...(tenant.enabledServices.includes("rapportage")?[{id:"meerwerk",title:"Meerwerk",content:extraWork}]:[]),{id:"templates",title:"Templates",content:<section className="panel catalogue-form-panel" aria-label="Templates"><p className="form-note">Beheer werkbon- en checklisttemplates voor terugkerende werkzaamheden. Leg taken, bezetting en controles vast in herbruikbare, versievaste templates.</p><Link className="secondary-button" href="/app/taken/templates">Werkbon- en checklisttemplates openen</Link></section>}]} />{dialog&&data&&<CatalogueDialog key={`${dialog}:${task?.id??category?.id??"new"}`} kind={dialog} task={task} category={category} data={data} tenant={tenant} onClose={()=>setDialog(null)} onSaved={async()=>{setDialog(null);await load();router.refresh();}}/>}</div>;
}

function CatalogueDialog({kind,task,category,data,tenant,onClose,onSaved}:{kind:"task"|"category";task:CatalogueTask|null;category:TaskCategory|null;data:TaskCatalogueData;tenant:TenantContext;onClose:()=>void;onSaved:()=>Promise<void>}) {
 const[step,setStep]=useState(0),[dirty,setDirty]=useState(false),[error,setError]=useState(""),[pending,start]=useTransition(),[categoryId,setCategoryId]=useState(task?.categoryId??data.categories.find(c=>c.active)?.id??"");
 const mutation=useRef(crypto.randomUUID()),form=useRef<HTMLFormElement>(null);
 const catalogueCategory=data.categories.find(c=>c.id===categoryId),reporting=tenant.enabledServices.includes("rapportage");
 const submit=()=>{if(!form.current?.reportValidity())return;const values=new FormData(form.current);let input:CatalogueCommand;
  if(kind==="category")input={action:"category_save",...(category?{id:category.id,version:category.version}:{}),name:String(values.get("name")),prefix:String(values.get("prefix"))};
  else input={action:"task_save",...(task?{id:task.id,version:task.version}:{}),...(categoryId?{categoryId}:{}),name:String(values.get("name")),description:String(values.get("description")),discipline:String(values.get("discipline")),duration:Number(values.get("duration")),...(!task||data.finance?{priceCents:Math.round(Number(values.get("price"))*100),vatBasisPoints:Math.round(Number(values.get("vat"))*100)}:{}),extraWork:values.get("extraWork")==="on",requiresPhoto:values.get("requiresPhoto")==="on",requiresSignature:values.get("requiresSignature")==="on"};
  start(async()=>{const result=await saveTaskCatalogue({...input,mutationId:mutation.current});if(!result.ok){setError(result.error);return;}toast.success(kind==="category"?"Categorie opgeslagen":"Taak opgeslagen");await onSaved();});
 };
 return <WorkOrderDialog eyebrow="CATALOGUS" title={kind==="category"?(category?"Categorie bewerken":"Nieuwe taakcategorie"):(task?"Taak bewerken":"Nieuwe taak")} description={kind==="category"?"Kies een naam en prefix voor automatische taaknummering.":task?`${task.code} · nieuwe taakversie`:"De taakcode volgt automatisch uit de categorie."} tenant={tenant} dirty={dirty} busy={pending} onClose={onClose}>
 {kind==="task"&&<ol className="catalogue-steps" aria-label="Taakwizard"><li aria-current={step===0?"step":undefined}>1 · Taak & tarief</li><li aria-current={step===1?"step":undefined}>2 · Uitvoering & bewijs</li></ol>}
 <form ref={form} id="catalogue-edit" className="wo-dialog-body wo-form catalogue-form" onSubmit={e=>{e.preventDefault();if(kind==="task"&&step===0){setStep(1);return;}submit();}} onChange={()=>{setDirty(true);mutation.current=crypto.randomUUID();}}>
  {kind==="category"?<><label>Naam<input name="name" required minLength={2} maxLength={120} defaultValue={category?.name}/></label><label>Prefix<input name="prefix" required maxLength={12} pattern="[A-Za-z0-9][A-Za-z0-9-]{0,11}" placeholder="SCH" defaultValue={category?.prefix}/></label><p className="wide">Nieuwe taken worden genummerd als PREFIX-001, PREFIX-002, enzovoort.</p></>:<><div hidden={step!==0} className="catalogue-step-fields"><label>Categorie<select aria-label="Categorie" required={!task} value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{task&&!task.categoryId&&<option value="">Zonder categorie</option>}{data.categories.filter(c=>c.active||c.id===task?.categoryId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Taakcode<input readOnly value={task?.code??(catalogueCategory?`${catalogueCategory.prefix}-${String(catalogueCategory.next_number).padStart(3,"0")} (verwacht)` : "Kies een categorie")}/></label><label>Naam<input name="name" required minLength={2} maxLength={180} defaultValue={task?.name}/></label><label>Discipline<input name="discipline" required minLength={2} maxLength={100} defaultValue={task?.discipline}/></label><label>Duur (minuten)<input name="duration" type="number" required min={1} max={1440} defaultValue={task?.duration??60}/></label>{(!task||data.finance)&&<><label>Prijs excl. btw<input name="price" type="number" required step="0.01" min={0} defaultValue={task?.priceCents===undefined?"":task.priceCents/100}/></label><label>Btw %<input name="vat" type="number" required step="0.01" min={0} max={100} defaultValue={task?.vatBasisPoints===undefined?21:task.vatBasisPoints/100}/></label></>}<label className="wide">Beschrijving<textarea name="description" maxLength={3000} rows={3} defaultValue={task?.description??""}/></label></div><div hidden={step!==1} className="catalogue-step-fields"><h3 className="wide">Afspraken voor deze taak</h3><label className="catalogue-check wide"><input name="extraWork" type="checkbox" disabled={!reporting} defaultChecked={task?.extraWork}/>Mag als meerwerk worden aangeboden</label><label className="catalogue-check wide"><input name="requiresSignature" type="checkbox" disabled={!reporting} defaultChecked={task?.requiresSignature}/>Klant moet het opleverrapport ondertekenen</label><label className="catalogue-check wide"><input name="requiresPhoto" type="checkbox" disabled={!reporting} defaultChecked={task?.requiresPhoto}/>Foto van de werkzaamheden verplicht</label><p className="wide">Deze afspraken volgen de taakversie op de werkbon. Meerwerk blijft afzonderlijk ter beoordeling.</p>{!reporting&&<p className="wide">Schakel Rapportage in om meerwerk en bewijsafspraken te gebruiken.</p>}</div></>}
 {error&&<p className="wo-error wide" role="alert">{error}</p>}
 </form><footer className="wizard-footer"><button type="button" className="secondary-button" disabled={pending} onClick={kind==="task"&&step===1?()=>setStep(0):()=>{if(!dirty||window.confirm("Je wijzigingen zijn nog niet opgeslagen. Wil je ze weggooien?"))onClose();}}>{kind==="task"&&step===1?"Vorige":"Annuleren"}</button><button type="submit" form="catalogue-edit" className="primary-button" disabled={pending}>{pending?"Opslaan…":kind==="task"&&step===0?"Volgende":"Opslaan"}</button></footer>
 </WorkOrderDialog>;
}
