kind = "web"
previewPath = "/"
title = "Veele Backoffice"
version = "1.0.0"
id = "artifacts/backoffice"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22138

[services.development]
run = "pnpm --filter @workspace/backoffice run dev"

[services.production.build]
args = [ "pnpm", "--filter", "@workspace/backoffice", "run", "build" ]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = [ "pnpm", "--filter", "@workspace/backoffice", "run", "start" ]

[services.production.run.env]
PORT = "22138"
NODE_ENV = "production"

[services.env]
PORT = "22138"
BASE_PATH = "/"
