import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  timestamp,
  integer,
  numeric,
  bigint,
  jsonb,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { customersTable } from "./customers";
import { objectsTable } from "./objects";
import { personnelTable } from "./personnel";
import { taskCodesTable, tenantTaskCodePricesTable, tenantTaskCodesTable } from "./task-codes";
import { tenantsTable } from "./tenants";

// ─── Status & Priority enums ───────────────────────────────────────────────────

export const ASSIGNMENT_STATUSES = [
  "requested",
  "review",
  "quote_preparation",
  "awaiting_approval",
  "approved",
  "plannable",
  "scheduled",
  "seen",
  "en_route",
  "in_progress",
  "not_completed",
  "completed",
  "report_submitted",
  "report_approved",
  "invoice_ready",
  "invoiced",
  "paid",
  "closed",
  "cancelled",
] as const;

export type AssignmentStatus = (typeof ASSIGNMENT_STATUSES)[number];

export const ASSIGNMENT_PRIORITIES = ["low", "normal", "high", "urgent"] as const;
export type AssignmentPriority = (typeof ASSIGNMENT_PRIORITIES)[number];

export const ASSIGNMENT_MATERIAL_APPROVAL_STATUSES = [
  "pending",
  "approved",
  "rejected",
] as const;
export type AssignmentMaterialApprovalStatus =
  (typeof ASSIGNMENT_MATERIAL_APPROVAL_STATUSES)[number];


export const ASSIGNMENT_PARTICIPANT_STATUSES = [
  "assigned",
  "seen",
  "en_route",
  "in_progress",
  "paused",
  "completed",
  "not_completed",
  "removed",
] as const;
export type AssignmentParticipantStatus = (typeof ASSIGNMENT_PARTICIPANT_STATUSES)[number];

export const ASSIGNMENT_COMPLETION_POLICIES = [
  "all_required_participants",
  "any_participant",
  "first_final_outcome",
] as const;
export type AssignmentCompletionPolicy = (typeof ASSIGNMENT_COMPLETION_POLICIES)[number];

// ─── Allowed status transitions ────────────────────────────────────────────────

export const ASSIGNMENT_STATUS_TRANSITIONS: Record<AssignmentStatus, AssignmentStatus[]> = {
  requested:         ["review", "plannable", "cancelled"],
  review:            ["quote_preparation", "approved", "plannable", "cancelled"],
  quote_preparation: ["awaiting_approval", "cancelled"],
  awaiting_approval: ["approved", "review", "cancelled"],
  approved:          ["plannable", "cancelled"],
  plannable:         ["scheduled", "cancelled"],
  scheduled:         ["seen", "en_route", "in_progress", "plannable", "cancelled"],
  seen:              ["en_route", "in_progress", "scheduled", "cancelled"],
  en_route:          ["in_progress", "scheduled", "cancelled"],
  in_progress:       ["completed", "not_completed"],
  not_completed:     ["in_progress", "plannable", "report_submitted"],
  completed:         ["report_submitted"],
  report_submitted:  ["report_approved", "completed"],
  report_approved:   ["invoice_ready"],
  invoice_ready:     ["invoiced"],
  invoiced:          ["paid"],
  paid:              ["closed"],
  closed:            [],
  cancelled:         [],
};

// ─── Tables ────────────────────────────────────────────────────────────────────

/**
 * Central entity — drives planning, reporting, and invoicing.
 * Always linked to a customer; optionally to a specific object.
 *
 * scheduledDate / scheduledStart / scheduledEnd are stored as plain strings
 * (YYYY-MM-DD and HH:MM) to avoid timezone ambiguity in a multinational context.
 */
export const assignmentsTable = pgTable("assignments", {
  id:             uuid("id").primaryKey().defaultRandom(),
  tenantId:       uuid("tenant_id")
    .notNull()
    .references(() => tenantsTable.id, { onDelete: "cascade" }),
  /** Auto-generated by DB trigger trg_assignments_set_code — e.g. SCH-2026-0600001. */
  code:           varchar("code", { length: 20 }).notNull().unique().$defaultFn(() => ""),
  title:          varchar("title", { length: 255 }).notNull(),
  description:    text("description"),

  customerId:     uuid("customer_id")
    .notNull()
    .references(() => customersTable.id, { onDelete: "cascade" }),
  objectId:       uuid("object_id")
    .references(() => objectsTable.id, { onDelete: "set null" }),

  /** Current lifecycle status — see ASSIGNMENT_STATUS_TRANSITIONS for allowed moves. */
  status:         varchar("status", { length: 50 })
    .notNull()
    .default("requested"),
  priority:       varchar("priority", { length: 20 })
    .notNull()
    .default("normal"),

  /** YYYY-MM-DD — timezone-safe date string */
  scheduledDate:  varchar("scheduled_date", { length: 10 }),
  /** HH:MM */
  scheduledStart: varchar("scheduled_start", { length: 5 }),
  /** HH:MM */
  scheduledEnd:   varchar("scheduled_end", { length: 5 }),

  /** Historical execution address snapshot used for map/routes and work order integrity. */
  executionAddressLine1: text("execution_address_line_1"),
  executionAddressLine2: text("execution_address_line_2"),
  executionPostalCode: varchar("execution_postal_code", { length: 20 }),
  executionCity: varchar("execution_city", { length: 120 }),
  executionStateOrRegion: varchar("execution_state_or_region", { length: 120 }),
  executionCountryCode: varchar("execution_country_code", { length: 2 }),
  executionFormattedAddress: text("execution_formatted_address"),
  executionLatitude: numeric("execution_latitude", { precision: 9, scale: 6 }),
  executionLongitude: numeric("execution_longitude", { precision: 9, scale: 6 }),
  executionGooglePlaceId: varchar("execution_google_place_id", { length: 255 }),
  executionLocationSource: varchar("execution_location_source", { length: 40 }),
  executionLocationSnapshotAt: timestamp("execution_location_snapshot_at", { withTimezone: true }),
  executionLocationUpdatedAt: timestamp("execution_location_updated_at", { withTimezone: true }),

  /** When the assigned personnel member first opened the work order. */
  seenAt:          timestamp("seen_at", { withTimezone: true }),
  /** First timestamp at which any assigned personnel member marked the work order as en route. */
  enRouteAt:       timestamp("en_route_at", { withTimezone: true }),
  /** Actual start timestamp captured from the personnel PWA. */
  actualStartedAt: timestamp("actual_started_at", { withTimezone: true }),
  /** Actual completion or not-completed timestamp captured from the personnel PWA. */
  actualCompletedAt: timestamp("actual_completed_at", { withTimezone: true }),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  cancelledBy: uuid("cancelled_by"),
  cancellationReason: text("cancellation_reason"),
  /** Reason selected by personnel when the work order cannot be completed. */
  completionReason: varchar("completion_reason", { length: 160 }),
  /** Optional personnel notes for completed/not-completed closeout. */
  completionNotes: text("completion_notes"),
  /** Whether customer signature is required before the personnel PWA can complete the work order. */
  customerSignatureRequired: boolean("customer_signature_required").notNull().default(false),
  /** Data URL for the captured customer signature. */
  customerSignatureDataUrl: text("customer_signature_data_url"),
  /** Timestamp for the customer signature capture. */
  customerSignedAt: timestamp("customer_signed_at", { withTimezone: true }),

  /** Management-only internal notes. */
  notes:          text("notes"),

  /**
   * Optional free-text region requirement.
   * Must match personnel.region (case-insensitive, trimmed) when set.
   * NULL = no regional restriction.
   */
  requiredRegion: varchar("required_region", { length: 100 }),
  /** Explicit team size for smart planning. Defaults to one person. */
  requiredPersonnelCount: integer("required_personnel_count").notNull().default(1),

  isActive:       boolean("is_active").notNull().default(true),
  createdAt:      timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:      timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  /** Supabase Auth UUID of the staff member who created the record. */
  createdBy:      uuid("created_by"),
});

/** Many-to-many: personnel assigned to an assignment. */
export const assignmentPersonnelTable = pgTable(
  "assignment_personnel",
  {
    id:           uuid("id").primaryKey().defaultRandom(),
    assignmentId: uuid("assignment_id")
      .notNull()
      .references(() => assignmentsTable.id, { onDelete: "restrict" }),
    personnelId:  uuid("personnel_id")
      .notNull()
      .references(() => personnelTable.id, { onDelete: "restrict" }),
    /**
     * 'assigned'  — planned by the planner (default).
     * 'suggested' — self-applied by the field worker via the personeels-PWA.
     * 'declined'  — planner rejected the self-application.
     * Requires migration 016_assignment_personnel_status.sql to be run first.
     */
    status:       varchar("status", { length: 20 }).notNull().default("assigned"),
    assignedAt:   timestamp("assigned_at", { withTimezone: true }).notNull().defaultNow(),
    assignedBy:   uuid("assigned_by"),
    selectedAt: timestamp("selected_at", { withTimezone: true }),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    unassignedAt: timestamp("unassigned_at", { withTimezone: true }),
    unassignedBy: uuid("unassigned_by"),
    unassignmentReason: text("unassignment_reason"),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    cancelledBy: uuid("cancelled_by"),
    cancellationReason: text("cancellation_reason"),
    lifecycleVersion: bigint("lifecycle_version", { mode: "number" }).notNull().default(1),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (t) => [
    uniqueIndex("assignment_personnel_unique_idx").on(t.assignmentId, t.personnelId),
  ],
);

/** Append-only snapshots of completed staffing lifecycle states. */
export const assignmentPersonnelLifecycleHistoryTable = pgTable(
  "assignment_personnel_lifecycle_history",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    assignmentPersonnelId: uuid("assignment_personnel_id")
      .notNull()
      .references(() => assignmentPersonnelTable.id, { onDelete: "restrict" }),
    tenantId: uuid("tenant_id").notNull().references(() => tenantsTable.id, { onDelete: "restrict" }),
    assignmentId: uuid("assignment_id").notNull().references(() => assignmentsTable.id, { onDelete: "restrict" }),
    personnelId: uuid("personnel_id").notNull().references(() => personnelTable.id, { onDelete: "restrict" }),
    status: varchar("status", { length: 20 }).notNull(),
    assignedAt: timestamp("assigned_at", { withTimezone: true }).notNull(),
    assignedBy: uuid("assigned_by"),
    selectedAt: timestamp("selected_at", { withTimezone: true }),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    unassignedAt: timestamp("unassigned_at", { withTimezone: true }),
    unassignedBy: uuid("unassigned_by"),
    unassignmentReason: text("unassignment_reason"),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    cancelledBy: uuid("cancelled_by"),
    cancellationReason: text("cancellation_reason"),
    lifecycleVersion: bigint("lifecycle_version", { mode: "number" }).notNull(),
    transition: varchar("transition", { length: 20 }).notNull(),
    recordedAt: timestamp("recorded_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("assignment_personnel_lifecycle_history_version_unique").on(t.assignmentPersonnelId, t.lifecycleVersion),
    index("assignment_personnel_lifecycle_history_lookup_idx").on(t.tenantId, t.assignmentId, t.personnelId, t.lifecycleVersion),
  ],
);

/** Canonical per-person execution record for one assigned participant episode. */
export const assignmentParticipantExecutionsTable = pgTable(
  "assignment_participant_executions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenantsTable.id, { onDelete: "cascade" }),
    assignmentId: uuid("assignment_id")
      .notNull()
      .references(() => assignmentsTable.id, { onDelete: "cascade" }),
    personnelId: uuid("personnel_id")
      .notNull()
      .references(() => personnelTable.id, { onDelete: "restrict" }),
    assignmentPersonnelId: uuid("assignment_personnel_id")
      .notNull()
      .references(() => assignmentPersonnelTable.id, { onDelete: "restrict" }),
    participantStatus: varchar("participant_status", { length: 32 }).notNull().default("assigned"),
    isRequired: boolean("is_required").notNull().default(true),
    seenAt: timestamp("seen_at", { withTimezone: true }),
    enRouteAt: timestamp("en_route_at", { withTimezone: true }),
    actualStartedAt: timestamp("actual_started_at", { withTimezone: true }),
    pausedAt: timestamp("paused_at", { withTimezone: true }),
    resumedAt: timestamp("resumed_at", { withTimezone: true }),
    actualCompletedAt: timestamp("actual_completed_at", { withTimezone: true }),
    completionOutcome: varchar("completion_outcome", { length: 32 }),
    completionReason: varchar("completion_reason", { length: 160 }),
    completionNotes: text("completion_notes"),
    completionPolicy: varchar("completion_policy", { length: 32 }).notNull().default("all_required_participants"),
    idempotencyKey: text("idempotency_key"),
    version: bigint("version", { mode: "number" }).notNull().default(1),
    lastActorUserId: uuid("last_actor_user_id"),
    lastActorPersonnelId: uuid("last_actor_personnel_id"),
    auditMetadata: jsonb("audit_metadata").notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (t) => [
    uniqueIndex("assignment_participant_execution_active_link_unique").on(t.assignmentPersonnelId).where(sql`${t.participantStatus} <> 'removed'`),
    uniqueIndex("assignment_participant_execution_active_person_unique").on(t.assignmentId, t.personnelId).where(sql`${t.participantStatus} <> 'removed'`),
    index("assignment_participant_execution_assignment_idx").on(t.tenantId, t.assignmentId, t.participantStatus),
    index("assignment_participant_execution_personnel_idx").on(t.tenantId, t.personnelId, t.participantStatus),
  ],
);


/** Task codes scoped to an assignment (the actual work to be performed). */
export const assignmentTasksTable = pgTable("assignment_tasks", {
  id:           uuid("id").primaryKey().defaultRandom(),
  assignmentId: uuid("assignment_id")
    .notNull()
    .references(() => assignmentsTable.id, { onDelete: "cascade" }),
  taskCodeId:   uuid("task_code_id")
    .references(() => taskCodesTable.id, { onDelete: "set null" }),
  tenantTaskCodeId: uuid("tenant_task_code_id")
    .references(() => tenantTaskCodesTable.id, { onDelete: "set null" }),
  tenantTaskCodePriceId: uuid("tenant_task_code_price_id")
    .references(() => tenantTaskCodePricesTable.id, { onDelete: "set null" }),
  /** Historical task-code snapshot used by quotes/invoices after prices change. */
  taskCodeCode: varchar("task_code_code", { length: 50 }),
  taskCodeName: varchar("task_code_name", { length: 200 }),
  taskCodePrice: numeric("task_code_price", { precision: 10, scale: 2 }),
  taskCodeInvoiceable: boolean("task_code_invoiceable"),
  notes:        text("notes"),
  sortOrder:    integer("sort_order").notNull().default(0),
  completedAt:  timestamp("completed_at", { withTimezone: true }),
  completedBy:  uuid("completed_by"),
});

/** Extra work added by personnel during or after assignment execution. */
export const assignmentExtraWorkTable = pgTable("assignment_extra_work", {
  id:           uuid("id").primaryKey().defaultRandom(),
  assignmentId: uuid("assignment_id")
    .notNull()
    .references(() => assignmentsTable.id, { onDelete: "cascade" }),
  taskCodeId:   uuid("task_code_id")
    .references(() => taskCodesTable.id, { onDelete: "set null" }),
  /** Snapshot of task code name at time of entry — preserved if code is later renamed. */
  taskCodeName: varchar("task_code_name", { length: 200 }),
  description:  text("description").notNull(),
  hours:        numeric("hours", { precision: 5, scale: 2 }),
  price:        numeric("price", { precision: 10, scale: 2 }),
  createdBy:    uuid("created_by").notNull(),
  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Photos uploaded by personnel for an assignment (optionally linked to an extra work item). */
export const assignmentPhotosTable = pgTable("assignment_photos", {
  id:           uuid("id").primaryKey().defaultRandom(),
  tenantId:     uuid("tenant_id")
    .references(() => tenantsTable.id, { onDelete: "cascade" }),
  assignmentId: uuid("assignment_id")
    .notNull()
    .references(() => assignmentsTable.id, { onDelete: "cascade" }),
  extraWorkId:  uuid("extra_work_id")
    .references(() => assignmentExtraWorkTable.id, { onDelete: "set null" }),
  storagePath:  text("storage_path").notNull(),
  uploadedBy:   uuid("uploaded_by").notNull(),
  assignmentParticipantExecutionId: uuid("assignment_participant_execution_id")
    .references(() => assignmentParticipantExecutionsTable.id, { onDelete: "set null" }),
  assignmentPersonnelId: uuid("assignment_personnel_id")
    .references(() => assignmentPersonnelTable.id, { onDelete: "set null" }),
  personnelId: uuid("personnel_id")
    .references(() => personnelTable.id, { onDelete: "set null" }),
  visibilityScope: varchar("visibility_scope", { length: 32 }).notNull().default("internal_until_approved"),
  /** Set to true by management (backoffice) to make the photo visible to the customer. */
  isApproved:   boolean("is_approved").notNull().default(false),
  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** Material and consumables registered by personnel during execution. */
export const assignmentMaterialUsageTable = pgTable("assignment_material_usage", {
  id:           uuid("id").primaryKey().defaultRandom(),
  tenantId:     uuid("tenant_id").references(() => tenantsTable.id, { onDelete: "cascade" }),
  assignmentId: uuid("assignment_id")
    .notNull()
    .references(() => assignmentsTable.id, { onDelete: "cascade" }),
  materialId: uuid("material_id"),
  materialCodeSnapshot: varchar("material_code_snapshot", { length: 40 }),
  registeredName: text("registered_name"),
  registeredQuantity: numeric("registered_quantity", { precision: 12, scale: 3 }),
  registeredUnitLabel: varchar("registered_unit_label", { length: 40 }),
  stockLocationId: uuid("stock_location_id"),
  stockMovementId: uuid("stock_movement_id"),
  usesStock: boolean("uses_stock").notNull().default(false),
  isOther: boolean("is_other").notNull().default(false),
  approvedName: text("approved_name"),
  approvedQuantity: numeric("approved_quantity", { precision: 12, scale: 3 }),
  approvedUnitLabel: varchar("approved_unit_label", { length: 40 }),
  approvedUnitPrice: numeric("approved_unit_price", { precision: 12, scale: 2 }),
  approvedVatRate: numeric("approved_vat_rate", { precision: 5, scale: 2 }),
  invoiceable: boolean("invoiceable").notNull().default(false),
  customerVisible: boolean("customer_visible").notNull().default(false),
  approvalStatus: varchar("approval_status", { length: 30 })
    .notNull()
    .default("pending")
    .$type<AssignmentMaterialApprovalStatus>(),
  approvedBy: uuid("approved_by"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  approvalReason: text("approval_reason"),
  invoiceId: uuid("invoice_id"),
  photoDocumentId: uuid("photo_document_id"),
  clientMutationId: varchar("client_mutation_id", { length: 80 }),
  name:         text("name").notNull(),
  quantity:     numeric("quantity", { precision: 10, scale: 2 }).notNull().default("1"),
  unitPrice:    numeric("unit_price", { precision: 10, scale: 2 }).notNull().default("0"),
  unitLabel:    varchar("unit_label", { length: 40 }),
  notes:        text("notes"),
  createdBy:    uuid("created_by").notNull(),
  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:    timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

/** Timeline notes written by personnel during assignment execution. */
export const assignmentReportNotesTable = pgTable("assignment_report_notes", {
  id:           uuid("id").primaryKey().defaultRandom(),
  assignmentId: uuid("assignment_id")
    .notNull()
    .references(() => assignmentsTable.id, { onDelete: "cascade" }),
  body:         text("body").notNull(),
  createdBy:    uuid("created_by").notNull(),
  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:    timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

/** Media attachments linked to a report timeline note. */
export const assignmentReportNoteAttachmentsTable = pgTable("assignment_report_note_attachments", {
  id:           uuid("id").primaryKey().defaultRandom(),
  tenantId:     uuid("tenant_id")
    .references(() => tenantsTable.id, { onDelete: "cascade" }),
  noteId:       uuid("note_id")
    .notNull()
    .references(() => assignmentReportNotesTable.id, { onDelete: "cascade" }),
  assignmentId: uuid("assignment_id")
    .notNull()
    .references(() => assignmentsTable.id, { onDelete: "cascade" }),
  storagePath:  text("storage_path").notNull(),
  fileName:     text("file_name").notNull(),
  mimeType:     varchar("mime_type", { length: 120 }),
  fileSize:     bigint("file_size", { mode: "number" }),
  uploadedBy:   uuid("uploaded_by").notNull(),
  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type AssignmentExtraWork       = typeof assignmentExtraWorkTable.$inferSelect;
export type InsertAssignmentExtraWork = typeof assignmentExtraWorkTable.$inferInsert;
export type AssignmentPhoto           = typeof assignmentPhotosTable.$inferSelect;
export type InsertAssignmentPhoto     = typeof assignmentPhotosTable.$inferInsert;
export type AssignmentMaterialUsage   = typeof assignmentMaterialUsageTable.$inferSelect;
export type AssignmentReportNote      = typeof assignmentReportNotesTable.$inferSelect;
export type AssignmentReportNoteAttachment = typeof assignmentReportNoteAttachmentsTable.$inferSelect;

// ─── Zod schemas ──────────────────────────────────────────────────────────────

export const insertAssignmentSchema = createInsertSchema(assignmentsTable).omit({
  id: true,
  tenantId: true,
  code: true,
  createdAt: true,
  updatedAt: true,
});

export const selectAssignmentSchema = createSelectSchema(assignmentsTable);
export const updateAssignmentSchema  = insertAssignmentSchema.partial();

export type InsertAssignment = z.infer<typeof insertAssignmentSchema>;
export type UpdateAssignment = z.infer<typeof updateAssignmentSchema>;
export type Assignment       = z.infer<typeof selectAssignmentSchema>;
