import {
  pgTable,
  uniqueIndex,
  uuid,
  varchar,
  text,
  boolean,
  numeric,
  timestamp,
} from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { sectorsTable } from "./sectors";
import { customerTypesTable } from "./customer-types";
import { tenantsTable } from "./tenants";

export const CUSTOMER_STATUSES = ["lead", "prospect", "active", "inactive", "blocked", "archived"] as const;
export type CustomerStatus = (typeof CUSTOMER_STATUSES)[number];

export const customersTable = pgTable(
  "customers",
  {
    id:           uuid("id").primaryKey().defaultRandom(),
    tenantId:     uuid("tenant_id")
      .notNull()
      .references(() => tenantsTable.id, { onDelete: "cascade" }),
    name:         varchar("name", { length: 255 }).notNull(),
    /** Auto-generated by DB trigger trg_customers_set_code — never set by application code. */
    code:         varchar("code", { length: 50 }).notNull().unique().$defaultFn(() => ""),
    sectorId:     uuid("sector_id").references(() => sectorsTable.id, { onDelete: "set null" }),

    address:      text("address"),
    city:         varchar("city", { length: 100 }),
    postalCode:   varchar("postal_code", { length: 20 }),
    country:      varchar("country", { length: 100 }).notNull().default("NL"),
    addressLine1: text("address_line_1"),
    addressLine2: text("address_line_2"),
    stateOrRegion: varchar("state_or_region", { length: 120 }),
    countryCode: varchar("country_code", { length: 2 }).default("NL"),
    formattedAddress: text("formatted_address"),
    googlePlaceId: varchar("google_place_id", { length: 255 }),
    locationSource: varchar("location_source", { length: 40 }),
    locationVerifiedAt: timestamp("location_verified_at", { withTimezone: true }),
    locationUpdatedAt: timestamp("location_updated_at", { withTimezone: true }),
    latitude:     numeric("latitude", { precision: 9, scale: 6 }),
    longitude:    numeric("longitude", { precision: 9, scale: 6 }),
    geocodedAt:   timestamp("geocoded_at", { withTimezone: true }),
    geocodingProvider: varchar("geocoding_provider", { length: 40 }),
    geocodingStatus:   varchar("geocoding_status", { length: 30 })
      .notNull()
      .default("pending"),
    geocodingConfidence: numeric("geocoding_confidence", { precision: 5, scale: 2 }),
    geocodingError: text("geocoding_error"),

    // Legacy single-contact fields (kept for backward compat)
    contactName:  varchar("contact_name", { length: 200 }),
    /**
     * Contact address for customer communication. Portal authorization is based
     * on explicit customer_users links, so the e-mail uniqueness boundary is the
     * current tenant rather than the whole platform.
     */
    contactEmail: varchar("contact_email", { length: 255 }),
    contactPhone: varchar("contact_phone", { length: 50 }),

    // Extended CRM fields
    tradeName:                varchar("trade_name", { length: 255 }),
    legalEntity:              varchar("legal_entity", { length: 255 }),
    registrationCountry:      varchar("registration_country", { length: 100 }),
    vatNumber:                varchar("vat_number", { length: 50 }),
    chamberOfCommerceNumber:  varchar("chamber_of_commerce_number", { length: 50 }),
    website:                  varchar("website", { length: 255 }),
    mobile:                   varchar("mobile", { length: 50 }),
    customerTypeId:           uuid("customer_type_id").references(() => customerTypesTable.id, { onDelete: "set null" }),
    /** CRM lifecycle status */
    status:                   varchar("status", { length: 20 }).notNull().default("active"),
    /** Supabase Auth user UUID of the account manager responsible for this customer. */
    accountManagerId:         uuid("account_manager_id"),

    isActive:     boolean("is_active").notNull().default(true),

    /**
     * Internal staff notes — never shown to customer-portal users.
     *
     * DB-level enforcement (Supabase production):
     *   migrations/002_sprint1_rls.sql runs:
     *     REVOKE SELECT (notes) ON customers FROM authenticated;
     *   so customer-role queries can never read this column.
     *   Backoffice uses service_role key which bypasses RLS and sees all columns.
     *
     * Application-layer enforcement:
     *   Customer-facing Server Components and API routes must also omit this field.
     *
     * Additional protection:
     *   Internal notes are additionally mirrored to `customer_notes` table
     *   (management-only RLS, no authenticated SELECT policy).
     */
    notes:        text("notes"),

    createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt:    timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
    /** Supabase Auth user UUID of the staff member who created the record. */
    createdBy:    uuid("created_by"),
  },
  (table) => [
    uniqueIndex("customers_tenant_contact_email_unique_idx").on(table.tenantId, table.contactEmail),
  ],
);

export const insertCustomerSchema = createInsertSchema(customersTable).omit({
  id: true,
  tenantId: true,
  code: true,
  createdAt: true,
  updatedAt: true,
});

export const selectCustomerSchema = createSelectSchema(customersTable);
export const updateCustomerSchema  = insertCustomerSchema.partial();

export type InsertCustomer = z.infer<typeof insertCustomerSchema>;
export type UpdateCustomer = z.infer<typeof updateCustomerSchema>;
export type Customer       = z.infer<typeof selectCustomerSchema>;
