import {
  pgTable,
  uuid,
  varchar,
  text,
  date,
  numeric,
  timestamp,
} from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { customersTable } from "./customers";
import { assignmentsTable } from "./assignments";

// ─── Status ────────────────────────────────────────────────────────────────────

export const INVOICE_STATUSES = ["draft", "sent", "paid", "cancelled"] as const;
export type InvoiceStatus = (typeof INVOICE_STATUSES)[number];

// ─── Table ─────────────────────────────────────────────────────────────────────

/**
 * Invoices generated from approved-report assignments.
 * invoice_number is auto-generated by DB trigger trg_invoices_set_number.
 * Format: FACT-YYYY-NNNN
 */
export const invoicesTable = pgTable("invoices", {
  id:             uuid("id").primaryKey().defaultRandom(),

  /** Auto-generated: FACT-YYYY-NNNN. Never set by application code. */
  invoiceNumber:  varchar("invoice_number", { length: 30 }).notNull().unique().$defaultFn(() => ""),

  customerId:     uuid("customer_id")
    .notNull()
    .references(() => customersTable.id, { onDelete: "restrict" }),

  assignmentId:   uuid("assignment_id")
    .notNull()
    .references(() => assignmentsTable.id, { onDelete: "restrict" }),

  /** Subtotal excl. VAT, in EUR. */
  amount:         numeric("amount", { precision: 12, scale: 2 }).notNull().default("0"),

  /** VAT rate, e.g. 21.00 for 21%. */
  vatPercentage:  numeric("vat_percentage", { precision: 5, scale: 2 }).notNull().default("21"),

  /** Computed: amount × vatPercentage / 100 */
  vatAmount:      numeric("vat_amount", { precision: 12, scale: 2 }).notNull().default("0"),

  /** Computed: amount + vatAmount */
  totalAmount:    numeric("total_amount", { precision: 12, scale: 2 }).notNull().default("0"),

  /** Current invoice status. Transitions: draft → sent → paid, or → cancelled. */
  status:         varchar("status", { length: 20 }).notNull().default("draft"),

  /** ISO date string YYYY-MM-DD */
  dueDate:        date("due_date").notNull(),

  /** ISO date string YYYY-MM-DD — set when markInvoicePaid is called. */
  paidDate:       date("paid_date"),

  notes:          text("notes"),

  createdBy:      uuid("created_by"),
  createdAt:      timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:      timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

// ─── Zod schemas ───────────────────────────────────────────────────────────────

export const insertInvoiceSchema = createInsertSchema(invoicesTable).omit({
  id:            true,
  invoiceNumber: true,
  vatAmount:     true,
  totalAmount:   true,
  createdAt:     true,
  updatedAt:     true,
});

export const selectInvoiceSchema = createSelectSchema(invoicesTable);
export const updateInvoiceSchema  = insertInvoiceSchema.partial();

export type InsertInvoice = z.infer<typeof insertInvoiceSchema>;
export type UpdateInvoice = z.infer<typeof updateInvoiceSchema>;
export type Invoice       = z.infer<typeof selectInvoiceSchema>;
