import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  timestamp,
  jsonb,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { customersTable } from "./customers";
import { sectorsTable } from "./sectors";

/**
 * A service location or physical asset belonging to a customer.
 * Assignments are always linked to an object.
 */
export const objectsTable = pgTable("objects", {
  id:          uuid("id").primaryKey().defaultRandom(),
  customerId:  uuid("customer_id").notNull().references(() => customersTable.id, { onDelete: "cascade" }),
  sectorId:    uuid("sector_id").references(() => sectorsTable.id, { onDelete: "set null" }),

  name:        varchar("name", { length: 255 }).notNull(),
  /** Auto-generated by DB trigger trg_objects_set_code — never set by application code. */
  code:        varchar("code", { length: 50 }).notNull().unique().$defaultFn(() => ""),

  address:     text("address"),
  city:        varchar("city", { length: 100 }),
  postalCode:  varchar("postal_code", { length: 20 }),

  description: text("description"),
  isActive:    boolean("is_active").notNull().default(true),

  // ── Primary contact (single, quick-access) ────────────────────────────────
  contactName:     varchar("contact_name",     { length: 200 }),
  contactFunction: varchar("contact_function", { length: 100 }),
  contactPhone:    varchar("contact_phone",    { length: 50 }),
  contactEmail:    varchar("contact_email",    { length: 255 }),

  // ── Extended fields (migration 023) ────────────────────────────────────────
  serviceType:           varchar("service_type", { length: 100 }),
  accessInfo:            text("access_info"),
  keyInfo:               text("key_info"),
  alarmInfo:             text("alarm_info"),
  fixedInstructions:     text("fixed_instructions"),
  specialNotes:          text("special_notes"),
  requiredRoles:         jsonb("required_roles").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  requiredCertificates:  jsonb("required_certificates").$type<string[]>().notNull().default(sql`'[]'::jsonb`),

  createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:   timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  /** Supabase Auth user UUID of the staff member who created the record. */
  createdBy:   uuid("created_by"),
});

export const insertObjectSchema = createInsertSchema(objectsTable).omit({
  id: true,
  code: true,
  createdAt: true,
  updatedAt: true,
});

export const selectObjectSchema = createSelectSchema(objectsTable);
export const updateObjectSchema  = insertObjectSchema.partial();

export type InsertObject  = z.infer<typeof insertObjectSchema>;
export type UpdateObject  = z.infer<typeof updateObjectSchema>;
export type ServiceObject = z.infer<typeof selectObjectSchema>;
