import {
  pgTable,
  uuid,
  varchar,
  boolean,
  timestamp,
  jsonb,
  text,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { rolesTable } from "./roles";
import { sectorsTable } from "./sectors";

/**
 * Field worker / employee profile.
 *
 * user_id links to Supabase auth.users (nullable — a personnel record can
 * exist before the employee has been invited to create a portal account).
 * The FK to auth.users is enforced in migrations/002_sprint1_rls.sql.
 *
 * RLS: employees may SELECT their own record (WHERE user_id = auth.uid()).
 *      Management has full access.
 */
export const personnelTable = pgTable("personnel", {
  id:           uuid("id").primaryKey().defaultRandom(),
  /** Supabase Auth UUID — nullable until the employee activates their account. */
  userId:       uuid("user_id").unique(),

  /** Auto-generated by DB trigger trg_personnel_set_code — never set by application code. */
  code:         varchar("code", { length: 20 }).notNull().unique().$defaultFn(() => ""),

  firstName:    varchar("first_name", { length: 100 }).notNull(),
  lastName:     varchar("last_name", { length: 100 }).notNull(),
  email:        varchar("email", { length: 255 }).notNull().unique(),
  phone:        varchar("phone", { length: 50 }),
  addressStreet:     varchar("address_street", { length: 200 }),
  addressPostalCode: varchar("address_postal_code", { length: 20 }),
  addressCity:       varchar("address_city", { length: 120 }),
  addressCountry:    varchar("address_country", { length: 80 }).notNull().default("Nederland"),
  avatarUrl:         text("avatar_url"),
  avatarPath:        text("avatar_path"),

  /** Primary role used for planning eligibility checks. */
  roleId:       uuid("role_id").references(() => rolesTable.id, { onDelete: "set null" }),
  /** Primary operational sector used for planning eligibility checks. */
  sectorId:     uuid("sector_id").references(() => sectorsTable.id, { onDelete: "set null" }),
  region:       varchar("region", { length: 100 }),

  /**
   * Certificates with optional expiry date.
   * Shape: [{ name: string; expires_at?: string (ISO date) }]
   * Migration 025 converts the legacy string[] format.
   */
  certificates: jsonb("certificates").$type<{ name: string; expires_at?: string }[]>().notNull().default(sql`'[]'::jsonb`),
  diplomas:     jsonb("diplomas").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  knowledge:    jsonb("knowledge").$type<string[]>().notNull().default(sql`'[]'::jsonb`),

  isActive:     boolean("is_active").notNull().default(true),
  isAvailable:  boolean("is_available").notNull().default(true),

  /**
   * Timestamp of when the last invite email was sent.
   * NULL  = no invite sent yet.
   * NOT NULL + user_id NULL = invite sent, account not yet activated.
   * user_id NOT NULL = account activated (linked on first PWA login).
   */
  inviteSentAt: timestamp("invite_sent_at", { withTimezone: true }),

  // ── Extended fields (migration 024) ────────────────────────────────────────
  /** Employment type: vast, parttime, flex, oproep, zzp, tijdelijk */
  personnelType:       varchar("personnel_type", { length: 20 }),
  /** Available for emergency/urgent assignments outside normal schedule */
  emergencyAvailable:  boolean("emergency_available").notNull().default(false),
  /** Additional preferred regions beyond the primary region field */
  preferredRegions:    jsonb("preferred_regions").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  /** Contract details: { start_date, end_date, contract_type, hours_per_week } */
  contractInfo:        jsonb("contract_info").$type<{
    start_date?:     string;
    end_date?:       string;
    contract_type?:  string;
    hours_per_week?: number;
  } | null>(),

  notificationEmailEnabled:    boolean("notification_email_enabled").notNull().default(true),
  notificationPushEnabled:     boolean("notification_push_enabled").notNull().default(true),
  notificationPlanningEnabled: boolean("notification_planning_enabled").notNull().default(true),
  notificationNewsEnabled:     boolean("notification_news_enabled").notNull().default(true),
  notificationHoursEnabled:    boolean("notification_hours_enabled").notNull().default(true),
  profileUpdatedAt:            timestamp("profile_updated_at", { withTimezone: true }),

  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:    timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertPersonnelSchema = createInsertSchema(personnelTable).omit({
  id: true,
  code: true,
  inviteSentAt: true,
  createdAt: true,
  updatedAt: true,
});

export const selectPersonnelSchema = createSelectSchema(personnelTable);
export const updatePersonnelSchema  = insertPersonnelSchema.partial();

export type InsertPersonnel = z.infer<typeof insertPersonnelSchema>;
export type UpdatePersonnel = z.infer<typeof updatePersonnelSchema>;
export type Personnel       = z.infer<typeof selectPersonnelSchema>;
