import {
  index,
  pgTable,
  uuid,
  varchar,
  text,
  date,
  numeric,
  timestamp,
} from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { customersTable } from "./customers";
import { assignmentsTable } from "./assignments";
import { tenantsTable } from "./tenants";

// ─── Status ────────────────────────────────────────────────────────────────────

export const QUOTE_STATUSES = [
  "draft",
  "sent",
  "approved",
  "rejected",
  "expired",
] as const;

export type QuoteStatus = (typeof QUOTE_STATUSES)[number];

// ─── Table ─────────────────────────────────────────────────────────────────────

/**
 * Quotes (offertes) linked to assignments in the review lifecycle stage.
 * quote_number is auto-generated by DB trigger trg_quotes_set_number.
 * Format: OFF-YYYY-NNNN
 */
export const quotesTable = pgTable(
  "quotes",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    tenantId: uuid("tenant_id").references(() => tenantsTable.id, { onDelete: "cascade" }),

    /** Auto-generated: OFF-YYYY-NNNN. Never set by application code. */
    quoteNumber: varchar("quote_number", { length: 30 })
      .notNull()
      .unique()
      .$defaultFn(() => ""),

    assignmentId: uuid("assignment_id")
      .notNull()
      .references(() => assignmentsTable.id, { onDelete: "restrict" }),

    customerId: uuid("customer_id")
      .notNull()
      .references(() => customersTable.id, { onDelete: "restrict" }),

    /** Proposed amount in EUR (excl. VAT). */
    amount: numeric("amount", { precision: 12, scale: 2 }).notNull().default("0"),

    /** Quote expiry date — ISO date string YYYY-MM-DD. */
    validityDate: date("validity_date").notNull(),

    /** Lifecycle: draft → sent → approved | rejected | expired. */
    status: varchar("status", { length: 20 }).notNull().default("draft"),

    /** Internal management notes — not visible to customers. */
    notes: text("notes"),

    /** Reason provided when a quote is rejected. */
    rejectionReason: text("rejection_reason"),

    createdBy: uuid("created_by"),
    approvedBy: uuid("approved_by"),
    approvedAt: timestamp("approved_at", { withTimezone: true }),

    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (table) => [
    index("quotes_tenant_idx").on(table.tenantId),
    index("quotes_tenant_assignment_idx").on(table.tenantId, table.assignmentId),
    index("quotes_tenant_customer_idx").on(table.tenantId, table.customerId),
  ],
);

// ─── Zod schemas ───────────────────────────────────────────────────────────────

export const insertQuoteSchema = createInsertSchema(quotesTable).omit({
  id: true,
  tenantId: true,
  quoteNumber: true,
  createdAt: true,
  updatedAt: true,
});

export const selectQuoteSchema = createSelectSchema(quotesTable);
export const updateQuoteSchema = insertQuoteSchema.partial();

export type InsertQuote = z.infer<typeof insertQuoteSchema>;
export type UpdateQuote = z.infer<typeof updateQuoteSchema>;
export type Quote       = z.infer<typeof selectQuoteSchema>;
