-- Keep every existing document/invoice field and authorization check. Only
-- require live same-customer identity on the two legacy report lists.
create or replace function public.customer_portal_documents(target_tenant uuid)
returns jsonb language plpgsql stable security definer set search_path='' as $$
begin
 if not private.object_session_active() then raise exception 'Geen toegang' using errcode='42501';end if;
 return jsonb_build_object(
 'documents',coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'title',d.title,'version',d.version,'category',d.category,'date',d.document_on,'validUntil',d.valid_until)) from public.customer_documents d where d.tenant_id=target_tenant and private.customer_document_access(target_tenant,d.id)),'[]'),
 'reports',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'body',r.body,'at',r.created_at,'orderId',w.id,'number',w.work_order_number,'object',o.name)) from public.report_entries r join public.work_orders w on w.tenant_id=r.tenant_id and w.id=r.work_order_id join public.objects o on o.tenant_id=w.tenant_id and o.id=w.object_id where r.tenant_id=target_tenant and private.service_enabled(target_tenant,'rapportage') and r.customer_visible and r.deleted_at is null and w.status in ('approved','invoice_ready','invoiced') and exists(select 1 from public.object_customer_bindings b where b.tenant_id=target_tenant and b.object_id=o.id and b.user_id=auth.uid() and b.active) and exists(select 1 from public.customer_portal_accounts a where a.tenant_id=target_tenant and a.customer_id=w.customer_id and a.user_id=auth.uid() and private.customer_account_access(target_tenant,a.id))),'[]'),
 'workReports',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'version',r.version,'number',r.snapshot->>'number','object',r.snapshot->'object'->>'name','approvedAt',r.approved_at) order by r.approved_at desc,r.version desc) from public.work_order_report_versions r join public.work_orders w on w.tenant_id=r.tenant_id and w.id=r.work_order_id where r.tenant_id=target_tenant and r.state='approved' and private.service_enabled(target_tenant,'rapportage') and exists(select 1 from public.object_customer_bindings b where b.tenant_id=target_tenant and b.object_id=w.object_id and b.user_id=auth.uid() and b.active) and exists(select 1 from public.customer_portal_accounts a where a.tenant_id=target_tenant and a.customer_id=w.customer_id and a.user_id=auth.uid() and private.customer_account_access(target_tenant,a.id))),'[]'),
 'invoices',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'number',i.invoice_number,'date',i.issued_on,'due',i.due_on,'total',i.total_cents,'paid',i.paid_cents,'status',i.status,'pdf',i.pdf_storage_path is not null)) from public.invoices i where i.tenant_id=target_tenant and private.customer_invoice_access(target_tenant,i.id)),'[]'));
end $$;
