"use client";
import { useCallback, useEffect, useState, useTransition } from "react";
import Link from "next/link";
import { RefreshCw, ClipboardList, FileText, History } from "lucide-react";
import { getDossierChain, saveCustomerAgreement } from "@/app/app/dossier-actions";
import { actionLabels, executionLabels, requestStatus, commercialStatus, isClosedAction } from "@/lib/dossiers/status";
import type { ChainScope, DossierChain, Agreement } from "@/lib/dossiers/model";
import type { WorkspaceData } from "@/lib/data/workspace";
import { ObjectForm } from "@/components/fieldgrid/objects/forms";
import { CompactFilterMenu } from "./compact-filter-menu";

export type ChainView = "actions" | "requests" | "agreements" | "documents" | "timeline" | "finance";
const money = (cents: number) => new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR" }).format(cents / 100);
export function DossierChainPanel({ scope, view, workspace, timezone = "Europe/Amsterdam", canCommercial = false, excludeSource }: { excludeSource?: string; scope: ChainScope; view: ChainView; workspace?: WorkspaceData; timezone?: string; canCommercial?: boolean }) {
  const [data, setData] = useState<DossierChain | null>(null); const [error, setError] = useState(""); const [pending, start] = useTransition();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("open"); const [kind, setKind] = useState(""); const [agreement, setAgreement] = useState<Agreement | "new" | null>(null);
  const { customerId, objectId, personnelId, orderId } = scope;
  const load = useCallback(() => start(async () => { const r = await getDossierChain({ customerId, objectId, personnelId, orderId }); if (r.ok) { setData(r.data); setError(""); } else { setData(null); setError(r.error); } }), [customerId, objectId, personnelId, orderId]);
  useEffect(() => { load(); const focus = () => load(); window.addEventListener("focus", focus); const timer = setInterval(() => { if (document.visibilityState === "visible") load(); }, 30000); return () => { window.removeEventListener("focus", focus); clearInterval(timer); }; }, [load]);
  const date = (value: string | null) => value ? new Intl.DateTimeFormat("nl-NL", { dateStyle: "medium", timeZone: timezone }).format(new Date(value.length === 10 ? `${value}T12:00:00Z` : value)) : "—";
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: timezone }).format(new Date());
  if (error) return <div className="dossier-notice" role="alert">{error}<button className="secondary-button" onClick={load}>Opnieuw proberen</button></div>;
  if (!data) return <p role="status">Gekoppelde dossiers laden…</p>;
  if(view==="documents"&&excludeSource&&!data.documents.some(d=>d.source_kind!==excludeSource))return null;
  const titles = { actions: "Gezamenlijke opvolging", requests: "Verzoeken & meerwerk", agreements: "Klantafspraken & contracten", documents: "Gekoppelde documenten", timeline: "Dossierhistorie", finance: "Financiële opvolging" };
  return <section className="dossier-card chain-panel" aria-label={titles[view]}>
    <div className="dossier-section-heading"><div><h2>{titles[view]}</h2><p className="dossier-muted">Bekijk afspraken, documenten en opvolging uit de verbonden dossiers.</p></div><div className="object-actions"><button className="resource-action" onClick={load} disabled={pending} aria-label="Dossiergegevens vernieuwen"><RefreshCw size={15}/>Vernieuwen</button>{view === "actions"&&<CompactFilterMenu activeCount={[query,kind,filter!=="open"?filter:""].filter(Boolean).length} contentClassName="dossier-filter-popover"><div className="dossier-toolbar"><label>Zoeken<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Actie of taak…"/></label><label>Type<select value={kind} onChange={e => setKind(e.target.value)}><option value="">Alle typen</option><option value="request">Klantverzoek</option><option value="execution">Uitvoeringstaak</option><option value="object">Objectactie</option><option value="personnel">Personeelsactie</option></select></label><label>Filter<select value={filter} onChange={e => setFilter(e.target.value)}><option value="open">Openstaand</option><option value="late">Deadline overschreden</option><option value="all">Alle statussen</option></select></label></div></CompactFilterMenu>}</div></div>
    {view === "actions" && <>
      <div className="table-scroll"><table className="resource-table"><thead><tr><th>Actie</th><th>Type</th><th>Status</th><th>Deadline</th><th>Acties</th></tr></thead><tbody>{data.actions.filter(a => (!kind || a.kind === kind) && a.title.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || !isClosedAction(a.status) && (filter !== "late" || !!a.due_on && a.due_on < today))).map(a => <tr key={`${a.kind}:${a.id}`}><td><strong>{a.title}</strong><small>Versie {a.version} · {a.owner_id ? "Verantwoordelijke vastgelegd" : "Nog toe te wijzen"}</small></td><td>{{ request: "Klantverzoek", execution: "Uitvoeringstaak", object: "Objectactie", personnel: "Personeelsactie" }[a.kind]}</td><td><span className="dossier-status">{a.kind === "request" ? requestStatus(a.status, a.needs_review) : (a.kind === "execution" ? executionLabels : actionLabels)[a.status] || "Controleren"}</span></td><td>{date(a.due_on)}{a.due_on && a.due_on < today && !isClosedAction(a.status) && <small>Deadline overschreden</small>}</td><td><Link className="resource-action" href={a.href}>Open bron</Link></td></tr>)}</tbody></table></div>{!data.actions.length && <p className="dossier-empty"><ClipboardList/>Nog geen gekoppelde acties.</p>}<p className="dossier-muted">Lezen is geen afronding. Wijzig een taak bij de bron; alle dossierweergaven volgen dezelfde registratie.</p></>}
    {view === "requests" && <>{data.requests.map(r => <article className="object-record" key={r.id} id={`request-${r.id}`}><header><h3>{r.title}</h3><span className="dossier-status">{requestStatus(r.state, r.needs_review)}</span></header><p>{r.body}</p><small>Verzoekversie {r.version} · {date(r.created_at)}</small>{r.response && <p>Terugkoppeling: {r.response}</p>}{r.needs_review && <p className="dossier-notice">De afspraak of het verzoek is gewijzigd. Beoordeling is opnieuw nodig.</p>}{r.proposals.map(p => <p key={p.id}>Voorstel v{p.version} · {money(p.price_cents * p.quantity)} excl. btw · {commercialStatus(r.state, !!p.accepted_at)}{p.accepted_at && ` · akkoord vastgelegd op ${date(p.accepted_at)}`}</p>)}{!r.proposals.length && r.state === "regular" && <p>Binnen contract · geen extra kosten</p>}<footer><Link className="resource-action" href={`/app/objecten/${r.object_id}?tab=instructies#request-${r.id}`}>Beoordelen bij object</Link><Link className="resource-action" href={`/app/werkbonnen/${r.work_order_id}`}>Concrete werkbon</Link></footer></article>)}{!data.requests.length && <p className="dossier-empty">Nog geen verzoeken bij deze selectie.</p>}</>}
    {view === "documents" && <>{data.documents.filter(d=>d.source_kind!==excludeSource).map(d => <article className="dossier-event" key={d.id}><FileText size={18}/><div><strong>{d.title}</strong><small>{{ hr: "Vertrouwelijk personeel", commercial: "Interne klantafspraak", operational: "Operationeel", restricted: "Beperkte toegang" }[d.classification] || "Private opslag"} · versie {d.version}</small><small>Upload: {date(d.created_at)} · documentdatum: {date(d.document_on)} · geldig tot: {date(d.valid_until)}</small></div><a className="resource-action" href={d.href}>Openen</a></article>)}{!data.documents.some(d=>d.source_kind!==excludeSource) && <p className="dossier-empty">Geen toegankelijke gekoppelde documenten.</p>}<p className="dossier-muted">Je opent hetzelfde document vanuit ieder gekoppeld dossier. Alleen bevoegde gebruikers kunnen het downloaden.</p></>}
    {view === "timeline" && <>{data.timeline.map(e => <article className="dossier-event" key={e.id}><History size={18}/><div><strong>{{ object_visit_requests: "Klantverzoek", object_records: "Objectregistratie", objects: "Object", object_nodes: "Locatieonderdeel", object_request_proposals: "Meerwerkvoorstel", object_documents: "Document" }[e.type] || "Dossierregistratie"} {e.event === "created" ? "toegevoegd" : "bijgewerkt"}</strong><small>{date(e.at)} · versie {e.version}</small></div></article>)}{!data.timeline.length && <p className="dossier-empty">Nog geen wijzigingen in deze context.</p>}</>}
    {view === "finance" && <>{data.invoices.map(i => <article className="dossier-event" key={i.id}><div><strong>{i.number || "Concept"}</strong><small>{money(i.total)} · betaald {money(i.paid)} · vervalt {date(i.due)}</small></div><Link className="resource-action" href={`/app/facturen?record=${i.id}`}>Open factuur</Link></article>)}{!data.invoices.length && <p className="dossier-empty">Geen facturen of geen financiële toegang.</p>}</>}
    {view === "agreements" && <>{canCommercial && workspace && customerId && <button className="primary-button" onClick={() => setAgreement("new")}>Klantafspraak vastleggen</button>}{data.agreements.map(a => <article className="object-record" key={a.id}><header><h3>{a.title}</h3><span className="dossier-status">{a.state==='draft'?'Concept':a.state==='ended'?'Beëindigd':'Vastgelegd'} · versie {a.version}{data.agreements.some(n => n.previous_id === a.id) ? " · opvolger beschikbaar" : ""}</span></header><p>{date(a.starts_on)} – {date(a.ends_on)}{a.accepted_on&&<> · Akkoord: {a.accepted_by_name}, {date(a.accepted_on)}</>}</p>{a.lines.map(l => <p key={l.id}>{l.scope} · {l.quantity} eenheden × {money(l.price_cents)} · {{visit:"per bezoek",hour:"per uur",once:"eenmalig",week:"per week",month:"per maand"}[l.price_basis]||l.price_basis} · limiet {money(l.limit_cents)}{l.extra_work&&" · vooraf toegestaan meerwerk"}</p>)}<footer>{a.evidence_document_id && <a className="resource-action" href={`/api/files/customer-document/${a.evidence_document_id}`}>Akkoordbewijs</a>}{canCommercial && workspace && !data.agreements.some(n => n.previous_id === a.id) && <button className="resource-action" onClick={() => setAgreement(a)}>Nieuwe versie</button>}</footer></article>)}{!data.agreements.length && <p className="dossier-empty">Nog geen vastgelegde klantafspraken, of geen commerciële toegang. Er wordt geen akkoord aangenomen.</p>}{agreement && workspace && customerId && <AgreementForm key={agreement === "new" ? "new" : agreement.id} customerId={customerId} previous={agreement === "new" ? undefined : agreement} workspace={workspace} onClose={() => setAgreement(null)} onSaved={() => { setAgreement(null); load(); }}/>}</>}
  </section>;
}

function AgreementForm({ customerId, previous, workspace, onClose, onSaved }: { customerId: string; previous?: Agreement; workspace: WorkspaceData; onClose: () => void; onSaved: () => void }) {
  const [id] = useState(() => crypto.randomUUID());
  const [lineIds,setLineIds]=useState(()=>(previous?.lines.length?previous.lines.map(l=>l.id):[crypto.randomUUID()]));
  return <div className="chain-agreement-form"><h3>{previous ? "Nieuwe contractversie" : "Klantafspraak vastleggen"}</h3><p className="dossier-notice">Leg alleen een werkelijk overeengekomen afspraak vast. Upload eerst het akkoordbewijs bij Documenten. Een wijziging bewaart de vorige versie.</p><ObjectForm action={saveCustomerAgreement} onSuccess={onSaved}>
    <input name="id" type="hidden" value={id}/><input name="customerId" type="hidden" value={customerId}/><input name="previousId" type="hidden" value={previous?.id || ""}/>
    <label className="wide">Titel<input name="title" required defaultValue={previous?.title}/></label><label>Geldig vanaf<input name="startsOn" type="date" required/></label><label>Geldig tot<input name="endsOn" type="date"/></label><label>Akkoordgever<input name="acceptedBy" required minLength={2}/></label><label>Akkoorddatum<input name="acceptedOn" type="date" required/></label>
    <label className="wide">Akkoordbewijs<select name="documentId" required><option value="">Kies een geüpload klantdocument</option>{workspace.customerDocuments.filter(d => d.customer_id === customerId).map(d => <option value={d.id} key={d.id}>{d.title} · versie {d.version}</option>)}</select></label>
    <input type="hidden" name="lineCount" value={lineIds.length}/>
    {lineIds.map((key,index)=>{const l=previous?.lines.find(line=>line.id===key);return <fieldset className="wide chain-contract-line" key={key}><legend>Contractregel {index+1}</legend><label>Object<select aria-label="Object" name={`objectId-${index}`} required defaultValue={l?.object_id || ""}><option value="">Kies een object</option>{workspace.objects.filter(o => o.customer_id === customerId).map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Catalogustaak<select aria-label="Catalogustaak" name={`taskRevisionId-${index}`} required defaultValue={l?.task_revision_id || ""}><option value="">Kies een taakversie</option>{workspace.taskRevisions.map(r => <option key={r.id} value={r.id}>{workspace.tasks.find(t => t.id === r.task_id)?.name} · versie {r.revision}</option>)}</select></label>
    <label className="wide">Afgesproken omvang<textarea name={`scope-${index}`} required minLength={2} defaultValue={l?.scope}/></label><label>Maximale hoeveelheid per bezoek<input name={`quantity-${index}`} type="number" min="0.001" step="0.001" required defaultValue={l?.quantity || 1}/></label><label>Prijs per eenheid excl. btw<input name={`price-${index}`} type="number" min="0" step="0.01" required defaultValue={(l?.price_cents || 0) / 100}/></label><label>Maximumbedrag per bezoek excl. btw<input name={`limit-${index}`} type="number" min="0" step="0.01" required defaultValue={(l?.limit_cents || 0) / 100}/></label>{lineIds.length>1&&<button type="button" className="resource-action" onClick={()=>setLineIds(ids=>ids.filter(id=>id!==key))}>Regel verwijderen</button>}</fieldset>;})}
    <button type="button" className="secondary-button wide" disabled={lineIds.length>=100} onClick={()=>setLineIds(ids=>[...ids,crypto.randomUUID()])}>Contractregel toevoegen</button>
  </ObjectForm><button className="secondary-button" data-discard-form onClick={onClose}>Sluiten</button></div>;
}
