"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowUpRight, CalendarDays, CheckCircle2, ClipboardList, Clock3, FileText, History, MoreHorizontal, Pencil, Plus, ShieldCheck, UsersRound, X } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { toast } from "sonner";
import type { WorkspaceData } from "@/lib/data/workspace";
import type { DossierData } from "@/lib/personnel/dossier-data";
import type { TenantContext } from "@/lib/auth/context";
import { dossierTabs, dossierDefinitions, businessToday, employmentStatus, currentContract, dossierSignals, certificateValidity, noticeDeadline, contractDeadlines, type DossierRecord, type DossierTab, type DossierValues, type RecordKind } from "@/lib/personnel/dossier";
import { DossierRecordEditor, DossierUpload, QualificationCatalogEditor } from "./personnel-dossier-forms";
import { dossierRecordHistory, prepareDossierChecklist, setQualificationRequirementActive } from "@/app/app/personeel/dossier-actions";
import type { Json } from "@/lib/database.types";
import { brandThemeStyle } from "@/lib/branding/palette";

const date=(value:unknown)=>value?new Intl.DateTimeFormat("nl-NL",{dateStyle:"medium",timeZone:"Europe/Amsterdam"}).format(new Date(String(value).length===10?`${value}T12:00:00Z`:String(value))):"—";
const labels:Record<string,string>={preparation:"In voorbereiding",active:"Actief",leaving:"Uitdiensttreding gepland",former:"Uit dienst",archived:"Gearchiveerd",invited:"Uitgenodigd",inactive:"Inactief",scheduled:"Gepland",processing:"Wordt verstuurd",sent:"Verzonden",failed:"Mislukt",cancelled:"Vervallen",uncertain:"Verzending onzeker",draft:"Concept",approved:"Goedgekeurd",open:"Open",completed:"Afgerond",stored:"Opgeslagen"};
const documentLabels:Record<string,string>={contract:"Contract",addendum:"Addendum",certificate:"Certificaatbewijs",review:"Gesprek",training:"Opleiding",instruction:"Instructie",asset:"Middelenbevestiging",notice:"Schriftelijke aanzegging"};
function Status({children,tone="neutral"}:{children:React.ReactNode;tone?:string}){return <span className={`dossier-status ${tone}`}>{children}</span>;}
function Empty({children}:{children:React.ReactNode}){return <div className="dossier-empty"><ClipboardList size={28}/><p>{children}</p></div>;}

export function PersonnelDossier({tenant,personnelId,data,workspace,tab}:{tenant:TenantContext;personnelId:string;data:DossierData;workspace:WorkspaceData;tab:DossierTab}) {
 const router=useRouter();const [checklistPending,startChecklist]=useTransition();
 const createChecklist=(type:"onboarding"|"offboarding")=>startChecklist(async()=>{const result=await prepareDossierChecklist(personnelId,type);if(!result.ok)toast.error(result.error);else{toast.success("Checklist klaargezet voor jou");router.refresh();}});
 const toggleRequirement=(id:string,active:boolean)=>startChecklist(async()=>{const result=await setQualificationRequirementActive(personnelId,id,active);if(!result.ok)toast.error(result.error);else{toast.success(active?"Eis hervat":"Eis gepauzeerd");router.refresh();}});
 const person=workspace.personnel.find(p=>p.id===personnelId)!;const today=businessToday();
 const [editor,setEditor]=useState<{kind:RecordKind;record?:DossierRecord;previousId?:string;initialValues?:DossierValues}|null>(null);
 const [upload,setUpload]=useState<{previous?:DossierData["documents"][number];metadataOnly?:boolean;relatedId?:string;category?:string}|null>(null);const [catalog,setCatalog]=useState(false);
 const [query,setQuery]=useState("");const [statusFilter,setStatusFilter]=useState("");const [sort,setSort]=useState("new");const [period,setPeriod]=useState(today.slice(0,7));
 const [versions,setVersions]=useState<Json[]|null>(null);const [historyPending,startHistory]=useTransition();
 const contract=currentContract(data.records);const profile=data.records.find(r=>r.kind==="profile");
 const employment=employmentStatus(person.status,profile?.data.employmentStatus);
 const tasks=data.records.filter(r=>["task","checklist"].includes(r.kind)&&r.status!=="completed");const certificates=data.records.filter(r=>r.kind==="certificate");const reviews=data.records.filter(r=>r.kind==="review");const signals=dossierSignals(data.records,today);
 const assignments=workspace.assignments.filter(a=>a.personnel_id===person.id);const gaps=(workspace.qualificationGaps??[]).filter(g=>g.personnel_id===person.id);const relevantIds=new Set(assignments.map(a=>a.work_order_id));const orders=workspace.workOrders.filter(w=>relevantIds.has(w.id));
 const common={personnelId,primary:tenant.primaryColor,accent:tenant.accentColor};
 const href=(next:DossierTab,id?:string)=>`/app/personeel/${person.id}?tab=${next}${id?`#record-${id}`:""}`;
 const functionName=workspace.functions.find(f=>f.id===contract?.data.functionId)?.name||workspace.personnelFunctions.filter(p=>p.personnel_id===person.id).map(p=>workspace.functions.find(f=>f.id===p.function_id)?.name).filter(Boolean).join(" · ")||"Functie nog niet vastgelegd";
 const profileValues:DossierValues={...profile?.data,name:person.full_name,employeeNumber:person.employee_number,email:person.email||"",phone:person.phone||"",employmentStatus:employment};
 const editProfile=()=>setEditor({kind:"profile",record:profile?{...profile,data:profileValues}:undefined,initialValues:profileValues});
 const openHistory=(id:string)=>startHistory(async()=>{const result=await dossierRecordHistory(person.id,id);if(!result.ok)toast.error(result.error);else setVersions(result.versions);});
 const showRecords=(kinds:RecordKind[])=>{
  const rows=data.records.filter(r=>kinds.includes(r.kind)).filter(r=>!query||r.title.toLowerCase().includes(query.toLowerCase())).filter(r=>!statusFilter||r.status===statusFilter||r.kind==="certificate"&&certificateValidity(r.data)===statusFilter).sort((a,b)=>sort==="name"?a.title.localeCompare(b.title,"nl"):b.updatedAt.localeCompare(a.updatedAt));
  return <><div className="dossier-toolbar"><label>Zoeken<input aria-label="Zoeken in tabblad" placeholder="Zoek op titel…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Alle statussen</option>{[...new Map(kinds.flatMap(k=>dossierDefinitions[k].statuses)).entries()].map(([k,v])=><option value={k} key={k}>{v}</option>)}{kinds.includes("certificate")&&["Nog niet geldig","Geldig","Verloopt binnenkort","Verlopen","Geen einddatum"].map(s=><option key={s}>{s}</option>)}</select></label><label>Sorteren<select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Recent gewijzigd</option><option value="name">Naam A–Z</option></select></label><span>{rows.length} registraties</span></div>
   {kinds.includes("certificate")&&rows.some(r=>r.kind==="certificate")&&<section className="dossier-card"><div className="table-scroll"><table className="resource-table"><thead><tr>{["Certificaat","Niveau","Behaald","Geldig tot","Verificatie","Geldigheid","Acties"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.filter(r=>r.kind==="certificate").map(r=><tr key={r.id}><td>{r.title}<small>{String(r.data.code)}</small></td><td>{String(r.data.level||"—")}</td><td>{date(r.data.issuedOn)}</td><td>{r.data.endsOn?date(r.data.endsOn):"Geen einddatum"}</td><td>{dossierDefinitions.certificate.statuses.find(([k])=>k===r.status)?.[1]}</td><td>{certificateValidity(r.data)}</td><td><div className="resource-actions"><a className="resource-action" href={href("certificaten",r.id)}>Bekijk</a><button className="resource-action" onClick={()=>setEditor({kind:"certificate",record:r})}>Controleer / bewerk</button></div></td></tr>)}</tbody></table></div></section>}
   {rows.length?<div className="dossier-records">{rows.map(record=><article className="dossier-card" id={`record-${record.id}`} key={record.id}><header><div><span className="eyebrow">{dossierDefinitions[record.kind].title}</span><h3>{record.title}</h3></div><Status tone={["approved","completed","active","seen"].includes(record.status)?"green":"neutral"}>{dossierDefinitions[record.kind].statuses.find(([k])=>k===record.status)?.[1]||labels[record.status]||record.status}</Status></header>
    {record.kind==="certificate"&&<p><Status tone={certificateValidity(record.data)==="Verlopen"?"danger":"neutral"}>{certificateValidity(record.data)}</Status> <small>Geldig-tot is inclusief · controle en geldigheid staan los van elkaar</small></p>}
    <dl className="dossier-facts">{dossierDefinitions[record.kind].fields.filter(f=>record.data[f.key]&&f.type!=="documents"&&!["reminderEmails","reminderDays","ownerId","managerId","relatedId"].includes(f.key)).map(f=><div key={f.key}><dt>{f.label}</dt><dd>{f.type==="date"?date(record.data[f.key]):f.key==="functionId"?workspace.functions.find(x=>x.id===record.data[f.key])?.name:f.options?.find(([k])=>k===record.data[f.key])?.[1]||String(record.data[f.key])}</dd></div>)}</dl>
    {record.kind==="contract"&&<p className="dossier-notice">{noticeDeadline(record.data)?`Aanzegdeadline: ${date(noticeDeadline(record.data))}. Een reminder vervangt nooit schriftelijke aanzegging.`:"Aanzegging: niet automatisch vastgesteld; toepasselijkheid en cao blijven te beoordelen."} Opeenvolgende contracten vragen een afzonderlijke beoordeling.</p>}
    {record.kind==="certificate"&&record.data.verifiedAt&&<small>Controle vastgelegd op {date(record.data.verifiedAt)} · {data.owners.find(o=>o.id===record.data.verifiedBy)?.label||"Bevoegde beheerder"}</small>}
    <div className="dossier-doc-links">{(record.data.document_ids as string[]??[]).map(id=>{const doc=data.documents.find(d=>d.id===id);return doc?<a key={id} href={`/api/files/personnel-document/${id}`} target="_blank" rel="noreferrer"><FileText size={15}/>{doc.title} · v{doc.version}</a>:null;})}</div>
    <footer><button className="resource-action" onClick={()=>setEditor({kind:record.kind,record})}><Pencil size={14}/>Bewerk</button><button className="resource-action" disabled={historyPending} onClick={()=>openHistory(record.id)}><History size={14}/>Historie</button>
     {["contract","certificate"].includes(record.kind)&&<button className="resource-action" onClick={()=>setEditor({kind:record.kind,previousId:record.id,initialValues:{...record.data,title:`${record.title} · vervolg`,document_ids:[],startsOn:"",endsOn:"",writtenNoticeOn:"",noticeEvidence:"",signatureStatus:"unsigned",verificationNote:""}})}>{record.kind==="contract"?"Verlengen":"Vernieuwen"}</button>}
     {record.kind==="contract"&&<button className="resource-action" onClick={()=>setUpload({relatedId:record.id,category:"addendum"})}>Addendum toevoegen</button>}
     <button className="resource-action" onClick={()=>setEditor({kind:"task",initialValues:{relatedId:record.id,title:`Opvolging: ${record.title}`}})}>Taak toevoegen</button><small>Versie {record.revision} · {date(record.updatedAt)}</small></footer>
   </article>)}</div>:<Empty>Nog geen registraties voor deze selectie. Voeg een registratie toe of pas de filters aan.</Empty>}</>;
 };
 const sectionHeader=(title:string,description:string,actions?:React.ReactNode)=><div className="dossier-section-heading"><div><h2>{title}</h2><p>{description}</p></div><div className="dossier-actions">{actions}</div></div>;
 const add=(kind:RecordKind,label:string)=><button className="primary-button" onClick={()=>setEditor({kind})}><Plus size={16}/>{label}</button>;
 const periodEntries=workspace.timeEntries.filter(r=>r.personnel_id===person.id&&businessToday(new Date(r.starts_at)).slice(0,7)===period);
 const hours=(entries:typeof periodEntries)=>entries.reduce((sum,r)=>sum+(r.ends_at?(new Date(r.ends_at).getTime()-new Date(r.starts_at).getTime())/3600000:0),0).toLocaleString("nl-NL",{maximumFractionDigits:1});
 const tabCounts:Partial<Record<DossierTab,number>>={contracten:data.records.filter(r=>r.kind==="contract"&&r.status!=="ended").length,certificaten:certificates.filter(r=>r.status!=="approved"||["Verlopen","Verloopt binnenkort"].includes(certificateValidity(r.data))).length,ontwikkeling:reviews.filter(r=>r.status!=="completed").length,tijdlijn:tasks.length,documenten:data.documents.length,middelen:data.records.filter(r=>r.kind==="asset"&&r.status!=="returned").length};
 const requiredCodes=[...new Set([...data.requirements.filter(r=>r.active&&r.scope==="function"&&(r.subject_id===contract?.data.functionId||workspace.personnelFunctions.some(f=>f.personnel_id===person.id&&f.function_id===r.subject_id))).map(r=>r.code),...(workspace.functions.find(f=>f.id===contract?.data.functionId)?.required_certificate_codes??[]),...workspace.personnelFunctions.filter(f=>f.personnel_id===person.id).flatMap(f=>workspace.functions.find(fn=>fn.id===f.function_id)?.required_certificate_codes??[])])];
 const missingCodes=requiredCodes.filter(code=>!certificates.some(c=>c.data.code===code&&c.status==="approved"&&["Geldig","Geen einddatum","Verloopt binnenkort"].includes(certificateValidity(c.data))));
 return <div className="personnel-dossier">
  <Link className="dossier-back" href="/app/personeel"><ArrowLeft size={16}/>Terug naar personeel</Link>
  <header className="dossier-hero"><div className="dossier-person"><span className="dossier-avatar">{person.full_name.split(/\s/).map(s=>s[0]).join("").slice(0,2)}</span><div><span className="eyebrow">PERSONEELSDOSSIER 360 · {person.employee_number}</span><h1>{person.full_name}</h1><p>{functionName} · {String(contract?.data.team||"Team nog niet vastgelegd")}</p><small>Leidinggevende: {data.owners.find(o=>o.id===contract?.data.managerId)?.label||workspace.personnel.find(p=>p.user_id===contract?.data.managerId)?.full_name||"Nog niet vastgelegd"}</small></div></div><div className="dossier-hero-actions"><Status>{labels[employment]||employment}</Status><div className="dossier-actions"><button className="secondary-button" onClick={editProfile}><Pencil size={15}/>Bewerken</button><button className="secondary-button" onClick={()=>setUpload({})}><FileText size={15}/>Document toevoegen</button>{add("task","Taak toevoegen")}</div></div></header>
  <nav className="dossier-tabs" aria-label="Dossieronderdelen">{dossierTabs.slice(0,5).map(([key,label])=><Link aria-current={tab===key?"page":undefined} href={href(key)} key={key}>{label}{!!tabCounts[key]&&<span className="dossier-tab-count" aria-hidden="true">{tabCounts[key]}</span>}</Link>)}<Popover><PopoverTrigger className={dossierTabs.slice(5).some(([key])=>key===tab)?"active":""}><MoreHorizontal size={16}/>Meer</PopoverTrigger><PopoverContent align="end" className="dossier-tab-menu">{dossierTabs.slice(5).map(([key,label])=><Link aria-current={tab===key?"page":undefined} href={href(key)} key={key}>{label}{!!tabCounts[key]&&<span className="dossier-tab-count" aria-hidden="true">{tabCounts[key]}</span>}</Link>)}</PopoverContent></Popover></nav>
  <label className="dossier-mobile-tabs">Dossieronderdeel<select aria-label="Dossieronderdeel" value={tab} onChange={e=>{location.href=href(e.target.value as DossierTab);}}>{dossierTabs.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>

  {tab==="overzicht"&&<>
   <div className="dossier-metrics">{[
    {icon:FileText,label:"Dienstverband",value:contract?dossierDefinitions.contract.fields.find(f=>f.key==="employmentType")?.options?.find(([k])=>k===contract.data.employmentType)?.[1]||contract.title:"Nog vast te leggen",sub:contract?`${contract.data.hours||"—"} uur per week · ${contract.data.endsOn?date(contract.data.endsOn):"Geen einddatum"} · Eerstvolgende deadline: ${date(contractDeadlines(contract.data)[0]?.date)}`:"Voeg een overeenkomst toe",target:"contracten"},
    {icon:ShieldCheck,label:"Certificaten",value:`${certificates.filter(c=>c.status==="approved"&&["Geldig","Geen einddatum","Verloopt binnenkort"].includes(certificateValidity(c.data))).length} geldig`,sub:`${missingCodes.length} ontbrekend · ${certificates.filter(c=>c.status==="review"||c.status==="unverified").length} in controle · ${certificates.filter(c=>certificateValidity(c.data)==="Verloopt binnenkort").length} verlopen binnenkort`,target:"certificaten"},
    {icon:ClipboardList,label:"Acties",value:`${tasks.length} openstaand`,sub:`${tasks.filter(t=>t.data.priority==="urgent").length} urgent · ${tasks.filter(t=>t.dueOn&&t.dueOn<today).length} te laat`,target:"tijdlijn"},
    {icon:UsersRound,label:"Gesprekken",value:reviews.filter(r=>r.data.startsOn&&String(r.data.startsOn)>=today).sort((a,b)=>String(a.data.startsOn).localeCompare(String(b.data.startsOn)))[0]?.data.startsOn?date(reviews.filter(r=>r.data.startsOn&&String(r.data.startsOn)>=today).sort((a,b)=>String(a.data.startsOn).localeCompare(String(b.data.startsOn)))[0].data.startsOn):"Geen gepland gesprek",sub:`Laatste: ${date(reviews.filter(r=>r.status==="completed").sort((a,b)=>String(b.data.startsOn).localeCompare(String(a.data.startsOn)))[0]?.data.startsOn)}`,target:"ontwikkeling"},
   ].map(m=><Link href={href(m.target as DossierTab)} className="dossier-metric" key={m.label}><span><m.icon size={20}/>{m.label}</span><strong>{m.value}</strong><small>{m.sub}</small></Link>)}</div>
   <div className="dossier-columns"><section className="dossier-card">{sectionHeader("Actie nodig","Deadlines en opvolging vanuit dit dossier.",<Link href={href("tijdlijn")} className="text-link">Alle acties<ArrowUpRight size={14}/></Link>)}{signals.length?signals.slice(0,7).map(s=><Link className="dossier-event" key={`${s.id}:${s.date}:${s.title}`} href={href(s.tab,s.id)}><CalendarDays size={18}/><span><strong>{s.title}</strong><small>{date(s.date)}</small></span><Status tone={s.overdue?"danger":"amber"}>{s.overdue?"Deadline overschreden":"Komt eraan"}</Status></Link>):<Empty>Er zijn geen naderende deadlines of open signalen.</Empty>}</section>
   <section className="dossier-card">{sectionHeader("Dossiercheck","Een controle op vastlegging, geen beoordeling van de medewerker.")}<div className="dossier-checklist">{[["Contract vastgelegd",!!contract,"contracten"],["Zakelijk contact aanwezig",!!person.email,"persoon"],["Vereiste kwalificaties aanwezig",missingCodes.length===0,"certificaten"],["Getekend contractbewijs gekoppeld",!!contract&&contract.data.signatureStatus==="signed","documenten"]].map(([label,done,target])=><Link key={String(label)} href={href(target as DossierTab)}><CheckCircle2 size={17}/><span>{label}</span><Status tone={done?"green":"amber"}>{done?"Vastgelegd":"Controleren"}</Status></Link>)}</div><p className="dossier-muted">Foto en noodcontact zijn optioneel. Vereisten hangen af van dienstverband en werkzaamheden.</p></section></div>
   <section className="dossier-card">{sectionHeader("Indiensttreding & uitdiensttreding","Registreer noodzakelijke stappen en het bewijs van uitvoering.",<><button className="secondary-button" disabled={checklistPending} onClick={()=>createChecklist("onboarding")}>Indienstchecklist voor mij</button><button className="secondary-button" disabled={checklistPending} onClick={()=>createChecklist("offboarding")}>Uitdienstchecklist voor mij</button>{add("checklist","Onderdeel toevoegen")}</>)}{data.records.some(r=>r.kind==="checklist")?data.records.filter(r=>r.kind==="checklist").map(r=><button className="dossier-event" id={`record-${r.id}`} key={r.id} onClick={()=>setEditor({kind:"checklist",record:r})}><CheckCircle2 size={18}/><span><strong>{r.title}</strong><small>{r.data.checklistType==="offboarding"?"Uitdiensttreding":"Indiensttreding"} · {date(r.dueOn)}</small></span><Status>{labels[r.status]||r.status}</Status></button>):<Empty>Voeg bijvoorbeeld contractcontrole, introductie, veiligheidsinstructies of retour van middelen toe.</Empty>}</section>
   <section className="dossier-card">{sectionHeader("Recent in het dossier","Gebeurtenissen zonder vertrouwelijke inhoud in de samenvatting.")}<Timeline data={data} href={href}/></section>
  </>}
  {tab==="persoon"&&<section className="dossier-card">{sectionHeader("Persoonsgegevens","Functie, team, leidinggevende en contracturen komen uit de actuele overeenkomst.",<button className="primary-button" onClick={editProfile}><Pencil size={16}/>Gegevens bewerken</button>)}<dl className="dossier-facts">{dossierDefinitions.profile.fields.filter(f=>profileValues[f.key]).map(f=><div key={f.key}><dt>{f.label}</dt><dd>{f.options?.find(([key])=>key===profileValues[f.key])?.[1]||String(profileValues[f.key])}</dd></div>)}<div><dt>Functie</dt><dd>{functionName}</dd></div><div><dt>Startdatum</dt><dd>{date(contract?.data.startsOn||person.start_date)}</dd></div><div><dt>Accountstatus</dt><dd>{data.accountStatus?(labels[data.accountStatus]||"Niet actief"):"Geen portaalaccount"} · los van het dienstverband</dd></div></dl></section>}
  {tab==="contracten"&&<>{sectionHeader("Dienstverband & contracten","Actuele, toekomstige en historische overeenkomsten. Verlengingen behouden het vorige record.",add("contract","Nieuwe overeenkomst"))}{showRecords(["contract"])}</>}
  {tab==="certificaten"&&<>{sectionHeader("Certificaten & bevoegdheden","Verificatie en geldigheid worden afzonderlijk bijgehouden.",<><button className="secondary-button" onClick={()=>setCatalog(true)}>Catalogus & eisen</button>{add("vog","VOG-controle")}{add("certificate","Certificaat toevoegen")}</>)}{missingCodes.length>0&&<p className="dossier-notice">Ontbrekende functie-eisen: {missingCodes.join(", ")}. Controleer bewijs en de volledige uitvoeringsperiode.</p>}{gaps.length>0&&<section className="dossier-card"><h3>Controleer geplande inzet</h3><p>Deze vereisten worden niet gehaald voor de volledige uitvoeringsperiode.</p>{gaps.map(g=>{const a=assignments.find(a=>a.id===g.assignment_id);const w=orders.find(w=>w.id===a?.work_order_id);return <Link className="dossier-event" key={`${g.assignment_id}:${g.code}`} href={href("inzet",g.assignment_id)}><span><strong>{w?.work_order_number} · {g.code}</strong><small>{date(a?.projected_start_at)} – {date(a?.projected_end_at)}</small></span><Status tone={g.hard_requirement?"danger":"amber"}>{g.hard_requirement?"Harde eis ontbreekt":"Waarschuwing"}</Status></Link>;})}</section>}{showRecords(["certificate","vog"])}<section className="dossier-card"><h3>Ingestelde werkgerelateerde eisen</h3>{data.requirements.length?data.requirements.map(r=><div className="dossier-event" key={r.id}><span><strong>{r.code} · {({function:"Functie",service:"Werkzaamheden",customer:"Klant",object:"Object",work_order:"Werkbon"} as Record<string,string>)[r.scope]}</strong><small>{r.service_name||workspace.functions.find(f=>f.id===r.subject_id)?.name||workspace.customers.find(c=>c.id===r.subject_id)?.name||workspace.objects.find(o=>o.id===r.subject_id)?.name||workspace.workOrders.find(w=>w.id===r.subject_id)?.work_order_number} · {r.hard_requirement?"Harde eis":"Waarschuwing"}</small></span><Status>{r.active?"Actief":"Gepauzeerd"}</Status><button className="resource-action" disabled={checklistPending} onClick={()=>toggleRequirement(r.id,!r.active)}>{r.active?"Pauzeren":"Hervatten"}</button></div>):<p>Er zijn nog geen aanvullende eisen ingesteld. Bestaande functie-eisen blijven gelden.</p>}</section></>}
  {tab==="ontwikkeling"&&<>{sectionHeader("Beoordelingen & ontwikkeling","Plan gesprekken, bewaar conceptverslagen en maak afspraken met concrete opvolging.",<>{add("review","Gesprek plannen")}<button className="secondary-button" onClick={()=>setEditor({kind:"review",initialValues:{startsOn:today}})}>Verslag toevoegen</button></>)}{showRecords(["review"])}</>}
  {tab==="middelen"&&<>{sectionHeader("Bedrijfsmiddelen & toegang","Uitgifte, ontvangst, retour en feitelijke schade. Geen toegangsrollen of geheime codes.",add("asset","Middel uitgeven"))}{showRecords(["asset"])}<p className="dossier-notice">Accountstatus: {data.accountStatus?(labels[data.accountStatus]||"Niet actief"):"Geen portaalaccount"}. Afsluiten van toegang verloopt via het bestaande accountproces; archiveren van het dossier wist geen account.</p></>}
  {tab==="verzuim"&&<>{sectionHeader("Verzuim & re-integratie","Afgeschermde administratieve procesgegevens, zonder medische inhoud.",add("absence","Melding registreren"))}<p className="dossier-notice">Arbodienstkoppeling en een gevalideerde cao-/procesconfiguratie zijn niet aangesloten. Registreer afgestemde afspraken handmatig; dit is geen volledige juridische automatisering. De planning ziet alleen ‘Niet beschikbaar’.</p>{showRecords(["absence"])}</>}
  {tab==="notities"&&<>{sectionHeader("Notities & afspraken","Feitelijke, noodzakelijke informatie. Melding, onderzoek en conclusie blijven onderscheiden.",add("note","Notitie toevoegen"))}<p className="dossier-notice">Vertrouwelijk HR. ‘Intern’ is geen uitzondering op inzagerechten. Geen privé- of medische dossiers verzamelen.</p>{showRecords(["note"])}</>}
  {tab==="documenten"&&<>{sectionHeader("Documenten","Eén bestand, meerdere relaties. Vorige versies blijven behouden.",<button className="primary-button" onClick={()=>setUpload({})}><Plus size={16}/>Document toevoegen</button>)}<div className="dossier-toolbar"><label>Zoeken<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Zoek document…"/></label><label>Categorie<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Alle categorieën</option>{Object.entries(documentLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Sorteren<select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Nieuwste eerst</option><option value="name">Titel A–Z</option></select></label></div><section className="dossier-card"><div className="table-scroll"><table className="resource-table"><thead><tr>{["Document","Categorie","Versie","Datum","Classificatie","Acties"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.documents.filter(d=>d.title.toLowerCase().includes(query.toLowerCase())&&(!statusFilter||d.document_type===statusFilter)).sort((a,b)=>sort==="name"?a.title.localeCompare(b.title):b.created_at.localeCompare(a.created_at)).map(d=><tr key={d.id} id={`record-${d.id}`}><td><strong>{d.title}</strong><small>{d.file_name}</small>{data.records.filter(r=>(r.data.document_ids as string[]??[]).includes(d.id)).map(r=><small key={r.id}><Link href={href(dossierDefinitions[r.kind].tab,r.id)}>{r.title}</Link></small>)}<small>Uploader: {data.owners.find(o=>o.id===d.created_by)?.label||"Bevoegde beheerder"}</small></td><td>{documentLabels[d.document_type]||d.document_type}</td><td>v{d.version}{d.previous_id&&<small>Vervolgversie</small>}</td><td>{date(d.created_at)}<small>Document: {date((d.dossier_data as Record<string,Json>)?.documentDate)}</small></td><td>{d.dossier_managed?"Vertrouwelijk HR":d.visible_to_employee?"Gedeeld met medewerker":"Intern"}<small>Bewaarbeleid: {String((d.dossier_data as Record<string,Json>)?.retention||"Nog te beoordelen")}</small></td><td><div className="resource-actions"><a className="resource-action" href={`/api/files/personnel-document/${d.id}`} target="_blank" rel="noreferrer">Bekijk / download</a>{d.dossier_managed&&<button className="resource-action" onClick={()=>setUpload({previous:d,metadataOnly:true})}>Metadata bewerken</button>}<button className="resource-action" onClick={()=>setUpload({previous:d})}>Nieuwe versie</button><button className="resource-action" onClick={()=>openHistory(d.id)}>Historie</button></div></td></tr>)}</tbody></table></div>{!data.documents.length&&<Empty>Nog geen documenten. Upload het eerste noodzakelijke document.</Empty>}<p className="dossier-muted">Bestandstype en grootte worden gecontroleerd. Malwarecontrole en externe digitale ondertekening zijn niet aangesloten. Bewaarbeleid wordt per document vastgelegd; verwijderen is een afzonderlijk proces.</p></section></>}
  {tab==="inzet"&&<>{sectionHeader("Inzet & werkhistorie","Rechtstreeks uit de bestaande planning en werkbonnen.",<Link className="secondary-button" href="/app/planning">Open planbord</Link>)}<section className="dossier-card"><h3>Beschikbaarheid</h3>{workspace.availability.filter(a=>a.personnel_id===person.id).map(a=><p key={a.id}>{date(a.starts_at)} – {date(a.ends_at)} · {a.kind==="available"?"Beschikbaar":"Niet beschikbaar"}</p>)}{!workspace.availability.some(a=>a.personnel_id===person.id)&&<p>Geen uitzonderingen geregistreerd.</p>}</section><section className="dossier-card"><div className="table-scroll"><table className="resource-table"><thead><tr><th>Werkbon</th><th>Klant / object</th><th>Uitvoering</th><th>Status</th><th>Vastgelegde eisen</th></tr></thead><tbody>{orders.map(order=>{const assignment=assignments.find(a=>a.work_order_id===order.id)!;return <tr key={order.id} id={`record-${assignment.id}`}><td><Link href={`/app/werkbonnen/${order.id}`}>{order.work_order_number}</Link></td><td><Link href={`/app/klanten?record=${order.customer_id}`}>{workspace.customers.find(c=>c.id===order.customer_id)?.name}</Link><small><Link href={`/app/objecten?record=${order.object_id}`}>{workspace.objects.find(o=>o.id===order.object_id)?.name}</Link></small></td><td>{date(assignment.projected_start_at)}<small>{date(assignment.projected_end_at)}</small></td><td>{labels[order.status]||({planned:"Gepland",released:"Vrijgegeven",invoiced:"Gefactureerd",cancelled:"Geannuleerd"} as Record<string,string>)[order.status]||"In uitvoering"}</td><td>{gaps.filter(g=>g.assignment_id===assignment.id).map(g=><p key={g.code}><Status tone={g.hard_requirement?"danger":"amber"}>{g.code} · {g.hard_requirement?"Harde eis ontbreekt":"Controleren"}</Status></p>)}{Array.isArray(assignment.qualification_snapshot)&&assignment.qualification_snapshot.length?`${assignment.qualification_snapshot.length} eisen vastgelegd`:"Geen eisen vastgelegd"}</td></tr>;})}</tbody></table></div>{!orders.length&&<Empty>Er zijn nog geen gekoppelde werkbonnen.</Empty>}</section></>}
  {tab==="uren"&&<>{sectionHeader("Uren & verlof","De bestaande urenregistratie en beschikbaarheid blijven leidend.")}<label className="dossier-period">Periode<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><div className="dossier-metrics"><div className="dossier-metric"><span><Clock3/>Geregistreerd</span><strong>{hours(periodEntries.filter(e=>e.kind!=="break"))} uur</strong></div><div className="dossier-metric"><span>Goedgekeurd</span><strong>{hours(periodEntries.filter(e=>e.status==="approved"&&e.kind!=="break"))} uur</strong></div><div className="dossier-metric"><span>Gepland</span><strong>{assignments.filter(a=>businessToday(new Date(a.projected_start_at)).slice(0,7)===period&&a.status!=="cancelled").reduce((s,a)=>s+(new Date(a.projected_end_at).getTime()-new Date(a.projected_start_at).getTime())/3600000,0).toLocaleString("nl-NL")} uur</strong></div><div className="dossier-metric"><span>Actuele contracturen</span><strong>{contract?.data.hours||"—"} / week</strong></div></div><p className="dossier-notice">Verlofsaldi, salarisverwerking en automatische overurenberekening zijn niet gekoppeld. Contracturen kunnen per ingangsdatum verschillen; er wordt geen fictief saldo getoond.</p><section className="dossier-card">{periodEntries.map(e=><div className="dossier-event" key={e.id}><Clock3 size={16}/><span><strong>{date(e.starts_at)}</strong><small>{({work:"Werk",travel:"Reis",break:"Pauze",correction:"Correctie"} as Record<string,string>)[e.kind]} · {hours([e])} uur</small></span><Status>{labels[e.status]||"In behandeling"}</Status>{e.assignment_id&&<Link className="resource-action" href={`/app/werkbonnen/${workspace.assignments.find(a=>a.id===e.assignment_id)?.work_order_id}`}>Bekijk werkbon</Link>}</div>)}{!periodEntries.length&&<Empty>Geen uren in deze periode.</Empty>}</section><section className="dossier-card"><h3>Verlofregistraties</h3>{workspace.availability.filter(a=>a.personnel_id===person.id&&a.kind==="leave").map(a=><p key={a.id}>{date(a.starts_at)} – {date(a.ends_at)} · {a.approved_at?"Goedgekeurd":"In behandeling"}</p>)}{!workspace.availability.some(a=>a.personnel_id===person.id&&a.kind==="leave")&&<p>Nog geen verlof geregistreerd.</p>}</section></>}
  {tab==="tijdlijn"&&<>{sectionHeader("Tijdlijn & taken","Taken en verzendingen hebben een afzonderlijke status. Gelezen betekent niet afgehandeld.",add("task","Taak toevoegen"))}{showRecords(["task","checklist"])}<section className="dossier-card"><h3>Gebeurtenissen</h3><Timeline data={data} href={href} filters/></section><section className="dossier-card"><h3>Reminderverzendingen</h3><p>Servergestuurde verwerking via de bestaande worker. Stel ontvangers expliciet per registratie in.</p>{data.deliveries.map(d=><div className="dossier-event" key={d.id}><CalendarDays size={16}/><span><strong>{date(d.due_on)}</strong><small>{d.recipient_user_id?"In-app · geselecteerde verantwoordelijke":d.recipient} · {d.attempts} pogingen</small>{d.last_error&&<small>{d.last_error}</small>}</span><Status tone={d.status==="failed"||d.status==="uncertain"?"danger":"neutral"}>{labels[d.status]}</Status></div>)}{!data.deliveries.length&&<Empty>Geen verzendingen gepland. Kies een deadline, ontvanger en herinneringsmoment.</Empty>}</section></>}

  {editor&&<DossierRecordEditor key={`${editor.kind}:${editor.record?.id||editor.previousId||"new"}`} {...common} {...editor} data={data} workspace={workspace} onClose={()=>setEditor(null)}/>}
  {upload&&<DossierUpload {...common} {...upload} onClose={()=>setUpload(null)}/>}
  {catalog&&<QualificationCatalogEditor {...common} workspace={workspace} data={data} onClose={()=>setCatalog(false)}/>}
  {versions&&<Dialog open onOpenChange={open=>{if(!open)setVersions(null);}}><DialogContent className="dossier-dialog" style={brandThemeStyle(tenant.primaryColor,tenant.accentColor)} showCloseButton={false}><header><div><DialogTitle>Versiehistorie</DialogTitle><DialogDescription>Oude registraties blijven intact en zijn alleen hier in het afgeschermde dossier zichtbaar.</DialogDescription></div><button className="icon-button" aria-label="Sluiten" onClick={()=>setVersions(null)}><X/></button></header><div className="dossier-history">{versions.map((v,i)=>{const row=v as Record<string,Json>;const payload=(row.dossier_data??{}) as Record<string,Json>;return <section className="dossier-card" key={i}><h3>Versie {String(row.dossier_revision)} · {date(row.updated_at)}</h3><p>{data.owners.find(o=>o.id===row.updated_by)?.label||"Bevoegde beheerder"}</p><dl>{Object.entries(payload).filter(([key])=>!["document_ids","generatedFrom","relatedId","ownerId","managerId"].includes(key)).map(([key,value])=><div key={key}><dt>{Object.values(dossierDefinitions).flatMap(d=>d.fields).find(f=>f.key===key)?.label||key}</dt><dd>{String(value)}</dd></div>)}</dl></section>;})}{!versions.length&&<Empty>Van deze oudere registratie is nog geen dossierhistorie beschikbaar.</Empty>}</div></DialogContent></Dialog>}
 </div>;
}

function Timeline({data,href,filters=false}:{data:DossierData;href:(tab:DossierTab,id?:string)=>string;filters?:boolean}) {
 const [type,setType]=useState("");const [period,setPeriod]=useState("");
 const events=data.history.filter(e=>(!type||e.source_table===type)&&(!period||businessToday(new Date(e.created_at)).slice(0,7)===period));
 return <>{filters&&<div className="dossier-toolbar"><label>Gebeurtenistype<select value={type} onChange={e=>setType(e.target.value)}><option value="">Alle gebeurtenissen</option>{[["personnel_contracts","Contract"],["certificates","Certificaat"],["personnel_documents","Document"],["personnel_notes","Notitie"],["personnel_dossier_items","Overige dossierregistraties"]].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Maand<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label></div>}{events.length?<div>{events.slice(0,filters?250:10).map(event=>{const record=data.records.find(r=>r.id===event.source_id);return <Link className="dossier-event" key={event.id} href={href(record?dossierDefinitions[record.kind].tab:"documenten",event.source_id)}><History size={17}/><span><strong>{event.source_table==="personnel_documents"?"Document":record?dossierDefinitions[record.kind].title:"Dossierregistratie"} {event.revision===1?"toegevoegd":"bijgewerkt"}</strong><small>{date(event.created_at)} · versie {event.revision} · {data.owners.find(o=>o.id===event.actor_user_id)?.label||"Bevoegde beheerder"}</small></span><ArrowUpRight size={16}/></Link>;})}</div>:<Empty>Nog geen dossiergebeurtenissen voor deze selectie.</Empty>}</>;
}
