"use client";
import { ArrivalSettings } from "../travel-settings";
import { WorkOrderSignatureSettings } from "../work-orders/settings";
import {DossierChainPanel} from "../dossier-chain";
import {CommercialDossierPanel} from "../commercial/dossier-panel";
import {useState,type ReactNode} from "react";
import Link from "next/link";
import {ArrowLeft,Plus,Pencil,CalendarDays,FileText,CheckCircle2,MapPin,History,Building2} from "lucide-react";
import type {TenantContext} from "@/lib/auth/context";
import {objectTabs,objectStates,objectTypes,recordStates,nodeKinds,objectDate,addressLine,valuesOf,type ObjectData,type ObjectTab,type RecordKind,type Row} from "@/lib/objects/model";
import {objectRecordVersions,reviewObjectRequest,saveCustomerObjectBinding,extendObjectAccess,saveObjectRequirement,setObjectReminderRecipient} from "@/app/app/objecten/actions";
import type {Json} from "@/lib/database.types";
import {ObjectDialog,ObjectForm,ObjectWizard,NodeEditor,RecordEditor,DocumentEditor,Choice} from "./forms";
import {VaultCard} from "./vault-card";

type Editor={kind:"node";node?:Row<"object_nodes">}|{kind:"record";recordKind:RecordKind;record?:Row<"object_records">}|{kind:"document";previous?:Row<"object_documents">}|{kind:"object"}|{kind:"request";request:Row<"object_visit_requests">}|null;
const Empty=({children}:{children:ReactNode})=><p className="dossier-empty">{children}</p>;
const Chip=({value}:{value:string})=><span className={`resource-status resource-status-${["active","completed","accepted"].includes(value)?"green":"neutral"}`}>{recordStates[value]||value}</span>;
export function ObjectDossier({data,tenant,tab}:{data:ObjectData;tenant:TenantContext;tab:ObjectTab}){
 const o=data.object;const [editor,setEditor]=useState<Editor>(null);const [versions,setVersions]=useState<Json[]|null>(null);const [historyError,setHistoryError]=useState("");
 const href=(target:ObjectTab)=>`/app/objecten/${o.id}?tab=${target}`;
 const common={data,tenant,onClose:()=>setEditor(null)};
 const add=(kind:RecordKind,label:string)=> <button className="primary-button" onClick={()=>setEditor({kind:"record",recordKind:kind})}><Plus size={16}/>{label}</button>;
 const history=async(id:string)=>{const r=await objectRecordVersions(o.id,id);if(r.ok){setVersions(r.versions);setHistoryError("");}else setHistoryError(r.error);};
 const section=(title:string,description:string,action?:ReactNode)=><div className="object-section-title"><div><h2>{title}</h2><p>{description}</p></div>{action&&<div className="object-actions">{action}</div>}</div>;
 const records=(kinds:RecordKind[])=>{const rows=data.records.filter(r=>kinds.includes(r.kind as RecordKind));return rows.length?<div className="object-records">{rows.map(r=><article className="object-record" id={`record-${r.id}`} key={r.id}><header><div><span className="eyebrow">{data.nodes.find(n=>n.id===r.node_id)?.name||"Gehele object"} · versie {r.version}</span><h3>{r.title}</h3></div><Chip value={r.state}/></header><p className="object-prose">{r.body}</p><dl className="object-inline-facts">{r.service&&<div><dt>Dienst</dt><dd>{r.service}</dd></div>}{r.due_on&&<div><dt>Opvolgen vóór</dt><dd>{r.due_on}</dd></div>}{r.work_order_id&&<div><dt>Alleen afspraak</dt><dd><Link href={`/app/werkbonnen/${r.work_order_id}`}>{data.orders.find(w=>w.id===r.work_order_id)?.work_order_number}</Link></dd></div>}{r.instruction_type&&<div><dt>Geldigheid</dt><dd>{({fixed:"Vast",temporary:"Tijdelijk",appointment:"Afspraakgebonden"})[r.instruction_type]} · {objectDate(r.starts_at,tenant.timezone)}{r.ends_at&&` tot ${objectDate(r.ends_at,tenant.timezone)}`}</dd></div>}</dl>{Object.entries(valuesOf(r.details)).filter(([,v])=>v).map(([k,v])=><p className="dossier-muted" key={k}>{({category:"Categorie",frequency:"Frequentie",window:"Venster",checklist:"Checklist",equipment:"Middelen",evidence:"Resultaat / opvolging",quantity:"Hoeveelheid",unit:"Eenheid",acknowledgement:"Leesbevestiging vereist"} as Record<string,string>)[k]||k}: {v===true?"Ja":String(v)}</p>)}<footer><button className="resource-action" onClick={()=>setEditor({kind:"record",recordKind:r.kind as RecordKind,record:r})}><Pencil size={14}/>Bewerken</button><button className="resource-action" onClick={()=>void history(r.id)}><History size={14}/>Versies</button></footer></article>)}</div>:<Empty>Nog geen registraties. Voeg de gegevens toe die voor dit object nodig zijn.</Empty>;};
 const visits=(showReports=false)=><section className="dossier-card">{section(showReports?"Werkbonnen & rapporten":"Concrete afspraken","Dezelfde uitvoeringen als in het planbord en de werkbonnenmodule.",<Link className="secondary-button" href="/app/planning"><CalendarDays size={16}/>Planbord openen</Link>)}<div className="object-records">{data.orders.map(w=><article className="object-record" key={w.id}><header><div><Link href={`/app/werkbonnen/${w.id}`}><h3>{w.work_order_number}</h3></Link><p>{w.discipline} · {objectDate(w.projected_start_at,tenant.timezone)}</p></div><span className="resource-status">{({planned:"Gepland",released:"Vrijgegeven",seen:"Gezien",travelling:"Onderweg",in_progress:"In uitvoering",completed:"Uitgevoerd",returned:"Teruggestuurd",under_review:"In controle",correction_required:"Correctie nodig",approved:"Goedgekeurd",invoice_ready:"Klaar voor facturatie",invoiced:"Gefactureerd",cancelled:"Geannuleerd"})[w.status]}</span></header><p>{data.assignments.filter(a=>a.work_order_id===w.id&&a.status!=="cancelled").map(a=>data.personnel.find(p=>p.id===a.personnel_id)?.full_name||"Medewerker").join(", ")||"Nog geen medewerkers toegewezen"}</p><p>{data.requests.filter(r=>r.work_order_id===w.id&&r.needs_review).length} verzoeken te beoordelen</p>{showReports&&data.reports.filter(r=>r.work_order_id===w.id).map(r=><blockquote key={r.id}>{r.body}<small>{objectDate(r.created_at,tenant.timezone)}</small></blockquote>)}<footer><Link className="resource-action" href={`/app/werkbonnen/${w.id}`}>Werkbon openen</Link><Link className="resource-action" href={href("instructies")}>Instructies en verzoeken</Link></footer></article>)}</div>{!data.orders.length&&<Empty>Nog geen bezoeken gepland. Plan een werkbon via het bestaande planbord.</Empty>}{showReports&&<Link className="text-link" href="/app/rapporten">Naar rapportcontrole en bestaande facturatie</Link>}</section>;
 const next=data.orders.filter(w=>!["completed","cancelled","returned","under_review","approved","invoice_ready","invoiced"].includes(w.status)).sort((a,b)=>(a.projected_start_at||"z").localeCompare(b.projected_start_at||"z"))[0];
 const open=data.records.filter(r=>["open","progress"].includes(r.state));
 const pendingRequests=data.requests.filter(r=>r.needs_review);
 const tree=(parent:string|null,depth=0):ReactNode=><ul className="object-tree" aria-label={depth===0?"Locatieonderdelen":undefined}>{data.nodes.filter(n=>n.parent_id===parent).map(n=><li key={n.id}><article><Building2 size={18}/><div><strong>{n.name}</strong><small>{nodeKinds[n.kind as keyof typeof nodeKinds]}{n.code&&` · ${n.code}`}{!n.active&&" · Gearchiveerd"}</small><small>{String(valuesOf(n.details).address||"")}</small></div><button className="resource-action" onClick={()=>setEditor({kind:"node",node:n})}>Bewerk</button><button className="resource-action" onClick={()=>void history(n.id)}>Historie</button></article>{depth<6&&tree(n.id,depth+1)}</li>)}</ul>;
 return <div className="object-dossier">
 <Link className="dossier-back" href="/app/objecten"><ArrowLeft size={16}/>Terug naar objecten</Link>
 <header className="page-intro resource-intro"><div><span className="eyebrow">{o.object_number} · {objectTypes[o.object_type as keyof typeof objectTypes]||o.object_type}</span><h1>{o.name}</h1><p><Link href={`/app/klanten?record=${o.customer_id}`}>{data.customer.name}</Link> · {addressLine(o.address)}</p><span className="resource-status">{objectStates[o.dossier_status as keyof typeof objectStates]}</span></div><div className="object-actions"><button className="secondary-button" onClick={()=>setEditor({kind:"object"})}><Pencil size={16}/>Bewerken</button><Link className="secondary-button" href="/app/planning"><CalendarDays size={16}/>Planning</Link><button className="primary-button" onClick={()=>setEditor({kind:"record",recordKind:"instruction"})}><Plus size={16}/>Instructie toevoegen</button></div></header>
 <nav className="dossier-tabs object-tabs" aria-label="Objectdossier tabbladen">{objectTabs.map(([k,label])=><Link key={k} href={href(k)} className={tab===k?"active":""} aria-current={tab===k?"page":undefined}>{label}</Link>)}</nav>
 {tab==="overzicht"&&<>
 <div className="object-metrics">{[["Volgende uitvoering",next?objectDate(next.projected_start_at,tenant.timezone):"Nog niet gepland","afspraken"],["Verzoeken",`${pendingRequests.length} te beoordelen`,"instructies"],["Open acties",String(open.filter(r=>r.kind==="task").length),"instructies"],["Laatste rapport",data.reports[0]?objectDate(data.reports[0].created_at,tenant.timezone):"Nog geen rapport","werkbonnen"]].map(([label,value,target])=><Link className="dossier-card" href={href(target as ObjectTab)} key={label}><small>{label}</small><strong>{value}</strong></Link>)}</div>
 <div className="dossier-columns"><section className="dossier-card">{section("Aandacht & opvolging","Actuele verzoeken, kwaliteitsmeldingen en praktische acties.")}{pendingRequests.map(r=><Link className="dossier-event" key={r.id} href={href("instructies")}><FileText size={18}/><span><strong>{r.title}</strong><small>Verzoek bij {data.orders.find(w=>w.id===r.work_order_id)?.work_order_number} · beoordeling nodig</small></span></Link>)}{open.map(r=><Link key={r.id} className="dossier-event" href={href(r.kind==="quality"?"kwaliteit":r.kind==="material"?"materialen":"instructies")}><CheckCircle2 size={18}/><span><strong>{r.title}</strong><small>{r.due_on?`Opvolgen vóór ${r.due_on}`:"Nog geen deadline"}</small></span></Link>)}{!open.length&&!pendingRequests.length&&<Empty>Geen open aandachtspunten.</Empty>}</section>
 <section className="dossier-card">{section("Dossiercheck","Controleer wat nodig is om veilig en goed voorbereid te starten.")}<div className="dossier-checklist">{[["Klant en locatie",!!o.customer_id&&!!addressLine(o.address),"locatie"],["Bereikbaarheid",data.contacts.length>0||data.records.some(r=>r.kind==="contact"),"contact"],["Werkprogramma",data.records.some(r=>r.kind==="programme"),"diensten"],["Veiligheidsinstructies beoordeeld",data.records.some(r=>r.kind==="instruction"&&r.state==="active"),"instructies"]].map(([label,done,target])=><Link href={href(target as ObjectTab)} key={String(label)}><CheckCircle2 size={17}/><span>{label}</span><span>{done?"Vastgelegd":"Nog controleren"}</span></Link>)}</div><p className="dossier-muted">Niet ieder object heeft dezelfde vereisten. De kluis toont hier nooit geheime waarden.</p></section></div></>}
 {tab==="overzicht"&&<ArrivalSettings object={o}/>}
 {tab==="locatie"&&<><section className="dossier-card">{section("Locatie & structuur","Optionele gebouwen, verdiepingen, zones, ruimten en onderdelen.",<button className="primary-button" onClick={()=>setEditor({kind:"node"})}><Plus size={16}/>Onderdeel toevoegen</button>)}<p><MapPin size={16}/>{addressLine(o.address)}</p><p>{o.location_description}</p>{o.latitude!==null&&<p>Coördinaten: {o.latitude}, {o.longitude}</p>}{data.nodes.length?tree(null):<Empty>Geen onderverdeling nodig? Laat dit leeg. Anders kun je hierboven een eerste onderdeel toevoegen.</Empty>}</section></>}
 {tab==="contact"&&<><section className="dossier-card">{section("Klantcontacten","De bestaande contactpersonen uit het klantdossier.",<Link className="secondary-button" href={`/app/klanten?record=${o.customer_id}`}>Klantdossier openen</Link>)}{data.contacts.map(c=><article className="dossier-event" key={c.id}><div><strong>{c.full_name}</strong><small>{[c.role,c.email,c.phone].filter(Boolean).join(" · ")}</small></div></article>)}{!data.contacts.length&&<Empty>Nog geen contactpersonen bij deze klant.</Empty>}</section><section className="dossier-card">{section("Locatiecontact & bereikbaarheid","Openingstijden, aanmelden, parkeren, laden/lossen en noodprocedures.",add("contact","Gegevens toevoegen"))}{records(["contact"])}</section>
 {tenant.roles.some(r=>["tenant_admin","management"].includes(r))&&<section className="dossier-card">{section("Klanttoegang tot dit object","Alleen voor een gecontroleerd bestaand account. Een contactpersoon krijgt niet automatisch toegang.")}<ObjectForm action={saveCustomerObjectBinding}><input type="hidden" name="objectId" value={o.id}/><label>Geverifieerd e-mailadres van de klant<input name="email" type="email" required placeholder="E-mailadres van het bestaande klantaccount"/></label><p className="dossier-notice wide">Controleer vooraf dat dit account bij deze klant hoort. Hiermee geef je expliciet toegang tot de bezoeken en gedeelde verzoeken van dit object. Dit verstuurt geen accountuitnodiging.</p><label>Binding<select name="active"><option value="true">Actief</option><option value="false">Intrekken</option></select></label><label className="dossier-check wide"><input type="checkbox" name="manageSecrets"/>Deze klant mag ook beveiligde objectgegevens beheren na e-mailverificatie</label></ObjectForm><p className="dossier-muted">{data.bindings.filter(b=>b.active).length} actieve bindingen · klantomgeving: /klant</p>{data.bindings.map(b=><p key={b.id}>{data.customerAccounts.find(u=>u.user_id===b.user_id)?.email||"Account niet meer beschikbaar"} · {b.active?"Actief":"Ingetrokken"}{b.manage_secrets?" · Kluisbeheer":""}</p>)}</section>}</>}
 {tab==="toegang"&&<><section className="dossier-card">{section("Normale toegangsprocedure","Praktische voorbereiding zonder alarm- of kluiscodes.",add("access","Procedure toevoegen"))}<p className="object-prose">{o.access_instructions||"Nog geen algemene bezoekprocedure vastgelegd."}</p>{records(["access"])}</section><VaultCard objectId={o.id} nodes={data.nodes.filter(n=>n.active)} assignments={data.assignments.filter(a=>!["completed","cancelled","returned"].includes(a.status)).map(a=>({id:a.id,label:`${data.orders.find(w=>w.id===a.work_order_id)?.work_order_number} · ${data.personnel.find(p=>p.id===a.personnel_id)?.full_name}`}))}/>
 <section className="dossier-card">{section("Uitloop van een concrete uitvoering","Een expliciete uitzondering van maximaal vier uur. De medewerker moet opnieuw verifiëren.")}<ObjectForm action={extendObjectAccess}><input name="objectId" type="hidden" value={o.id}/><Choice name="assignmentId" label="Actuele medewerkerstoewijzing" required options={data.assignments.filter(a=>["released","seen","travelling","in_progress"].includes(a.status)).map(a=>[a.id,`${data.orders.find(w=>w.id===a.work_order_id)?.work_order_number} · ${data.personnel.find(p=>p.id===a.personnel_id)?.full_name}`])}/><label>Toegang eindigt op ({tenant.timezone})<input name="endsAt" type="datetime-local" required/></label><label className="wide">Reden voor uitloop<textarea name="reason" required minLength={5}/></label></ObjectForm></section></>}
 {tab==="diensten"&&<><section className="dossier-card">{section("Diensten & werkprogramma","Koppel de afgesproken omvang aan bestaande catalogusversies. Een concept is nog geen goedgekeurde uitbreiding.",add("programme","Werkprogramma toevoegen"))}{records(["programme"])}</section><section className="dossier-card">{section("Kwalificatie-eisen","Dezelfde catalogus en bewijzen als in Personeel 360; controle over de volledige uitvoering.")}{data.requirements.map(r=><p key={r.id}>{data.qualificationTypes.find(q=>q.code===r.code)?.name||r.code} · {r.hard_requirement?"Verplicht":"Signalering"} · {r.active?"Actief":"Gepauzeerd"}</p>)}<ObjectForm action={saveObjectRequirement}><input name="objectId" type="hidden" value={o.id}/><Choice name="code" label="Bestaand kwalificatietype" required options={data.qualificationTypes.map(q=>[q.code,q.name])}/><label className="dossier-check"><input type="checkbox" name="hard" defaultChecked/>Verplicht voor inzet</label></ObjectForm><Link className="text-link" href="/app/personeel/acties">Bekijk toekomstige inzetproblemen</Link></section></>}
 {tab==="afspraken"&&visits()}
 {tab==="diensten"&&<WorkOrderSignatureSettings objectId={o.id}/>}
 {tab==="commercieel"&&<CommercialDossierPanel customerId={o.customer_id} objectId={o.id} timezone={tenant.timezone}/>}
 {tab==="werkbonnen"&&visits(true)}
 {tab==="instructies"&&<><section className="dossier-card">{section("Klantverzoeken per bezoek","Lezen betekent niet dat uitvoering of extra kosten zijn goedgekeurd.")}{data.requests.map(r=><article key={r.id} id={`request-${r.id}`} className="object-record"><header><h3>{r.title}</h3><Chip value={r.state}/></header><p>{r.body}</p><small>{data.orders.find(w=>w.id===r.work_order_id)?.work_order_number} · {objectDate(r.created_at,tenant.timezone)} · versie {r.version}</small>{r.needs_review&&<p className="dossier-notice">Beoordeling nodig{r.review_note?`: ${r.review_note}`:". Controleer scope, planning en capaciteit."}</p>}{r.response&&<p>Terugkoppeling: {r.response}</p>}{data.proposals.filter(p=>p.request_id===r.id).map(p=><p key={p.id}>Voorstel v{p.version}: {new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"}).format(p.price_cents*p.quantity/100)} excl. btw · {p.accepted_at?`Akkoord op ${objectDate(p.accepted_at,tenant.timezone)}`:"Nog geen akkoord"}</p>)}<footer><button className="secondary-button" onClick={()=>setEditor({kind:"request",request:r})}>Beoordelen / opvolgen</button><button className="resource-action" onClick={()=>void history(r.id)}>Versies</button></footer></article>)}{!data.requests.length&&<Empty>Nog geen klantverzoeken bij dit object.</Empty>}</section><section className="dossier-card">{section("Instructies & taken","Vaste, tijdelijke en bezoekgebonden instructies blijven afzonderlijk herkenbaar.",<>{add("instruction","Instructie toevoegen")}{add("task","Taak toevoegen")}</>)}{records(["instruction","task"])}</section></>}
 {tab==="kwaliteit"&&<section className="dossier-card">{section("Kwaliteit & incidenten","Controle, klacht, compliment, schade, toegang of veiligheid — met eigenaar en opvolging.",add("quality","Melding toevoegen"))}{records(["quality"])}</section>}
 {tab==="materialen"&&<section className="dossier-card">{section("Materialen & voorzieningen","Voorraad, middelen, water, stroom, opslag, tekort of defect. Personeelsuitgifte blijft bij het personeelsdossier.",add("material","Registratie toevoegen"))}{records(["material"])}</section>}
 {tab==="documenten"&&<section className="dossier-card">{section("Documenten & plattegronden","Private bestanden met locatie- en uitvoeringscontext. Malwarecontrole is niet aangesloten.",<button className="primary-button" onClick={()=>setEditor({kind:"document"})}><Plus size={16}/>Document toevoegen</button>)}{data.documents.map(d=><article className="dossier-event" key={d.id}><FileText size={20}/><div><strong>{d.title}</strong><small>Versie {d.version} · {data.nodes.find(n=>n.id===d.node_id)?.name||"Gehele object"} · {Math.ceil(d.size_bytes/1024)} KB{d.valid_until&&` · geldig tot ${d.valid_until}`}</small><small>{d.category==="security"?"Beveiligingsplattegrond: uitsluitend management":"Private objectopslag"} · Niet gescand</small></div><a className="resource-action" href={`/api/files/object-document/${d.id}`} target="_blank" rel="noreferrer">Openen</a><button className="resource-action" onClick={()=>setEditor({kind:"document",previous:d})}>Nieuwe versie</button></article>)}{!data.documents.length&&<Empty>Nog geen documenten. Voeg alleen noodzakelijke, gecontroleerde bestanden toe.</Empty>}</section>}
 {tab==="tijdlijn"&&<section className="dossier-card">{section("Tijdlijn","Objectwijzigingen en opvolging. Technische toegangslogs en geheime waarden staan hier nooit.")}{data.history.map(h=>{const s=valuesOf(h.snapshot);return <article className="dossier-event" key={h.id}><History size={18}/><div><strong>{String(s.title||s.name||"Objectregistratie")} · {h.event==="created"?"toegevoegd":"bijgewerkt"}</strong><small>{objectDate(h.created_at,tenant.timezone)} · versie {h.version}</small></div><button className="resource-action" onClick={()=>void history(h.source_id)}>Versies</button></article>;})}{!data.history.length&&<Empty>Nog geen dossierwijzigingen sinds de invoering van Object 360.</Empty>}</section>}
 {["overzicht","diensten","afspraken"].includes(tab)&&data.qualificationGaps.length>0&&<section className="dossier-card"><h2>Inzetbaarheid vraagt aandacht</h2>{data.qualificationGaps.map(g=>{const a=data.assignments.find(a=>a.id===g.assignment_id);return <p key={`${g.assignment_id}:${g.code}`}><Link href={`/app/werkbonnen/${a?.work_order_id}`}>{data.orders.find(w=>w.id===a?.work_order_id)?.work_order_number}</Link> · {data.personnel.find(p=>p.id===g.personnel_id)?.full_name} · {g.code}: {g.hard_requirement?"verplicht bewijs ontbreekt voor de volledige periode":"bewijs controleren"}</p>;})}</section>}
 {tab==="diensten"&&<DossierChainPanel scope={{objectId:o.id}} view="agreements" timezone={tenant.timezone}/>}
 {tab==="instructies"&&<DossierChainPanel scope={{objectId:o.id}} view="actions" timezone={tenant.timezone}/>}
 {tab==="documenten"&&<DossierChainPanel scope={{objectId:o.id}} view="documents" excludeSource="object" timezone={tenant.timezone}/>}
 {historyError&&<p role="alert">{historyError}</p>}
 {tab==="tijdlijn"&&<section className="dossier-card">{section("Herinneringen instellen","Deze ontvangers krijgen maximaal één dagelijkse in-appherinnering bij open verzoeken, deadlines, kwalificatieproblemen, aflopende toegang of materiaaltekorten. Zonder ontvanger wordt niets verstuurd.")}<ObjectForm action={setObjectReminderRecipient}><input name="objectId" type="hidden" value={o.id}/><Choice name="userId" label="Bestaande bevoegde ontvanger" required options={data.owners.map(u=>[u.id,u.label])}/><label>Herinneringen<select name="active"><option value="true">Inschakelen</option><option value="false">Uitschakelen</option></select></label></ObjectForm>{data.reminderRecipients.map(r=><p key={r.user_id}>{data.owners.find(u=>u.id===r.user_id)?.label||"Account niet meer actief"} · {r.active?"Ingeschakeld":"Uitgeschakeld"}</p>)}</section>}
 {editor?.kind==="object"&&<ObjectWizard tenant={tenant} object={o} customers={[data.customer]} onClose={()=>setEditor(null)}/>}
 {editor?.kind==="node"&&<NodeEditor {...common} node={editor.node}/>}
 {editor?.kind==="record"&&<RecordEditor {...common} kind={editor.recordKind} record={editor.record}/>}
 {editor?.kind==="document"&&<DocumentEditor {...common} previous={editor.previous}/>}
 {editor?.kind==="request"&&<ObjectDialog tenant={tenant} title="Verzoek beoordelen" description="Een reguliere taak is inbegrepen. Een meerwerkvoorstel vraagt afzonderlijk klantakkoord en blijft onder rapportcontrole." onClose={()=>setEditor(null)}><ObjectForm action={reviewObjectRequest} onSuccess={()=>setEditor(null)}><input name="objectId" type="hidden" value={o.id}/><input name="id" type="hidden" value={editor.request.id}/><input name="version" type="hidden" value={editor.request.version}/><label>Besluit<select name="decision"><option value="review">In beoordeling / herplanning beoordeeld</option><option value="regular">Inbegrepen: reguliere taak</option><option value="proposal">Buiten scope: meerwerkvoorstel</option>{data.extraAgreementOptions.length>0&&<option value="contract_extra">Meerwerk binnen vastgelegd contractakkoord</option>}<option value="rejected">Niet uitvoeren</option><option value="completed">Uitgevoerd</option><option value="partial">Deels uitgevoerd</option><option value="not_done">Niet uitgevoerd</option></select></label>{data.extraAgreementOptions.length>0&&<><Choice name="agreementLineId" label="Vooraf toegestaan meerwerk" options={data.extraAgreementOptions.map(a=>[a.id,`${a.title} · v${a.version} · ${a.scope} · maximaal € ${(a.limitCents/100).toFixed(2)} per bezoek`])}/><p className="dossier-notice wide">Bij contractmeerwerk gelden de taak, prijs, looptijd en gezamenlijke limiet van de geselecteerde afspraak. Rapportcontrole blijft vereist.</p></>}<Choice name="taskRevisionId" label="Catalogustaak (voor taak of voorstel)" options={data.taskRevisions.map(r=>[r.id,data.tasks.find(t=>t.id===r.task_id)?.name||r.id])}/><label>Hoeveelheid<input name="quantity" type="number" min="0.001" step="0.001" defaultValue={1}/></label><label>Prijs per eenheid excl. btw (alleen voorstel)<input name="price" type="number" min={0} step="0.01" defaultValue={0}/></label><label className="wide">Omvang / beoordeling / resultaat<textarea name="reason" required minLength={2}/></label><label className="wide">Terugkoppeling aan klant<textarea name="response"/></label></ObjectForm></ObjectDialog>}
 {versions&&<ObjectDialog tenant={tenant} title="Versiehistorie" description="Eerdere vastlegging blijft behouden bij wijzigingen." onClose={()=>setVersions(null)}><div className="object-version-list">{versions.map((v,i)=>{const s=valuesOf(v);return <article className="object-record" key={i}><h3>Versie {String(s.version)} · {String(s.title||s.name||"Registratie")}</h3><p>{String(s.body||s.location_description||"")}</p><p>{String(s.review_note||"")}</p><small>{String(s.state||s.dossier_status||"")}</small></article>;})}</div></ObjectDialog>}
 </div>;
}
