"use client";
import { AddressInput } from "../address-input";
import { useFormChanges, confirmDiscard } from "../unsaved-form";
import { useState, useTransition, type ReactNode, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { toast } from "sonner";
import { X, ChevronLeft, ChevronRight, ShieldCheck } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { brandThemeStyle } from "@/lib/branding/palette";
import { localDateTime } from "@/lib/planning/time";
import type { ActionResult } from "@/lib/actions/result";
import type { TenantContext } from "@/lib/auth/context";
import { objectStates,objectTypes,recordStates,nodeKinds,valuesOf,type ObjectData,type Row,type RecordKind } from "@/lib/objects/model";
import { saveObject,saveObjectNode,saveObjectRecord,uploadObjectDocument } from "@/app/app/objecten/actions";

export function ObjectDialog({title,description,children,tenant,onClose}:{title:string;description:string;children:ReactNode;tenant:Pick<TenantContext,"primaryColor"|"accentColor">;onClose:()=>void}){
 return <Dialog open onOpenChange={open=>{if(!open&&confirmDiscard())onClose();}}><DialogContent showCloseButton={false} className="dossier-dialog object-dialog" style={brandThemeStyle(tenant.primaryColor,tenant.accentColor)}><header><div><span className="eyebrow">OBJECTDOSSIER</span><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></div><button type="button" className="icon-button" aria-label="Sluiten" onClick={()=>{if(confirmDiscard())onClose();}}><X size={20}/></button></header>{children}</DialogContent></Dialog>;
}
export function ObjectForm({action,children,onSuccess,label="Opslaan"}:{action:(form:FormData)=>Promise<ActionResult>;children:ReactNode;onSuccess?:()=>void;label?:string}){
 const {ref:formRef,changed:formChanged,saved:formSaved}=useFormChanges();const [pending,start]=useTransition();const [error,setError]=useState("");const router=useRouter();
 return <form ref={formRef} onChange={formChanged} className="dossier-form" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);setError("");start(async()=>{try{const r=await action(form);if(!r.ok){setError(r.error);return;}formSaved();toast.success("Opgeslagen");router.refresh();onSuccess?.();}catch{setError("Opslaan is niet gelukt. Probeer opnieuw.");}});}}><div className="dossier-form-fields">{children}{error&&<p className="auth-message error wide" role="alert">{error}</p>}</div><footer><button className="primary-button" disabled={pending}>{pending?"Opslaan…":label}</button></footer></form>;
}
export function Choice({name,label,options,value="",required=false}:{name:string;label:string;options:Array<[string,string]>;value?:string;required?:boolean}){
 return <label>{label}<select aria-label={label} name={name} defaultValue={value} required={required}><option value="">Geen / niet van toepassing</option>{options.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;
}
export function ObjectWizard({customers,tenant,customerId="",object,onClose,onSaved}:{customers:Array<Pick<Row<"customers">,"id"|"name"|"status">>;tenant:TenantContext;customerId?:string;object?:Row<"objects">;onClose:()=>void;onSaved?:(id:string)=>void}){
 const [id]=useState(()=>object?.id||crypto.randomUUID());const [step,setStep]=useState(1);const [pending,start]=useTransition();const [error,setError]=useState("");const [review,setReview]=useState<Record<string,string>>({});const router=useRouter();
 const steps=object?["Identiteit","Locatie","Controle"]:["Klant","Locatie","Structuur","Contact","Diensten","Veiligheid","Beveiligd","Controle"];
 const checkStep=(form:HTMLFormElement)=>{const fields=form.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>("fieldset:not([hidden]) input,fieldset:not([hidden]) select,fieldset:not([hidden]) textarea");return [...fields].every(f=>f.reportValidity());};
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);form.set("id",id);form.set("version",String(object?.version??0));setError("");start(async()=>{const r=await saveObject(form);if(!r.ok){setError(r.error);return;}toast.success("Object opgeslagen");onClose();if(onSaved)onSaved(r.id);else router.push(`/app/objecten/${r.id}`);router.refresh();});};
 return <ObjectDialog tenant={tenant} title={object?"Object bewerken":"Nieuw object"} description="Van locatie naar volledig dossier. Extra onderdelen kun je later aanvullen." onClose={onClose}>
 <ol className="dossier-steps object-wizard-steps">{steps.map((s,i)=><li key={s} className={step>=i+1?"active":""} aria-current={step===i+1?"step":undefined}><b>{i+1}</b><span>{s}</span></li>)}</ol>
 <form className="dossier-form" noValidate onSubmit={submit}>
 <fieldset hidden={step!==1} className="dossier-form-fields"><legend>Bij welke klant hoort deze locatie?</legend><Choice name="customerId" label="Klant" required value={object?.customer_id||customerId} options={customers.filter(c=>c.status!=="inactive").map(c=>[c.id,c.name])}/><label>Objectnaam<input name="name" required minLength={2} maxLength={160} defaultValue={object?.name}/></label><label>Type<select name="type" defaultValue={object?.object_type||"other"}>{Object.entries(objectTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><p className="dossier-notice wide">Nog geen klant? Maak die eerst aan via <Link className="text-link" href="/app/klanten?new=1">Nieuwe klant</Link>. Er kan geen object zonder klant worden opgeslagen.</p></fieldset>
 <fieldset hidden={step!==2} className="dossier-form-fields"><legend>Waar gaan we aan het werk?</legend><AddressInput initial={object?.address} required legacyFields/><input type="hidden" name="latitude" value=""/><input type="hidden" name="longitude" value=""/><label className="wide">Ingang of herkenningspunt<input name="locationDescription" defaultValue={object?.location_description}/></label><label className="wide">Normale bezoekprocedure<textarea name="instructions" rows={3} defaultValue={object?.access_instructions??""} placeholder="Bij wie melden, welke ingang, waar parkeren… Geen geheime codes."/></label></fieldset>
 {!object&&<>
 <fieldset hidden={step!==3} className="dossier-form-fields"><legend>Maak de locatie herkenbaar</legend><label className="wide">Ruimten (optioneel, één per regel)<textarea name="structure" rows={5} placeholder={"Receptie\nVergaderruimte\nToiletten"}/></label><p className="dossier-notice wide">Je kunt dit leeg laten. Gebouwen, verdiepingen, zones en subobjecten voeg je later in het dossier toe of orden je daar.</p></fieldset>
 <fieldset hidden={step!==4} className="dossier-form-fields"><legend>Contact en bereikbaarheid</legend><label className="wide">Praktische afspraken<textarea name="contact" rows={5} placeholder="Locatiecontact, openingstijden, aanmelden, parkeren en laden/lossen"/></label><p className="dossier-notice wide">Bestaande klantcontacten zijn direct beschikbaar in het dossier; je hoeft ze niet opnieuw in te voeren.</p></fieldset>
 <fieldset hidden={step!==5} className="dossier-form-fields"><legend>Wat is afgesproken?</legend><label className="wide">Werkprogramma (optioneel)<textarea name="programme" rows={5} placeholder="Werkzaamheden, frequentie, uitvoeringsvenster, checklist en vereisten"/></label><p className="dossier-notice wide">Dit wordt als concept bewaard. Koppel daarna de bestaande catalogustaken en kwalificatie-eisen.</p></fieldset>
 <fieldset hidden={step!==6} className="dossier-form-fields"><legend>Veilig en goed voorbereid</legend><label className="wide">Vaste veiligheidsinstructie (optioneel)<textarea name="safety" rows={5} placeholder="Noodprocedure, persoonlijke bescherming, water/stroom en opslag. Geen alarm- of kluiscodes."/></label></fieldset>
 <fieldset hidden={step!==7} className="dossier-form-fields"><legend>Beveiligde gegevens apart bewaren</legend><div className="dossier-notice wide"><ShieldCheck size={22}/><p>Alarm- en sleutelkluiscodes voeg je na het opslaan toe via ‘Toegang & beveiligde gegevens’. Je bevestigt je toegang eerst per e-mail. Vul geheime waarden nooit in gewone instructies in.</p></div></fieldset>
 </>}
 <fieldset hidden={step!==steps.length} className="dossier-form-fields"><legend>Controleer het object</legend><dl className="dossier-facts wide"><div><dt>Klant</dt><dd>{customers.find(c=>c.id===review.customerId)?.name}</dd></div><div><dt>Object</dt><dd>{review.name}</dd></div><div><dt>Adres</dt><dd>{[review.street,review.postalCode,review.city].filter(Boolean).join(", ")}</dd></div></dl><label>Status na opslaan<select name="status" defaultValue={object?.dossier_status||"draft"}>{Object.entries(objectStates).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><p className="dossier-notice wide">Concept: nog aanvullen. Actief: beschikbaar voor nieuwe planning. Gepauzeerd of gearchiveerd: de historie blijft bewaard.</p></fieldset>
 {error&&<p role="alert" className="auth-message error">{error}</p>}
 <footer><button className="secondary-button" type="button" disabled={pending} onClick={()=>step===1?onClose():setStep(s=>s-1)}><ChevronLeft size={16}/>{step===1?"Annuleren":"Vorige"}</button>{step<steps.length?<button key="next" className="primary-button" type="button" onClick={e=>{const form=e.currentTarget.form!;if(checkStep(form)){setReview(Object.fromEntries(new FormData(form)) as Record<string,string>);setStep(s=>s+1);}}}>Volgende<ChevronRight size={16}/></button>:<button key="save" className="primary-button" disabled={pending}>{pending?"Opslaan…":object?"Wijzigingen opslaan":"Object aanmaken"}</button>}</footer>
 </form></ObjectDialog>;
}

type EditorProps={data:ObjectData;tenant:TenantContext;onClose:()=>void};
export function NodeEditor({data,tenant,onClose,node}:{node?:Row<"object_nodes">}&EditorProps){
 const [id]=useState(()=>node?.id||crypto.randomUUID());const d=valuesOf(node?.details??{});
 return <ObjectDialog tenant={tenant} title={node?"Locatieonderdeel bewerken":"Locatieonderdeel toevoegen"} description="Een kleine locatie mag onderdelen overslaan. Historische versies blijven bewaard." onClose={onClose}><ObjectForm action={saveObjectNode} onSuccess={onClose}>
 <input type="hidden" name="objectId" value={data.object.id}/><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={node?.version??0}/>
 <label>Naam<input name="name" required defaultValue={node?.name}/></label><label>Type<select name="kind" defaultValue={node?.kind||"room"}>{Object.entries(nodeKinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <Choice name="parentId" label="Onderdeel van" value={node?.parent_id??""} options={data.nodes.filter(n=>n.active&&n.id!==id).map(n=>[n.id,n.name])}/><label>Herkenningscode<input name="code" defaultValue={node?.code}/></label><label>Volgorde<input name="position" type="number" defaultValue={node?.position??0}/></label><label>Status<select name="active" defaultValue={String(node?.active??true)}><option value="true">Actief</option><option value="false">Gearchiveerd</option></select></label>
 {[["address","Afwijkend adres / ingang"],["quantity","Oppervlakte / hoeveelheid"],["material","Materiaalsoort"],["usage","Gebruik"],["accessibility","Toegankelijkheid"]].map(([k,v])=><label key={k}>{v}<input name={k} defaultValue={String(d[k]??"")}/></label>)}
 </ObjectForm></ObjectDialog>;
}
export function RecordEditor({data,tenant,onClose,kind,record}:{kind:RecordKind;record?:Row<"object_records">}&EditorProps){
 const [id]=useState(()=>record?.id||crypto.randomUUID());const d=valuesOf(record?.details??{});const [instructionType,setInstructionType]=useState(record?.instruction_type||"fixed");
 const names={contact:"Contact en bereikbaarheid",access:"Toegangsprocedure",programme:"Werkprogramma",instruction:"Instructie",quality:"Kwaliteitsmelding",material:"Materiaal of voorziening",task:"Opvolgtaak"};
 return <ObjectDialog tenant={tenant} title={`${record?"Bewerk":"Nieuw"} · ${names[kind]}`} description="Bewaar alleen zakelijke informatie. Geheime codes horen uitsluitend in de kluis." onClose={onClose}><ObjectForm action={saveObjectRecord} onSuccess={onClose}>
 <input type="hidden" name="objectId" value={data.object.id}/><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={record?.version??0}/><input type="hidden" name="kind" value={kind}/>
 <label className="wide">Titel<input name="title" required maxLength={180} defaultValue={record?.title}/></label><label className="wide">Omschrijving<textarea name="body" rows={4} defaultValue={record?.body}/></label>
 <label>Status<select name="state" defaultValue={record?.state||(["instruction","contact","access"].includes(kind)?"active":"open")}>{["draft","open","active","progress","completed","partial","not_done","archived"].map(k=><option key={k} value={k}>{recordStates[k]}</option>)}</select></label>
 <Choice name="nodeId" label="Locatieonderdeel" value={record?.node_id??""} options={data.nodes.filter(n=>n.active||n.id===record?.node_id).map(n=>[n.id,n.name])}/>
 {kind==="instruction"?<label>Geldigheid<select aria-label="Geldigheid" name="instructionType" value={instructionType} onChange={e=>setInstructionType(e.target.value)}><option value="fixed">Vast vanaf ingangsdatum</option><option value="temporary">Tijdelijke periode</option><option value="appointment">Alleen deze afspraak</option></select></label>:<input type="hidden" name="instructionType" value=""/>}
 <Choice name="workOrderId" label="Concrete afspraak" required={kind==="instruction"&&instructionType==="appointment"} value={record?.work_order_id??""} options={data.orders.map(w=>[w.id,`${w.work_order_number} · ${w.discipline}`])}/>
 <label>Geldig vanaf<input name="startsAt" type="datetime-local" required={kind==="instruction"} defaultValue={record?.starts_at?localDateTime(record.starts_at,tenant.timezone):kind==="instruction"?localDateTime(new Date().toISOString(),tenant.timezone):""}/></label><label>Geldig tot<input name="endsAt" type="datetime-local" required={kind==="instruction"&&instructionType==="temporary"} defaultValue={record?.ends_at?localDateTime(record.ends_at,tenant.timezone):""}/></label>
 <Choice name="ownerId" label="Verantwoordelijke" value={record?.owner_user_id??""} options={data.owners.map(o=>[o.id,o.label])}/><label>Opvolgen vóór<input name="dueOn" type="date" defaultValue={record?.due_on??""}/></label>
 <label>Dienst / discipline<input name="service" defaultValue={record?.service}/></label>
 {kind==="programme"?<Choice name="taskRevisionId" label="Taak uit bestaande catalogus" value={record?.task_revision_id??""} options={data.taskRevisions.map(r=>[r.id,`${data.tasks.find(t=>t.id===r.task_id)?.name||"Taak"} · versie ${r.revision}`])}/>:<input name="taskRevisionId" type="hidden" value={record?.task_revision_id??""}/>}
 {kind==="programme"?<Choice name="agreementLineId" label="Vastgelegde klantafspraak" value={record?.agreement_line_id??""} options={data.agreementOptions.map(a=>[a.id,`${a.title} · v${a.version} · ${a.scope}`])}/>:<input name="agreementLineId" type="hidden" value={record?.agreement_line_id??""}/>}
 {kind==="contact"?<Choice name="contactId" label="Bestaand klantcontact" value={record?.contact_id??""} options={data.contacts.map(c=>[c.id,c.full_name])}/>:<input name="contactId" type="hidden" value={record?.contact_id??""}/>}
 {kind==="material"?<Choice name="assetId" label="Gerelateerde personeelsuitgifte" value={record?.personnel_asset_id??""} options={data.assets.map(a=>[a.id,a.title])}/>:<input name="assetId" type="hidden" value={record?.personnel_asset_id??""}/>}
 {kind==="quality"?<label>Soort melding<select name="category" defaultValue={String(d.category??"inspection")}>{[["inspection","Kwaliteitscontrole"],["complaint","Klacht"],["compliment","Compliment"],["damage","Schade"],["access","Toegangsprobleem"],["unsafe","Onveilige situatie"]].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>:<label>Categorie / signaal<input name="category" defaultValue={String(d.category??"")} placeholder={kind==="material"?"Voorraad, tekort, defect, aanvulling…":""}/></label>}
 {[["frequency","Frequentie","programme"],["window","Uitvoeringsvenster","programme"],["checklist","Checklist / gewenste rapportage","programme"],["equipment","Benodigde middelen","programme"],["quantity","Hoeveelheid / voorraad","material"],["unit","Eenheid","material"]].map(([k,label,forKind])=>kind===forKind?<label key={k}>{label}<input name={k} defaultValue={String(d[k]??"")}/></label>:<input key={k} name={k} type="hidden" value={String(d[k]??"")}/>)}
 <label className="wide">Resultaat, herstelactie of reden<textarea name="evidence" defaultValue={String(d.evidence??"")}/></label>
 {kind==="instruction"&&<label className="dossier-check wide"><input name="acknowledgement" type="checkbox" defaultChecked={d.acknowledgement===true}/>Medewerker moet deze versie lezen en bevestigen</label>}
 </ObjectForm></ObjectDialog>;
}
export function DocumentEditor({data,tenant,onClose,previous}:{previous?:Row<"object_documents">}&EditorProps){
 return <ObjectDialog tenant={tenant} title={previous?"Nieuwe documentversie":"Document toevoegen"} description="Private opslag · PDF, JPG of PNG · maximaal 10 MB" onClose={onClose}><ObjectForm action={uploadObjectDocument} onSuccess={onClose}>
 <input name="objectId" type="hidden" value={data.object.id}/><input name="previousId" type="hidden" value={previous?.id??""}/><label>Titel<input name="title" required defaultValue={previous?.title}/></label><label>Categorie<select name="category" defaultValue={previous?.category||"instruction"}>{[["instruction","Instructie"],["floorplan","Plattegrond"],["report","Rapport"],["agreement","Afspraak"],["photo","Foto"],["other","Overig"],["security","Beveiligingsplattegrond (alleen management)"]].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <Choice name="nodeId" label="Locatieonderdeel" value={previous?.node_id??""} options={data.nodes.map(n=>[n.id,n.name])}/><Choice name="recordId" label="Gerelateerde instructie / registratie" value={previous?.record_id??""} options={data.records.map(r=>[r.id,r.title])}/><Choice name="orderId" label="Concrete afspraak" value={previous?.work_order_id??""} options={data.orders.map(r=>[r.id,r.work_order_number])}/><label>Dienst<input name="service" defaultValue={previous?.service}/></label><label>Geldig tot<input name="validUntil" type="date" defaultValue={previous?.valid_until??""}/></label><label className="wide">Bestand<input name="document" type="file" accept=".pdf,.jpg,.jpeg,.png" required/></label>
 <p className="dossier-notice wide">Malwarescanning is niet aangesloten. Upload alleen gecontroleerde bestanden. Geen geheime codes in documenten; beveiligingsplattegronden zijn uitsluitend voor management.</p>
 </ObjectForm></ObjectDialog>;
}
