"use client";
import { HelpTip } from "../help-tip";
import {useMemo,useState,useTransition} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {Plus,Eye,Pencil,Trash2,MoreHorizontal,Search,ChevronLeft,ChevronRight} from "lucide-react";
import {toast} from "sonner";
import {Popover,PopoverTrigger,PopoverContent} from "@/components/ui/popover";
import type {TenantContext} from "@/lib/auth/context";
import {addressLine,objectStates,objectTypes,objectDate,valuesOf,type Row} from "@/lib/objects/model";
import {archiveObjectDossier} from "@/app/app/objecten/actions";
import {ObjectWizard} from "./forms";
import {CompactFilterMenu} from "../compact-filter-menu";

export function ObjectList({tenant,objects,customers,orders,records,requests,initialCustomer,create}:{tenant:TenantContext;objects:Row<"objects">[];customers:Row<"customers">[];orders:Array<Pick<Row<"work_orders">,"id"|"object_id"|"projected_start_at"|"discipline"|"status">>;records:Array<Pick<Row<"object_records">,"object_id"|"kind"|"state"|"service">>;requests:Array<{object_id:string;needs_review:boolean}>;initialCustomer:string;create:boolean}){
 const [query,setQuery]=useState("");const [customer,setCustomer]=useState(initialCustomer);const [status,setStatus]=useState("");const [type,setType]=useState("");const [city,setCity]=useState("");const [service,setService]=useState("");const [attention,setAttention]=useState("");const [sort,setSort]=useState("name");const [page,setPage]=useState(1);const [editor,setEditor]=useState<Row<"objects">|"new"|null>(create?"new":null);const [pending,start]=useTransition();const router=useRouter();
 const serviceNames=[...new Set([...records.map(r=>r.service),...orders.map(o=>o.discipline)].filter(Boolean))].sort();
 const rows=useMemo(()=>objects.filter(o=>(!customer||o.customer_id===customer)&&(!status||o.dossier_status===status)&&(!type||o.object_type===type)&&(!city||String(valuesOf(o.address).city??"")===city)&&(!service||records.some(r=>r.object_id===o.id&&r.service===service)||orders.some(w=>w.object_id===o.id&&w.discipline===service))&&(!attention||attention==="quality"&&records.some(r=>r.object_id===o.id&&r.kind==="quality"&&["open","progress"].includes(r.state))||attention==="request"&&requests.some(r=>r.object_id===o.id))&&[o.name,o.object_number,addressLine(o.address),customers.find(c=>c.id===o.customer_id)?.name].some(v=>v?.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>{const value=(o:Row<"objects">)=>sort==="number"?o.object_number:sort==="customer"?customers.find(c=>c.id===o.customer_id)?.name??"":o.name;return value(a).localeCompare(value(b),"nl")*(sort==="name-desc"?-1:1);}),[objects,customer,status,type,city,service,attention,query,sort,records,orders,requests,customers]);
 const pages=Math.max(1,Math.ceil(rows.length/20));const currentPage=Math.min(page,pages);
 const activeFilters=[query,customer,status,type,city,service,attention].filter(Boolean).length;
 const filter=(label:string,value:string,set:(v:string)=>void,options:Array<[string,string]>)=><label>{label}<select value={value} onChange={e=>{set(e.target.value);setPage(1);}}><option value="">Alles</option>{options.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;
 return <div className="object-dossier"><header className="page-intro resource-intro"><div><span className="eyebrow">LOCATIES<HelpTip>Van locatie en werkprogramma tot uitvoering en opvolging.</HelpTip></span><h1>Objecten</h1></div><button className="primary-button" disabled={!customers.some(c=>!["inactive","archived","draft"].includes(c.status))} onClick={()=>setEditor("new")}><Plus size={16}/>Nieuw object</button></header>
 {!customers.length&&<p className="dossier-notice">Maak eerst een klant aan via <Link href="/app/klanten?new=1">Klanten</Link>.</p>}
 <div className="compact-filter-bar"><span className="compact-filter-result">{rows.length} {rows.length===1?"object":"objecten"}</span><CompactFilterMenu activeCount={activeFilters} contentClassName="object-filter-popover"><section className="object-filters" aria-label="Zoeken en filteren"><label className="object-search"><Search size={17}/><input aria-label="Objecten zoeken" placeholder="Zoek object, klant, nummer of adres…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label>
 {filter("Klant",customer,setCustomer,customers.map(c=>[c.id,c.name]))}{filter("Status",status,setStatus,Object.entries(objectStates))}{filter("Type",type,setType,Object.entries(objectTypes))}{filter("Plaats",city,setCity,[...new Set(objects.map(o=>String(valuesOf(o.address).city??"")))].filter(Boolean).sort().map(c=>[c,c]))}{filter("Dienst",service,setService,serviceNames.map(s=>[s,s]))}{filter("Aandacht",attention,setAttention,[["quality","Kwaliteitsmelding"],["request","Verzoek beoordelen"]])}<label>Sortering<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Naam A–Z</option><option value="name-desc">Naam Z–A</option><option value="number">Objectnummer</option><option value="customer">Klant</option></select></label></section>
 </CompactFilterMenu></div>
 <section className="panel resource-table-panel"><div className="table-scroll"><table className="resource-table"><thead><tr>{["Objectnummer","Naam","Klant","Type","Plaats / adres","Status","Diensten","Volgende afspraak","Aandacht","Acties"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice((currentPage-1)*20,currentPage*20).map(o=>{const next=orders.filter(w=>w.object_id===o.id&&w.projected_start_at).sort((a,b)=>a.projected_start_at!.localeCompare(b.projected_start_at!))[0];const services=[...new Set([...records.filter(r=>r.object_id===o.id).map(r=>r.service),...orders.filter(w=>w.object_id===o.id).map(w=>w.discipline)].filter(Boolean))];const count=requests.filter(r=>r.object_id===o.id).length+records.filter(r=>r.object_id===o.id&&["quality","task"].includes(r.kind)&&["open","progress"].includes(r.state)).length;
 return <tr key={o.id}><td>{o.object_number}</td><td><Link href={`/app/objecten/${o.id}`}><strong>{o.name}</strong></Link></td><td><Link href={`/app/klanten?record=${o.customer_id}`}>{customers.find(c=>c.id===o.customer_id)?.name}</Link></td><td>{objectTypes[o.object_type as keyof typeof objectTypes]??o.object_type}</td><td>{addressLine(o.address)}</td><td><span className={`resource-status resource-status-${o.dossier_status==="active"?"green":"neutral"}`}>{objectStates[o.dossier_status as keyof typeof objectStates]}</span></td><td>{services.join(", ")||"—"}</td><td>{next?objectDate(next.projected_start_at,tenant.timezone):"Nog niet gepland"}</td><td>{count?`${count} openstaand`:"—"}</td><td><div className="resource-actions"><Link className="resource-action" href={`/app/objecten/${o.id}`}><Eye size={13}/>Bekijk</Link><button className="resource-action" onClick={()=>setEditor(o)}><Pencil size={13}/>Bewerk</button><button className="resource-action danger" disabled={pending||o.dossier_status==="archived"} onClick={()=>{if(!confirm("Object archiveren? Alle gekoppelde uitvoering en historie blijft bewaard."))return;const f=new FormData();f.set("id",o.id);f.set("version",String(o.version));start(async()=>{const r=await archiveObjectDossier(f);if(!r.ok)toast.error(r.error);else router.refresh();});}}><Trash2 size={13}/>Verwijder</button><Popover><PopoverTrigger asChild><button className="resource-action"><MoreHorizontal size={13}/>Meer</button></PopoverTrigger><PopoverContent className="resource-more-content" aria-label="Meer informatie en acties" align="end" collisionPadding={12}><Link href={`/app/objecten/${o.id}?tab=afspraken`}>Afspraken bekijken</Link><Link href={`/app/objecten/${o.id}?tab=documenten`}>Documenten</Link><Link href={`/app/objecten/${o.id}?tab=tijdlijn`}>Tijdlijn</Link></PopoverContent></Popover></div></td></tr>;})}</tbody></table></div>{!rows.length&&<div className="resource-empty"><Search size={22}/><strong>Geen objecten gevonden</strong><span>Pas de filters aan of voeg een object toe.</span></div>}<footer className="object-pagination"><span>{rows.length} objecten · pagina {currentPage} van {pages}</span><button className="secondary-button" aria-label="Vorige pagina" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button><button className="secondary-button" aria-label="Volgende pagina" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button></footer></section>
 {editor&&<ObjectWizard tenant={tenant} customers={customers} object={editor==="new"?undefined:editor} customerId={customer} onClose={()=>setEditor(null)}/>}</div>;
}
