"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { LockKeyhole, ShieldCheck, EyeOff } from "lucide-react";

type Item={id:string;name:string;kind:string;version:number;nodeId:string|null};
type Reply={ok:boolean;error?:string;items?:Item[];canManage?:boolean;email?:string;challengeId?:string;grantId?:string;expiresAt?:string;value?:string};
export function VaultCard({objectId,orderId=null,nodes=[],assignments=[]}:{objectId:string;orderId?:string|null;nodes?:Array<{id:string;name:string}>;assignments?:Array<{id:string;label:string}>}){
 const [items,setItems]=useState<Item[]>([]);const [canManage,setCanManage]=useState(false);const [email,setEmail]=useState("");const [selected,setSelected]=useState("");
 const [challenge,setChallenge]=useState("");const [grant,setGrant]=useState("");const [code,setCode]=useState("");const [value,setValue]=useState("");const [expires,setExpires]=useState("");const [remaining,setRemaining]=useState(0);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [editing,setEditing]=useState(false);const formRef=useRef<HTMLFormElement>(null);const generation=useRef(0);
 const request=useCallback(async(operation:string,input:Record<string,string|number|boolean>={},itemId:string|null=selected||null):Promise<Reply>=>{
  try{const r=await fetch("/api/objects/vault",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({objectId,orderId,itemId,operation,input})});return await r.json();}catch{return {ok:false,error:"Geen verbinding. Beveiligde gegevens zijn alleen online beschikbaar."};}
 },[objectId,orderId,selected]);
 const clear=useCallback(()=>{generation.current++;setValue("");setCode("");setChallenge("");setGrant("");setExpires("");setEditing(false);formRef.current?.reset();if(grant)void request("hide",{grantId:grant});},[grant,request]);
 const load=useCallback(async()=>{const r=await request("metadata",{},null);if(r.ok){setItems(r.items??[]);setCanManage(Boolean(r.canManage));setEmail(r.email??"");}else setMessage(r.error??"Toegang niet beschikbaar.");},[request]);
 useEffect(()=>{const lifetime=generation;let active=true;request("metadata",{},null).then(r=>{if(!active)return;if(r.ok){setItems(r.items??[]);setCanManage(Boolean(r.canManage));setEmail(r.email??"");}else setMessage(r.error??"Toegang niet beschikbaar.");});return()=>{active=false;lifetime.current++;};},[objectId,orderId,request]);
 useEffect(()=>{
  const hide=()=>{clear();};const visibility=()=>{if(document.hidden)hide();};window.addEventListener("blur",hide);window.addEventListener("offline",hide);window.addEventListener("pagehide",hide);document.addEventListener("visibilitychange",visibility);
  return()=>{window.removeEventListener("blur",hide);window.removeEventListener("offline",hide);window.removeEventListener("pagehide",hide);document.removeEventListener("visibilitychange",visibility);};
 },[clear]);
 useEffect(()=>{
  if(!grant||!expires)return;
  const tick=()=>{const seconds=Math.max(0,Math.ceil((Date.parse(expires)-Date.now())/1000));setRemaining(seconds);if(!seconds)clear();};
  const timer=window.setInterval(tick,1000);let running=false;
  const poll=window.setInterval(async()=>{if(running)return;running=true;const epoch=generation.current;const r=await request("check",{grantId:grant});running=false;if(epoch===generation.current&&!r.ok){clear();setMessage("De toegang is verlopen of gewijzigd. Bevestig opnieuw.");}},5000);
  return()=>{clearInterval(timer);clearInterval(poll);};
 },[grant,expires,clear,request]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage("");try{await fn();}finally{setBusy(false);}};
 const current=items.find(i=>i.id===selected);
 return <section className="dossier-card object-vault" aria-label="Beveiligde objectgegevens"><div className="object-section-title"><LockKeyhole size={23}/><div><h2>Beveiligde gegevens</h2><p>Alleen online, voor je huidige sessie en toegestane werkzaamheden.</p></div></div>
 <p className="dossier-notice">Sluit het gebouw af en plaats sleutels terug vóór je de werkbon definitief afrondt. Geen code ontvangen? Neem contact op met je leidinggevende; gebruik geen gewone berichten voor alarm- of kluiscodes.</p>
 <div className="dossier-form-fields"><label>Gegeven<select aria-label="Gegeven" value={selected} onChange={e=>{clear();setSelected(e.target.value);}}><option value="">{canManage?"Nieuw beveiligd gegeven":"Kies een toegestaan gegeven"}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · versie {i.version}</option>)}</select></label><div className="object-vault-context"><ShieldCheck size={18}/><span>{email?`Verificatie per e-mail: ${email}`:"Alleen expliciet toegewezen gegevens zijn beschikbaar binnen je uitvoeringsvenster."}</span></div></div>
 {!canManage&&!items.length&&<p className="dossier-empty">Momenteel geen gegevens beschikbaar. Controleer je toewijzing, het tijdvenster en de vrijgave met je leidinggevende.</p>}
 {!grant&&(canManage||selected)&&<div className="object-vault-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{const epoch=generation.current;const r=await request("request");if(epoch!==generation.current)return;if(!r.ok){setMessage(r.error!);return;}setChallenge(r.challengeId!);setCode("");setMessage("Je ontvangt een e-mail met een eenmalige verificatiecode. Deze is maximaal vijf minuten geldig.");})}>{busy?"Bezig…":challenge?"Nieuwe code aanvragen":"Verificatiecode aanvragen"}</button>
 {challenge&&<form className="object-otp-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const epoch=generation.current;const r=await request("verify",{challengeId:challenge,code});setCode("");if(epoch!==generation.current)return;if(!r.ok){setMessage(r.error!);return;}setGrant(r.grantId!);setExpires(r.expiresAt!);setRemaining(Math.max(0,Math.ceil((Date.parse(r.expiresAt!)-Date.now())/1000)));if(selected){const revealed=await request("read",{grantId:r.grantId!});if(epoch!==generation.current)return;if(revealed.ok)setValue(revealed.value??"");else{clear();setMessage(revealed.error!);}}else setEditing(true);});}}><label>Code uit je e-mail<input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" required maxLength={6}/></label><button className="primary-button" disabled={busy}>Bevestigen</button></form>}</div>}
 {grant&&<><div className="object-vault-actions"><span role="timer">Nog {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,"0")} beschikbaar</span><button type="button" className="secondary-button" onClick={clear}><EyeOff size={16}/>Verbergen</button></div>{value&&!editing&&<pre className="object-secret-value" data-private>{value}</pre>}{canManage&&selected&&!editing&&<button type="button" className="secondary-button" onClick={()=>setEditing(true)}>Code wijzigen / incident opvolgen</button>}
 {canManage&&editing&&<form ref={formRef} className="dossier-form" autoComplete="off" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const input:Record<string,string|number|boolean>={grantId:grant,name:String(f.get("name")),kind:String(f.get("kind")),nodeId:String(f.get("nodeId")),value:String(f.get("value")),validUntil:String(f.get("validUntil")),version:current?.version??0,externalChanged:f.get("externalChanged")==="on"};void run(async()=>{const r=await request("save",input);input.value="";clear();setMessage(r.ok?"Beveiligd opgeslagen. Eerdere inzage is ingetrokken.":r.error!);await load();});}}><div className="dossier-form-fields"><label>Naam<input name="name" required minLength={2} defaultValue={current?.name}/></label><label>Type<select name="kind" defaultValue={current?.kind||"access"}><option value="access">Toegangscode</option><option value="alarm">Alarmcode</option><option value="key_safe">Sleutelkluiscode</option><option value="sensitive_instruction">Gevoelige instructie</option></select></label><label>Locatieonderdeel<select name="nodeId" defaultValue={current?.nodeId??""}><option value="">Gehele object</option>{nodes.map(n=><option value={n.id} key={n.id}>{n.name}</option>)}</select></label><label>Geldig tot (optioneel, tijdzone van je organisatie)<input name="validUntil" type="datetime-local"/></label><label className="wide">Nieuwe geheime waarde<input name="value" type="password" required autoComplete="new-password" maxLength={4000}/></label>{selected&&<label className="dossier-check wide"><input name="externalChanged" type="checkbox" required/>Ik bevestig dat de code ook bij het alarm, de kluis of het toegangssysteem is gewijzigd.</label>}</div><footer><button className="primary-button" disabled={busy}>Versleuteld opslaan</button></footer></form>}
 {canManage&&selected&&assignments.length>0&&<form className="object-scope-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const r=await request("scope",{grantId:grant,assignmentId:String(f.get("assignmentId")),active:f.get("active")==="true"});setMessage(r.ok?"Toewijzingsscope bijgewerkt; oude inzage is niet meer geldig.":r.error!);});}}><label>Beschikbaar voor concrete toewijzing<select name="assignmentId" required>{assignments.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><label>Toegang<select name="active"><option value="true">Toestaan binnen uitvoeringsvenster + OTP</option><option value="false">Intrekken</option></select></label><button className="secondary-button" disabled={busy}>Scope opslaan</button></form>}
 </>}
 {message&&<p role="status" className="dossier-notice">{message}</p>}
 <small className="dossier-muted">E-mailverificatie is een extra bevestiging, geen onafhankelijke sterke MFA. Intrekken stopt nieuwe inzage; een al gelezen code vereist zo nodig fysieke codewijziging.</small>
 </section>;
}
