"use client";
import {useState} from "react";
import Link from "next/link";
import type {VisitContext,VisitRequest} from "@/lib/objects/model";
import {recordStates,objectDate,addressLine} from "@/lib/objects/model";
import {submitVisitRequest,acceptVisitProposal,acknowledgeVisitInstruction,uploadVisitAttachment,acknowledgeVisitRequest,updateVisitRequest} from "@/app/klant/actions";
import {ObjectForm,Choice} from "./forms";
import {VaultCard} from "./vault-card";

export function ObjectVisit({context,timezone,customerMode=false,manageSecrets=false}:{context:VisitContext;timezone:string;customerMode?:boolean;manageSecrets?:boolean}){
 const [editing,setEditing]=useState<VisitRequest|null>(null);const [requestId,setRequestId]=useState(()=>crypto.randomUUID());const [adding,setAdding]=useState(false);const o=context.object;const w=context.order;
 const mutable=w&&["planned","released","seen","travelling","in_progress"].includes(w.status);
 return <div className="object-dossier"><Link className="dossier-back" href={customerMode?"/klant":"/staff"}>← Terug naar {customerMode?"mijn afspraken":"mijn werkbonnen"}</Link><header className="page-intro"><span className="eyebrow">{o.number}{w&&` · ${w.number}`}</span><h1>{o.name}</h1><p>{addressLine(o.address)}</p>{w&&<p>{w.service} · {objectDate(w.start,timezone)} tot {objectDate(w.end,timezone)}</p>}</header>
 {!customerMode&&<section className="dossier-card"><h2>Voorbereiding & instructies</h2><p className="object-prose">{o.instructions||"Geen algemene bezoekprocedure vastgelegd."}</p>{context.instructions.map(r=><article className="object-record" key={r.id}><h3>{r.title}</h3><small>{({fixed:"Vaste instructie",temporary:"Tijdelijke instructie",appointment:"Alleen deze afspraak"})[r.instruction_type||"fixed"]} · versie {r.version}</small><p className="object-prose">{r.body}</p>{r.read?<span className="resource-status resource-status-green">Deze versie gelezen</span>:<ObjectForm action={acknowledgeVisitInstruction} label="Deze versie gelezen"><input name="orderId" type="hidden" value={w!.id}/><input name="recordId" type="hidden" value={r.id}/><input name="version" type="hidden" value={r.version}/></ObjectForm>}</article>)}{!context.instructions.length&&<p>Nog geen aanvullende instructies voor dit bezoek.</p>}<p className="dossier-notice">Tegenstrijdige instructies? Stop bij twijfel en vraag je leidinggevende om beoordeling. Een dagnotitie vervangt geen veiligheidsregel.</p></section>}
 {w&&<section className="dossier-card"><div className="object-section-title"><div><h2>Verzoeken bij dit bezoek</h2><p>Een verzoek geldt alleen voor {w.number}. Lezen is geen akkoord voor uitvoering of kosten.</p></div>{mutable&&<button className="primary-button" onClick={()=>{setEditing(null);setAdding(!adding);}}>Instructie of verzoek toevoegen</button>}</div>
 {adding&&<ObjectForm key={editing?.id??requestId} action={editing?updateVisitRequest:submitVisitRequest} label={editing?"Wijziging versturen":"Verzoek versturen"} onSuccess={()=>{setAdding(false);setEditing(null);setRequestId(crypto.randomUUID());}}><input name="id" type="hidden" value={editing?.id??requestId}/><input name="version" type="hidden" value={editing?.version??0}/><input name="objectId" type="hidden" value={o.id}/><input name="orderId" type="hidden" value={w.id}/><label className="wide">Titel<input name="title" required minLength={2} maxLength={180} defaultValue={editing?.title}/></label><label className="wide">Wat wil je doorgeven?<textarea name="body" required minLength={2} maxLength={10000} rows={4} defaultValue={editing?.body}/></label><Choice name="nodeId" label="Locatieonderdeel" value={editing?.node_id??""} options={context.nodes.map(n=>[n.id,n.name])}/><label>Soort verzoek<select name="kind" defaultValue={editing?.kind??"attention"}><option value="attention">Aandachtspunt</option><option value="change">Praktische wijziging</option><option value="problem">Probleem</option><option value="extra">Extra werkzaamheden aanvragen</option></select></label><label>Prioriteit<select name="priority" defaultValue={editing?.priority??"normal"}><option value="normal">Normaal</option><option value="high">Hoog</option><option value="urgent">Urgent</option></select></label><label>Gewenste terugkoppeling<input name="feedback" maxLength={1000} defaultValue={editing?.feedback}/></label><p className="dossier-notice wide">Voeg geen alarm-, sleutelkluis- of toegangscodes toe. Een bijlage kun je na het opslaan aan dit verzoek toevoegen. Extra werk wordt pas na beoordeling en zo nodig afzonderlijk prijsakkoord uitgevoerd.</p></ObjectForm>}
 {context.requests.map(r=><article className="object-record" key={r.id}><header><h3>{r.title}</h3><span className="resource-status">{recordStates[r.state]||r.state}</span></header><small>{objectDate(r.created_at,timezone)} · versie {r.version} · {context.nodes.find(n=>n.id===r.node_id)?.name||"Gehele object"}</small><p>{r.body}</p><div className="object-actions">{r.read?<span className="resource-status resource-status-green">Deze versie gelezen</span>:<ObjectForm action={acknowledgeVisitRequest} label="Verzoek gelezen"><input name="requestId" type="hidden" value={r.id}/><input name="version" type="hidden" value={r.version}/></ObjectForm>}{mutable&&!r.work_order_task_id&&r.created_by===context.userId&&<button className="secondary-button" onClick={()=>{setEditing(r);setAdding(true);}}>Verzoek wijzigen</button>}</div>{r.needs_review&&<p className="dossier-notice">Ontvangen; beoordeling van uitvoering, scope en capaciteit volgt nog.</p>}{r.response&&<p>Terugkoppeling: {r.response}</p>}{r.proposals.map((p,i)=><section className="object-proposal" key={p.id}><h4>Voorstel versie {p.version}</h4><p>{p.scope}</p><strong>{new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"}).format(p.price_cents*p.quantity/100)} excl. btw</strong><p>{p.quantity} × € {(p.price_cents/100).toFixed(2)} · btw {p.vat_basis_points/100}%</p>{p.accepted_at?<p>Akkoord vastgelegd op {objectDate(p.accepted_at,timezone)}.</p>:customerMode&&i===0&&r.state==="proposal"&&!r.needs_review&&mutable?<ObjectForm action={acceptVisitProposal} label="Akkoord met deze omvang en prijs"><input name="proposalId" type="hidden" value={p.id}/><label className="dossier-check wide"><input type="checkbox" required/>Ik ga akkoord met deze voorstelversie, de omschreven werkzaamheden en het genoemde bedrag.</label></ObjectForm>:<p>Nog geen akkoord op deze versie.</p>}</section>)}{r.documents.map(d=><p key={d.id}><a className="text-link" target="_blank" rel="noreferrer" href={`/api/files/object-document/${d.id}?order=${w.id}`}>{d.title} · versie {d.version}</a></p>)}{mutable&&<details><summary>Bijlage toevoegen aan dit verzoek</summary><ObjectForm action={uploadVisitAttachment} label="Bijlage uploaden"><input name="objectId" type="hidden" value={o.id}/><input name="orderId" type="hidden" value={w.id}/><input name="requestId" type="hidden" value={r.id}/><label>Titel<input name="title" required minLength={2}/></label><label>Bestand (PDF, JPG of PNG)<input name="document" type="file" accept=".pdf,.jpg,.jpeg,.png" required/></label><p className="dossier-notice wide">Maximaal 10 MB. Malwarecontrole is niet aangesloten; upload alleen gecontroleerde bestanden zonder geheime waarden.</p></ObjectForm></details>}</article>)}{!context.requests.length&&<p>Er zijn nog geen verzoeken bij deze afspraak.</p>}</section>}
 {(!customerMode||manageSecrets)&&<VaultCard objectId={o.id} orderId={customerMode?null:w?.id??null} nodes={context.nodes}/>}
 </div>;
}
