import type { AssignmentStatus } from "@workspace/db";

export const STATUS_LABEL: Record<AssignmentStatus, string> = {
  requested:         "Aangevraagd",
  review:            "In beoordeling",
  quote_preparation: "Offerte opstellen",
  awaiting_approval: "Wacht op klantakkoord",
  approved:          "Goedgekeurd",
  plannable:         "Planbaar",
  scheduled:         "Ingepland",
  seen:              "Gezien door medewerker",
  en_route:          "Onderweg",
  in_progress:       "In uitvoering",
  not_completed:     "Afgemeld / niet afgerond",
  cancelled:         "Geannuleerd",
  completed:         "Afgerond",
  report_submitted:  "Rapport ter controle",
  report_approved:   "Rapport goedgekeurd",
  invoice_ready:     "Factureerbaar",
  invoiced:          "Gefactureerd",
  paid:              "Betaald",
  closed:            "Afgehandeld",
};

export const STATUS_COLOR: Record<AssignmentStatus, { bg: string; color: string }> = {
  requested:         { bg: "#EFF6FF", color: "#1D4ED8" },
  review:            { bg: "#FEF9C3", color: "#A16207" },
  quote_preparation: { bg: "#FEF9C3", color: "#A16207" },
  awaiting_approval: { bg: "#FEF9C3", color: "#A16207" },
  approved:          { bg: "#DCFCE7", color: "#15803D" },
  plannable:         { bg: "#E0F2FE", color: "#0369A1" },
  scheduled:         { bg: "#E0F2FE", color: "#0369A1" },
  seen:              { bg: "#E0F2FE", color: "#0369A1" },
  en_route:          { bg: "#CCFBF1", color: "#115E59" },
  in_progress:       { bg: "#FEF3C7", color: "#D97706" },
  not_completed:     { bg: "#FEE2E2", color: "#B91C1C" },
  cancelled:         { bg: "#FEE2E2", color: "#991B1B" },
  completed:         { bg: "#DCFCE7", color: "#15803D" },
  report_submitted:  { bg: "#F0FDF4", color: "#15803D" },
  report_approved:   { bg: "#F0FDF4", color: "#15803D" },
  invoice_ready:     { bg: "#EDE9FE", color: "#6D28D9" },
  invoiced:          { bg: "#EDE9FE", color: "#6D28D9" },
  paid:              { bg: "#DCFCE7", color: "#15803D" },
  closed:            { bg: "#F1F5F9", color: "#334155" },
};
